### ISSUE TITLE
请问下，现在一天能有多少京豆，大概。

### ISSUE THREAD

**Issue by zengxiangj** [lxk0301/jd_scripts#100]
我只有100多，200的样子

**Comment by leoaka** [comment]
差不多 没什么活动

**Comment by forestchu** [comment]
action不是没了吗 京豆怎么来的

**Comment by zengxiangj** [comment]
> action不是没了吗 京豆怎么来的

action只是食用方法之一，没了，不是还有其它食用方法么

**Comment by Luochen-1996** [comment]
> 我只有100多，200的样子

为啥我就几十啊=-=，我还是plus会员呢

**Comment by forestchu** [comment]
[](url)
![Xnip2020-11-16_11-20-30](https://user-images.githubusercontent.com/29486582/99209291-cc233280-27fd-11eb-9f1e-95c79c820f57.jpg) 腾讯云函数一直执行失败,为什么呢
