### ISSUE TITLE
 jd_joy_reward.js  0 点 8点 16点准时兑换出错

### ISSUE THREAD

**Issue by 269569205** [lxk0301/jd_scripts#109]
我发现 11月12号以后 兑换都没记录了
自己在凌晨0点手动执行了一下这个脚本，报错了，过了一分钟再执行 京豆被兑换完毕了

**Comment by wanthigh** [comment]
同，12号以后就没有兑换成功的记录

**Comment by 09wqlin** [comment]
因为这个活动本来就已经没豆可以给你换了，当然显示错误

**Comment by zengxiangj** [comment]
> 因为这个活动本来就已经没豆可以给你换了，当然显示错误

现在没有活动不能换了？
我发现我的12号之后也没兑换成功过，还有京小超兑换也不行jd_joy_reward

**Comment by lxk0301** [comment]
本来就是鱼多肉少， 需要抢购的东西， 换不到也很正常。

报错是因为京东那边返回的没有数据。原因有很多

**Comment by lqrqw13** [comment]
同12号开始就没兑到过，不过今天16：00场兑换成功了

**Comment by lxk0301** [comment]
> 同12号开始就没兑到过，不过今天16：00场兑换成功了

羡慕

**Comment by sgzman** [comment]
昨天夜里我兑换500豆子
