### ISSUE TITLE
action 疑似被封，运行就提示this check failed

### ISSUE THREAD

**Issue by zerokos** [lxk0301/jd_scripts#113]
有一样情况的吗？

**Comment by lxk0301** [comment]
不是被封，

**Comment by xuelang7009** [comment]
同样情况，怎么解决呢？

**Comment by hrt941009** [comment]
每月最多2k次

**Comment by xuelang7009** [comment]
改了runs-on 也不行。

**Comment by 428255177** [comment]
有没有解决的办法，我也有这个情况了，就在今天

**Comment by Walter689** [comment]
git action 现在每个月最多2000次限制了？

**Comment by lxk0301** [comment]
> git action 现在每个月最多2000次限制了？

开源仓库没限制

**Comment by Tersd07** [comment]
公开仓库没限制，私人仓库每个月2000分钟运行配额。
这里查看 https://github.com/settings/billing

**Comment by zerokos** [comment]
感谢楼上的诸位，原因是私有仓库有时间限制，解决方法是新建一个公开仓库。。
@xuelang7009 @428255177
