### ISSUE TITLE
关于解决腾讯云函数不会自动重新加载导致没反映的情况的解决方案

### ISSUE THREAD

**Issue by lijialong1313** [lxk0301/jd_scripts#115]
我搜索了一下百度通过[这篇博文](https://blog.hellozwh.com/?post=433)

文章中提到可以使用delete去取消缓存，逼迫重新加载。

这应该能解决云函数的热加载问题（本人测试没问题）。

大概代码是：

> index.js
```
'use strict';
exports.main_handler = async (event, context, callback) => {
  delete require.cache[require.resolve('./jd_fruit.js')];//脚本名字和下方一致
  require('./jd_fruit.js') //这里写你想要的脚本
}
```

太久没用这个忘记怎么传图了，大概就把index.js在前面加这样一句就可以了，加好之后设定5分钟试一下

**Comment by lijialong1313** [comment]
再提一句，似乎更好的方法是[这篇文章中](http://fex.baidu.com/blog/2015/05/nodejs-hot-swapping/)

```
function cleanCache(modulePath) {
    var module = require.cache[modulePath];
    // remove reference in module.parent
    if (module.parent) {
        module.parent.children.splice(module.parent.children.indexOf(module), 1);
    }
    require.cache[modulePath] = null;
}
```

这样甚至能防止内存泄漏（不知道云函数有没有）

**Comment by lxk0301** [comment]
> 再提一句，似乎更好的方法是[这篇文章中](http://fex.baidu.com/blog/2015/05/nodejs-hot-swapping/)
> 
> ```
> function cleanCache(modulePath) {
>     var module = require.cache[modulePath];
>     // remove reference in module.parent
>     if (module.parent) {
>         module.parent.children.splice(module.parent.children.indexOf(module), 1);
>     }
>     require.cache[modulePath] = null;
> }
> ```
> 
> 这样甚至能防止内存泄漏（不知道云函数有没有）

多谢. 不过第二种方法好像云函数行不通

**Comment by lijialong1313** [comment]
> > 再提一句，似乎更好的方法是[这篇文章中](http://fex.baidu.com/blog/2015/05/nodejs-hot-swapping/)
> > ```
> > function cleanCache(modulePath) {
> >     var module = require.cache[modulePath];
> >     // remove reference in module.parent
> >     if (module.parent) {
> >         module.parent.children.splice(module.parent.children.indexOf(module), 1);
> >     }
> >     require.cache[modulePath] = null;
> > }
> > ```
> > 
> > 
> > 这样甚至能防止内存泄漏（不知道云函数有没有）
> 
> 多谢. 不过第二种方法好像云函数行不通

应该是第二种没啥用。（第二种我没试过）

第二种应该就是判断一下cache的那个引用还在不在。在的话就把他干掉。

我是搞后端的，这一方面我是真的不太懂QwQ

**Comment by DoveBoy** [comment]
感谢😊
