### ISSUE TITLE
请教 腾讯云云函数 GitHub Action部署教程 硬是部处在香港，怎么切换

### ISSUE THREAD

**Issue by Jumeng-ms** [lxk0301/jd_scripts#120]
以前轻应用开香港的时候进去云函数默认是广州的，然后新增了香港后 进去云函数都是默认香港，然后用GitHub Action部署也默认是香港 有办法切换不？

**Comment by iouAkira** [comment]
@Jumeng-ms serverless.yml 里面第14行，自己调整

**Comment by Jumeng-ms** [comment]
> @Jumeng-ms serverless.yml 里面第14行，自己调整

谢谢，顾着部处没看代码
