### ISSUE TITLE
金融猪脚本好像该出问题来了？我只有一个账号，却提示我账号234...

### ISSUE THREAD

**Issue by zengxiangj** [lxk0301/jd_scripts#122]
金融养猪
【提示】cookie已失效
京东账号6 null
请重新登录获取
https://bean.m.jd.com/

server酱发送通知消息成功

您未提供Bark的APP推送BARK_PUSH，取消Bark推送消息通知

您未提供telegram机器人推送所需的TG_BOT_TOKEN和TG_USER_ID，取消telegram推送消息通知

您未提供钉钉机器人推送所需的DD_BOT_TOKEN或者DD_BOT_SECRET，取消钉钉推送消息通知

您未提供iGot的推送IGOT_PUSH_KEY，取消iGot推送消息通知

开始【京东账号7】null

==============📣系统通知📣==============
金融养猪
【提示】cookie已失效
京东账号7 null
请重新登录获取
https://bean.m.jd.com/

server酱发送通知消息成功

您未提供Bark的APP推送BARK_PUSH，取消Bark推送消息通知

您未提供telegram机器人推送所需的TG_BOT_TOKEN和TG_USER_ID，取消telegram推送消息通知

您未提供钉钉机器人推送所需的DD_BOT_TOKEN或者DD_BOT_SECRET，取消钉钉推送消息通知

您未提供iGot的推送IGOT_PUSH_KEY，取消iGot推送消息通知

开始【京东账号8】null

==============📣系统通知📣==============
金融养猪
【提示】cookie已失效
京东账号8 null
请重新登录获取
https://bean.m.jd.com/

server酱发送通知消息成功

**Comment by chaoticjoy** [comment]
所有都有问题了，疯狂通知

**Comment by lxk0301** [comment]
@chaoticjoy 我的问题, 已修复.
