### ISSUE TITLE
发现好货心愿单领京豆

### ISSUE THREAD

**Issue by ITdesk01** [lxk0301/jd_scripts#123]
## 入口

1.需要京东APP升级到最新版本
2.点击发现好货，然后进去
![6d93ea9699f008d16d5d6fb58925dfb](https://user-images.githubusercontent.com/38835844/99641810-b9229380-2a85-11eb-96cf-62900f47a027.jpg)

3.点击货品添加到心愿，每个货品5京豆，最多领50个
![b81ff70783dc10cbdc677a2a34b1d60](https://user-images.githubusercontent.com/38835844/99642115-1585b300-2a86-11eb-8f15-076138c1a0fc.jpg)
![b9ef722f287a7450cf9817db7506c13](https://user-images.githubusercontent.com/38835844/99642168-2504fc00-2a86-11eb-93bc-db6636648ca1.jpg)

4.不需要了。点击右上角❤，进去可以批量删除
![b81ff70783dc10cbdc677a2a34b1d60_看图王](https://user-images.githubusercontent.com/38835844/99642441-7c0ad100-2a86-11eb-98c6-9eec96f73d60.jpg)

![124a23327c845bad795e4138a5ce299](https://user-images.githubusercontent.com/38835844/99642241-3c43e980-2a86-11eb-8d5b-e3e86acc2bc2.jpg)

**Comment by lxk0301** [comment]
@ITdesk01 早上就尝试过了, 做不了 ,sign无法解密

**Comment by ITdesk01** [comment]
那就先挂着吧，看看有没有大佬懂点，应该是可以搞得，再不行就手动一下，一天50豆也还是可观的

**Comment by ITdesk01** [comment]
辛苦了大佬

**Comment by lxk0301** [comment]
> 那就先挂着吧，看看有没有大佬懂点，应该是可以搞得，再不行就手动一下，一天50豆也还是可观的

哈哈。好。你倒是挺有梦想的

**Comment by ITdesk01** [comment]
> > 那就先挂着吧，看看有没有大佬懂点，应该是可以搞得，再不行就手动一下，一天50豆也还是可观的
> 
> 哈哈。好。你倒是挺有梦想的

人没有梦想跟咸鱼有啥两样，能撸点是一点

**Comment by ATing-GitHub** [comment]
大佬，京东cookie两小时失效一次是咋回事呀

**Comment by ITdesk01** [comment]
> 大佬，京东cookie两小时失效一次是咋回事呀

重新抓，按教程来，手机登录都是30天

**Comment by ATing-GitHub** [comment]
那个教程呀，发一下呗，谢谢啦



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ITdesk01 <notifications@github.com&gt;
发送时间: 2020年11月21日 10:52
收件人: lxk0301/jd_scripts <jd_scripts@noreply.github.com&gt;
抄送: ATing-GitHub <1084305144@qq.com&gt;, Comment <comment@noreply.github.com&gt;
主题: 回复：[lxk0301/jd_scripts] 发现好货心愿单领京豆 (#123)





  
大佬，京东cookie两小时失效一次是咋回事呀
  
重新抓，按教程来，手机登录都是30天
