### ISSUE TITLE
Openwrt可以运行的shell脚本

### ISSUE THREAD

**Issue by ITdesk01** [lxk0301/jd_scripts#124]
脚本地址：https://github.com/ITdesk01/JD_Script
![搜狗截图20201119171157](https://user-images.githubusercontent.com/38835844/99645571-5bdd1100-2a8a-11eb-97d0-c50f1981e4da.png)

调用https://github.com/lxk0301/jd_scripts  项目的JS脚本，并使其在openwrt能够用愉快跑起j脚本，可以定时更新，定时跟进lxk0301/jd_scripts项目有兴趣可以拿去用

**Comment by EvineDeng** [comment]
里面有私货，未申明。

**Comment by ITdesk01** [comment]
> 里面有私货，未申明。

已添加声明
