### ISSUE TITLE
增加自定义 User-Agent 功能

### ISSUE THREAD

**Issue by ShallowAi** [lxk0301/jd_scripts#127]
## 期望增加的功能

A：增加一个 UA 的设置于jd_cookie.js，其他脚本进行读取 若未定义则使用默认UA，在1111的活动中52著名的脚本有因为相同UA导致黑活动无法参加的实例。

**Comment by Tersd07** [comment]
![image](https://user-images.githubusercontent.com/73736683/99670325-53e19900-2aab-11eb-84ce-3cc949752319.png)
用这个正则
```js
(?<=(["'`])User-Agent\1:\s(["'`]))jdapp.+?(?=\2)
```
很容易替换以`jdapp`开头的UA。

**Comment by lxk0301** [comment]
这个工程量有点大。每个脚步都要弄

**Comment by JunShine** [comment]
加个参数设置ua可以吧？

**Comment by lxk0301** [comment]
> 加个参数设置ua可以吧？

那也是都需要每个脚本去修改的

**Comment by lxk0301** [comment]
> ## 期望增加的功能
> A：增加一个 UA 的设置于jd_cookie.js，其他脚本进行读取 若未定义则使用默认UA，在1111的活动中52著名的脚本有因为相同UA导致黑活动无法参加的实例。

你确定是UA导致的么😂😂

**Comment by lxk0301** [comment]
已加此功能 @ShallowAi @Tersd07 @shylocks 

https://github.com/lxk0301/jd_scripts/commit/5109e4f4bf3423d3f9c5712ec1dda9e1ec874fec

帮忙测测看看有没有异常或者漏网之鱼。

自定义UA环境变量 `JD_USER_AGENT`

**Comment by Tersd07** [comment]
![image](https://user-images.githubusercontent.com/73736683/99928978-64816000-2d86-11eb-912d-41dfe7c267fc.png)


```
(?<=(["'`])User-Agent\1)(?:\s*:\s*)(["`]).+?\2
```
替换内容：
```
: $.isNode() ? (process.env.JD_USER_AGENT ? process.env.JD_USER_AGENT : "jdapp;iPhone;9.2.2;14.2;%E4%BA%AC%E4%B8%9C/9.2.2 CFNetwork/1206 Darwin/20.1.0") : ($.getdata('JDUA') ? $.getdata('JDUA') : "jdapp;iPhone;9.2.2;14.2;%E4%BA%AC%E4%B8%9C/9.2.2 CFNetwork/1206 Darwin/20.1.0")
```
排除的文件：`backUp,test2.js,jd_818*

**Comment by lxk0301** [comment]
@Tersd07 。。。。咋还漏了这么多。记得昨晚都改完了。 可能忘记保存了🥲🥲🥲

**Comment by lxk0301** [comment]
> ![image](https://user-images.githubusercontent.com/73736683/99928978-64816000-2d86-11eb-912d-41dfe7c267fc.png)
> 
> ```
> (?<=(["'`])User-Agent\1)(?:\s*:\s*)(["`]).+?\2
> ```
> 
> 替换内容：
> 
> ```
> : $.isNode() ? (process.env.JD_USER_AGENT ? process.env.JD_USER_AGENT : "jdapp;iPhone;9.2.2;14.2;%E4%BA%AC%E4%B8%9C/9.2.2 CFNetwork/1206 Darwin/20.1.0") : ($.getdata('JDUA') ? $.getdata('JDUA') : "jdapp;iPhone;9.2.2;14.2;%E4%BA%AC%E4%B8%9C/9.2.2 CFNetwork/1206 Darwin/20.1.0")
> ```
> 
> 排除的文件：`backUp,test2.js,jd_818*`

已改，但是不知道替换了UA ， 会不会对脚本请求到的数据有没有影响。

**Comment by treatself** [comment]
Action怎么给多账号每个账号都设置一个UA

**Comment by lxk0301** [comment]
@treatself 不能

**Comment by jw10126121** [comment]
UA格式都是jdapp开头的吗？我抓包，怎么没有，直接Dalvik/2.1.0 (Linux; U……这样的，尴尬

**Comment by lxk0301** [comment]
> UA格式都是jdapp开头的吗？我抓包，怎么没有，直接Dalvik/2.1.0 (Linux; U……这样的，尴尬

也有这种格式的

![image](https://user-images.githubusercontent.com/21308593/100215144-a3144780-2f4b-11eb-8fca-847a872526d0.png)
