### ISSUE TITLE
腾讯云云函数 GitHub Action部署教程 无法传递JD_COOKIE

### ISSUE THREAD

**Issue by Jumeng-ms** [lxk0301/jd_scripts#130]
在github 设置好 JD_COOKIE 然后再部署过去腾讯云那边，其他设置好的环境变量能传递，JD_COOKIE没传递成功（我的是多个cookie）。昨天一直签到不成功说没有cookie，然后今天在腾讯云函数哪里设置好JD_COOKIE就能签到

**Comment by iouAkira** [comment]
> 在github 设置好 JD_COOKIE 然后再部署过去腾讯云那边，其他设置好的环境变量能传递，JD_COOKIE没传递成功（我的是多个cookie）。昨天一直签到不成功说没有cookie，然后今天在腾讯云函数哪里设置好JD_COOKIE就能签到

多 `cookie` 要用 `&` 不要用换行。`sed`  往 `serverless.yml` 写的时候不方便处理

**Comment by Jumeng-ms** [comment]
> > 在github 设置好 JD_COOKIE 然后再部署过去腾讯云那边，其他设置好的环境变量能传递，JD_COOKIE没传递成功（我的是多个cookie）。昨天一直签到不成功说没有cookie，然后今天在腾讯云函数哪里设置好JD_COOKIE就能签到
> 
> 多 `cookie` 要用 `&` 不要用换行。`sed` 往 `serverless.yml` 写的时候不方便处理

换行和&都试过我都传输不到过去。昨天用开始用& 然后好像第一个有个空格然后换了换行，今天早上再换& 保证没有多余空格 还是不行，然后直接自己添加变量然后才可以。个例？

**Comment by doudou628** [comment]
Github Action 部署到腾讯云Secrets环境变量除了填写TENCENT_SECRET_ID和TENCENT_SECRET_KEY值，还需要填哪些？action之后没有传递到腾讯云

**Comment by iouAkira** [comment]
> > > 在github 设置好 JD_COOKIE 然后再部署过去腾讯云那边，其他设置好的环境变量能传递，JD_COOKIE没传递成功（我的是多个cookie）。昨天一直签到不成功说没有cookie，然后今天在腾讯云函数哪里设置好JD_COOKIE就能签到
> > 
> > 
> > 多 `cookie` 要用 `&` 不要用换行。`sed` 往 `serverless.yml` 写的时候不方便处理
> 
> 换行和&都试过我都传输不到过去。昨天用开始用& 然后好像第一个有个空格然后换了换行，今天早上再换& 保证没有多余空格 还是不行，然后直接自己添加变量然后才可以。个例？

把空格之类的也都删掉试试吧
![image](https://user-images.githubusercontent.com/6993269/99754367-3819d980-2b23-11eb-9ee3-c8a0be4e1bc0.png)

**Comment by iouAkira** [comment]
> TENCENT_SECRET_ID和TENCENT_SECRET_KEY

TENCENT_SECRET_ID和TENCENT_SECRET_KEY 是部署用的，不需要传到腾讯云函数，其他的要配置什么看自己需求
[点这里](https://github.com/lxk0301/jd_scripts/blob/master/githubAction.md#%E4%B8%8B%E6%96%B9%E6%8F%90%E4%BE%9B%E4%BD%BF%E7%94%A8%E5%88%B0%E7%9A%84-secrets%E5%85%A8%E9%9B%86%E5%90%88)

**Comment by Jumeng-ms** [comment]
> Github Action 部署到腾讯云Secrets环境变量除了填写TENCENT_SECRET_ID和TENCENT_SECRET_KEY值，还需要填哪些？action之后没有传递到腾讯云

se

> > > > 在github 设置好 JD_COOKIE 然后再部署过去腾讯云那边，其他设置好的环境变量能传递，JD_COOKIE没传递成功（我的是多个cookie）。昨天一直签到不成功说没有cookie，然后今天在腾讯云函数哪里设置好JD_COOKIE就能签到
> > > 
> > > 
> > > 多 `cookie` 要用 `&` 不要用换行。`sed` 往 `serverless.yml` 写的时候不方便处理
> > 
> > 
> > 换行和&都试过我都传输不到过去。昨天用开始用& 然后好像第一个有个空格然后换了换行，今天早上再换& 保证没有多余空格 还是不行，然后直接自己添加变量然后才可以。个例？
> 
> 把空格之类的也都删掉试试吧
> ![image](https://user-images.githubusercontent.com/6993269/99754367-3819d980-2b23-11eb-9ee3-c8a0be4e1bc0.png)

有空再试了，现在能用，不折腾了，在腾讯更换cookies 也挺方便的

**Comment by Jumeng-ms** [comment]
> Github Action 部署到腾讯云Secrets环境变量除了填写TENCENT_SECRET_ID和TENCENT_SECRET_KEY值，还需要填哪些？action之后没有传递到腾讯云

默认添加到HK的可以切换地区看下，Secrets看这里需要什么添加什么 [https://github.com/lxk0301/jd_scripts/blob/master/githubAction.md#%E4%B8%8B%E6%96%B9%E6%8F%90%E4%BE%9B%E4%BD%BF%E7%94%A8%E5%88%B0%E7%9A%84-secrets%E5%85%A8%E9%9B%86%E5%90%88](url)

**Comment by tommyhe1217** [comment]
> 然后今天在腾讯云函数哪里设置好JD_COOKIE就能签到

请问你是如何在腾讯云函数里设置JD_COOKIE的，求指导。

**Comment by Jumeng-ms** [comment]
> > 然后今天在腾讯云函数哪里设置好JD_COOKIE就能签到
> 
> 请问你是如何在腾讯云函数里设置JD_COOKIE的，求指导。

函数服务-函数名称（scf-jdscript）-函数配置-编辑-环境变量   
添加即可，添加后可以直接改index.js测试
'use strict';
exports.main_handler = async (event, context, callback) => {
  require('./xxxxx.js') //这里写你想要的脚本
}
测试cookie 没问题的换回原来的代码

**Comment by doudou628** [comment]
谢谢大佬解答，不过还是部属不到云函数，放弃了
![image](https://user-images.githubusercontent.com/67134811/99770244-7ffc2900-2b42-11eb-97f7-fc7de8c76300.png)
![image](https://user-images.githubusercontent.com/67134811/99770253-825e8300-2b42-11eb-874a-2f3cea6d7c1b.png)

**Comment by Jumeng-ms** [comment]
> 谢谢大佬解答，不过还是部属不到云函数，放弃了
> ![image](https://user-images.githubusercontent.com/67134811/99770244-7ffc2900-2b42-11eb-97f7-fc7de8c76300.png)
> ![image](https://user-images.githubusercontent.com/67134811/99770253-825e8300-2b42-11eb-874a-2f3cea6d7c1b.png)

你的action 少了个"部署到腾讯云函数" 你删除重新fork 一下

**Comment by doudou628** [comment]
不是说不能fork吗 ，我是克隆的 难怪不行呢

**Comment by Jumeng-ms** [comment]
> 不是说不能fork吗 ，我是克隆的 难怪不行呢

克隆应该也可以啊是看看是不是缺少了文件

**Comment by doudou628** [comment]
嗯嗯 谢谢大佬解答

**Comment by tommyhe1217** [comment]
![image](https://user-images.githubusercontent.com/66045818/99772890-94dabb80-2b46-11eb-8539-7acd38283773.png)
这里部署完ccookie信息后，再同步部署到腾讯云函数就可以了。

**Comment by Jumeng-ms** [comment]
> ![image](https://user-images.githubusercontent.com/66045818/99772890-94dabb80-2b46-11eb-8539-7acd38283773.png)
> 这里部署完ccookie信息后，再同步部署到腾讯云函数就可以了。

同步代码  作者对文件修改的话，这里会被覆盖

**Comment by jokersjjj** [comment]
我也遇到过 我找到的问题是直接从浏览器复制过来的cookie在pt_pin前面的分号“；”会有一个空格，把空格删掉就传过去了。

**Comment by Jone2008** [comment]
就在云函数里面的香港服务器里查看一下，就是在那里，看到该函数里面的环境变量就看得到全部了

**Comment by bluewatercg** [comment]
> 就在云函数里面的香港服务器里查看一下，就是在那里，看到该函数里面的环境变量就看得到全部了

编辑函数，查看环境变量哪里

**Comment by Paladinhanxiao** [comment]
> 
> 
> > > 然后今天在腾讯云函数哪里设置好JD_COOKIE就能签到
> > 
> > 
> > 请问你是如何在腾讯云函数里设置JD_COOKIE的，求指导。
> 
> 函数服务-函数名称（scf-jdscript）-函数配置-编辑-环境变量
> 添加即可，添加后可以直接改index.js测试
> 'use strict';
> exports.main_handler = async (event, context, callback) => {
> require('./xxxxx.js') //这里写你想要的脚本
> }
> 测试cookie 没问题的换回原来的代码

我看您是规避了这个问题吧？ 但是无法传递cookie的问题还是没有得到有效解决。

**Comment by iouAkira** [comment]
> > > > 然后今天在腾讯云函数哪里设置好JD_COOKIE就能签到
> > > 
> > > 
> > > 请问你是如何在腾讯云函数里设置JD_COOKIE的，求指导。
> > 
> > 
> > 函数服务-函数名称（scf-jdscript）-函数配置-编辑-环境变量
> > 添加即可，添加后可以直接改index.js测试
> > 'use strict';
> > exports.main_handler = async (event, context, callback) => {
> > require('./xxxxx.js') //这里写你想要的脚本
> > }
> > 测试cookie 没问题的换回原来的代码
> 
> 我看您是规避了这个问题吧？ 但是无法传递cookie的问题还是没有得到有效解决。

有没有解决，你看最新的说明试了吗？
