### ISSUE TITLE
jd_bean_sign.js 报错

### ISSUE THREAD

**Issue by jmluang** [lxk0301/jd_scripts#131]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [x] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：定时任务运行的时候报错，无签到，无结果通知。手动执行能收到结果

### (2) 详细日志
A：
```
HTTPError: Response code 414 (Request-URI Too Large)
    at Request.<anonymous> (/scripts/node_modules/got/dist/source/as-promise/index.js:117:42)
    at processTicksAndRejections (internal/process/task_queues.js:97:5) {
  code: undefined,
  timings: {
    start: 1605838403663,
    socket: 1605838403665,
    lookup: 1605838403665,
    connect: 1605838403667,
    secureConnect: 1605838403674,
    upload: 1605838403674,
    response: 1605838403676,
    end: 1605838403677,
    error: undefined,
    abort: undefined,
    phases: {
      wait: 2,
      dns: 0,
      tcp: 2,
      tls: 7,
      request: 0,
      firstByte: 2,
      download: 1,
      total: 14
    }
  }
}
```

### (1) Node.js版本

A：v12.18.4

### (2) npm版本

A：6.14.6

### (3)npm install的日志

A：
audited 205 packages in 2.211s

11 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

**Comment by lxk0301** [comment]
![image](https://user-images.githubusercontent.com/21308593/99750495-74493c00-2b1b-11eb-94ac-f7451313960e.png)


看到这个提示说明了吗？

**Comment by jmluang** [comment]
> ![image](https://user-images.githubusercontent.com/21308593/99750495-74493c00-2b1b-11eb-94ac-f7451313960e.png)
> 
> 看到这个提示说明了吗？

我只用到tg了阿

**Comment by lxk0301** [comment]
你是 bark等于后面的=""  引号没有删除吧？

**Comment by lxk0301** [comment]
> > ![image](https://user-images.githubusercontent.com/21308593/99750495-74493c00-2b1b-11eb-94ac-f7451313960e.png)
> > 看到这个提示说明了吗？
> 
> 抱歉没说清楚，我只用了tg.

如果仅仅是tg的话， 我们这边目前都是推送成功的，不会报错

**Comment by jmluang** [comment]
> 你是 bark等于后面的="" 引号没有删除吧？
@lxk0301  非常感谢！我瞎了没看到，删除后确实没有了提示。

不过这个脚本确实连续两晚没执行了，同时间的脚本执行没问题，所以我怀疑是这个脚本的问题。可惜我日志定时清空了，无其他信息可以看。。
今晚保留日志看看。非常感谢！

**Comment by lxk0301** [comment]
> > 你是 bark等于后面的="" 引号没有删除吧？
> > @lxk0301  非常感谢！我瞎了没看到，删除后确实没有了提示。
> 
> 不过这个脚本确实连续两晚没执行了，同时间的脚本执行没问题，所以我怀疑是这个脚本的问题。可惜我日志定时清空了，无其他信息可以看。。
> 今晚保留日志看看。非常感谢！

是这样的 。之前为了兼容腾讯云函数， 所以把下载的路径多添加了tmp文件夹， 你具体可以看看docker方法一中里面的readme

**Comment by lxk0301** [comment]
https://github.com/lxk0301/jd_scripts/blob/master/docker/crontab_list_ts.sh#L15

按这里的，重新修改一下即可

**Comment by iouAkira** [comment]
> https://github.com/lxk0301/jd_scripts/blob/master/docker/crontab_list_ts.sh#L15
> 
> 按这里的，重新修改一下即可

使用了自定自定义任务的话需要，不过要注意下

**Comment by iouAkira** [comment]
> https://github.com/lxk0301/jd_scripts/blob/master/docker/crontab_list_ts.sh#L15
> 
> 按这里的，重新修改一下即可

使用了自定自定义任务的话需要，不过要注意下 
如果很久没更新镜像的话 按这里
https://github.com/lxk0301/jd_scripts/blob/master/docker/crontab_list.sh#L15
如果更新了镜像的话 按这里
https://github.com/lxk0301/jd_scripts/blob/master/docker/crontab_list_ts.sh#L15

**Comment by jmluang** [comment]
感谢两位！更新镜像后解决了👍

**Comment by xuelang7009** [comment]
Error: Cannot find module '/home/runner/jd_scripts/jd_plantBean.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Error: Process completed with exit code 1.

**Comment by Yue-xin97** [comment]
Error: in method 'console_log', argument 1 of type 'char *'
    at Socket.process.stderr.write.console._stderr.write.console._stdout.write.process.stdout.write (/var/runtime/node12/WrapLog.js:24:14)
    at execSync (child_process.js:664:20)
    at execSign (/var/user/jd_bean_sign.js:64:11)
    at /var/user/jd_bean_sign.js:47:13
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
腾讯云里面运行签到会报这个错误该怎么解决?

**Comment by lxk0301** [comment]
> Error: in method 'console_log', argument 1 of type 'char *'
> at Socket.process.stderr.write.console._stderr.write.console._stdout.write.process.stdout.write (/var/runtime/node12/WrapLog.js:24:14)
> at execSync (child_process.js:664:20)
> at execSign (/var/user/jd_bean_sign.js:64:11)
> at /var/user/jd_bean_sign.js:47:13
> at processTicksAndRejections (internal/process/task_queues.js:97:5)
> 腾讯云里面运行签到会报这个错误该怎么解决?

暂不知
