### ISSUE TITLE
惊喜工厂报错

### ISSUE THREAD

**Issue by lsh26** [lxk0301/jd_scripts#134]
当用户未开通惊喜工厂时会产生报错
发电机：当前 0 电力，最大值 300 电力
完成任务：共领取0电力
(node:23120) UnhandledPromiseRejectionWarning: ReferenceError: productionId is not defined
    at /usr/local/jd/scripts/jd_dreamFactory.js:132:90
    at new Promise (<anonymous>)
    at investElectric (/usr/local/jd/scripts/jd_dreamFactory.js:131:10)
    at jdDreamFactory (/usr/local/jd/scripts/jd_dreamFactory.js:80:9)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async /usr/local/jd/scripts/jd_dreamFactory.js:56:7
(Use `node --trace-warnings ...` to show where the warning was created)
(node:23120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:23120) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

**Comment by id77** [comment]
@lsh26 生产进度：15%
发电机：当前 300 电力，最大值 300 电力
发电机：电力可翻倍并收获
收取 0 电力
任务：每日开工打卡可完成
领取每日开工打卡任务奖励成功，收获：100电力

❗️京喜工厂, 错误!
ReferenceError: Can't find variable: Atomics
成功投入电力700电力
打工电力：收取失败，明日才可领取

**Comment by lxk0301** [comment]
> 当用户未开通惊喜工厂时会产生报错
> 发电机：当前 0 电力，最大值 300 电力
> 完成任务：共领取0电力
> (node:23120) UnhandledPromiseRejectionWarning: ReferenceError: productionId is not defined
> at /usr/local/jd/scripts/jd_dreamFactory.js:132:90
> at new Promise ()
> at investElectric (/usr/local/jd/scripts/jd_dreamFactory.js:131:10)
> at jdDreamFactory (/usr/local/jd/scripts/jd_dreamFactory.js:80:9)
> at processTicksAndRejections (internal/process/task_queues.js:93:5)
> at async /usr/local/jd/scripts/jd_dreamFactory.js:56:7
> (Use `node --trace-warnings ...` to show where the warning was created)
> (node:23120) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
> (node:23120) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

已做处理，
