### ISSUE TITLE
serverless.yml 怎么使用，deploy_tencent_scf.yml 已经有了但actions中不显示，

### ISSUE THREAD

**Issue by bluewatercg** [lxk0301/jd_scripts#135]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否仔细阅读了教程
- [x ] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [x ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：serverless.yml 怎么使用，deploy_tencent_scf.yml 已经有了但actions中不显示，
已经import 了，环境变量也社会好了
repo_sync.的任务可以看到
deploy_tencent_scf任务看不到，请问如何设置
![image](https://user-images.githubusercontent.com/16874662/99776998-a45d0300-2b4c-11eb-97c4-20c9966ed744.png)

### (2) 详细日志
A：serverless.yml 怎么使用，deploy_tencent_scf.yml 已经有了但actions中不显示，

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by umichan0621** [comment]
2个key填一下，运行下action就部署到tx了

**Comment by lxk0301** [comment]
https://github.com/lxk0301/jd_scripts/issues/158

**Comment by lxk0301** [comment]
![990AAC75-6DCD-465C-B321-C4783BE9A498](https://user-images.githubusercontent.com/21308593/99957132-23a73c80-2dc2-11eb-8bee-44ce5cd0ebe9.png)

**Comment by lxk0301** [comment]
![AE675FF4-6D6A-47D2-A9F9-F4045FC5FF3C](https://user-images.githubusercontent.com/21308593/99957222-4a657300-2dc2-11eb-8753-2f2abdef4df0.jpeg)

**Comment by bluewatercg** [comment]
> 2个key填一下，运行下action就部署到tx了，workflow文件编辑下稍微改改看看

引用项目方式的问题，我之前是导入项目的，所以不行

**Comment by bluewatercg** [comment]
这个问题已经解决了，大佬帮忙fixed下
