### ISSUE TITLE
建议更改Server酱发送的逻辑

### ISSUE THREAD

**Issue by happyzjhao** [lxk0301/jd_scripts#136]
## 期望增加的功能

A：希望Server酱可以一起发送失效的账号信息，Server酱一下子发送次数太多会被拉黑，碰到昨天的bug就会有点危险

## 入口

A：

**Comment by lxk0301** [comment]
不好弄, 只能增加每次发消息的间隔时间

**Comment by happyzjhao** [comment]
> 不好弄, 只能增加每次发消息的间隔时间

好吧，那就算了
