### ISSUE TITLE
建议摇钱树金果不要自动兑换成金币

### ISSUE THREAD

**Issue by hjfmailbox** [lxk0301/jd_scripts#137]
## 期望增加的功能

A：建议摇钱树金果不要自动兑换成金币，因为金币有有效期。或者利用Secret自由控制

**Comment by lxk0301** [comment]
已加。具体去看环境变量

**Comment by hjfmailbox** [comment]
MONEY_TREE_SELL_FRUIT
参数好像没有起作用，部署时没有看到添加到环境变量
![image](https://user-images.githubusercontent.com/24580456/100309978-161ecc00-2fe7-11eb-93d7-fffcd0eb7b3c.png)

**Comment by lxk0301** [comment]
@hjfmailbox 可能是云函数那块没增加
