### ISSUE TITLE
萌宠关闭通知后，勋章完成也不通知，希望像水果那样只关闭日常通知，勋章完成，强制通知。

### ISSUE THREAD

**Issue by AboutCXJ** [lxk0301/jd_scripts#139]
## 期望增加的功能

A：萌宠关闭通知后，勋章完成也不通知，希望像水果那样只关闭日常通知，勋章完成，强制通知。

## 入口

A：。。

**Comment by lxk0301** [comment]
现在本来就有这功能啊

**Comment by AboutCXJ** [comment]
<img width="625" alt="截屏2020-11-21 下午3 43 34" src="https://user-images.githubusercontent.com/19811825/99870730-645f5400-2c10-11eb-8ab4-8bff32f77e6d.png">
今天有一个账号徽章 完成了没有通知

**Comment by lxk0301** [comment]
> <img alt="截屏2020-11-21 下午3 43 34" width="625" src="https://user-images.githubusercontent.com/19811825/99870730-645f5400-2c10-11eb-8ab4-8bff32f77e6d.png">
> 
> 今天有一个账号徽章 完成了没有通知

这问题我知道, 等你今天第二次运行的时候,就会提醒了的

**Comment by AboutCXJ** [comment]
> > <img alt="截屏2020-11-21 下午3 43 34" width="625" src="https://user-images.githubusercontent.com/19811825/99870730-645f5400-2c10-11eb-8ab4-8bff32f77e6d.png">
> > 今天有一个账号徽章 完成了没有通知
> 
> 这问题我知道, 等你今天第二次运行的时候,就会提醒了的

我手动运行了2次 ,都没收到

**Comment by lxk0301** [comment]
> > > <img alt="截屏2020-11-21 下午3 43 34" width="625" src="https://user-images.githubusercontent.com/19811825/99870730-645f5400-2c10-11eb-8ab4-8bff32f77e6d.png">
> > > 今天有一个账号徽章 完成了没有通知
> > 
> > 
> > 这问题我知道, 等你今天第二次运行的时候,就会提醒了的
> 
> 我手动运行了2次 ,都没收到

 不应该啊, 你看看日志,有没有发送的log

**Comment by AboutCXJ** [comment]
> > > > <img alt="截屏2020-11-21 下午3 43 34" width="625" src="https://user-images.githubusercontent.com/19811825/99870730-645f5400-2c10-11eb-8ab4-8bff32f77e6d.png">
> > > > 今天有一个账号徽章 完成了没有通知
> > > 
> > > 
> > > 这问题我知道, 等你今天第二次运行的时候,就会提醒了的
> > 
> > 
> > 我手动运行了2次 ,都没收到
> 
> 不应该啊, 你看看日志,有没有发送的log

<img width="762" alt="截屏2020-11-21 下午3 59 38" src="https://user-images.githubusercontent.com/19811825/99871060-9d002d00-2c12-11eb-99bc-3f448a2151ef.png">
没有发送，直接就下一个号了

**Comment by lxk0301** [comment]
我把符合可以兑换的条件写死 是可以推送的,你这边没有推送可能是 京东那边异常数据没更新, 要不就是京东已经改了 符合兑换 的条件
![image](https://user-images.githubusercontent.com/21308593/99871350-8e1a7a00-2c14-11eb-89a7-f58f24ef84d0.png)

**Comment by lxk0301** [comment]
![image](https://user-images.githubusercontent.com/21308593/99871357-ad190c00-2c14-11eb-85a6-91e8c6f22579.png)
之前满足的条件是一个等于5,一个为true. 

我这边手上没有成功的萌宠好, 看不到新的数据,  

要不你就发送你的京东cookie给我邮件我测试一下, 然后等我测试完毕,你再退出登录或者修改密码使其cookie过期,

要不你就自己抓包看看上面两个数据



要不就是继续等我这边有可成功兑换的萌宠号

**Comment by AboutCXJ** [comment]
> ![image](https://user-images.githubusercontent.com/21308593/99871357-ad190c00-2c14-11eb-85a6-91e8c6f22579.png)
> 之前满足的条件是一个等于5,一个为true.
> 
> 我这边手上没有成功的萌宠好, 看不到新的数据,
> 
> 要不你就发送你的京东cookie给我邮件我测试一下, 然后等我测试完毕,你再退出登录或者修改密码使其cookie过期,
> 
> 要不你就自己抓包看看上面两个数据
> 
> 要不就是继续等我这边有可成功兑换的萌宠号

你邮箱多少
