### ISSUE TITLE
请问每一次版本更新，我群晖里的docker要不要手动去删除原来的容器，再添加新的？

### ISSUE THREAD

**Issue by yeli008** [lxk0301/jd_scripts#141]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ ] 没有类似的issue 

Q：是否仔细阅读了教程
- [ ] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
只有docker镜像更新你才需要重新部署容器，其他时候不需要。

**Comment by yeli008** [comment]
我看docker hub里显示4天前updated，我是大概1周前拉的容器，是不是要把容器删掉重新添加？

**Comment by EvineDeng** [comment]
容器和镜像都删除后重新拉取并部署。

**Comment by zwb0619** [comment]
docker部署，重新拉取镜像，没发现有镜像有更新
用群晖部署的镜像。
另外，我自己修改的my_crontab_list.sh，发现导入镜像后，crontab -l 出来的结果和my_crontab_list.sh的内容不一致
