### ISSUE TITLE
云函数是不支持种豆吗？

### ISSUE THREAD

**Issue by chihwell** [lxk0301/jd_scripts#143]
我发现部署到云函数运行后，种豆不会执行，所以想问下是云函数的问题吗？

**Comment by xiaojie1234** [comment]
TypeError: 'caller', 'callee', and 'arguments' properties may not be accessed on strict mode functions or the arguments objects for calls to them!

**Comment by lxk0301** [comment]
把index.js里面的'use strict';删掉

**Comment by chihwell** [comment]
> 把index.js里面的'use strict';删掉

谢谢大佬，农场也一样的问题，同样删除'use strict'就能解决吗？

**Comment by lxk0301** [comment]
> > 把index.js里面的'use strict';删掉
> 
> 谢谢大佬，农场也一样的问题，同样删除'use strict'就能解决吗？

是 ，不过你所有的脚本， 不都是一个云函数么？  一个云函数的话， 都是经过这个公用index.js啊
