### ISSUE TITLE
东东超市bug

### ISSUE THREAD

**Issue by xiaojie1234** [lxk0301/jd_scripts#144]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [x] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：没有加入商圈无法做任务

### (2) 详细日志
A： 京小超, 失败! 原因: TypeError: Cannot read property 'teamName' of undefined!

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by lxk0301** [comment]
更新使用最新脚本即可。早上已经提交解决了

**Comment by xiaojie1234** [comment]
> 更新使用最新脚本即可。早上已经提交解决了

ok，谢谢
