### ISSUE TITLE
取消关注功能代码有误

### ISSUE THREAD

**Issue by indingpig** [lxk0301/jd_scripts#146]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [x] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：取消关注商品的功能，代码有点小问题，在jd_unsubscribe.js文件104行，如果是indexOf的话，那不应该=== 0；匹配的文字不一定会在0位，改成!== -1才能实现需求；或者indexOf改成includes方法

### (2) 详细日志
A：

### (1) Node.js版本

A：v14.15.1

### (2) npm版本

A：6.14.8

### (3)npm install的日志

A：

**Comment by lxk0301** [comment]
也不能说有误。最开始的构想是匹配全部数据。输入全部的名称

**Comment by lxk0301** [comment]
已修改
