### ISSUE TITLE
arm64架构的docker镜像时区有问题

### ISSUE THREAD

**Issue by ericwang2006** [lxk0301/jd_scripts#149]
测试方法, 在arm64的设备上运行
```
docker run --rm --privileged=true akyakya/jd_scripts /bin/date
```
显示的不是东8区时间，x86架构的镜像没有这个问题问题
此问题可能是由于批量多架构编译导致的，目前原因不详，我自己批量生成7中架构的docker镜像也有这个问题
但是一次只编译一种arm64架构的docker镜像就没有这个问题
我自己重新编译了一次这个镜像，目前显示正常，下面是测试日志
```
root@volumio-hall:~# docker run --rm --privileged=true akyakya/jd_scripts /bin/date  && docker run --rm --privileged=true ericwang2006/jd_scripts /bin/date
Sun Nov 22 15:26:20  2020
Sun Nov 22 23:26:26 CST 2020
```

**Comment by zhuzf88** [comment]
我有两台armbian，一台arm64，一台armhf，arm64的docker时间正常，armhf的docker时间为utc时间。

**Comment by ericwang2006** [comment]
> 我有两台armbian，一台arm64，一台armhf，arm64的docker时间正常，armhf的docker时间为utc时间。

我的是armhf， 看来和系统有关系

**Comment by Qliangw** [comment]
我群晖里的docker时区也是不正常的...求教 怎么解决
