### ISSUE TITLE
建议增加延时做任务功能

### ISSUE THREAD

**Issue by jw10126121** [lxk0301/jd_scripts#150]
## 期望增加的功能

A：目前发现因为批量领京豆导致黑号1个月，常看到领京豆间隔时间1秒，是否可以增加一个功能，用来随机一个时间来延时做任务，或者延时领豆，看是否能有效避免这个问题。

## 入口

A：目前发现因为批量领京豆导致黑号1个月，常看到领京豆间隔时间1秒，是否可以增加一个功能，用来随机一个时间来延时做任务，或者延时领豆，看是否能有效避免这个问题。

**Comment by lxk0301** [comment]
黑号也不是这个导致的， 我自己号一直没问题 

你要延迟 ，就加这个环境变量

![image](https://user-images.githubusercontent.com/21308593/99924381-0dbf5a80-2d75-11eb-8af5-20088981da53.png)

**Comment by jw10126121** [comment]
> 黑号也不是这个导致的， 我自己号一直没问题
> 
> 你要延迟 ，就加这个环境变量
> 
> ![image](https://user-images.githubusercontent.com/21308593/99924381-0dbf5a80-2d75-11eb-8af5-20088981da53.png)

就是有发现这个问题，所以，看这个时间，是否延时个随机时间，这样是不是更好一点？

**Comment by yjjuneyjj** [comment]
显示火爆，就拿京豆去充点话费；或者添加一个大额商品，建立一个大额付费订单，然后不付费取消掉，可能影响账号隐藏评级。

**Comment by jw10126121** [comment]
> 显示火爆，就拿京豆去充点话费；或者添加一个大额商品，建立一个大额付费订单，然后不付费取消掉，可能影响账号隐藏评级。


账号隐藏评级？

**Comment by lxk0301** [comment]
账号会黑 ， 估计就是小号，或者万年不买东西的号吧， 这么多人用， 并没见过使用了京豆签到被黑的

**Comment by jw10126121** [comment]
> 账号会黑 ， 估计就是小号，或者万年不买东西的号吧， 这么多人用， 并没见过使用了京豆签到被黑的

并不是小号，是一直买东西，并且还是plus会员。。

**Comment by lxk0301** [comment]
@jw10126121 去这里提这issue吧，
https://github.com/NobyDa/Script/issues

**Comment by jw10126121** [comment]
> @jw10126121 去这里提这issue吧，
> https://github.com/NobyDa/Script/issues

好的。辛苦大佬了。

**Comment by jw10126121** [comment]
> @jw10126121 去这里提这issue吧，
> https://github.com/NobyDa/Script/issues

延时功能，最好是所有能延时的任务都有，而不局限签到延时。

**Comment by zhuzf88** [comment]
> ## 期望增加的功能
> A：目前发现因为批量领京豆导致黑号1个月，常看到领京豆间隔时间1秒，是否可以增加一个功能，用来随机一个时间来延时做任务，或者延时领豆，看是否能有效避免这个问题。
> 
> ## 入口
> A：目前发现因为批量领京豆导致黑号1个月，常看到领京豆间隔时间1秒，是否可以增加一个功能，用来随机一个时间来延时做任务，或者延时领豆，看是否能有效避免这个问题。

你怎么判断黑号的？一个月是指已经黑了一个月？现在账号信誉评级是几星？

**Comment by jw10126121** [comment]
> > ## 期望增加的功能
> > A：目前发现因为批量领京豆导致黑号1个月，常看到领京豆间隔时间1秒，是否可以增加一个功能，用来随机一个时间来延时做任务，或者延时领豆，看是否能有效避免这个问题。
> > ## 入口
> > A：目前发现因为批量领京豆导致黑号1个月，常看到领京豆间隔时间1秒，是否可以增加一个功能，用来随机一个时间来延时做任务，或者延时领豆，看是否能有效避免这个问题。
> 
> 你怎么判断黑号的？一个月是指已经黑了一个月？现在账号信誉评级是几星？

领取不了优惠券，打电话去官方问。
