### ISSUE TITLE
云函数运行返回数据:null

### ISSUE THREAD

**Issue by erudite72** [lxk0301/jd_scripts#153]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否仔细阅读了教程
- [x ] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [x ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：action部署到腾讯云函数，测试后返回数据null，server酱没有推送

### (2) 详细日志
A：返回数据:

null

日志:

START RequestId: 1de568b4-0674-4606-b35a-9507445c9ad2

Event RequestId: 1de568b4-0674-4606-b35a-9507445c9ad2

2020-11-23T03:53:32.042Z 1de568b4-0674-4606-b35a-9507445c9ad2 TypeError: Cannot read property 'split' of undefined

    at Runtime.exports.main_handler [as handler] (/var/user/index.js:6:40)

    at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:215:23)

    at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:55:12)

    at listOnTimeout (internal/timers.js:549:17)

    at processTimers (internal/timers.js:492:7)

 

END RequestId: 1de568b4-0674-4606-b35a-9507445c9ad2

Report RequestId: 1de568b4-0674-4606-b35a-9507445c9ad2 Duration:1ms Memory:128MB MemUsage:52.792969MB

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by lxk0301** [comment]
这里有类似的
https://github.com/lxk0301/jd_scripts/issues/132

**Comment by erudite72** [comment]
![image](https://user-images.githubusercontent.com/38214509/99931503-bbd7fe00-2d8f-11eb-935a-1398d370c080.png)
改成本地运行后，调用成功，返回数据null

日志：返回数据:

null

日志:

START RequestId: a03795c9-7683-493e-8a6d-c7c323298f29

Event RequestId: a03795c9-7683-493e-8a6d-c7c323298f29

2020-11-23T05:26:59.186Z a03795c9-7683-493e-8a6d-c7c323298f29 TypeError: Cannot read property 'split' of undefined

    at Runtime.exports.main_handler [as handler] (/var/user/index.js:6:40)

    at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:215:23)

    at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:55:12)

    at listOnTimeout (internal/timers.js:549:17)

    at processTimers (internal/timers.js:492:7)

 

END RequestId: a03795c9-7683-493e-8a6d-c7c323298f29

Report RequestId: a03795c9-7683-493e-8a6d-c7c323298f29 Duration:7ms Memory:128MB MemUsage:13.671875MB

**Comment by lxk0301** [comment]
> ![image](https://user-images.githubusercontent.com/38214509/99931503-bbd7fe00-2d8f-11eb-935a-1398d370c080.png)
> 改成本地运行后，调用成功，返回数据null
> 
> 日志：返回数据:
> 
> null
> 
> 日志:
> 
> START RequestId: a03795c9-7683-493e-8a6d-c7c323298f29
> 
> Event RequestId: a03795c9-7683-493e-8a6d-c7c323298f29
> 
> 2020-11-23T05:26:59.186Z a03795c9-7683-493e-8a6d-c7c323298f29 TypeError: Cannot read property 'split' of undefined
> 
> ```
> at Runtime.exports.main_handler [as handler] (/var/user/index.js:6:40)
> 
> at Runtime.handleOnce (/var/runtime/node12/Runtime.engine.js:215:23)
> 
> at Timeout._onTimeout (/var/runtime/node12/Runtime.engine.js:55:12)
> 
> at listOnTimeout (internal/timers.js:549:17)
> 
> at processTimers (internal/timers.js:492:7)
> ```
> 
> END RequestId: a03795c9-7683-493e-8a6d-c7c323298f29
> 
> Report RequestId: a03795c9-7683-493e-8a6d-c7c323298f29 Duration:7ms Memory:128MB MemUsage:13.671875MB

貌似是cookie的问题。从action导过来的cookie会有问题

**Comment by erudite72** [comment]
![image](https://user-images.githubusercontent.com/38214509/99936758-dcf41b00-2d9e-11eb-9520-ccddc6ea6aca.png)
那我这也没法修改cookie呀

**Comment by lxk0301** [comment]
cookie又不是在这里修改， 截这个图有什么用， 去环境变量修改cookie

**Comment by Jone2008** [comment]
actions云函数自动部署，默认部署到云函数的香港服务器里

**Comment by erudite72** [comment]
云函数里改cookie就没问题了

**Comment by jpcnmm** [comment]
> 云函数里改cookie就没问题了

运到同样的错误了，怎么在云函数里改cookie啊
