### ISSUE TITLE
actions云函数自动部署 不显示在actions的workflow 中

### ISSUE THREAD

**Issue by bluewatercg** [lxk0301/jd_scripts#158]
## 1.关于你要提交的问题
actions云函数自动部署 的workflow 不显示在actions中
Q：是否搜索了issue（包括已关闭的issue）
- [ x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x ] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ x] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：actions云函数自动部署 的workflow 不显示在actions中请问如何配置，看了触发机制是
on:
  workflow_dispatch:，但就是不触发
目前sync-lxk0301-scripts这个正常运行，
![image](https://user-images.githubusercontent.com/16874662/99940155-973b5080-2da6-11eb-936a-398396d15252.png)

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by Jone2008** [comment]
deploy_tencent_scf.yml就是了 重新获取更下一下SLS_QcsRole和SCF_QcsRole把 对应的secrets别填错了

**Comment by bluewatercg** [comment]
> deploy_tencent_scf.yml就是了 重新获取更下一下SLS_QcsRole和SCF_QcsRole把 对应的secrets别填错了
我看了下本身有，
![image](https://user-images.githubusercontent.com/16874662/99941937-d1f2b800-2da9-11eb-8b32-4ae9a56b6008.png)

secrets中SLS_QcsRole和SCF_QcsRole 的Value 我应该填写哪些信息
![image](https://user-images.githubusercontent.com/16874662/99942019-f353a400-2da9-11eb-8f33-4cd58f8cea47.png)

**Comment by Jone2008** [comment]
Github Action 部署教程里面有  ：
2. 在这里新建一个访问密钥新建密钥
将SecretId和SecretKey分别配置在仓库的secrets变量里面， TENCENT_SECRET_ID对应你的SecretId的值，TENCENT_SECRET_KEY对应你的SecretKey的值

**Comment by iouAkira** [comment]
@Jone2008 这个不显示，根配置不配置那些参数没有关系，看你的仓库设置

**Comment by bluewatercg** [comment]
> TENCENT_SECRET_KEY

这2值我尝试update，但不触发，
![image](https://user-images.githubusercontent.com/16874662/99942585-e1becc00-2daa-11eb-8204-661bfad14d45.png)

**Comment by Jone2008** [comment]
> @Jone2008 这个不显示，根配置不配置那些参数没有关系，看你的仓库设置

好 一下对应错了

**Comment by bluewatercg** [comment]
> > @Jone2008 这个不显示，根配置不配置那些参数没有关系，看你的仓库设置
> 
> 好 一下对应错了
大佬是这个吗
![image](https://user-images.githubusercontent.com/16874662/99942959-75909800-2dab-11eb-9bb1-c8aacdc69bad.png)

**Comment by iouAkira** [comment]
> > > @Jone2008 这个不显示，根配置不配置那些参数没有关系，看你的仓库设置
> > 
> > 
> > 好 一下对应错了
> > 大佬是这个吗
> > ![image](https://user-images.githubusercontent.com/16874662/99942959-75909800-2dab-11eb-9bb1-c8aacdc69bad.png)

截图的workflow钩上，更新一下PAT，在同步一下主库 或者手动改一下 `deploy_tencent_scf.yml` 加个随便哪一行后面最后加个空格 保存试一下

**Comment by bluewatercg** [comment]
> > > > @Jone2008 这个不显示，根配置不配置那些参数没有关系，看你的仓库设置
> > > 
> > > 
> > > 好 一下对应错了
> > > 大佬是这个吗
> > > ![image](https://user-images.githubusercontent.com/16874662/99942959-75909800-2dab-11eb-9bb1-c8aacdc69bad.png)
> 
> 截图的workflow钩上，更新一下PAT，在同步一下主库 或者手动改一下 `deploy_tencent_scf.yml` 加个随便哪一行后面最后加个空格 保存试一下

也是过了，直接触发库的强制覆盖，就死活不执行腾讯云
![image](https://user-images.githubusercontent.com/16874662/99943744-be951c00-2dac-11eb-935e-9e64ded0e7c2.png)

**Comment by iouAkira** [comment]
好好读一下我说的2种方式，你都试过了？

**Comment by bluewatercg** [comment]
> 好好读一下我说的2种方式，你都试过了？

我不是fork 的会不会受影响

**Comment by bluewatercg** [comment]
已经搞定，感谢大佬的帮助，问题点在于我的库是导入的，我换了其他 方式正常了

**Comment by feng705470052** [comment]
有没有部署好的大佬，教下怎么弄，我部署云函数弄不出来，

**Comment by Chase2179** [comment]
腾讯函数部署的都是香港，删除重新部署还是香港，部署到国内怎么搞？
