### ISSUE TITLE
新活动「京东赚赚」

### ISSUE THREAD

**Issue by DingChang90** [lxk0301/jd_scripts#159]
## 期望增加的功能

A：增加「京东赚赚」功能

## 入口

A：群里看到的JS链接
https://raw.githubusercontent.com/whyour/hundun/master/quanx/jdzz.js

**Comment by lxk0301** [comment]
这不是有脚步了嘛😂😂

**Comment by Twinzo1** [comment]
需要token,不能使用action跑
