### ISSUE TITLE
获取20个固定的互助码建议

### ISSUE THREAD

**Issue by lsh26** [lxk0301/jd_scripts#160]
问题：
每次执行脚本时，发现获取的20个固定互助码总是已满5次助力，程序会尝试对其一个个进行助力，导致脚本执行时间被拖长。

建议：
能否增加一个可配置的参数，使程序可以配置是否要获取20个固定互助码的功能

**Comment by lxk0301** [comment]
@lsh26 云端运行时间过长也无所谓啦。手机端到到时候随机码减少吧。取5个的样子
