### ISSUE TITLE
更新一下docker镜像

### ISSUE THREAD

**Issue by jy1989** [lxk0301/jd_scripts#164]
已经7天没有更新了

[https://hub.docker.com/r/akyakya/jd_scripts/tags?page=1&ordering=last_updated](https://hub.docker.com/r/akyakya/jd_scripts/tags?page=1&ordering=last_updated)

**Comment by lxk0301** [comment]
@jy1989 ？？？？？？一脸懵

**Comment by iouAkira** [comment]
@jy1989 ？？？更新什么，脚本都是最新的
