### ISSUE TITLE
docker方法1运行时，日志里经常有错误 user root: parse error at 59

### ISSUE THREAD

**Issue by xiaoxue508** [lxk0301/jd_scripts#166]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [x] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：docker里经常有这个错误 user root: parse error at 59

### (2) 详细日志
A： 
47 files changed, 3065 insertions(+), 555 deletions(-)
 create mode 100644 .github/ISSUE_TEMPLATE/bug_report.md
 create mode 100644 .github/ISSUE_TEMPLATE/feature_request.md
 delete mode 100644 .github/pull.yml
 create mode 100644 .github/workflows/deploy_tencent_scf.yml
 create mode 100644 icon/iCloud5.png
 create mode 100644 icon/iCloud6.png
 create mode 100644 jd_necklace.js
 create mode 100644 jd_small_home.js
Welcome to Node.js v12.18.4.
Type ".help" for more information.
> crond[8]: user root: parse error at 59

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by iouAkira** [comment]
如果使用默认定时任务列表，请更新镜像。如果使用自定义，请更新镜像&自己排查问题
