### ISSUE TITLE
能否增加任务随机顺序功能,做任务自定义延迟时间设置,以防大家同一时间同一任务黑号

### ISSUE THREAD

**Issue by nickol998** [lxk0301/jd_scripts#167]
## 期望增加的功能

A：

## 入口

A：
能否增加任务随机顺序功能,做任务自定义延迟时间设置,以防大家同一时间同一任务黑号

**Comment by jw10126121** [comment]
黑号，说是，同一时间做太多任务，就是太快了，所以增加延时应该能有效防黑。。

**Comment by lxk0301** [comment]
不加，没必要

**Comment by lxk0301** [comment]
京东要想黑你号 ， 早就黑了， 不要找个延迟来心理自我安慰，没用的

**Comment by EvineDeng** [comment]
@jw10126121 你自己改cron不就错开了

**Comment by jw10126121** [comment]
要错开，是很简单，但是1秒内执行多个任务，这个得脚本实现。 

客服给的答复，就是说，后台显示01秒02毫秒完成点击1，客服回了我一句，正常点击1-3秒，卡的还有10秒点击的，所以不会是手动操作的。
