### ISSUE TITLE
京东每日签到脚本显示签到情况日志

### ISSUE THREAD

**Issue by MisterGlasses** [lxk0301/jd_scripts#176]
## 期望增加的功能

A：
希望京东每日签到脚本显示签到情况日志。
因为现在bark无法正常推送，在只使用bark推送的情况下，完全不知道签到成功与否跟详细情况，只能手动查看，但是现脚本并不打印签到情况日志，望大佬增加。

**Comment by lxk0301** [comment]
@MisterGlasses 就算是失败， 你也无能为力。日志你也不会天天去看吧， 知道拿到了多少京豆就行了吧。
或者换其他的通知方式？

**Comment by EvineDeng** [comment]
不用bark通知就可以做到很长了。

**Comment by lxk0301** [comment]
> ## 期望增加的功能
> A：
> 希望京东每日签到脚本显示签到情况日志。
> 因为现在bark无法正常推送，在只使用bark推送的情况下，完全不知道签到成功与否跟详细情况，只能手动查看，但是现脚本并不打印签到情况日志，望大佬增加。

已添加签到log记录.
![image](https://user-images.githubusercontent.com/21308593/100408176-56dd1a80-30a5-11eb-9f7c-cb7d37eaaab6.png)

**Comment by MisterGlasses** [comment]
> > ## 期望增加的功能
> > A：
> > 希望京东每日签到脚本显示签到情况日志。
> > 因为现在bark无法正常推送，在只使用bark推送的情况下，完全不知道签到成功与否跟详细情况，只能手动查看，但是现脚本并不打印签到情况日志，望大佬增加。
> 
> 已添加签到log记录.
> ![image](https://user-images.githubusercontent.com/21308593/100408176-56dd1a80-30a5-11eb-9f7c-cb7d37eaaab6.png)

麻烦了

**Comment by lxk0301** [comment]
@MisterGlasses 题外话, 话说你不是用的是 `sazs34/MyActions`的嘛,  咋到我这边提这个issues了,

**Comment by MisterGlasses** [comment]
> @MisterGlasses 题外话, 话说你不是用的是 `sazs34/MyActions`的嘛, 咋到我这边提这个issues了,

我都有在用 况且你这才是上游仓库
