### ISSUE TITLE
东东工厂报错

### ISSUE THREAD

**Issue by justcopy** [lxk0301/jd_scripts#177]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [x] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：东东工厂无法执行

### (2) 详细日志
A：

❗️东东工厂, 错误!
TypeError: Cannot read property 'bizCode' of undefined
    at /root/scripts/jd_jdfactory.js:496:27
    at got.post.then.message (/root/scripts/jd_jdfactory.js:603:5694)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

❗️东东工厂, 错误!
TypeError: Cannot read property 'bizCode' of undefined
    at /root/scripts/jd_jdfactory.js:327:27
    at got.post.then.message (/root/scripts/jd_jdfactory.js:603:5694)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

### (1) Node.js版本

A：v12.19.1

### (2) npm版本

A：6.14.8

### (3)npm install的日志

A：
npm WARN saveError ENOENT: no such file or directory, open '/root/shell/package.json'
npm WARN enoent ENOENT: no such file or directory, open '/root/shell/package.json'
npm WARN shell No description
npm WARN shell No repository field.
npm WARN shell No README data
npm WARN shell No license field.

up to date in 2.657s
found 0 vulnerabilities

**Comment by EvineDeng** [comment]
运行的shell还是运行的js？如果是shell，在哪运行的，如果是js，又在哪里运行的？

似乎你在错误路径运行了。

**Comment by justcopy** [comment]
shell 和script都运行过，shell和scrppt都一样。

**Comment by justcopy** [comment]
npm install是在shell下执行的

**Comment by EvineDeng** [comment]
> npm install是在shell下执行的

npm install必然应该在scripts下执行。。。。

**Comment by justcopy** [comment]
哦哦 ，我再试试

**Comment by justcopy** [comment]
![image](https://user-images.githubusercontent.com/45755204/100326821-6c9b0300-3005-11eb-9b8d-847d956fb3de.png)
还是一样的

**Comment by justcopy** [comment]
[root@iZbp19z scripts]# node jd_jdfactory.js 

🔔东东工厂, 开始!

******开始【京东账号1】*********


❗️东东工厂, 错误!
TypeError: Cannot read property 'bizCode' of undefined
    at /root/scripts/jd_jdfactory.js:496:27
    at got.post.then.message (/root/scripts/jd_jdfactory.js:603:5694)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

❗️东东工厂, 错误!
TypeError: Cannot read property 'bizCode' of undefined

**Comment by EvineDeng** [comment]
@lxk0301 这个得你来看了，能正常识别账号，shell似乎没问题，npm install看起来似乎也没问题。

**Comment by justcopy** [comment]
游戏肯定是开通的

**Comment by lxk0301** [comment]
> ![image](https://user-images.githubusercontent.com/45755204/100326821-6c9b0300-3005-11eb-9b8d-847d956fb3de.png)
> 还是一样的

加了一个log打印，五分钟后，跑最新的脚本，然后截图看看打印

**Comment by justcopy** [comment]
好的，那我等会重拉代码，手动执行下看看。

**Comment by lxk0301** [comment]
> 好的，那我等会重拉代码，手动执行下看看。

现在可执行了

**Comment by justcopy** [comment]
![image](https://user-images.githubusercontent.com/45755204/100328930-04015580-3008-11eb-9485-f0f74d2be5cb.png)

**Comment by lxk0301** [comment]
log显示登陆失败，。。。你是不是cookie不对，或者失效了

**Comment by justcopy** [comment]
其他都正常，就这个不行。

**Comment by justcopy** [comment]
![image](https://user-images.githubusercontent.com/45755204/100329702-fb5d4f00-3008-11eb-96ad-a09a83d7ecfc.png)

**Comment by lxk0301** [comment]
也确实奇怪， 你app上面看看此活动吧， 看看是不是活动火爆什么的

**Comment by justcopy** [comment]
app正常的，我刚才换了cookie也是不行。照理说出来用户名说明没有问题吧？

**Comment by lxk0301** [comment]
@justcopy 对，

**Comment by justcopy** [comment]
那这也太奇怪了

**Comment by lxk0301** [comment]
先关掉了 你的问题确实不知如何处理, 你如果后面解决了,再到此反馈一下吧

**Comment by justcopy** [comment]
> 先关掉了 你的问题确实不知如何处理, 你如果后面解决了,再到此反馈一下吧

知道啥问题了，添加cookie那块pt_key pt_pin 有个双引号，我删掉了。
加上问题就解决了。

**Comment by justcopy** [comment]
我是从docker到node js的。这两个cookie填写这块存在部分差异，

nodejs cookie必须加引号，要不有些脚本会提示cookie失效。
docker 版本不能加引号，要不有些脚本会提示cookie失效。

**Comment by EvineDeng** [comment]
> 我是从docker到node js的。这两个cookie填写这块存在部分差异，
> 
> nodejs cookie必须加引号，要不有些脚本会提示cookie失效。
> docker 版本不能加引号，要不有些脚本会提示cookie失效。

你可能key和pin间有个空格。

**Comment by lxk0301** [comment]
要不要引号。里面都写的很详细。是你们没去看

**Comment by justcopy** [comment]
> 要不要引号。里面都写的很详细。是你们没去看

嗯嗯，部署的时候没太注意，以为和docker是一样的。
