### ISSUE TITLE
怎么才能把自己的码加到api.turinglabs.net接口

### ISSUE THREAD

**Issue by fm1223** [lxk0301/jd_scripts#182]
想把自己的码加到api.turinglabs.net接口中，不知道行不行🤣
不行的话直接关闭issues就好😂

东东农场助力码
1e8a0f8a455a45e1934b4c4864dbbcb1
c13196155af9403480283c6ae9749e54
东东工厂助力码
P04z54XCjVWnYaS5n1RWT-rhSkU-iEooQ
P04z54XCjVWnYaS5m9cZ2Ws2i0bnN5PfNWNqmI
萌宠助力码
MTE1NDUyMjEwMDAwMDAwMzY1MzM0NTE=
MTE1NDQ5MzYwMDAwMDAwMzY2Mzk2OTM=
种豆得豆助力码
lhubofhlunfauk4ys646do6xdu5ac3f4ijdgqji
mlrdw3aw26j3whvc2wvzisch2ivzpctslsnck7i
京喜工厂分享码
PC-yzyURlilMIiB2ftCAVw==
2Ulj8cF7fqhTpQZy8nPu3Q==

**Comment by lxk0301** [comment]
莫名其妙？你既然知道就自己加

**Comment by fm1223** [comment]
> 莫名其妙？你既然知道就自己加

我只是看到了接口地址， 不知道怎么加进入呀😂

**Comment by lxk0301** [comment]
@fm1223 进群把。https://t.me/JD_fruit_pet
