### ISSUE TITLE
docker-compose部署后运行直接退出，jd_scripts exited with code 0

### ISSUE THREAD

**Issue by otary** [lxk0301/jd_scripts#185]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ x ] 没有类似的issue 

Q：是否仔细阅读了教程
- [ x ] 已仔细阅读教程 

## 2. 你使用的哪种部署方法
- [ x ] 方法三：Docker办法一

### (1) 具体问题
A：使用docker-compose部署

  jd_scripts:
    image: akyakya/jd_scripts
    container_name: jd_scripts
    volumes:
      - /data/jd_scripts/my_crontab_list.sh:/scripts/docker/my_crontab_list.sh
      - /data/jd_scripts/logs:/scripts/logs
    environment:
      - JD_COOKIE=pt_key=xxx;pt_pin=xxx;
      - JD_DEBUG=true
    command:
      - /bin/sh
      - -c
      - |
       # crontab /scripts/docker/my_crontab_list.sh
        crond
        git -C /scripts/ pull
        node

其中my_crontab_list.sh已经建在/data/jd_scripts/目录下了，并且用了推荐的默认的值了

### (2) 详细日志

Attaching to jd_scripts
jd_scripts                 | From https://github.com/lxk0301/jd_scripts
jd_scripts                 |    4cd5e34..6e81b62  master     -> origin/master
jd_scripts                 | Updating 4cd5e34..6e81b62
jd_scripts                 | Fast-forward
jd_scripts                 |  .github/ISSUE_TEMPLATE/bug_report.md      |   79 +++
jd_scripts                 |  .github/ISSUE_TEMPLATE/feature_request.md |   44 ++
jd_scripts                 |  .github/pull.yml                          |    6 -
jd_scripts                 |  .github/workflows/deploy_tencent_scf.yml  |  112 ++++
jd_scripts                 |  JD_extra_cookie.js                        |    2 +-
jd_scripts                 |  Loon/lxk0301_LoonTask.conf                |   13 +
jd_scripts                 |  README.md                                 |   15 +-
jd_scripts                 |  Surge/lxk0301_Task.sgmodule.sgmodule      |    1 +
jd_scripts                 |  backUp/jd_joy_help2.js                    |   33 +-
jd_scripts                 |  docker/crontab_list.sh                    |   16 +-
jd_scripts                 |  docker/crontab_list_ts.sh                 |   16 +-
jd_scripts                 |  githubAction.md                           |    9 +-
jd_scripts                 |  iCloud.md                                 |   31 +-
jd_scripts                 |  icon/iCloud5.png                          |  Bin 0 -> 50792 bytes
jd_scripts                 |  icon/iCloud6.png                          |  Bin 0 -> 52881 bytes
jd_scripts                 |  index.js                                  |   27 +-
jd_scripts                 |  jdCookie.js                               |    7 +-
jd_scripts                 |  jdFactoryShareCodes.js                    |   31 +
jd_scripts                 |  jd_818.js                                 |   36 +-
jd_scripts                 |  jd_bean_change.js                         |    4 +-
jd_scripts                 |  jd_bean_sign.js                           |    7 +-
jd_scripts                 |  jd_blueCoin.js                            |  221 +++---
jd_scripts                 |  jd_club_lottery.js                        |  126 +++-
jd_scripts                 |  jd_collectProduceScore.js                 |    2 +-
jd_scripts                 |  jd_daily_egg.js                           |   16 +-
jd_scripts                 |  jd_dreamFactory.js                        | 1035 +++++++++++++++++++++++------
jd_scripts                 |  jd_fruit.js                               |    8 +-
jd_scripts                 |  jd_jdfactory.js                           |  674 +++++++++++++++++++
jd_scripts                 |  jd_joy.js                                 |    6 +-
jd_scripts                 |  jd_joy_feedPets.js                        |    6 +-
jd_scripts                 |  jd_joy_reward.js                          |   39 +-
jd_scripts                 |  jd_joy_run.js                             |    4 +-
jd_scripts                 |  jd_joy_steal.js                           |    8 +-
jd_scripts                 |  jd_mohe.js                                |    4 +-
jd_scripts                 |  jd_moneyTree.js                           |   12 +-
jd_scripts                 |  jd_necklace.js                            |  309 +++++++++
jd_scripts                 |  jd_pet.js                                 |   18 +-
jd_scripts                 |  jd_pigPet.js                              |  367 +++++++++-
jd_scripts                 |  jd_plantBean.js                           |    6 +-
jd_scripts                 |  jd_redPacket.js                           |    6 +-
jd_scripts                 |  jd_shop.js                                |    6 +-
jd_scripts                 |  jd_small_home.js                          |  798 ++++++++++++++++++++++
jd_scripts                 |  jd_speed.js                               |    4 +-
jd_scripts                 |  jd_superMarket.js                         |   55 +-
jd_scripts                 |  jd_unsubscribe.js                         |   16 +-
jd_scripts                 |  jd_xtg.js                                 |   10 +-
jd_scripts                 |  lxk0301.boxjs.json                        |  117 ++--
jd_scripts                 |  sendNotify.js                             |   40 +-
jd_scripts                 |  serverless.yml                            |   69 +-
jd_scripts                 |  tencentscf.md                             |   35 +-
jd_scripts                 |  50 files changed, 3910 insertions(+), 596 deletions(-)
jd_scripts                 |  create mode 100644 .github/ISSUE_TEMPLATE/bug_report.md
jd_scripts                 |  create mode 100644 .github/ISSUE_TEMPLATE/feature_request.md
jd_scripts                 |  delete mode 100644 .github/pull.yml
jd_scripts                 |  create mode 100644 .github/workflows/deploy_tencent_scf.yml
jd_scripts                 |  create mode 100644 icon/iCloud5.png
jd_scripts                 |  create mode 100644 icon/iCloud6.png
jd_scripts                 |  create mode 100644 jdFactoryShareCodes.js
jd_scripts                 |  create mode 100644 jd_jdfactory.js
jd_scripts                 |  create mode 100644 jd_necklace.js
jd_scripts                 |  create mode 100644 jd_small_home.js
jd_scripts exited with code 0

运行docker后直接结束退出，logs目录下没有日志，请问是什么问题呢？

**Comment by EvineDeng** [comment]
logs目录下的日志不得在定时任务运行以后才会有么？

此issue建议关闭。

**Comment by iouAkira** [comment]
git -C /scripts/ pull 这一行删除在启动试一下，
