### ISSUE TITLE
关于各种活动的自己的互助码问题

### ISSUE THREAD

**Issue by a370263995** [lxk0301/jd_scripts#187]
## 期望增加的功能

A：专门添加一个日志，用来说明哪个活动，第几个账号的第几个互助码，每天执行一次的那种，(因为我添加的京东账号太多，查起来特别麻烦，所以请楼主大大们添加这个功能，，)例如:
种豆得豆活动:
账号1+名称
第1个互助码:xxx
第2个互助码:xxx
账号2+名称
第1个互助码:xxx
第2个互助码:xxx
当然，更希望是这样提示的:
种豆得豆
账号1+名称的互助码:xxx@xxx(两个)
账号2+名称的互助码:xxx@xxx@xxx(三个)

## 入口

A：

**Comment by EvineDeng** [comment]
互助码又不变，看一下日志单独记下来就这么难吗？

**Comment by a370263995** [comment]
> 互助码又不变，看一下日志单独记下来就这么难吗？
> 
> 每天都发一遍通知，岂不烦死。

啊，不好意思啊，我这里账号太多，运行的时候码不对号，造成了一些小麻烦，，

**Comment by EvineDeng** [comment]
一个账号一个游戏只有一个互助码，怎么会错号呢？

**Comment by a370263995** [comment]
如果可以的话，希望添加一个js，不会被触发，除非自己调用，比如测试它时(jd_huzhuma时)，会给出来哪个活动对应的账号的互助码，，，

**Comment by EvineDeng** [comment]
自己拿个小本本记好就行。

**Comment by taylorSZSS** [comment]
记在EXCEL里面，用公式自动分配助力对象，一对4，不会错的。5分钟搞定30个号。我就是了。

**Comment by lxk0301** [comment]
你懒想来麻烦我？  

我得到了什么？
