### ISSUE TITLE
签到脚本执行异常

### ISSUE THREAD

**Issue by YuanHuiZeng** [lxk0301/jd_scripts#191]
*****************开始京东账号15 jd_KwQOiZyWskLd京豆签到*******************

⚠️⚠️⚠️⚠️目前Bark APP推送通知消息对推送内容长度有限制，如使用此推送方式脚本会默认转换成简洁内容推送 ⚠️⚠️⚠️⚠️

开始替换变量
替换变量完毕

开始执行脚本签到，请稍等
没有提供通知推送，则打印脚本执行日志
京东签到脚本执行异常:Error: Command failed: C:\Program Files\nodejs\node.exe JD_DailyBonus.js

**Comment by lxk0301** [comment]
你这是本地PC执行的吧?  自己好好检查一下你的node环境和依赖包吧,

**Comment by xiaojie1234** [comment]
> 你这是本地PC执行的吧? 自己好好检查一下你的node环境和依赖包吧,

请问一下，云函数提示
2020-12-04T16:00:02.719Z 2dbe7a23-c6d7-46ee-9ba5-ad7066ada10a 开始替换变量
2020-12-04T16:00:02.721Z 2dbe7a23-c6d7-46ee-9ba5-ad7066ada10a 替换变量完毕
2020-12-04T16:00:02.721Z 2dbe7a23-c6d7-46ee-9ba5-ad7066ada10a
开始执行脚本签到，请稍等
2020-12-04T16:01:37.274Z 2dbe7a23-c6d7-46ee-9ba5-ad7066ada10a 京东签到脚本执行异常:Error: in method 'console_log', argument 1 of type 'char *'
这样是怎么回事呢。

**Comment by q4w5e6** [comment]
云函数目前只是通知有异常，执行没有问题的。

**Comment by xiaojie1234** [comment]
> 云函数目前只是通知有异常，执行没有问题的。

嗯嗯，好哒。

**Comment by iOSleep** [comment]
> 云函数目前只是通知有异常，执行没有问题的。

感谢

**Comment by erudite72** [comment]
> 云函数目前只是通知有异常，执行没有问题的。

2020-12-05T16:00:41.738Z 9198d95d-7234-4bd3-a82b-7a42fb3992ce 京东签到脚本执行异常:Error: in method 'console_log', argument 1 of type 'char *'
云函数通知这个，但是已经签过了是吗？

**Comment by zhongdi520** [comment]
> > 云函数目前只是通知有异常，执行没有问题的。
> 
> 2020-12-05T16：00：41.738Z 9198d95d-7234-4bd3-a82b-7a42fb3992ce京东签到脚本执行异常：错误：在方法'console_log'，类型的参数1 '字符*'
> 云函数通知这个，但是已经签过了是吗？

应该是通知问题，你把通知关了就不显示异常。好奇怪

**Comment by lxk0301** [comment]
部署过来的, 把环境变量里面, 通知相关的环境变量删掉, 就不会出现这个错误,

**Comment by lxk0301** [comment]
> > > 云函数目前只是通知有异常，执行没有问题的。
> > 
> > 
> > 2020-12-05T16：00：41.738Z 9198d95d-7234-4bd3-a82b-7a42fb3992ce京东签到脚本执行异常：错误：在方法'console_log'，类型的参数1 '字符*'
> > 云函数通知这个，但是已经签过了是吗？
> 
> 应该是通知问题，你把通知关了就不显示异常。好奇怪

你的把通知关了不会出现这个问题, 是什么意思?  也是环境变量吗? 还是说修改脚本删除脚本里面的通知功能?

**Comment by lxk0301** [comment]
![image](https://user-images.githubusercontent.com/21308593/101708885-352e5b00-3ac9-11eb-9602-86cb9c4c7485.png)
删除这块通知类的环境变量 .就不会出现上面的错误 `京东签到脚本执行异常:Error: in method 'console_log', argument 1 of type 'char *'`

**Comment by pikaqiu112** [comment]
@lxk0301 一样

**Comment by lxk0301** [comment]
> @lxk0301 一样

什么一样?

**Comment by pikaqiu112** [comment]
@lxk0301 全部异常了……

**Comment by Maccrack** [comment]
我这边也是同样的情况、云函数搭建的京东签到脚本要是不添加service酱可以正常运行不会报错、添加后可以运行、也有效果，但不能推送，把环境变量里面的的TG相关的变量删除还会报错、

> `2020-12-17T13:57:02.445Z  d340e8d0-765c-42e0-ad59-90635f27f769  京东签到脚本执行异常:Error: in method 'console_log', argument 1 of type 'char *'`
