### ISSUE TITLE
docker1 crontab_list.sh 金融养猪时间

### ISSUE THREAD

**Issue by deepdark111** [lxk0301/jd_scripts#192]
docker1 crontab_list.sh文件，金融养猪时间
![image](https://user-images.githubusercontent.com/67956668/100406430-bedd3200-30a0-11eb-863b-d15f310493b8.png)

crontab_list_ts.sh文件是正确的
![image](https://user-images.githubusercontent.com/67956668/100406437-c8ff3080-30a0-11eb-96ce-5c7391749b1b.png)

**Comment by lxk0301** [comment]
改了
