### ISSUE TITLE
京东萌宠新增了个浏览点点券的任务

### ISSUE THREAD

**Issue by shitouer0515** [lxk0301/jd_scripts#193]
大佬有空看下 *-*

**Comment by lxk0301** [comment]
截图, 我这里没看到有

**Comment by shitouer0515** [comment]
> 截图，我这里没看到有

![Uploading Screenshot_20201127_124829_com.jingdong.app.mall.jpg…]()

**Comment by shitouer0515** [comment]
![Uploading Screenshot_20201127_124829_com.jingdong.app.mall.jpg…]()

**Comment by shitouer0515** [comment]
我网太烂了🥺有空再传

**Comment by shitouer0515** [comment]
![Screenshot_20201127_131717](https://user-images.githubusercontent.com/10106144/100413700-f654da00-30b2-11eb-84f9-bc93cfd505de.jpg)

**Comment by shitouer0515** [comment]
> 截图, 我这里没看到有

![Screenshot_20201127_131717](https://user-images.githubusercontent.com/10106144/100413869-5ba8cb00-30b3-11eb-8c3e-f450763e72dc.jpg)

**Comment by lxk0301** [comment]
@shitouer0515 截图倒是看到了。不过这显示任务已经做完

**Comment by shitouer0515** [comment]
> @shitouer0515 截图倒是看到了。不过这显示任务已经做完
这是我手动做的   手机是安卓系统  可能是刚增加的吧  上几天还没有这任务

**Comment by lxk0301** [comment]
@shitouer0515 可能是安卓的有。我iOS没有。你给我一个安卓的UserAgent？

**Comment by shitouer0515** [comment]
> @shitouer0515 可能是安卓的有。我iOS没有。你给我一个安卓的UserAgent？
我是小白 不太懂  User-Agent: Dalvik/2.1.0 (Linux; U; Android 10; BLA-AL00 Build/HUAWEIBLA-AL00)  这个么  只是反馈下 要不我还是等大佬更新吧 *-*

**Comment by chihwell** [comment]
> 大佬有空看下 _-_

你这说的不是已经加上来的天天点点券吗？？

**Comment by shitouer0515** [comment]
> > 大佬有空看下 _-_
> 
> 你这说的不是已经加上来的天天点点券吗？？
> 跟领券中心入口那个一样的吧？

好像不太一样  从领券中心进 在萌宠里面这个任务不显示完成 , 从萌宠里面这个任务点进去才算完成    ,只不过反馈下我慢慢等大佬更新吧

**Comment by chihwell** [comment]
> > > 大佬有空看下 _-_
> > 
> > 
> > 你这说的不是已经加上来的天天点点券吗？？
> > 跟领券中心入口那个一样的吧？
> 
> 好像不太一样 从领券中心进 在萌宠里面这个任务不显示完成 , 从萌宠里面这个任务点进去才算完成 ,只不过反馈下我慢慢等大佬更新吧


> > > 大佬有空看下 _-_
> > 
> > 
> > 你这说的不是已经加上来的天天点点券吗？？
> > 跟领券中心入口那个一样的吧？
> 
> 好像不太一样 从领券中心进 在萌宠里面这个任务不显示完成 , 从萌宠里面这个任务点进去才算完成 ,只不过反馈下我慢慢等大佬更新吧

我这边看到是一样的，都是安卓，任务都是脚本完成的

**Comment by chihwell** [comment]
> > > 大佬有空看下 _-_
> > 
> > 
> > 你这说的不是已经加上来的天天点点券吗？？
> > 跟领券中心入口那个一样的吧？
> 
> 好像不太一样 从领券中心进 在萌宠里面这个任务不显示完成 , 从萌宠里面这个任务点进去才算完成 ,只不过反馈下我慢慢等大佬更新吧

还是说这个入口是为了做任务领狗粮？
