### ISSUE TITLE
请求增加京东农场批量删除好友的功能

### ISSUE THREAD

**Issue by Naivev** [lxk0301/jd_scripts#195]
好友到达一定数量后再邀请好友就无法获得水滴奖励了
![image](https://user-images.githubusercontent.com/45974159/100416096-9a8d4f80-30b8-11eb-8a83-c67bea8649ef.png)
![image](https://user-images.githubusercontent.com/45974159/100416104-9d884000-30b8-11eb-96fa-4ba9b47d4f08.png)

**Comment by lxk0301** [comment]
你自己在app上都不能删掉 ，叫我来删掉？我怎么给你删？我又不是你东哥，你是来搞笑的吧

**Comment by Naivev** [comment]
app里可以删啊，没说不能删啊，但是要手动一个个删除好麻烦的

**Comment by Naivev** [comment]
> 你自己在app上都不能删掉 ，叫我来删掉？我怎么给你删？我又不是你东哥，你是来搞笑的吧

app里可以删啊，没说不能删啊，但是要手动一个个删除好麻烦的

另外，说话这么冲干嘛，有病吧

**Comment by DoveBoy** [comment]
@Naivev 我想知道怎么删除，我不会，没见到过能删除的

**Comment by Naivev** [comment]
> @Naivev 我想知道怎么删除，我不会，没见到过能删除的

手机端不知道为什么不能上传图片，放图床上了
https://i.loli.net/2020/11/27/e9luQNMq31oVdwk.jpg

**Comment by DoveBoy** [comment]
@Naivev 居然是长按删除的，不是直接的删除按钮，估计不行

**Comment by Naivev** [comment]
> @Naivev 居然是长按删除的，不是直接的删除按钮，估计不行

好吧，那算了

**Comment by lxk0301** [comment]
> > 你自己在app上都不能删掉 ，叫我来删掉？我怎么给你删？我又不是你东哥，你是来搞笑的吧
> 
> app里可以删啊，没说不能删啊，但是要手动一个个删除好麻烦的
> 
> 另外，说话这么冲干嘛，有病吧

你才有病吧。我就说话冲怎么了，你有把问题描述清楚么？

下面都有人说不知道如何删除好友。
