### ISSUE TITLE
我发现了京东每天50豆的活动

### ISSUE THREAD

**Issue by Qa70601234** [lxk0301/jd_scripts#196]
京东有个心愿单，每天50豆，能不能也做个脚本？
就在首页里面有个发现好货旁，领取50京豆
<img src="https://imgchr.com/i/Dr3MNR">

**Comment by Qa70601234** [comment]
<img src="https://github.com/Qa70601234/jd_sign_bot/blob/master/%E7%83%AD%E6%9C%9B%E4%BA%B2%E7%83%AD.jpg">

**Comment by Choicc** [comment]
已经有人提过了#123
