### ISSUE TITLE
口袋书店

### ISSUE THREAD

**Issue by Twinzo1** [lxk0301/jd_scripts#197]
---
| name | about | title | labels | assignees |
| :-----: | :----: | :----: |  :----: |  :----: |
|功能建议| 请求实现新功能 |  口袋书店 |   |   |
--- 

 
 
 
 
 

 
## 期望增加的功能

A： 口袋书店

## 入口

A：
1.我的➡️京豆➡️签到领京豆
![image](https://user-images.githubusercontent.com/44726207/100434816-06cb7b80-30d8-11eb-9dc3-ea33cfcb83c3.png)
2.点进去后往下拉可看到京东图书馆签到
![image](https://user-images.githubusercontent.com/44726207/100434962-3aa6a100-30d8-11eb-88ab-2e35fe3b93ff.png)
3.点击屏幕右边中部赢京豆抽大奖
![image](https://user-images.githubusercontent.com/44726207/100435082-6164d780-30d8-11eb-84ec-40f4dda3513f.png)
4.口袋书店
![image](https://user-images.githubusercontent.com/44726207/100435179-8bb69500-30d8-11eb-9b89-e4324deab6e4.png)

顺便提及一下[其他游戏](https://github.com/lxk0301/jd_scripts/issues/92)

**Comment by EvineDeng** [comment]
这个我确信大佬已经知道了

**Comment by shylocks** [comment]
创建书店直接非法用户

**Comment by Twinzo1** [comment]
风险这么大🐎

**Comment by shylocks** [comment]
做不了的原因是要算sign
