### ISSUE TITLE
大佬 云函数怎么添加方糖的微信推送？

### ISSUE THREAD

**Issue by Kirietoan** [lxk0301/jd_scripts#20]
大佬 云函数怎么添加方糖的微信推送？

**Comment by myDawn** [comment]
> 大佬 云函数怎么添加方糖的微信推送？

你的运行成功了吗。。。

**Comment by lxk0301** [comment]
新建环境变量，环境变量名称和之前secret一样

**Comment by Kirietoan** [comment]
> 新建环境变量，环境变量名称和之前secret一样

好的大佬 对了 请问下 如何制作一个方糖的推送呢 我想给一个网易云的签到也加一个这个推送 能请教下你吗 有联系方式吗

**Comment by lxk0301** [comment]
如果是js脚本， 用我的那个 sendNotify.js就行 ，如果是其他语言的脚本， 自己弄

**Comment by Kirietoan** [comment]
> 如果是js脚本， 用我的那个 sendNotify.js就行 ，如果是其他语言的脚本， 自己弄

好的谢谢
