### ISSUE TITLE
新建仓库后运行action报错

### ISSUE THREAD

**Issue by Castle1984** [lxk0301/jd_scripts#22]
导入了yml后，原来的cookie也已写入secret，手动运行其中一个action，在checkout处报错，Determining the default branch报错信息“Error: Repository access blocked”，求教

**Comment by sgzman** [comment]
yml中checkout的仓库地址换乘你自己的。

**Comment by Castle1984** [comment]
好的，谢谢啦

**Comment by sgzman** [comment]
> 好的，谢谢啦

不客气

**Comment by qyaaaa** [comment]
怎么搞，是直接clone到本地，添加那些yml文件再推送到仓库里吗，checkout直接修改为自己的仓库名？

**Comment by xuelang7009** [comment]
checkout 地址在哪里设置 啊

**Comment by Castle1984** [comment]
建议这样吧：
①clone到自己的仓库
②将之前的workflows内文件中所有文件中的“lxk0301/scripts”批量替换成“自己的名字/克隆项目名”
③打开项目中的.github/workflows/, 右侧有add file键，批量上传刚刚所有的yml文件
④之后配置你原来的cookie和server酱
就这样啦

**Comment by sgzman** [comment]
> 建议这样吧：
> ①clone到自己的仓库
> ②将之前的workflows内文件中所有文件中的“lxk0301/scripts”批量替换成“自己的名字/克隆项目名”
> ③打开项目中的.github/workflows/, 右侧有add file键，批量上传刚刚所有的yml文件
> ④之后配置你原来的cookie和server酱
> 就这样啦

对， 就是这样。

**Comment by WYisShuaiBi** [comment]
> 建议这样吧：
> ①clone到自己的仓库
> ②将之前的workflows内文件中所有文件中的“lxk0301/scripts”批量替换成“自己的名字/克隆项目名”
> ③打开项目中的.github/workflows/, 右侧有add file键，批量上传刚刚所有的yml文件
> ④之后配置你原来的cookie和server酱
> 就这样啦

那这种方法怎么更新代码呢

**Comment by leecheng311** [comment]
mark

**Comment by qyaaaa** [comment]
> 建议这样吧：
> ①clone到自己的仓库
> ②将之前的workflows内文件中所有文件中的“lxk0301/scripts”批量替换成“自己的名字/克隆项目名”
> ③打开项目中的.github/workflows/, 右侧有add file键，批量上传刚刚所有的yml文件
> ④之后配置你原来的cookie和server酱
> 就这样啦

可以

**Comment by qingtai1991** [comment]
yml备份文件谁可以提供一下呢

**Comment by bokuosusume** [comment]
比较想要找 原来的yaml文件

**Comment by tommyhe1217** [comment]
> ②将之前的workflows内文件中所有文件中的“lxk0301/scripts”批量替换成“自己的名字/克隆项目名”

改成自己的名字/库名后报错，是为何？

**Comment by sgzman** [comment]
> > ②将之前的workflows内文件中所有文件中的“lxk0301/scripts”批量替换成“自己的名字/克隆项目名”
> 
> 改成自己的名字/库名后报错，是为何？

不应该报错的，你把报错信息贴出来。还有你改的yml部分代码

**Comment by ZHANGLIANGzhangliang** [comment]
> 建议这样吧：
> ①clone到自己的仓库
> ②将之前的workflows内文件中所有文件中的“lxk0301/scripts”批量替换成“自己的名字/克隆项目名”
> ③打开项目中的.github/workflows/, 右侧有add file键，批量上传刚刚所有的yml文件
> ④之后配置你原来的cookie和server酱
> 就这样啦

还有原来那些git action配置参数吗

**Comment by lxk0301** [comment]
不要fork我这边仓库就行。不然下次GitHub还会继续封这个仓库。

**Comment by tommyhe1217** [comment]
> 不应该报错的，你把报错信息贴出来。还有你改的yml部分代码

新建了自己的库，上传了备份的jd_speed.js和jd_speed.yml，
jd_speed.yml中的repository:修改为自己的名字/库名，报错信息如下：
![image](https://user-images.githubusercontent.com/66045818/98641380-9d710c00-2366-11eb-80b6-3052bac8eda5.png)
![image](https://user-images.githubusercontent.com/66045818/98641414-aeba1880-2366-11eb-80a4-7ab5a4d98b60.png)

**Comment by tommyhe1217** [comment]
> > 建议这样吧：
> > ①clone到自己的仓库
> > ②将之前的workflows内文件中所有文件中的“lxk0301/scripts”批量替换成“自己的名字/克隆项目名”
> > ③打开项目中的.github/workflows/, 右侧有add file键，批量上传刚刚所有的yml文件
> > ④之后配置你原来的cookie和server酱
> > 就这样啦
> 
> 还有原来那些git action配置参数吗

gitee里面有合集

**Comment by ZHANGLIANGzhangliang** [comment]
> > > 建议这样吧：
> > > ①clone到自己的仓库
> > > ②将之前的workflows内文件中所有文件中的“lxk0301/scripts”批量替换成“自己的名字/克隆项目名”
> > > ③打开项目中的.github/workflows/, 右侧有add file键，批量上传刚刚所有的yml文件
> > > ④之后配置你原来的cookie和server酱
> > > 就这样啦
> > 
> > 
> > 还有原来那些git action配置参数吗
> 
> gitee里面有合集

找到了多谢

**Comment by zdrka** [comment]
建了一个action模板库，可以试试
https://github.com/zdrka/Action-jd-scripts/generate

**Comment by sgzman** [comment]
> > 不应该报错的，你把报错信息贴出来。还有你改的yml部分代码
> 
> 新建了自己的库，上传了备份的jd_speed.js和jd_speed.yml，
> jd_speed.yml中的repository:修改为自己的名字/库名，报错信息如下：
> ![image](https://user-images.githubusercontent.com/66045818/98641380-9d710c00-2366-11eb-80b6-3052bac8eda5.png)
> ![image](https://user-images.githubusercontent.com/66045818/98641414-aeba1880-2366-11eb-80a4-7ab5a4d98b60.png)

你看看我的仓库里yml怎么设置的

**Comment by tommyhe1217** [comment]
> 你看看我的仓库里yml怎么设置的

你是如何批量连文件夹都上传的

**Comment by sgzman** [comment]
> 建了一个action模板库，可以试试
> https://github.com/zdrka/Action-jd-scripts/generate

我use 了这个模版建了个自己的仓库，然后想着直接用这个来执行action，发现不会自动运行。

**Comment by WYisShuaiBi** [comment]
> 建了一个action模板库，可以试试
> https://github.com/zdrka/Action-jd-scripts/generate

好用, 这方法会对作者造成影响吗

**Comment by sgzman** [comment]
> > 建了一个action模板库，可以试试
> > https://github.com/zdrka/Action-jd-scripts/generate
> 
> 好用, 这方法会对作者造成影响吗

我也不清楚哦

**Comment by askiter** [comment]
我的修改了yml文件里面的用户名和项目名，其他没动，执行的时候提示如下的错误

(node:2717) UnhandledPromiseRejectionWarning: Error: Cannot find module 'got'
Require stack:
- /home/runner/work/JDScripts/JDScripts/jd_speed.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.initGotEnv (/home/runner/work/JDScripts/JDScripts/jd_speed.js:513:3645)
    at Object.post (/home/runner/work/JDScripts/JDScripts/jd_speed.js:513:5101)
    at /home/runner/work/JDScripts/JDScripts/jd_speed.js:487:7
    at new Promise (<anonymous>)
    at TotalBean (/home/runner/work/JDScripts/JDScripts/jd_speed.js:473:10)
    at /home/runner/work/JDScripts/JDScripts/jd_speed.js:52:13
(Use `node --trace-warnings ...` to show where the warning was created)
(node:2717) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2717) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

请问这个问题怎么解决，谢谢

**Comment by sgzman** [comment]
> 我的修改了yml文件里面的用户名和项目名，其他没动，执行的时候提示如下的错误
> 
> (node:2717) UnhandledPromiseRejectionWarning: Error: Cannot find module 'got'
> Require stack:
> 
> * /home/runner/work/JDScripts/JDScripts/jd_speed.js
>   at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
>   at Function.Module._load (internal/modules/cjs/loader.js:725:27)
>   at Module.require (internal/modules/cjs/loader.js:952:19)
>   at require (internal/modules/cjs/helpers.js:88:18)
>   at Object.initGotEnv (/home/runner/work/JDScripts/JDScripts/jd_speed.js:513:3645)
>   at Object.post (/home/runner/work/JDScripts/JDScripts/jd_speed.js:513:5101)
>   at /home/runner/work/JDScripts/JDScripts/jd_speed.js:487:7
>   at new Promise ()
>   at TotalBean (/home/runner/work/JDScripts/JDScripts/jd_speed.js:473:10)
>   at /home/runner/work/JDScripts/JDScripts/jd_speed.js:52:13
>   (Use `node --trace-warnings ...` to show where the warning was created)
>   (node:2717) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
>   (node:2717) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
> 
> 请问这个问题怎么解决，谢谢

直接看这个吧：https://github.com/lxk0301/jd_scripts/issues/32

**Comment by lxk0301** [comment]
@zdrka 膜拜方式不可行。checkout还是走我主库。

**Comment by QianJoe** [comment]
cookie失效，怎么回事，有大佬知道吗

**Comment by guaosi** [comment]
mark一下解决方案

**Comment by jiegangwu** [comment]
mark

**Comment by tiantianwahaha** [comment]
自动更新怎么把我自己上传的yml文件删除了。。。应该怎么改才能自动同步除了yml文件夹之外的东西

**Comment by Caiiiiii** [comment]
> > 建议这样吧：
> > ①clone到自己的仓库
> > ②将之前的workflows内文件中所有文件中的“lxk0301/scripts”批量替换成“自己的名字/克隆项目名”
> > ③打开项目中的.github/workflows/, 右侧有add file键，批量上传刚刚所有的yml文件
> > ④之后配置你原来的cookie和server酱
> > 就这样啦
> 
> 那这种方法怎么更新代码呢

同问。

**Comment by 282206796** [comment]
> yml备份文件谁可以提供一下呢

gitee里面有l大的源码文件
