### ISSUE TITLE
惊喜工厂的瓜子已经兑换超时，方糖还是每个小时都会推送一次消息提醒去领取

### ISSUE THREAD

**Issue by wxjbb** [lxk0301/jd_scripts#226]
![image](https://user-images.githubusercontent.com/39824657/101233882-047ba980-36f6-11eb-8481-393027f7c1dd.png)
![image](https://user-images.githubusercontent.com/39824657/101233901-1cebc400-36f6-11eb-80e4-660997b2cda8.png)

**Comment by lxk0301** [comment]
@wxjbb 你自己新选择一个新的商品就是了。都通知了一天了。你还不去兑换。这能guai shui

**Comment by wxjbb** [comment]
懂了
