### ISSUE TITLE
东东工厂任务

### ISSUE THREAD

**Issue by Twinzo1** [lxk0301/jd_scripts#231]
---
 
 
 

## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [x] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A： 东东工厂10点-13点巡厂任务未完成

### (2) 详细日志
A：无

### (1) Node.js版本

A：无

### (2) npm版本

A：无

### (3)npm install的日志

A：无

**Comment by lxk0301** [comment]
东东工厂10点-13点巡厂任务未完成， 是你在这时间段没有运行过脚本吧

**Comment by Twinzo1** [comment]
GitHub actions运行的，每个小时都有运行

**Comment by lxk0301** [comment]
@Twinzo1 我自己的日志是显示已做完的

**Comment by Twinzo1** [comment]
我手动领取的话日志会显示这个任务已完成，没有领取的话，日志不会显示这个任务的相关内容

**Comment by lxk0301** [comment]
刚才修改提交了， 明天再看看吧  ，等你们反馈

**Comment by Twinzo1** [comment]
👌好的

**Comment by Twinzo1** [comment]
任务已做
