### ISSUE TITLE
windows运行目录问题

### ISSUE THREAD

**Issue by mengshouer** [lxk0301/jd_scripts#238]
windows跑jd_bean_sign.js时node运行目录带空格的话会报错，比如默认安装的C:\Program Files\nodejs\,   Program Files自带空格(

**Comment by EvineDeng** [comment]
路径外侧加引号

**Comment by lxk0301** [comment]
@mengshouer 自己的问题 跟脚本无关

**Comment by mengshouer** [comment]
算了，我改个安装目录。
