### ISSUE TITLE
大佬能有个具体的群晖docker部署教程吗？

### ISSUE THREAD

**Issue by zsrjim012** [lxk0301/jd_scripts#239]
![QQ图片20201207092439](https://user-images.githubusercontent.com/70929643/101299689-0d8f8680-386e-11eb-9cb9-6f4ca72ad676.png)

**Comment by xiaobaichiliangpi** [comment]
同求，jd_scripts.syno.json 这文件哪来的，不是很清楚

**Comment by avsba001** [comment]
教程很详细了啊，有点基础就够了
