### ISSUE TITLE
 金榜年终奖运行失败

### ISSUE THREAD

**Issue by aixiaolu** [lxk0301/jd_scripts#245]
❌ 金榜年终奖, 失败! 原因: Error: Cannot find module './jdSplitShareCodes.js'

Require stack:

- /var/user/jd_split.js

- /var/user/index.js

- /var/runtime/node12/UserFunction.js

- /var/runtime/node12/Runtime.engine.js

- /var/runtime/node12/bootstrap.js!

**Comment by lxk0301** [comment]
@aixiaolu 更新脚本吧，

**Comment by aixiaolu** [comment]
应该是调用这个jdSplitShareCodes.js没有去掉，到这就不行了，红包雨可以运行

**Comment by lxk0301** [comment]
> 应该是调用这个jdSplitShareCodes.js没有去掉，到这就不行了，红包雨可以运行

是你缺失文件，然后报错，不过我已经去掉引入这个文件了， 所以叫你更新脚本
