### ISSUE TITLE
腾讯函数部署的都是香港，删除重新部署还是香港，有没有影响？怎么部署到国内？

### ISSUE THREAD

**Issue by Chase2179** [lxk0301/jd_scripts#264]

**Comment by Chase2179** [comment]
腾讯函数部署的都是香港，删除重新部署还是香港，有没有影响？怎么部署到国内？

**Comment by Jone2008** [comment]
> 腾讯函数部署的都是香港，删除重新部署还是香港，有没有影响？怎么部署到国内？

serverless.yml这个文件里面修改：region: ap-guangzhou # 函数所在区域

**Comment by DoveBoy** [comment]
> 腾讯函数部署的都是香港，删除重新部署还是香港，有没有影响？怎么部署到国内？

换成国内后index.js里面地址访问不了

**Comment by Chase2179** [comment]
> > 腾讯函数部署的都是香港，删除重新部署还是香港，有没有影响？怎么部署到国内？
> 
> serverless.yml这个文件里面修改：region: ap-guangzhou # 函数所在区域

谢谢

**Comment by Chase2179** [comment]
> > 腾讯函数部署的都是香港，删除重新部署还是香港，有没有影响？怎么部署到国内？
> 
> 换成国内后index.js里面地址访问不了

明白
