### ISSUE TITLE
京东红包雨运行时间正确，却显示不在红包雨时间内

### ISSUE THREAD

**Issue by x1iu** [lxk0301/jd_scripts#272]
![image](https://user-images.githubusercontent.com/44594408/101461730-474bb480-3976-11eb-98a2-0470a136c82f.png)
北京时间下午三点，就是世界时七点。为什么提示不在时间内？

**Comment by q4w5e6** [comment]
https://raw.githubusercontent.com/lxk0301/jd_scripts/4b65ad5a8371f01602461f3b3d72d01c1983c03a/jd_live_redrain.js

临时办法有回退到这个版本来定时执行，不要在非指定的时间运行就好了。
![image](https://user-images.githubusercontent.com/51695264/101464719-f8a01980-3979-11eb-8d24-e8257281a525.png)

**Comment by x1iu** [comment]
好的，谢谢

**Comment by DoveBoy** [comment]
@shylocks 同样问题，云函数定时的显示不在红包雨时间之内，但是本地跑[jd_live_redrain.js](https://github.com/lxk0301/jd_scripts/blob/4b65ad5a8371f01602461f3b3d72d01c1983c03a/jd_live_redrain.js)正常
![image](https://user-images.githubusercontent.com/19201447/101476115-3d32b180-3988-11eb-8bb2-aa69f6ab76f6.png)
![image](https://user-images.githubusercontent.com/19201447/101476162-4de32780-3988-11eb-996d-5106c86e8e48.png)

**Comment by aixiaolu** [comment]
一样，望大佬修复

**Comment by shylocks** [comment]
云函数的时区不一样？挺难判断的

**Comment by x1iu** [comment]
可以加一个secret吗，自行设置

**Comment by lxk0301** [comment]
@shylocks 现在是什么导致的？脚本时间没处理好？

还是说京东返回的时间戳是根据系统时区来的？

**Comment by shylocks** [comment]
> @shylocks 现在是什么导致的？脚本时间没处理好？
> 
> 还是说京东返回的时间戳是根据系统时区来的？

京东返回的时间戳是UTC-8的，云函数调用的时间戳判读是根据云函数系统来的，不是用户的时区

**Comment by aixiaolu** [comment]
腾讯云的时间是东八区，也是提示不在红包雨时间内

**Comment by shylocks** [comment]
或者就去掉时间限制，加时间限制主要防止提示活动火爆，然后秋后算账

**Comment by lxk0301** [comment]
> > @shylocks 现在是什么导致的？脚本时间没处理好？
> > 还是说京东返回的时间戳是根据系统时区来的？
> 
> 京东返回的时间戳是UTC-8的，云函数调用的时间戳判读是根据云函数系统来的，不是用户的时区

奇怪。我看你的获取当前时间戳nowTs，是我那个不管在哪个时区拿到的都是北京地区的时间戳。居然还会有这问题

**Comment by danwangshimoluo** [comment]
我把if条件判断删了，哈哈哈

**Comment by LiJinChang** [comment]
Github Actions 的话可以在环境变量里加上 TZ: Asia/Shanghai

**Comment by DoveBoy** [comment]
@shylocks 现在云函数红包雨回退到前一个版本也不能用了，直接报错，新版本又提示“暂无红包雨”，实际手动可以正常领取，可有解决之道？
![image](https://user-images.githubusercontent.com/19201447/101560560-89203d80-39fe-11eb-8cda-554114f36a49.png)
![image](https://user-images.githubusercontent.com/19201447/101560323-fa132580-39fd-11eb-9937-ab26ecffabcb.png)

**Comment by danwangshimoluo** [comment]
把if条件判断删了，哈哈哈，按时执行就行，按时执行保证在红包雨时间内，就不会出现活动火爆了。

**Comment by danwangshimoluo** [comment]
云函数目前谁有可行的方法？

**Comment by servicehost** [comment]
> 
> 
> @shylocks 现在云函数红包雨回退到前一个版本也不能用了，直接报错，新版本又提示“暂无红包雨”，实际手动可以正常领取，可有解决之道？
> ![image](https://user-images.githubusercontent.com/19201447/101560560-89203d80-39fe-11eb-8cda-554114f36a49.png)
> ![image](https://user-images.githubusercontent.com/19201447/101560323-fa132580-39fd-11eb-9937-ab26ecffabcb.png)

同样的情况，红包雨全显示：暂无红包雨。

**Comment by iOSleep** [comment]
> 把if条件判断删了，哈哈哈，按时执行就行，按时执行保证在红包雨时间内，就不会出现活动火爆了。

index.js 里 执行本地 然后把 `jd_live_redrain.js` 里 76 行附近的 判断删去 跑成功了 不过今天是最后一天了 😂

**Comment by sgzman** [comment]
我的腾讯云跑的  ，也是提示不在范围内，上海地区

START RequestId:5038238a-cfd5-4ce2-81c0-894e9a9aa62c

2020-12-15T03:00:05.562Z 5038238a-cfd5-4ce2-81c0-894e9a9aa62c jd_live_redrain

2020-12-15T03:00:05.967Z 5038238a-cfd5-4ce2-81c0-894e9a9aa62c

🔔直播红包雨, 开始!

2020-12-15T03:00:05.968Z 5038238a-cfd5-4ce2-81c0-894e9a9aa62c 您的cookie选择的是用&隔开

2020-12-15T03:00:05.968Z 5038238a-cfd5-4ce2-81c0-894e9a9aa62c

====================共有2个京东账号Cookie=========

2020-12-15T03:00:05.970Z 5038238a-cfd5-4ce2-81c0-894e9a9aa62c ==================脚本执行- 北京时间(UTC+8)：12/15/2020, 11:00:05 AM=====================

2020-12-15T03:00:06.129Z 5038238a-cfd5-4ce2-81c0-894e9a9aa62c 下一场红包雨开始时间：Tue Dec 15 2020 03:00:00 GMT+0000 (Coordinated Universal Time)

2020-12-15T03:00:06.129Z 5038238a-cfd5-4ce2-81c0-894e9a9aa62c 下一场红包雨结束时间：Tue Dec 15 2020 03:05:00 GMT+0000 (Coordinated Universal Time)

2020-12-15T03:00:06.129Z 5038238a-cfd5-4ce2-81c0-894e9a9aa62c 不在红包雨时间之内

2020-12-15T03:00:06.129Z 5038238a-cfd5-4ce2-81c0-894e9a9aa62c

🔔直播红包雨, 结束! 🕛 0.162 秒

2020-12-15T03:00:06.129Z 5038238a-cfd5-4ce2-81c0-894e9a9aa62c  

END RequestId:5038238a-cfd5-4ce2-81c0-894e9a9aa62c

Report RequestId:5038238a-cfd5-4ce2-81c0-894e9a9aa62c Duration:569ms Memory:128MB MemUsage:84.175781MB

**Comment by DoveBoy** [comment]
删除所有包含`+ new Date().getTimezoneOffset() * 60 * 1000 + 8 * 60 * 60 * 1000`字段后正常

**Comment by sgzman** [comment]
> 删除所有包含`+ new Date().getTimezoneOffset() * 60 * 1000 + 8 * 60 * 60 * 1000`字段后正常

麻烦更新到仓库中吧

**Comment by lxk0301** [comment]
@sgzman https://raw.githubusercontent.com/lxk0301/jd_scripts/master/jd_live_redrain.js

最新的脚本已有修复此问题

**Comment by sgzman** [comment]
> @sgzman https://raw.githubusercontent.com/lxk0301/jd_scripts/master/jd_live_redrain.js
> 
> 最新的脚本已有修复此问题

![image](https://user-images.githubusercontent.com/31655098/102174567-c2fab380-3ed8-11eb-9f86-481e68eac441.png)
一点的时候执行，还是提示不在时间范围内

**Comment by DoveBoy** [comment]
@sgzman 手动改下就好了

**Comment by sgzman** [comment]
> @sgzman 手动改下就好了

是腾讯云函数执行的远程脚本，请问怎么改呢？

**Comment by DoveBoy** [comment]
@sgzman 我单独设置了一个，没有用远端的，短期脚本，没必要改repo里面的吧？

**Comment by sgzman** [comment]
> @sgzman 我单独设置了一个，没有用远端的，短期脚本，没必要改repo里面的吧？

好的，那我也单独设置一个

**Comment by Tersd07** [comment]
@lxk0301 @shylocks 
https://github.com/lxk0301/jd_scripts/blob/a11179ae801daeddcd305b792f0b85cdd89773cb/jd_live_redrain.js#L71
是这里的问题，因为无论什么时区的机器环境，
在同一时间运行获得的 `时间戳` 都是固定的，
所以单纯 `时间戳` 比较是没必要加上时区偏移的。
只有在格式化成具体时间才用上时区偏移。

脚本种的另一处。
https://github.com/lxk0301/jd_scripts/blob/a11179ae801daeddcd305b792f0b85cdd89773cb/jd_live_redrain.js#L181

**Comment by lxk0301** [comment]
> @lxk0301 @shylocks
> https://github.com/lxk0301/jd_scripts/blob/a11179ae801daeddcd305b792f0b85cdd89773cb/jd_live_redrain.js#L71
> 
> 
> 是这里的问题，因为无论什么时区的机器环境，
> 在同一时间运行获得的 `时间戳` 都是固定的，
> 所以单纯 `时间戳` 比较是没必要加上时区偏移的。
> 只有在格式化成具体时间才用上时区偏移。
> 脚本种的另一处。
> https://github.com/lxk0301/jd_scripts/blob/a11179ae801daeddcd305b792f0b85cdd89773cb/jd_live_redrain.js#L181

你的意思不需要71处的转换？ 直接拿`Date.now()`时间戳？

**Comment by sgzman** [comment]
> > @lxk0301 @shylocks
> > https://github.com/lxk0301/jd_scripts/blob/a11179ae801daeddcd305b792f0b85cdd89773cb/jd_live_redrain.js#L71
> > 
> > 是这里的问题，因为无论什么时区的机器环境，
> > 在同一时间运行获得的 `时间戳` 都是固定的，
> > 所以单纯 `时间戳` 比较是没必要加上时区偏移的。
> > 只有在格式化成具体时间才用上时区偏移。
> > 脚本种的另一处。
> > https://github.com/lxk0301/jd_scripts/blob/a11179ae801daeddcd305b792f0b85cdd89773cb/jd_live_redrain.js#L181
> 
> 你的意思不需要71处的转换？ 直接拿`Date.now()`时间戳？

![image](https://user-images.githubusercontent.com/31655098/102178824-0d802e00-3ee1-11eb-8d67-4eb096b11430.png)

**Comment by Tersd07** [comment]
> 
> 你的意思不需要71处的转换？ 直接拿`Date.now()`时间戳？

是的，时间戳比较是不用加时区偏移的，时区偏移的作用只在具体时间和时间戳之间的互转。

**Comment by lxk0301** [comment]
但是京东api给出的结束和开始时间戳是按北京来的，而运行`Date.now()`，会因你的运行系统加减的

**Comment by Tersd07** [comment]
> 
> 
> 但是京东api给出的结束和开始时间戳是按北京来的，而运行`Date.now()`，会因你的运行系统加减的

零时区和东八区在这一刻（同一时间）运行`Date.now()` 得到的时间戳是一样的，所以直接比较就可以了。

**Comment by sgzman** [comment]
今天11点的直播红包雨，云函数提示不在时间范围内。

2020-12-16T03:00:02.287Z c4c80b0a-acce-4689-bce1-2d91c18b1192 ==================脚本执行- 北京时间(UTC+8)：12/16/2020, 11:00:02 AM=====================

2020-12-16T03:00:02.487Z c4c80b0a-acce-4689-bce1-2d91c18b1192 下一场红包雨开始时间：Wed Dec 16 2020 01:00:00 GMT+0000 (Coordinated Universal Time)

2020-12-16T03:00:02.487Z c4c80b0a-acce-4689-bce1-2d91c18b1192 下一场红包雨结束时间：Wed Dec 16 2020 01:05:00 GMT+0000 (Coordinated Universal Time)

2020-12-16T03:00:02.487Z c4c80b0a-acce-4689-bce1-2d91c18b1192 不在红包雨时间之内

2020-12-16T03:00:02.487Z c4c80b0a-acce-4689-bce1-2d91c18b1192

**Comment by DoveBoy** [comment]
@sgzman 因为是真的没有，手动进取看也是没有的，官方调整了时间

**Comment by sgzman** [comment]
> @sgzman 因为是真的没有，手动进取看也是没有的，官方调整了时间

官方好皮

**Comment by servicehost** [comment]
> 
> 
> @sgzman 因为是真的没有，手动进取看也是没有的，官方调整了时间

手动进去是有的，11点时我看日志提示活动太火爆，进去后发现红包雨多了5分钟倒记时，不清楚是因为用脚本出现了这个延迟，还是官方改了又多加了5分钟。

**Comment by lxk0301** [comment]
@servicehost body每天都在变化的， 也是有人在维护 ，今天忘记抓包提交更新了， 所以提示未在时间内

**Comment by servicehost** [comment]
> 
> 
> @servicehost body每天都在变化的， 也是有人在维护 ，今天忘记抓包提交更新了， 所以提示未在时间内

原来如此。

另外，昨天晚上又出现超级红包雨了，就是对应的 jd_live_redrain2.js 晚上8点30，9点30..等等。

虽然此脚本下架了，但是之前跑这个脚本从来没有成功过，总会出现：

TypeError: Cannot read property '0' of undefined
    at jd_live_redrain2.js:110:41
    at got.post.then.message (jd_live_redrain2.js:247:5694)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)

这个提示

**Comment by lxk0301** [comment]
@servicehost 也没下架。只是迁移到了activity文件夹
