### ISSUE TITLE
东东工厂双账号第一个账号通知报错.qx运行

### ISSUE THREAD

**Issue by songyangzz** [lxk0301/jd_scripts#275]
==============📣系统通知📣==============
东东工厂
京东账号2158*****902_p
已选商品：暂无
心仪商品：暂无
当前剩余最多商品：蔡司镜头镜片清洁湿巾
兑换所需电量：480000
您当前总电量：483253
【满足】兑换蔡司镜头镜片清洁湿巾所需总电量：480000
请点击弹窗直达活动页面
选择此心仪商品并手动投入电量兑换
2020/12/08 17:51:35:811  <console>    [JS Console]: 
❗️东东工厂, 错误!
TypeError: undefined is not a function (near '...notify.sendNotify...')
2020/12/08 17:51:35:812  <console>    [JS Console]: 京东账号2158*****902_p
已选商品：暂无
心仪商品：暂无
当前剩余最多商品：蔡司镜头镜片清洁湿巾
兑换所需电量：480000
您当前总电量：483253
2020/12/08 17:51:35:813  <console>    [JS Console]: 
🔔东东工厂, 结束! 🕛 8.197 秒
2020/12/08 17:51:35:814  <console>    [JS Console]:

**Comment by lxk0301** [comment]
> ==============📣系统通知📣==============
> 东东工厂
> 京东账号2158_****902_p 已选商品：暂无 心仪商品：暂无 当前剩余最多商品：蔡司镜头镜片清洁湿巾 兑换所需电量：480000 您当前总电量：483253 【满足】兑换蔡司镜头镜片清洁湿巾所需总电量：480000 请点击弹窗直达活动页面 选择此心仪商品并手动投入电量兑换 2020/12/08 17:51:35:811 [JS Console]: ❗️东东工厂, 错误! TypeError: undefined is not a function (near '...notify.sendNotify...') 2020/12/08 17:51:35:812 [JS Console]: 京东账号2158****_902_p
> 已选商品：暂无
> 心仪商品：暂无
> 当前剩余最多商品：蔡司镜头镜片清洁湿巾
> 兑换所需电量：480000
> 您当前总电量：483253
> 2020/12/08 17:51:35:813 [JS Console]:
> 🔔东东工厂, 结束! 🕛 8.197 秒
> 2020/12/08 17:51:35:814 [JS Console]:

好的。

**Comment by lxk0301** [comment]
@lxk0301 已修复。5分钟后更新即可
