### ISSUE TITLE
新的互助它来了

### ISSUE THREAD

**Issue by CfortWang** [lxk0301/jd_scripts#28]
农场
>74421f55fbaa424eac3c051d8df2e649
a6d7c5d3921b4db78a446940443cbdef

萌宠
>MTE1NDUwMTI0MDAwMDAwMDM2MjgyNzAx
MTE1NDUwMTI0MDAwMDAwMDM4OTY4ODM5

种豆
>mlrdw3aw26j3wcceffzxh2me5uwreuxwavvu3tq
f5pavyxxlph5pnjhw6ek3eistzsyzbdfiprb74y

加了记得把自己的回复在下面

**Comment by PrimeMHD** [comment]
种豆得豆
> 2nljvyctc5anhcpeqdxz3dgb7a3h7wlwy7o5jii

东东农场
> 80dda086be6a449d99db7f841945bad5

东东萌宠
> MTAxODExNDYxMTAwMDAwMDAwMzk5Mzg1ODM=

求互！

**Comment by ZHANGLIANGzhangliang** [comment]
农场
7ea24c0e87aa4179b949608cac07a74f
7cc4b1348f344db0aa0567374011cba1
萌宠
MTAxODc2NTEzMTAwMDAwMDAyMDA1MDM0MQ==
MTAxODEyMjkxMDAwMDAwMDM5NTgwODUz
种豆
olmijoxgmjutyoh3goxuhuroiaqvclhzp6ui7gy
xooz5rk4vgwfmjat225uxziu4zpse5yx33wk5ja

加了，今晚回去给你加上

**Comment by Joemercy** [comment]
> 种豆得豆
> 
> > 2nljvyctc5anhcpeqdxz3dgb7a3h7wlwy7o5jii
> 
> 
> 
> 东东农场
> 
> > 80dda086be6a449d99db7f841945bad5
> 
> 
> 
> 东东萌宠
> 
> > MTAxODExNDYxMTAwMDAwMDAwMzk5Mzg1ODM=
> 
> 
> 
> 求互！

已加

京东农场fde222b927ba4b9ba9b3ebe62ae09ae5
京东萌宠MTE1NDUwMTI0MDAwMDAwMDM3MDI5MzU3
种豆得豆mlrdw3aw26j3xuay72ivzs66ilh4qb3iu6et6zq

麻烦您加一下我的

**Comment by PrimeMHD** [comment]
@CfortWang @ZHANGLIANGzhangliang @Joemercy  已添加

**Comment by yuezhu1997** [comment]
@PrimeMHD  @CfortWang @ZHANGLIANGzhangliang 
已添加，求互加
农场
c7b8a8b9bee04a30acc39f1f68105e2c
萌宠
MTAxODc2NTEzNDAwMDAwMDAyNzE5MDk3MQ==
种豆
olmijoxgmjutztpa4ictytxzfiptem5cxodq5bq

**Comment by ZHANGLIANGzhangliang** [comment]
@PrimeMHD @Hostage-02 去给你们加上

**Comment by mmsc2020** [comment]
京东农场
0bdf8f095bfd403c953705fe9e34178d

京东萌宠
MTE1NDQ5OTUwMDAwMDAwMzkwNDk2NTM=

种豆得豆
bqn4yrykl5tfwnzftmmqrl7vsy

**Comment by CfortWang** [comment]
> 农场
> 7ea24c0e87aa4179b949608cac07a74f
> 7cc4b1348f344db0aa0567374011cba1
> 萌宠
> MTAxODc2NTEzMTAwMDAwMDAyMDA1MDM0MQ==
> MTAxODEyMjkxMDAwMDAwMDM5NTgwODUz
> 种豆
> olmijoxgmjutyoh3goxuhuroiaqvclhzp6ui7gy
> xooz5rk4vgwfmjat225uxziu4zpse5yx33wk5ja
> 
> 加了，今晚回去给你加上
1

**Comment by CfortWang** [comment]
> @CfortWang @ZHANGLIANGzhangliang @Joemercy 已添加

1

**Comment by xiaokaig** [comment]
真有意思，昨天加了4个  没一个回的

**Comment by ZHANGLIANGzhangliang** [comment]
> > @CfortWang @ZHANGLIANGzhangliang @Joemercy 已添加
> 
> 1

OK 今晚去加上

**Comment by hrt941009** [comment]
这些东西在哪里找？？

**Comment by cksspk** [comment]
============账号1

京东农场 shareCode：3af2240c38724b81b884d534f5a74ec5
种豆得豆 shareCode：e7lhibzb3zek2q4jiziyrkhq2ppvey2lymmnm5q
京东萌宠 shareCode：MTE1NDUwMTI0MDAwMDAwMDM4ODMyMTgz
摇钱树 lKMoe1K-LcruztdhUzBivsAdoUJQ3Dik
============账号2
京东农场 shareCode：1bad7dc05d8f4d6d820bb17b613d5abf
种豆得豆 shareCode：mlrdw3aw26j3wuevjwrdgoaloazwief2wmeyuzi
京东萌宠 shareCode：MTE1NDAxNzgwMDAwMDAwMzk2Njc4NzU=
摇钱树 4fDZAfc9bZBkGwrkwhhIlMAdoUJQ3Dik

还有两个坑位，长期互助加 tg好友来。

**Comment by 8tender** [comment]
@cksspk 
已互

东东农场
7b00dfbe6d314c1da472bccb9c26be21
东东萌宠 MTAxODc2NTEzMTAwMDAwMDAyODA2ODMzNQ==
种豆得豆 jae2j7zm6vnyenp2wqunux7ch4

种豆用的小号加的 小号互助码，其他正常wrqpt6mmzjh2ylpfbp3k33kborlxs2n7t4rx4py

**Comment by 8tender** [comment]
> ============账号1
> 
> 
> 
> 京东农场 shareCode：3af2240c38724b81b884d534f5a74ec5
> 
> 种豆得豆 shareCode：e7lhibzb3zek2q4jiziyrkhq2ppvey2lymmnm5q
> 
> 京东萌宠 shareCode：MTE1NDUwMTI0MDAwMDAwMDM4ODMyMTgz
> 
> 摇钱树 lKMoe1K-LcruztdhUzBivsAdoUJQ3Dik
> 
> ============账号2
> 
> 京东农场 shareCode：1bad7dc05d8f4d6d820bb17b613d5abf
> 
> 种豆得豆 shareCode：mlrdw3aw26j3wuevjwrdgoaloazwief2wmeyuzi
> 
> 京东萌宠 shareCode：MTE1NDAxNzgwMDAwMDAwMzk2Njc4NzU=
> 
> 摇钱树 4fDZAfc9bZBkGwrkwhhIlMAdoUJQ3Dik
> 
> 
> 
> 还有两个坑位，长期互助加 tg好友来。
@cksspk 

已互

东东农场
7b00dfbe6d314c1da472bccb9c26be21
东东萌宠 MTAxODc2NTEzMTAwMDAwMDAyODA2ODMzNQ==
种豆得豆 jae2j7zm6vnyenp2wqunux7ch4

种豆用的小号加的 小号互助码，其他正常wrqpt6mmzjh2ylpfbp3k33kborlxs2n7t4rx4py

**Comment by cksspk** [comment]
> 东东农场
> 7b00dfbe6d314c1da472bccb9c26be21
> 东东萌宠 MTAxODc2NTEzMTAwMDAwMDAyODA2ODMzNQ==
> 种豆得豆 jae2j7zm6vnyenp2wqunux7ch4

两个账号都加进去了吗，最好加一下tg好友【（+1）2512419167】，长期稳定

**Comment by 8tender** [comment]
> > 东东农场
> 
> > 7b00dfbe6d314c1da472bccb9c26be21
> 
> > 东东萌宠 MTAxODc2NTEzMTAwMDAwMDAyODA2ODMzNQ==
> 
> > 种豆得豆 jae2j7zm6vnyenp2wqunux7ch4
> 
> 
> 
> 两个账号都加进去了吗，最好加一下tg好友【（+1）2512419167】，长期稳定

@kim_ctrl这个是我的telegram 你加我吧
+1 518 882 8683

**Comment by cksspk** [comment]
> > > 东东农场
> > 
> > 
> > > 7b00dfbe6d314c1da472bccb9c26be21
> > 
> > 
> > > 东东萌宠 MTAxODc2NTEzMTAwMDAwMDAyODA2ODMzNQ==
> > 
> > 
> > > 种豆得豆 jae2j7zm6vnyenp2wqunux7ch4
> > 
> > 
> > 两个账号都加进去了吗，最好加一下tg好友【（+1）2512419167】，长期稳定
> 
> @kim_ctrl这个是我的telegram 你加我吧
> +1 518 882 8683

原来我的电话号码打错了，我申请添加你了。

**Comment by 8tender** [comment]
> > > > 东东农场
> 
> > > 
> 
> > > 
> 
> > > > 7b00dfbe6d314c1da472bccb9c26be21
> 
> > > 
> 
> > > 
> 
> > > > 东东萌宠 MTAxODc2NTEzMTAwMDAwMDAyODA2ODMzNQ==
> 
> > > 
> 
> > > 
> 
> > > > 种豆得豆 jae2j7zm6vnyenp2wqunux7ch4
> 
> > > 
> 
> > > 
> 
> > > 两个账号都加进去了吗，最好加一下tg好友【（+1）2512419167】，长期稳定
> 
> > 
> 
> > @kim_ctrl这个是我的telegram 你加我吧
> 
> > +1 518 882 8683
> 
> 
> 
> 原来我的电话号码打错了，我申请添加你了。

根本没收到你的邀请 我互了你的账号1

**Comment by waf2311** [comment]
来的滴滴，位置足够
种豆得豆
tpjwlkvq5gsi4h2regwcr7rfpy3h7wlwy7o5jii
t52jiqtswyok5i6lsg2ycfr47bkzr6ocw3pbbyh6636hdakvtj5q
olmijoxgmjutyahybdtrpk7cbnmjggrfcv5mcyi

东东萌宠
MTE1NDQ5MzYwMDAwMDAwMzk2MTQ5MjM=
MTE1NDQ5OTIwMDAwMDAwMzk3MTQ3Njc=
MTE1NDQ5MzYwMDAwMDAwNDAyMzIzMDU=

东东农场
5806a9b3e12a4550a9ca98ffe9fa40a6
5a32e7d4b4234fafb463b5e6108e93b4
9d5a31dc663a41e89aacd410def3e316

**Comment by Cainxf** [comment]
@waf2311 加了你的第一个，求互

我的互助码：
农场FRUITSHARECODES：p45juc6xz6sxto6b5o4vco3pnq
萌宠PETSHARECODES：MTE1NDAxNzcwMDAwMDAwMzgxMTg1MjM=
种豆PLANT_BEAN_SHARECODES：01db9997b7f1463384401f177949a0cc

已加互助码：
FRUITSHARECODES：
fca74149d72e4439bcba8004b98654cf&5806a9b3e12a4550a9ca98ffe9fa40a6
PETSHARECODES：
MTAxODExNDYxMTEwMDAwMDAwMzk3NDk5NTM=&MTE1NDQ5MzYwMDAwMDAwMzk2MTQ5MjM=
PLANT_BEAN_SHARECODES：
4lwy5mz77xtwgpptpcojuugzqm&tpjwlkvq5gsi4h2regwcr7rfpy3h7wlwy7o5jii

车位还够，欢迎上车

**Comment by qiaodgn** [comment]
> 农场
> 
> > 74421f55fbaa424eac3c051d8df2e649
> > a6d7c5d3921b4db78a446940443cbdef
> 
> 萌宠
> 
> > MTE1NDUwMTI0MDAwMDAwMDM2MjgyNzAx
> > MTE1NDUwMTI0MDAwMDAwMDM4OTY4ODM5
> 
> 种豆
> 
> > mlrdw3aw26j3wcceffzxh2me5uwreuxwavvu3tq
> > f5pavyxxlph5pnjhw6ek3eistzsyzbdfiprb74y
> 
> 加了记得把自己的回复在下面



> 农场
> 
> > 74421f55fbaa424eac3c051d8df2e649
> > a6d7c5d3921b4db78a446940443cbdef
> 
> 萌宠
> 
> > MTE1NDUwMTI0MDAwMDAwMDM2MjgyNzAx
> > MTE1NDUwMTI0MDAwMDAwMDM4OTY4ODM5
> 
> 种豆
> 
> > mlrdw3aw26j3wcceffzxh2me5uwreuxwavvu3tq
> > f5pavyxxlph5pnjhw6ek3eistzsyzbdfiprb74y
> 
> 加了记得把自己的回复在下面

农场：
8803a839cf1f4a28ba202221095fb2f5
29e36177264243d088700cef10290cbf
c0c2d06c0a2646b9b361c983300e022b
宠萌：
MTAxODEyMjkxMDAwMDAwMDM5NjYyMDAx
MTAxODEyMjkyMDAwMDAwMDM5NzI5NDY5
MTAxODEyMjkxMDAwMDAwMDM5ODAyNDA3
种豆：
qfvwtim6bmqpsg6kwldc2up5yu
tp3wu4dkgtj7qbglpktxckojuq
pclm6pfvrikmzu3zj3fhzfbjmu5ac3f4ijdgqji

**Comment by wb-wzl20160815** [comment]
种豆得豆olmijoxgmjutzxiqqzkuqwm5t3n3dfmpodnzwza

4vvbjlml6tdfcfka3mrrdgk3bbork7jjpaoyvly
萌宠MTAxODc2NTEzOTAwMDAwMDAzMTI0MzI2MQ==

MTE1NDUyMjEwMDAwMDAwMzYwNjk5NTc=

农场4565def28447487aa86afff55f77078c

2b6f246a35ff420094e95caa2f13d435

发自我的iPhone

**Comment by noelff** [comment]
加了吗？

**Comment by qiaodgn** [comment]
> 农场
> 
> > 74421f55fbaa424eac3c051d8df2e649
> > a6d7c5d3921b4db78a446940443cbdef
> 
> 萌宠
> 
> > MTE1NDUwMTI0MDAwMDAwMDM2MjgyNzAx
> > MTE1NDUwMTI0MDAwMDAwMDM4OTY4ODM5
> 
> 种豆
> 
> > mlrdw3aw26j3wcceffzxh2me5uwreuxwavvu3tq
> > f5pavyxxlph5pnjhw6ek3eistzsyzbdfiprb74y
> 
> 加了记得把自己的回复在下面


> 种豆得豆
> 
> > 2nljvyctc5anhcpeqdxz3dgb7a3h7wlwy7o5jii
> 
> 东东农场
> 
> > 80dda086be6a449d99db7f841945bad5
> 
> 东东萌宠
> 
> > MTAxODExNDYxMTAwMDAwMDAwMzk5Mzg1ODM=
> 
> 求互！

农场：
8803a839cf1f4a28ba202221095fb2f5
29e36177264243d088700cef10290cbf
c0c2d06c0a2646b9b361c983300e022b
宠萌：
MTAxODEyMjkxMDAwMDAwMDM5NjYyMDAx
MTAxODEyMjkyMDAwMDAwMDM5NzI5NDY5
MTAxODEyMjkxMDAwMDAwMDM5ODAyNDA3
种豆：
qfvwtim6bmqpsg6kwldc2up5yu
tp3wu4dkgtj7qbglpktxckojuq
pclm6pfvrikmzu3zj3fhzfbjmu5ac3f4ijdgqji

**Comment by 8tender** [comment]
> 来的滴滴，位置足够
> 
> 种豆得豆
> 
> tpjwlkvq5gsi4h2regwcr7rfpy3h7wlwy7o5jii
> 
> t52jiqtswyok5i6lsg2ycfr47bkzr6ocw3pbbyh6636hdakvtj5q
> 
> olmijoxgmjutyahybdtrpk7cbnmjggrfcv5mcyi
> 
> 
> 
> 东东萌宠
> 
> MTE1NDQ5MzYwMDAwMDAwMzk2MTQ5MjM=
> 
> MTE1NDQ5OTIwMDAwMDAwMzk3MTQ3Njc=
> 
> MTE1NDQ5MzYwMDAwMDAwNDAyMzIzMDU=
> 
> 
> 
> 东东农场
> 
> 5806a9b3e12a4550a9ca98ffe9fa40a6
> 
> 5a32e7d4b4234fafb463b5e6108e93b4
> 
> 9d5a31dc663a41e89aacd410def3e316

@waf2311 弄了你每个程序第一个账户记得互我
种豆得豆
wrqpt6mmzjh2ylpfbp3k33kborlxs2n7t4rx4py
萌宠
MTAxODc2NTEzMTAwMDAwMDAyODA2ODMzNQ==
农场
cd12f662f26d4e00bd3395c12a62a849

**Comment by noelff** [comment]
农场8be38b68e10343ec8dd3cb009498b3cb
萌宠MTE1NDAxNzcwMDAwMDAwMzc4MzY2MzE=
种豆myse62g364zkeguz5xdtlqpxqm

**Comment by xin-code** [comment]
东东农场jd_fruit【农场4位 还剩4位】
554359d55fcc4a1fab5f17a946cbf338
4625d3914d044bacbae685e9d60f14c8

东东萌宠jd_pet 【萌宠5位 还剩5位】
MTE1NDQ5MzYwMDAwMDAwMzkwMTMzNTk=
MTAxODEyMjkxMDAwMDAwMDQwMDQ5ODU5

种豆得豆jd_plantBean 【种豆3位 还剩3位】
mlrdw3aw26j3xtlnoc5rovsdcl364xjx4ctvrhq
e7lhibzb3zek2volndkiirtldf2etf3cbfqgk5y

互互互 人在 秒回 ⭐  Telegram好友 18037289809

**Comment by Cainxf** [comment]
@xin-code 加了你的第一个号三个码，求互
农场FRUITSHARECODES：p45juc6xz6sxto6b5o4vco3pnq
萌宠PETSHARECODES：MTE1NDAxNzcwMDAwMDAwMzgxMTg1MjM=
种豆PLANT_BEAN_SHARECODES：01db9997b7f1463384401f177949a0cc

**Comment by cksspk** [comment]
> > > > > 东东农场
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 7b00dfbe6d314c1da472bccb9c26be21
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 东东萌宠 MTAxODc2NTEzMTAwMDAwMDAyODA2ODMzNQ==
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > > 种豆得豆 jae2j7zm6vnyenp2wqunux7ch4
> > 
> > 
> > > >
> > 
> > 
> > > >
> > 
> > 
> > > > 两个账号都加进去了吗，最好加一下tg好友【（+1）2512419167】，长期稳定
> > 
> > 
> > > 
> > 
> > 
> > > @kim_ctrl这个是我的telegram 你加我吧
> > 
> > 
> > > +1 518 882 8683
> > 
> > 
> > 原来我的电话号码打错了，我申请添加你了。
> 
> 根本没收到你的邀请 我互了你的账号1

兄弟，这个不是你的tg吗？
![image](https://user-images.githubusercontent.com/37790595/98919718-22e0f180-250a-11eb-8c46-cd519aba400d.png)

**Comment by cksspk** [comment]
> 东东农场jd_fruit【农场4位 还剩4位】
> 554359d55fcc4a1fab5f17a946cbf338
> 4625d3914d044bacbae685e9d60f14c8
> 
> 东东萌宠jd_pet 【萌宠5位 还剩5位】
> MTE1NDQ5MzYwMDAwMDAwMzkwMTMzNTk=
> MTAxODEyMjkxMDAwMDAwMDQwMDQ5ODU5
> 
> 种豆得豆jd_plantBean 【种豆3位 还剩3位】
> mlrdw3aw26j3xtlnoc5rovsdcl364xjx4ctvrhq
> e7lhibzb3zek2volndkiirtldf2etf3cbfqgk5y
> 
> 互互互 人在 秒回 ⭐ Telegram好友 18037289809

兄弟我加了你的，tg 我+1 2512419176

**Comment by zjs5201314** [comment]
> 农场
> 
> > 74421f55fbaa424eac3c051d8df2e649
> > a6d7c5d3921b4db78a446940443cbdef
> 
> 萌宠
> 
> > MTE1NDUwMTI0MDAwMDAwMDM2MjgyNzAx
> > MTE1NDUwMTI0MDAwMDAwMDM4OTY4ODM5
> 
> 种豆
> 
> > mlrdw3aw26j3wcceffzxh2me5uwreuxwavvu3tq
> > f5pavyxxlph5pnjhw6ek3eistzsyzbdfiprb74y
> 
> 加了记得把自己的回复在下面

已经添加
农场
8660b28dd4c64004920c44154899571b
种豆
mlrdw3aw26j3x6i33nwxsvmqgqkqo6ztzzt33si
mlrdw3aw26j3xavu6wjrur7lxeinhiaegksxfzy
萌宠
MTE1NDQ5OTUwMDAwMDAwNDAwNTA3NDE=

**Comment by zjs5201314** [comment]
农场
8660b28dd4c64004920c44154899571b
种豆
mlrdw3aw26j3x6i33nwxsvmqgqkqo6ztzzt33si
萌宠
MTE1NDQ5OTUwMDAwMDAwNDAwNTA3NDE=

**Comment by AlexQlynn** [comment]
> > 农场
> > > 74421f55fbaa424eac3c051d8df2e649
> > > a6d7c5d3921b4db78a446940443cbdef
> > 
> > 
> > 萌宠
> > > MTE1NDUwMTI0MDAwMDAwMDM2MjgyNzAx
> > > MTE1NDUwMTI0MDAwMDAwMDM4OTY4ODM5
> > 
> > 
> > 种豆
> > > mlrdw3aw26j3wcceffzxh2me5uwreuxwavvu3tq
> > > f5pavyxxlph5pnjhw6ek3eistzsyzbdfiprb74y
> > 
> > 
> > 加了记得把自己的回复在下面
> 
> 已经添加
> 农场
> 8660b28dd4c64004920c44154899571b
> 种豆
> mlrdw3aw26j3x6i33nwxsvmqgqkqo6ztzzt33si
> mlrdw3aw26j3xavu6wjrur7lxeinhiaegksxfzy
> 萌宠
> MTE1NDQ5OTUwMDAwMDAwNDAwNTA3NDE=

已加
京东种豆 vn4z3juyxwrrvncjaoawdlzvou4jhxs3lbk7l3i
京东萌宠 MTAxODc2NTEzMTAwMDAwMDAwMzE3MDkxNQ==
京东农场 0b3ad8c216224f4eb086d07a6aaa2884

**Comment by lxyok** [comment]
东东农场：844d1048d0264935a4c28322d4237237@9f9d6fcd291d44edb6a5c9ee295c0774
东东萌宠：MTAxODExNTM5NDAwMDAwMDAzOTc0MjI2Nw==@MTE1NDAxNzgwMDAwMDAwMzY1MzM4NjE=
种豆得豆：e7lhibzb3zek2vtmke2qtgtytqrd6jb6i2mtway@e7lhibzb3zek2hav43rcgeufsq5v5gpnjx6vkcy
两个号，加了我的，说一下 互加

**Comment by czxbin** [comment]
1:
东东农场 d9e0816b14274898a1450acdd8bc06ee
种豆得豆 7igmnio7goniqz3hfgaxbagi7m
东东萌宠 MTE1NDQ5MzYwMDAwMDAwMzcwMzU4OTk=

2:
东东农场 395601c02efa47e183fadd7552fc7529
种豆得豆 op2cwjhisskpqflyekqv4n7v4i3h7wlwy7o5jii
东东萌宠 MTE1NDUwMTI0MDAwMDAwMDM3MTIyMTMz

互助来，添加完互助码回复@我

**Comment by ykrank** [comment]
4个农场，5个萌宠坑，最好来一个没有助力其他人的号，我能全部填满

**Comment by ykrank** [comment]
> 1:
> 东东农场 d9e0816b14274898a1450acdd8bc06ee
> 种豆得豆 7igmnio7goniqz3hfgaxbagi7m
> 东东萌宠 MTE1NDQ5MzYwMDAwMDAwMzcwMzU4OTk=
> 
> 2:
> 东东农场 395601c02efa47e183fadd7552fc7529
> 种豆得豆 op2cwjhisskpqflyekqv4n7v4i3h7wlwy7o5jii
> 东东萌宠 MTE1NDUwMTI0MDAwMDAwMDM3MTIyMTMz
> 
> 互助来，添加完互助码回复@我

我有4个农场，5个萌宠坑，可以帮你填一半，要的话@我

**Comment by SuperAmi3401** [comment]
东东农场     76148f9a8b49440d8774089ef0df0202
种豆得豆     olmijoxgmjutzxbfdrapjktylqwiuth42vsx5qy
东东萌宠    MTAxODEyMjkxMDAwMDAwMDQwMzY2NTQ1

目前均只占了一个坑。求互，填了@我

**Comment by SuperAmi3401** [comment]
@ykrank 来嘛hxd

**Comment by donghaofei** [comment]
> 东东农场 76148f9a8b49440d8774089ef0df0202
> 种豆得豆 olmijoxgmjutzxbfdrapjktylqwiuth42vsx5qy
> 东东萌宠 MTAxODEyMjkxMDAwMDAwMDQwMzY2NTQ1
> 
> 目前均只占了一个坑。求互，填了@我
@SuperAmi3401 
农场
79588bc2437c48ca8bc36fe290a298dd
596303bb589e4621b17a2cbf23c6f1d8

萌宠
MTAxODc2NTEzMDAwMDAwMDAyOTk2MTY3Mw==
MTE1NDAxNzcwMDAwMDAwMzQ0Mzk3Nzk=

种豆
pclm6pfvrikmzpm6xdxhu4cnu77vysyem4kxisy
suqg5cye47cqmecvzxzvk3gkt4zkprqfokz3cxq

**Comment by lxyok** [comment]
@SuperAmi3401 
我农场 和 萌宠 还有位置
我的两个号
东东农场：844d1048d0264935a4c28322d4237237@9f9d6fcd291d44edb6a5c9ee295c0774
东东萌宠：MTAxODExNTM5NDAwMDAwMDAzOTc0MjI2Nw==@MTE1NDAxNzgwMDAwMDAwMzY1MzM4NjE=
种豆得豆：e7lhibzb3zek2vtmke2qtgtytqrd6jb6i2mtway@e7lhibzb3zek2hav43rcgeufsq5v5gpnjx6vkcy

**Comment by qaqc123** [comment]
种豆得豆e7lhibzb3zek2qvtgibycxn3wpvg4x2mtupscaa
还缺两个位置 
互加的@

**Comment by chihwell** [comment]
> 种豆得豆e7lhibzb3zek2qvtgibycxn3wpvg4x2mtupscaa
> 还缺两个位置
> 互加的@

@qaqc123 来

**Comment by SuperAmi3401** [comment]
@donghaofei 已加。

**Comment by SuperAmi3401** [comment]
求长期稳定互助关系，
加我tg:
ManhattanDr

**Comment by qaqc123** [comment]
种豆得豆e7lhibzb3zek2qvtgibycxn3wpvg4x2mtupscaa
缺一个

**Comment by czxbin** [comment]
1:
东东农场 d9e0816b14274898a1450acdd8bc06ee
种豆得豆 7igmnio7goniqz3hfgaxbagi7m
东东萌宠 MTE1NDQ5MzYwMDAwMDAwMzcwMzU4OTk=

2:
东东农场 395601c02efa47e183fadd7552fc7529
种豆得豆 op2cwjhisskpqflyekqv4n7v4i3h7wlwy7o5jii
东东萌宠 MTE1NDUwMTI0MDAwMDAwMDM3MTIyMTMz

互助来，添加完互助码回复@我

**Comment by donghaofei** [comment]
tg多少

发自我的iPhone

**Comment by xuanrr** [comment]
东东农场
a7861e984f2044599620879a770c5233
萌宠 MTAxODc2NTEzNTAwMDAwMDAyODk5NTE4Mw==
种豆得豆 e7lhibzb3zek3lt4uggfnijtyppiupb7d5dcgoq

互助tg@Zoctopus

**Comment by umichan0621** [comment]
萌宠：
MTAxODc2NTEzNTAwMDAwMDAyMzA2MTUwMQ==
农场：
2268f2503edd4d9d976774c3c591374a
种豆
vh5jxqjorpa4ds6baxdrzvhd3i3h7wlwy7o5jii
求互助，完事儿@一下

**Comment by umichan0621** [comment]
@qaqc123 已加
种豆
vh5jxqjorpa4ds6baxdrzvhd3i3h7wlwy7o5jii

**Comment by umichan0621** [comment]
@czxbin 两个号已加
萌宠：
MTAxODc2NTEzNTAwMDAwMDAyMzA2MTUwMQ==
农场：
2268f2503edd4d9d976774c3c591374a
种豆
vh5jxqjorpa4ds6baxdrzvhd3i3h7wlwy7o5jii

**Comment by xiegeg** [comment]
> 萌宠：
> MTAxODc2NTEzNTAwMDAwMDAyMzA2MTUwMQ ==
> 农场：
> 2268f2503edd4d9d976774c3c591374a
> 种豆
> vh5jxqjorpa4ds6baxdrzvhd3i3h7wlwy7o5jii
> 求互助，完事儿@一下

种豆

e7lhibzb3zek2qprli3dyxai5v4wdnmyqbtdm7i

mh5uulbrvnknlzvdcmukd7wuy23pcmua3pok2ba
种豆

804c76cdf9de40708b4d4022cb335ddf

b256ce5f4e764f939a254b629c5c8f46
萌宠
MTAxODEyMjkxMDAwMDAwMDM5MzgxMTA1

MTAxODEyMjkxMDAwMDAwMDM5ODA5OTgx

**Comment by xiegeg** [comment]
> 1：
> 东东农场d9e0816b14274898a1450acdd8bc06ee
> 种豆得豆7igmnio7goniqz3hfgaxbagi7m
> 东东萌宠MTE1NDQ5MzYwMDAwMDAwMzcwMzU4OTk =
> 
> 2：
> 东东农场395601c02efa47e183fadd7552fc7529
> 种豆得豆op2cwjhisskp​​qflyekqv4n7v4i3h7wlwy7o5jii
> 东东萌宠MTE1NDUwMTI0MDAwMDAwMDM3MTIyMTMz
> 
> 互助来，添加完互助码回复@我

种豆

e7lhibzb3zek2qprli3dyxai5v4wdnmyqbtdm7i

mh5uulbrvnknlzvdcmukd7wuy23pcmua3pok2ba
种豆

804c76cdf9de40708b4d4022cb335ddf

b256ce5f4e764f939a254b629c5c8f46
萌宠
MTAxODEyMjkxMDAwMDAwMDM5MzgxMTA1

MTAxODEyMjkxMDAwMDAwMDM5ODA5OTgx

**Comment by xiegeg** [comment]
种豆

e7lhibzb3zek2qprli3dyxai5v4wdnmyqbtdm7i

mh5uulbrvnknlzvdcmukd7wuy23pcmua3pok2ba
种豆

804c76cdf9de40708b4d4022cb335ddf

b256ce5f4e764f939a254b629c5c8f46
萌宠
MTAxODEyMjkxMDAwMDAwMDM5MzgxMTA1

MTAxODEyMjkxMDAwMDAwMDM5ODA5OTgx

**Comment by zhugui00** [comment]
@xiegeg 
萌宠： 
MTAxODEyMjkyMDAwMDAwMDM5MzIzMzQx
农场： 
b8d37c3f84d34df79a8655dfda660c66
种豆 
djc2ypndwi7fdbv7kcanog5yd4

萌宠：MTAxODExNDYxMTAwMDAwMDAwMzk0NjU5OTk=
农场：
780a2c4a50a04487af4f91e263cec491
种豆：
djc2ypndwi7fdmpioduf6cnunm

**Comment by umichan0621** [comment]
@xiegeg 萌宠加了，4个种豆？

**Comment by zhugui00** [comment]
@umichan0621  还有位置吗

**Comment by umichan0621** [comment]
@zhugui00 加你了

**Comment by zhugui00** [comment]
@umichan0621  ok 我也加了

**Comment by xiegeg** [comment]
种豆

e7lhibzb3zek2qprli3dyxai5v4wdnmyqbtdm7i

mh5uulbrvnknlzvdcmukd7wuy23pcmua3pok2ba
农场

804c76cdf9de40708b4d4022cb335ddf

b256ce5f4e764f939a254b629c5c8f46
萌宠
MTAxODEyMjkxMDAwMDAwMDM5MzgxMTA1

MTAxODEyMjkxMDAwMDAwMDM5ODA5OTgx

**Comment by xiegeg** [comment]
> @xiegeg萌宠加了，4个种豆？

错了，这是正确的
种豆

e7lhibzb3zek2qprli3dyxai5v4wdnmyqbtdm7i

mh5uulbrvnknlzvdcmukd7wuy23pcmua3pok2ba
农场

804c76cdf9de40708b4d4022cb335ddf

b256ce5f4e764f939a254b629c5c8f46
萌宠
MTAxODEyMjkxMDAwMDAwMDM5MzgxMTA1

MTAxODEyMjkxMDAwMDAwMDM5ODA5OTgx

**Comment by zhugui00** [comment]
@xiegeg 我加你了
萌宠：
MTAxODEyMjkyMDAwMDAwMDM5MzIzMzQx
MTAxODExNDYxMTAwMDAwMDAwMzk0NjU5OTk=
农场：
b8d37c3f84d34df79a8655dfda660c66
780a2c4a50a04487af4f91e263cec491
种豆
djc2ypndwi7fdbv7kcanog5yd4
djc2ypndwi7fdmpioduf6cnunm

**Comment by umichan0621** [comment]
@xiegeg 加上了

**Comment by forbibi** [comment]
京东种豆得豆（plantBean)   xaq3fso6ha2kqi34gekijjc3sklht2gwkpke22i
 东东萌宠 (pet)  MTE1NDAxNzgwMDAwMDAwMzY2ODc3MzE=
东东农场（水果）(fruit)   df2700bf2367427b92f0819ff142ebb7

**Comment by DamonChow** [comment]
京东种豆得豆（plantBean)      kzuwwnnl6zthevq7wzjnv2bj345ac3f4ijdgqji
东东萌宠 (pet)                          MTAxODc2NTEzMTAwMDAwMDAwNTIyMDExMw==
东东农场（水果）(fruit)           5819781d1b1241529ece7ed995b3efd2

**Comment by cwzg** [comment]
sharecode怎么获取？

**Comment by cwzg** [comment]
种豆得豆sharecode：ll3mwz2pg22errx3qhcsgit4im5ac3f4ijdgqji
东东农场sharecode：a4f8cd94a2a84030aa74dee712d897f4
东东萌宠sharecode：MTAxODcxOTI2NTAwMDAwMDAyNzMwMDI1NQ==

**Comment by kalagxw** [comment]
【东东农场互助码shareCode】 8161030c5bfb4d9f93a3fd93a2b5fb6a
【京东种豆得豆互助码shareCode】 4fdxadarnr3ecanshjk7s3ok7q
【东东萌宠互助码shareCode】 MTE1NDAxNzgwMDAwMDAwMzk5OTY0MjM=

**Comment by vinychou** [comment]
@kalagxw 已经加你了

**Comment by vinychou** [comment]
@kalagxw 
【东东农场互助码shareCode】9448e810525c44fca6ddc7c6e3689bcb
【京东种豆得豆互助码shareCode】okutqc72wd4ccuc7mu3ift5ulq3h7wlwy7o5jii
【东东萌宠互助码shareCode】MTAxODc2NTE0NzAwMDAwMDAyNDI1MDc4Mw==

**Comment by yaoshanliang** [comment]
互
农场：5365f9f30d4a4325bb65c39d37e9d5f5
