### ISSUE TITLE
能否添加选择云函数地区的变量

### ISSUE THREAD

**Issue by huangshi10492** [lxk0301/jd_scripts#280]

**Comment by aixiaolu** [comment]
severless.yml 里面可以自己修改

**Comment by huangshi10492** [comment]
> severless.yml 里面可以自己修改

同步上游仓库时会被覆盖，导致每次同步都要改一遍

**Comment by DoveBoy** [comment]
@huangshi10492 香港不好吗？可以访问最新的脚本地址，TG推送也不受影响

**Comment by huangshi10492** [comment]
😂

**Comment by aixiaolu** [comment]
> 😂

同步上游仓库是不是action自动同步云函数部署，那样没法修改severless参数吗

**Comment by huangshi10492** [comment]
> > 😂
> 
> 同步上游仓库是不是action自动同步云函数部署，那样没法修改severless参数吗

我说的同步是把这个仓库同步到我的仓库

**Comment by aixiaolu** [comment]
> > > 
> > 
> > 
> > 同步上游仓库是不是action自动同步云函数部署，那样没法修改severless参数吗
> 
> 我说的同步是把这个仓库同步到我的仓库

那没法了，大佬的要顾忌油管那些推送，选香港更全面点😂

**Comment by iouAkira** [comment]
https://github.com/lxk0301/jd_scripts/blob/master/.github/workflows/deploy_tencent_scf.yml#L28
可以你们谁在pr 云函数的可以加一个 
```

**Comment by iouAkira** [comment]
你们谁再pr 云函数相关的可以考虑加一下 测试一下
`if [ $DEPLOY_REGION ]; then sed -i "s/ap-hongkong/ap-guangzhou/g" serverless.yml; fi;`
和
`DEPLOY_REGION: ${{ secrets.DEPLOY_REGION}}`

**Comment by DoveBoy** [comment]
@iouAkira 我来测试
