### ISSUE TITLE
新加的PUBG活动错误

### ISSUE THREAD

**Issue by jk9527** [lxk0301/jd_scripts#288]
返回数据解析错误
![image](https://user-images.githubusercontent.com/40191829/101609898-7a5b7a00-3a42-11eb-9563-09d92e3299b8.png)

**Comment by Naivev** [comment]
action运行同错误
![image](https://user-images.githubusercontent.com/45974159/101610071-b8589e00-3a42-11eb-9f92-f55e4c5d7a90.png)

**Comment by lxk0301** [comment]
账号问题吧,  拿到的京东数据不完整

**Comment by pikaqiu112** [comment]
@lxk0301 什么意思

**Comment by jk9527** [comment]
我换过4，5个账号，全是这个错误

**Comment by QGsen** [comment]
> 我换过4，5个账号，全是这个错误

把代码中的助力部分函数删掉试试，我的删掉就成功了

**Comment by jk9527** [comment]
> > 我换过4，5个账号，全是这个错误
> 
> 把代码中的助力部分函数删掉试试，我的删掉就成功了

感谢，删掉助力别的任务可以执行了

**Comment by duandaxei** [comment]
`if (vo.shareId) console.log(`您的${$.name}好友助力码为：${vo.shareId}`)`
打印助力码前面加了判断后 可以了 `if (vo.shareId)`

**Comment by lxk0301** [comment]
> `if (vo.shareId) console.log(`您的${$.name}好友助力码为：${vo.shareId}`)`
> 打印助力码前面加了判断后 可以了 `if (vo.shareId)`

加个判断是可以 ,不过说到底还是部分账号的数据返回的不完整导致的

**Comment by duandaxei** [comment]
> > `if (vo.shareId) console.log(`您的${$.name}好友助力码为：${vo.shareId}`)`
> > 打印助力码前面加了判断后 可以了 `if (vo.shareId)`
> 
> 加个判断是可以 ,不过说到底还是部分账号的数据返回的不完整导致的

加了判断不报错 并且 还是输出了好友助力码。。。。。。
![image](https://user-images.githubusercontent.com/4309411/101714997-9fe59380-3ad5-11eb-816f-d87aece9cf99.png)

**Comment by Twinzo1** [comment]
本地运行是可以的
