### ISSUE TITLE
群晖跑自定义crontablist问题

### ISSUE THREAD

**Issue by Michaol** [lxk0301/jd_scripts#29]
完全是按照教程的默认设置，如果用默认的crontab list就一切正常，能看到运行的log。但是改用自定义my crontab list后，docker日志显示按时运行了指令，但是log里面是空白的，没有log就是无法判断是否正确执行。这个是什么情况？

**Comment by DarkAge2018** [comment]
一样，我用VPS也是这样子

**Comment by lxk0301** [comment]
大家用着都没问题，需要你们自己找问题了
