### ISSUE TITLE
超级直播间红包雨出错

### ISSUE THREAD

**Issue by askiter** [lxk0301/jd_scripts#290]
我是在Surge Tf版本里面跑的，我看在半点的时候确实执行了，但是没有任何提示出来，就手工执行了一下，报下面错误信息
Result: 
{

}

Log:
21:45:56.319335 
🔔超级直播间红包雨, 开始!
21:45:56.401722 
❗️超级直播间红包雨, 错误!
TypeError: undefined is not an object (evaluating 'data.data.iconArea[0]')
21:45:56.402417 
🔔超级直播间红包雨, 结束! 🕛 0.083 秒
21:45:56.402434 

请问这个问题如何处理？谢谢

**Comment by pikaqiu112** [comment]
@askiter 放弃

**Comment by GitCourser** [comment]
请问这个活动入口在哪里

**Comment by lxk0301** [comment]
> 我是在Surge Tf版本里面跑的，我看在半点的时候确实执行了，但是没有任何提示出来，就手工执行了一下，报下面错误信息
> Result:
> {
> 
> }
> 
> Log:
> 21:45:56.319335
> 🔔超级直播间红包雨, 开始!
> 21:45:56.401722
> ❗️超级直播间红包雨, 错误!
> TypeError: undefined is not an object (evaluating 'data.data.iconArea[0]')
> 21:45:56.402417
> 🔔超级直播间红包雨, 结束! 🕛 0.083 秒
> 21:45:56.402434
> 
> 请问这个问题如何处理？谢谢

不要手动执行
