### ISSUE TITLE
jd_bean_sign运行报错

### ISSUE THREAD

**Issue by wang-max1** [lxk0301/jd_scripts#291]
运行后telegram通知报错，错误如下
![image](https://user-images.githubusercontent.com/61648337/101657787-42265c80-3a7f-11eb-8194-207f07aa5d4f.png)
这个怎么解决，麻烦看下

**Comment by lxk0301** [comment]
就这一个脚本的通知出错?

**Comment by wang-max1** [comment]
> 就这一个脚本的通知出错?

只要有通知的都报错，我同时设置了bark和tg，就tg报错

**Comment by lxk0301** [comment]
@wang-max1 你docker的环境不能连接外网吧？

**Comment by wang-max1** [comment]
> @wang-max1 你docker的环境不能连接外网吧？
我刚测了一下，原因就是不能访问外网 
![image](https://user-images.githubusercontent.com/61648337/101730380-df6fa800-3af4-11eb-9994-a30a969082ef.png)

国内的阿里服务器  有什么解决办法么

**Comment by JunzhouLiu** [comment]
连接超时，部署在国内服务器上的话是没法通过tg进行消息推送的。
