### ISSUE TITLE
docker-compose部署的，这些助力邀请码该怎么填？

### ISSUE THREAD

**Issue by wxjbb** [lxk0301/jd_scripts#293]
苹果抽奖机，数码加购京豆，健康抽奖机，京喜故事，PUBG，东东小窝，金榜年终奖。
以上脚本都有显示自己的助力邀请码，但是不知道填在docker-compose.yml文件中时，使用的变量名是什么？

**Comment by wxjbb** [comment]
默认提供的配置文件中，只有这几个助力邀请码的填写示例
![image](https://user-images.githubusercontent.com/39824657/101716776-f2747f00-3ad8-11eb-96ee-5b77232204ea.png)
在[配置参考](https://github.com/lxk0301/jd_scripts/blob/master/githubAction.md#%E4%B8%8B%E6%96%B9%E6%8F%90%E4%BE%9B%E4%BD%BF%E7%94%A8%E5%88%B0%E7%9A%84-secrets%E5%85%A8%E9%9B%86%E5%90%88)中，也没有发现这些邀请码使用的环境变量名是多少。

**Comment by lxk0301** [comment]
暂没提供, 短期活动,
