### ISSUE TITLE
点点券活动新增部分项目貌似

### ISSUE THREAD

**Issue by hclbingxin** [lxk0301/jd_scripts#295]
![% VT2({FN77)24HUX_LBPKC](https://user-images.githubusercontent.com/75673629/101767912-dea03b80-3b1f-11eb-83e0-926726328ed4.jpg)

**Comment by hclbingxin** [comment]
![Uploading image.png…]()

**Comment by hclbingxin** [comment]
![image](https://user-images.githubusercontent.com/75673629/101768017-068f9f00-3b20-11eb-9b65-ebd032693ae4.png)

**Comment by lxk0301** [comment]
![602A454B-AF56-4183-B914-C6DE5B8643D8](https://user-images.githubusercontent.com/21308593/101782014-7a877280-3b33-11eb-8924-de3071775093.png)
我这边任务都做完了呢
