### ISSUE TITLE
京东，发现，看一看，看视频得豆子

### ISSUE THREAD

**Issue by sgzman** [lxk0301/jd_scripts#300]
有的是看30个视频得60 ，有的是35个视频得70.

**Comment by servicehost** [comment]
看一看 的这个活动，我就从来没有成功过，点旁边的浮窗领京豆 - 做任务，根本没任何反应。
点进具体页面中虽然会出现任务完成的进度浮窗，但完成后看任务根本一个也没成功。

**Comment by sgzman** [comment]
> 看一看 的这个活动，我就从来没有成功过，点旁边的浮窗领京豆 - 做任务，根本没任何反应。
> 点进具体页面中虽然会出现任务完成的进度浮窗，但完成后看任务根本一个也没成功。

我可以的

**Comment by servicehost** [comment]
> 
> 
> > 看一看 的这个活动，我就从来没有成功过，点旁边的浮窗领京豆 - 做任务，根本没任何反应。
> > 点进具体页面中虽然会出现任务完成的进度浮窗，但完成后看任务根本一个也没成功。
> 
> 我可以的

看你这么说，我换了台iOS设备试了下，果然可以。手机是android的，就是不行，无法完成任务。

**Comment by yjjuneyjj** [comment]
> > > 看一看 的这个活动，我就从来没有成功过，点旁边的浮窗领京豆 - 做任务，根本没任何反应。
> > > 点进具体页面中虽然会出现任务完成的进度浮窗，但完成后看任务根本一个也没成功。
> > 
> > 
> > 我可以的
> 
> 看你这么说，我换了台iOS设备试了下，果然可以。手机是android的，就是不行，无法完成任务。

是不是手机开发者选项里的动画缩放加速了？这个会影响的。

**Comment by servicehost** [comment]
> 是不是手机开发者选项里的动画缩放加速了？这个会影响的。

厉害，确实是这个原因，我之前改成了0.5x，改回1x后就正常了。

**Comment by enews** [comment]
今天执行了看一看的脚本,提示活动结束, 但是手机上看又有活动

**Comment by sgzman** [comment]
> 今天执行了看一看的脚本,提示活动结束, 但是手机上看又有活动

脚本今天刚出来，估计还是有bug的

**Comment by servicehost** [comment]
看一看现在的脚本确实还是有bug，试了最新版的 jd_watch.js，我只能完成2个任务，然后就不行了。
之后再次执行，就会提示：

discTaskList
京东看一看浏览次数：2/40
discAcceptTask
discAcceptTask
discTaskList
京东账号1

**Comment by sgzman** [comment]
> > 看一看现在的脚本确实还是有bug，试了最新版的 jd_watch.js，我只能完成2个任务，然后就不行了。
> > 之后再次执行，就会提示：
> > discTaskList
> > 京东看一看浏览次数：2/40
> > discAcceptTask
> > discAcceptTask
> > discTaskList
> > 京东账号1
> > 看了下代码的注释：
> > /*
> > 使用 Charles 抓包，使用正则表达式：functionId=disc(AcceptTask|DoTask) 过滤请求
> > 选中所有请求，将所有请求保存为 JSON Session File 名称为 watch.chlsj，将该文件与jd_watch.js放在相同目录中
> > 使用手机抓包，将functionId=discAcceptTask的请求填入acceptBody，将discDoTask的body填入doBody
> > */
> > 这个意思是要自己抓包添到代码里才可以的？
> 
> 是的。自己抓包。明天兼容一下 支持提供环境变量吧。到时候自己抓包自己用

有个疑问，

**Comment by servicehost** [comment]
> 是的。自己抓包。明天兼容一下 支持提供环境变量吧。到时候自己抓包自己用

OK，明白了，今天更新后可以正常跑了。但是每次都只能执行38个，到第39时就会出现如下提示：

"The `body` option must be a stream.Readable, string or Buffer"
京东看一看 API请求失败，请检查网路重试

再重复执行一次后才会把剩下的39、40跑完。

**Comment by pikaqiu112** [comment]
@servicehost 你直接叫说执行两次就好啦

**Comment by pikaqiu112** [comment]
@pikaqiu112

**Comment by servicehost** [comment]
> @servicehost 你直接叫说执行两次就好啦

我觉的详细说清第几次出现问题，更便于作者定位bug

**Comment by pikaqiu112** [comment]
@servicehost 哦哦哦...
