### ISSUE TITLE
docker方法一 ⚠️⚠️⚠️2020-12-11更新镜像

### ISSUE THREAD

**Issue by lxk0301** [lxk0301/jd_scripts#302]
⚠️⚠️⚠️2020-12-11更新镜像启动方式，虽然兼容旧版的运行启动方式，但是强烈建议更新镜像和配置后使用

更新后commad:指令配置不再需要
更新后可以使用自定义任务文件追加在默任务文件之后，比以前的完全覆盖多一个选择
新的自定两个环境变量为 CUSTOM_LIST_MERGE_TYPE:自定文件的生效方式可选值为append，overwrite默认为append ; CUSTOM_LIST_FILE: 自定义文件的名字
更新镜像增减镜像更新通知，以后镜像如果更新之后，会通知用户更新

**Comment by mengdie101** [comment]
rollbackFailedOptional: verb npm-session，群晖docker更新之后日志里出现这个是怎么回事，npm安装不成功吗，但是脚本好像运行正常

**Comment by creazy412** [comment]
如何才能进到 `http://api.turinglabs.net/api/v1/jd/bean/read/${randomCount}/`  这个助力码池中来呢？
