### ISSUE TITLE
TG发送通知有问题

### ISSUE THREAD

**Issue by xie0027** [lxk0301/jd_scripts#303]
TG不能正常发送通知
2020-12-11T10:05:52.434Z 913fd261-8745-4cb5-a1e9-4fd727b79308 HTTPError: Response code 400 (Bad Request)

    at Request.<anonymous> (/var/user/node_modules/got/dist/source/as-promise/index.js:117:42)

    at processTicksAndRejections (internal/process/task_queues.js:97:5) {

  name: 'HTTPError',

  code: undefined,

  timings: {

    start: 1607681148185,

    socket: 1607681148185,

    lookup: 1607681148189,

    connect: 1607681148445,

    secureConnect: 1607681148703,

    upload: 1607681148703,

    response: 1607681152433,

    end: 1607681152433,

    error: undefined,

    abort: undefined,

    phases: {

      wait: 0,

      dns: 4,

      tcp: 256,

      tls: 258,

      request: 0,

      firstByte: 3730,

      download: 0,

      total: 4248

    }

  }

}

**Comment by lxk0301** [comment]
自己的问题, 看着教程好好操作

**Comment by lxk0301** [comment]
https://github.com/lxk0301/jd_scripts/blob/master/backUp/TG_PUSH.md


少一个步骤, 给你创建的机器人,随便发个什么文字私聊一下

**Comment by xie0027** [comment]
好的 我自己直接调用API没有问题 晚点再试试  谢谢大佬！

**Comment by lxk0301** [comment]
> 好的 我自己直接调用API没有问题 晚点再试试 谢谢大佬！

那就是你两个环境变量没填写对

**Comment by xie0027** [comment]
后面测试是正常的了  然后顺带问一句  直播红包雨是不是活动没了啊？  从昨天开始就一直提示暂无红包雨

**Comment by lxk0301** [comment]
> 后面测试是正常的了 然后顺带问一句 直播红包雨是不是活动没了啊？ 从昨天开始就一直提示暂无红包雨

每次都要换东西。放弃吧
