### ISSUE TITLE
东东萌宠和种豆得豆错误会自动退出。

### ISSUE THREAD

**Issue by kylinpoet** [lxk0301/jd_scripts#314]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否仔细阅读了教程
- [x ] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [x ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：如果存在多个账号，当有一个账号的东东萌宠，种豆得豆等错误的时候，系统会自动退出。不会进行其它账号的处理。

### (2) 详细日志
A：
Dec 12 20:00:40 开始【京东账号2】李长东199
Dec 12 20:00:40 
Dec 12 20:00:53 随机取个20码放到您固定的互助码后面
Dec 12 20:00:53 第2个京东账号将要助力的好友["4npkonnsy7xi3p6pjfxg6ct5gll42gmvnz7zgoy","6dygkptofggtp6ffhbowku3xgu","mlrdw3aw26j3wgzjipsxgonaoyr2evrdsifsziy","4rklmphgold4eolmrjwy2bsk6a","e7lhibzb3zek3lg332apt7kdzkdponpudegqsri","lhcah5obphzcg5m5gyji2u44be","xzmrlv5qjuuek534ufbum2fvry","yxjqikof7eaxxcuvetay44pgsa","4npkonnsy7xi34poup5ogjyk7vju42ew6odx6ni","4npkonnsy7xi2yvn5ubzhxnf63twcrmpfk7emzi","4npkonnsy7xi3suwyjqzifyng6djsbatsdz7pta","5q5gjs3yqwxr7grtaqxlycwgybw2xahe2gcocrq","pcq74evje7vyvasjmjby7ye2gr75dszlm3espsy","hzsxvtmuobdm6iqf63u7zzkdfkpsxi4n5womggi","e7anq2a6unhwi7ktnumzxvau5q","olmijoxgmjutyjlva554mm6gwrydlstf4xej6ma","5htjgxhaayy3hlsj2sv4d6cenm3h7wlwy7o5jii","ugw6x5eu3cdtaj63yzxj3rrhva","4npkonnsy7xi2gabq7b7adyh4cjgh6jjsykbtnq","4pp7vs6pf3df7gvjymt2poq7uzwglsiz5iypmwy","e7lhibzb3zek2bqgete3ziweplgel2x63drdxsa","zq3dwgrx4lcnhuyfyuap22jna73xbovy3oehvla","4qwdga4m3vuok667vmfm6xlvbm5ac3f4ijdgqji"]
Dec 12 20:00:53 获取任务及基本信息
Dec 12 20:00:55 
Dec 12 20:00:55 ❌ 京东种豆得豆, 失败! 原因: TypeError: Cannot read property 'jwordShareInfo' of undefined!
Dec 12 20:00:55 
Dec 12 20:00:55 
Dec 12 20:00:55 🔔京东种豆得豆, 结束! 🕛 55.318 秒
Dec 12 20:00:55 
Dec 12 20:02:07 随机取个20码放到您固定的互助码后面

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by lxk0301** [comment]
这种没办法 你这账号拿到的数据不对
