### ISSUE TITLE
个人认为是目前 最简单方便的方法

### ISSUE THREAD

**Issue by sgzman** [lxk0301/jd_scripts#32]
https://github.com/zdrka/Action-jd-scripts/generate
①点击上述链接（感谢@zdrka提供的模板。），生成一个自己的仓库。
②在settings中的secrets中填写之前的配置。

然后等着执行action就行了,可以等半个小时一个小时看看会有action执行的记录不。
感觉是最简单的方法了。
就是不知道对作者的仓库会造成影响不@lxk0301

如果好用的话，可以把俺的分享码加到secrets进去哦

**东东萌宠** MTAxODc2NTE0NzAwMDAwMDAyMTg4MzQ2Mw==
**种豆得豆** mlrdw3aw26j3x33ecstbgztirjawf5wsbq7fpwi

**Comment by xiazhaoxiong** [comment]
唉

**Comment by zengxiangj** [comment]
点 页面上的  use this templete。又回到新建新建仓库的页面了。

**Comment by hrt941009** [comment]
自己把代码拉下来 自己搞个私有仓库 改下配置  自己仓库里面跑

**Comment by sgzman** [comment]
> 点 页面上的 use this templete。又回到新建新建仓库的页面了。

不需要点use this templete，我写错了

**Comment by bcb9866219** [comment]
Actions里没看到自动同步的action，怎么保持代码更新的？

**Comment by sgzman** [comment]
> Actions里没看到自动同步的action，怎么保持代码更新的？

不用保持，checkout的时候，就是大佬的代码仓库的js，你可以看一下action的运行日志

**Comment by WYisShuaiBi** [comment]
> > Actions里没看到自动同步的action，怎么保持代码更新的？
> 
> 不用保持，checkout的时候，就是大佬的代码仓库的js，你可以看一下action的运行日志

不过新增脚本或者删除脚本就麻烦了..得我们偶尔看看然后自己把yml写一份

**Comment by lxk0301** [comment]
肯定影响哇。action里面checkout都是从我这边git
clone，从我这里下载脚本的，到时候顺藤摸瓜，又摸到我这边来了，和你们fork走没差别。

到时候还会被封禁我主库。

**Comment by leecheng310** [comment]
> 肯定影响哇。action里面checkout都是从我这边git
> clone，从我这里下载脚本的，到时候顺藤摸瓜，又摸到我这边来了，和你们fork走没差别。
> 
> 到时候还会被封禁我主库。

大佬太难了· ···

**Comment by sgzman** [comment]
> 肯定影响哇。action里面checkout都是从我这边git
> clone，从我这里下载脚本的，到时候顺藤摸瓜，又摸到我这边来了，和你们fork走没差别。
> 
> 到时候还会被封禁我主库。

那我还是走自己的克隆的仓库吧，对于你的仓库来说安全点

**Comment by leecheng311** [comment]
多分一些克隆仓，加大摸瓜难度。
还有双十一过了，热度低了。活动少了。资源占用也会少很多。
