### ISSUE TITLE
仓库地址变更后docker版pull命令失效

### ISSUE THREAD

**Issue by sorakirahk** [lxk0301/jd_scripts#33]
由于仓库地址变更，导致docker执行pull命令时报错

> fatal: could not read Username for 'https://github.com': No such device or address

请问如何修改仓库地址？

**Comment by iouAkira** [comment]
@sorakirahk docker-compose pull更新镜像

**Comment by xiaokaig** [comment]
命令改下连接啊

**Comment by sorakirahk** [comment]
> @sorakirahk docker-compose pull更新镜像

看到你的评论后，于16：46分更新镜像，并且重启docker
还是报错

**Comment by lxk0301** [comment]
@sorakirahk 我自己都没问题 。 更新镜像就行，

**Comment by iouAkira** [comment]
> > @sorakirahk docker-compose pull更新镜像
> 
> 看到你的评论后，于16：46分更新镜像，并且重启docker
> 还是报错

如果你用的是 `restart`  应该是没使用新版镜像， 你使用 `docke-compose up -d` 自动重建试试吧

**Comment by sorakirahk** [comment]
> @sorakirahk 我自己都没问题 。 更新镜像就行，

> 如果你用的是 `restart` 应该是没使用新版镜像， 你使用 `docke-compose up -d` 自动重建试试吧

好的，我重新创建一下容器试试

**Comment by sorakirahk** [comment]
重建容器后成功更新镜像
