### ISSUE TITLE
docker的jxstory.js似乎会卡死

### ISSUE THREAD

**Issue by 627992512** [lxk0301/jd_scripts#335]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [x] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：jxstory.js似乎会卡死，然后大量占用内存

### (2) 详细日志
A：🔔京喜故事, 开始!

====================共有1个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：12/13/2020, 12:10:11 AM=====================

开始获取京喜故事配置文件

共1个京东账号

您提供了0个账号的京喜故事助力码

******开始【京东账号1】末蓝星星*********

由于您第1个京东账号未提供shareCode,将采纳本脚本自带的助力码

第1个京东账号将要助力的好友["qSDHMwUOz7onHcMyaju4KmdSXWf0dlv7LVnTt1Wzemo=","iuGNoGYvk9YdEImUAz25Wyzm7oeggrm0JSIYgZdHJGI="]
异常：{"msg":"当前不在活动时间内哦~","nowTime":1607789465,"ret":2006}
助力朋友[qSDHMwUOz7onHcMyaju4KmdSXWf0dlv7LVnTt1Wzemo=]失败：当前不在活动时间内哦~
助力朋友[iuGNoGYvk9YdEImUAz25Wyzm7oeggrm0JSIYgZdHJGI=]失败：当前不在活动时间内哦~
签到钞票：收取失败，当前不在活动时间内哦~
去做任务：去京喜工厂投电力
异常：{"data":{"awardStatus":0,"completedTimes":0,"dateTypeExtra":"","updateTime":0,"userStatusConfigExtra":""},"msg":"亲,活动太火爆了,请稍后再试吧!","ret":1015}
领取去京喜工厂投电力任务奖励失败，任务已领奖
去做任务：去签到领现金提现,去工厂挑好货开造,出海寻宝领100元红包
做任务完成！
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
去做任务：去签到领现金提现,去工厂挑好货开造,出海寻宝领100元红包
做任务完成！
领取去签到领现金提现,去工厂挑好货开造,出海寻宝领100元红包任务奖励成功，收获：5000钞票
去做任务：去签到领现金提现,去工厂挑好货开造,出海寻宝领100元红包
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
去做任务：去签到领现金提现,去工厂挑好货开造,出海寻宝领100元红包
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
去做任务：0元领整箱鲜果零食,上岛0元领爆款好物,邀好友分百万红包
做任务完成！
领取0元领整箱鲜果零食,上岛0元领爆款好物,邀好友分百万红包任务奖励成功，收获：5000钞票
去做任务：0元领整箱鲜果零食,上岛0元领爆款好物,邀好友分百万红包
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
去做任务：0元领整箱鲜果零食,上岛0元领爆款好物,邀好友分百万红包
做任务完成！
领取0元领整箱鲜果零食,上岛0元领爆款好物,邀好友分百万红包任务奖励成功，收获：5000钞票
去做任务：0元领整箱鲜果零食,上岛0元领爆款好物,邀好友分百万红包
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
去做任务：逛一逛“抽纸盒”,逛一逛“保鲜袋”,逛一逛“原木筷”,逛一逛“水彩笔”
做任务完成！
领取逛一逛“抽纸盒”,逛一逛“保鲜袋”,逛一逛“原木筷”,逛一逛“水彩笔”任务奖励成功，收获：5000钞票
去做任务：逛一逛“抽纸盒”,逛一逛“保鲜袋”,逛一逛“原木筷”,逛一逛“水彩笔”
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
去做任务：逛一逛“抽纸盒”,逛一逛“保鲜袋”,逛一逛“原木筷”,逛一逛“水彩笔”
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
去做任务：逛一逛“抽纸盒”,逛一逛“保鲜袋”,逛一逛“原木筷”,逛一逛“水彩笔”
做任务完成！
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
去做任务：逛一逛“抽纸盒”,逛一逛“保鲜袋”,逛一逛“原木筷”,逛一逛“水彩笔”
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
去做任务：逛一逛“东东超市”,逛一逛“马克杯”,逛一逛“发带”,逛一逛“保鲜袋”
做任务完成！
领取逛一逛“东东超市”,逛一逛“马克杯”,逛一逛“发带”,逛一逛“保鲜袋”任务奖励成功，收获：5000钞票
去做任务：逛一逛“东东超市”,逛一逛“马克杯”,逛一逛“发带”,逛一逛“保鲜袋”
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
去做任务：逛一逛“东东超市”,逛一逛“马克杯”,逛一逛“发带”,逛一逛“保鲜袋”
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
去做任务：逛一逛“东东超市”,逛一逛“马克杯”,逛一逛“发带”,逛一逛“保鲜袋”
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
去做任务：逛一逛“东东超市”,逛一逛“马克杯”,逛一逛“发带”,逛一逛“保鲜袋”
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
"Response code 401 (Unauthorized)"
京喜故事 API请求失败，请检查网路重试
完成任务：共领取25000钞票
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒
点击厂长过快，休息25秒

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by 627992512** [comment]
下面全是这个：点击厂长过快，休息25秒

**Comment by DoveBoy** [comment]
@627992512 活动都结束了，还在跑这个脚本？

**Comment by lxk0301** [comment]
活动已结束。删除或者禁用此脚本吧

**Comment by 627992512** [comment]
好的好的
