### ISSUE TITLE
BARK能否改成完整链接？

### ISSUE THREAD

**Issue by Mark-1215** [lxk0301/jd_scripts#339]
## 期望增加的功能

A：BARK期望能改成完整链接，因为BARK很多人是自己搭建的服务，这样可以更好的避免隐私泄露问题。

## 入口

A：

**Comment by lxk0301** [comment]
一直都兼容自建的

直接环境变量填完整链接即可

https://github.com/lxk0301/jd_scripts/blob/master/sendNotify.js#L42

**Comment by Mark-1215** [comment]
原来如此，建议在教程上注明~感谢提醒

**Comment by lxk0301** [comment]
> 原来如此，建议在教程上注明~感谢提醒
> https://github.com/lxk0301/jd_scripts/blob/master/githubAction.md#%E4%B8%8B%E6%96%B9%E6%8F%90%E4%BE%9B%E4%BD%BF%E7%94%A8%E5%88%B0%E7%9A%84-secrets%E5%85%A8%E9%9B%86%E5%90%88

等你添加注明pr过来
