### ISSUE TITLE
不知道我这个方法可不可行，我自己可以用

### ISSUE THREAD

**Issue by sensi-ribbed** [lxk0301/jd_scripts#34]
我用了一个方法，似乎不用去大佬的库下载脚本
1. 首先在gitee里面fork大佬的jd_scripts库，在自己fork的库新建一个分支，在新建分支里面上传大佬的yml执行文件。
2.在github新建一个库，把大佬的repo_sync.yml文件上传
3.在gitee你新建分支里把yml执行文件的checkout的仓库地址全部换成你自己github新建库的地址：
 - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: 你自己的GitHub新建库
4.在GitHub新库和gitee你的分支里面，把repo_sync.yml文件的 下面三个参数修改一下：
         source_repo: "https://gitee.com/你自己的名字/jd_scripts.git"
          source_branch: "gitee里面你新建的分支"
          destination_branch: "GitHub里你的新库（main或者master）"

5.回到github在action里运行sync-lxk0301-scripts，不出意外所有文件就都过来了，接下来就没啥问题了。
6.这样大佬更新代码，我们可以在gitee同步，然后合并自己的分支，GitHub可以自动同步自己的gitee分支。

**Comment by ilredirana** [comment]
听起来很不错啊，我也试试

**Comment by nxppru** [comment]
请问第三部是改第一步上传的15个yml还是单独repo_sync.yml文件？

**Comment by HenryTSZ** [comment]
> 请问第三部是改第一步上传的15个yml还是单独repo_sync.yml文件？

这 15 个 yml 在哪里呀, 我咋找不到啊

**Comment by blacklisten** [comment]
@sensi-ribbed @JohnHa0  没同步过来，是一个url地址？还是 用户名/仓库名？ 两种我都试了...都没成功呀，可否在给详细一点的描述
![image](https://user-images.githubusercontent.com/26319882/98761203-e7fa9300-240f-11eb-8822-c0aedfe51a72.png)

**Comment by ilredirana** [comment]
> > 请问第三部是改第一步上传的15个yml还是单独repo_sync.yml文件？
> 
> 这 15 个 yml 在哪里呀, 我咋找不到啊

initial commit里面有

**Comment by blacklisten** [comment]
> > > 请问第三部是改第一步上传的15个yml还是单独repo_sync.yml文件？
> > 
> > 
> > 这 15 个 yml 在哪里呀, 我咋找不到啊
> 
> initial commit里面有

大佬给我指点指点？一直同步不过来啊

**Comment by sensi-ribbed** [comment]
> @sensi-ribbed @JohnHa0 没同步过来，是一个url地址？ 还是 用户名/仓库名？ 两种我都试了... 都没成功呀，可否在给详细一点的描述
> ![image](https://user-images.githubusercontent.com/26319882/98761203-e7fa9300-240f-11eb-8822-c0aedfe51a72.png)

你这个运行完成了啊，如果步骤正确，没有显示有文件同步过来，点一下星星star，然后刷新页面

**Comment by sensi-ribbed** [comment]
> > @sensi-ribbed @JohnHa0 没同步过来，是一个url地址？ 还是 用户名/仓库名？ 两种我都试了... 都没成功呀，可否在给详细一点的描述
> > ![image](https://user-images.githubusercontent.com/26319882/98761203-e7fa9300-240f-11eb-8822-c0aedfe51a72.png)
> 
> 你这个运行完成了啊，如果步骤正确，没有显示有文件同步过来，点一下星星star，然后刷新页面

擦，看错了，你这个失败了，那有地方没有对

**Comment by blacklisten** [comment]
@sensi-ribbed 你的repo_sync.yml是拿的旧的还是新仓库里面最新的呢，我发现我拿的最新的，我找一个旧的试试

**Comment by blacklisten** [comment]
repo_sync: 
![image](https://user-images.githubusercontent.com/26319882/98763292-ad472980-2414-11eb-912b-9149ee0eb49d.png)
其它yml：
![image](https://user-images.githubusercontent.com/26319882/98763329-c0f29000-2414-11eb-8592-99489adfafc7.png)
有什么问题么... @sensi-ribbed

**Comment by sensi-ribbed** [comment]
> @sensi-ribbed 你的repo_sync.yml是拿的旧的还是新仓库里面最新的呢，我发现我拿的最新的，我找一个旧的试试

一样吧，主要是：
1. repo_sync.yml文件
 if: env.PAT
        with:
          source_repo: "这里填gitee地址"
          source_branch: "dev"  //这里是gitee新建分支（我是dev，你自己随便起的行）
          destination_branch: "master" //这里是你Github自建库的（不是master就是main或者你自己随便起的）

2.修改workflows的全部执行yml文件：

steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: sensi-ribbed/jd_scripts  //这里修改你自己的Gthub新建库

3.就这几步，然后gitee里master分支同步大佬代码，自己把master分支合并到新建dev分支，到Github跑repo_sync.yml
4.如果步骤正确，没有显示有文件同步过来，点一下星星star，然后刷新页面

**Comment by blacklisten** [comment]
没仔细看代码...  这个是需要自己申请下PAT的对吧 @sensi-ribbed

**Comment by sensi-ribbed** [comment]
> 没仔细看代码... 这个是需要自己申请下PAT的对吧 @sensi-ribbed

艹，当然了，你以前用大佬repo_sync不用PAT的吗

**Comment by blacklisten** [comment]
> > 没仔细看代码... 这个是需要自己申请下PAT的对吧 @sensi-ribbed
> 
> 艹，当然了，你以前用大佬repo_sync不用PAT的吗

![image](https://user-images.githubusercontent.com/26319882/98764193-40349380-2416-11eb-905f-4539743238bb.png)
多亏了你这行代码，我一直没去仔细看...  现在可以了，多谢大佬

**Comment by nxppru** [comment]
生成PTA要选repo, workflow权限

**Comment by nxppru** [comment]
生成PAT要选repo, workflow权限

**Comment by a619665203** [comment]
大佬们有没有交流群

**Comment by nxppru** [comment]
如何避免自己新建github中repo_sync.yml文件本身不被更新

**Comment by HenryTSZ** [comment]
> UPSTREAM_REPO=https://gitee.com/henrytsz/jd_scripts.git
> BRANCHES=yml:main
> Resetting origin to: ***github.com/HenryTSZ/jd-yml
> Adding tmp_upstream https://gitee.com/henrytsz/jd_scripts.git
> Fetching tmp_upstream
> fatal: could not read Username for 'https://gitee.com': No such device or address

**Comment by sensi-ribbed** [comment]
> > UPSTREAM_REPO=https://gitee.com/henrytsz/jd_scripts.git
> > BRANCHES=yml:main
> > Resetting origin to: ***github.com/HenryTSZ/jd-yml
> > Adding tmp_upstream https://gitee.com/henrytsz/jd_scripts.git
> > Fetching tmp_upstream
> > fatal: could not read Username for 'https://gitee.com': No such device or address
> 
> 大佬, 这个是不是说分支有问题呀? gitee 新分支是 yml, github 新仓库是 main

你这个是新建的公开库么，地址打不开

**Comment by HenryTSZ** [comment]
> > > UPSTREAM_REPO=https://gitee.com/henrytsz/jd_scripts.git
> > > BRANCHES=yml:main
> > > Resetting origin to: ***github.com/HenryTSZ/jd-yml
> > > Adding tmp_upstream https://gitee.com/henrytsz/jd_scripts.git
> > > Fetching tmp_upstream
> > > fatal: could not read Username for 'https://gitee.com': No such device or address
> > 
> > 
> > 大佬, 这个是不是说分支有问题呀? gitee 新分支是 yml, github 新仓库是 main
> 
> 你这个是新建的公开库么，地址打不开

哦, 私有的, 默认竟然是私有的, 终于好了, 感谢大佬

**Comment by sansuouba** [comment]
gitee里master分支同步大佬代码，自己把master分支合并到新建分支，大佬知道下，如何合并到新建分支下，谢谢

**Comment by WYisShuaiBi** [comment]
新加了新的脚本 或者删除了活动脚本 我们是不是要自己改yml了呀

**Comment by danwangshimoluo** [comment]
后期同步更新大佬的文件还要重新来是吧？

**Comment by ljh740** [comment]
感谢大佬 成功了 但是jd_bean_sign是我手动执行的- -
明天看看有没有自动触发
