### ISSUE TITLE
jd_blueCoin.js 经常兑换不完

### ISSUE THREAD

**Issue by qiangxinglin** [lxk0301/jd_scripts#352]
docker 方法一
在0点时兑换经常遇到活动太火爆了, 导致20京豆可能只兑换2-3次就结束了
log如下:
```
    Dec 16 00:00:26 🔔京小超兑换奖品, 开始!
    Dec 16 00:00:26
    Dec 16 00:00:26 【京东账号1】a1
    Dec 16 00:00:26 【兑换万能的京豆】成功
    Dec 16 00:00:26
    Dec 16 00:00:26
    Dec 16 00:00:26 ==============📣系统通知📣==============
    Dec 16 00:00:26 京小超兑换奖品
    Dec 16 00:00:26 【京东账号1】a1
    Dec 16 00:00:26 【兑换万能的京豆】成功，数量：2个
    Dec 16 00:00:26
    Dec 16 00:00:26 【京东账号2】a2
    Dec 16 00:00:26 【兑换万能的京豆】活动太火爆了,请稍后再试
    Dec 16 00:00:26
    Dec 16 00:00:26
    Dec 16 00:00:26 【京东账号3】a3
    Dec 16 00:00:26 【兑换万能的京豆】活动太火爆了,请稍后再试
    Dec 16 00:00:26
    Dec 16 00:00:26
    Dec 16 00:00:26 【京东账号4】a4
    Dec 16 00:00:26 【兑换万能的京豆】成功
    Dec 16 00:00:26
    Dec 16 00:00:26
    Dec 16 00:00:26 ==============📣系统通知📣==============
    Dec 16 00:00:26 京小超兑换奖品
    Dec 16 00:00:26 【京东账号4】a4
    Dec 16 00:00:26 【兑换万能的京豆】成功，数量：3个
    Dec 16 00:00:26
    Dec 16 00:00:26 🔔京小超兑换奖品, 结束! 🕛 25.25 秒
```

之后手动重新运行`node jd_blueCoin.js`会将剩余的豆子成功兑换完毕

**Comment by sgzman** [comment]
在九点或者十点的时候兑换20豆子，不要在0点兑换了

**Comment by lxk0301** [comment]
@sgzman 要换20。可以设置其他时间点。比如凌晨1:00

**Comment by sgzman** [comment]
> @sgzman 要换20。可以设置其他时间点。比如凌晨1:00

发现云函数也不是很方便，触发器不能修改，且只能最多十个，而且账号多的话，很多会超过900s。目前我是复制了3个函数，所以就有了30个触发器。
建议，在部署到云函数的的时候，函数名称不要固定，比如说以时间戳结尾。这样的话，就可以每次部署都是最新的了。老的函数可以手动删除或者看看能自动删除不。

在请问一句，有没有什么能自动同步最新的脚本，且不限制脚本运行时长，不限制触发器数量的方式呢？QX的话，搞不起，太浪费电了。

**Comment by lqrqw** [comment]
> > @sgzman 要换20。可以设置其他时间点。比如凌晨1:00
> 
> 发现云函数也不是很方便，触发器不能修改，且只能最多十个，而且账号多的话，很多会超过900s。目前我是复制了3个函数，所以就有了30个触发器。
> 建议，在部署到云函数的的时候，函数名称不要固定，比如说以时间戳结尾。这样的话，就可以每次部署都是最新的了。老的函数可以手动删除或者看看能自动删除不。
> 
> 在请问一句，有没有什么能自动同步最新的脚本，且不限制脚本运行时长，不限制触发器数量的方式呢？QX的话，搞不起，太浪费电了。

本地docker跑就好了，白嫖哪有不限制的

**Comment by DoveBoy** [comment]
@lqrqw 说的好在理😂

**Comment by sgzman** [comment]
> > > @sgzman 要换20。可以设置其他时间点。比如凌晨1:00
> > 
> > 
> > 发现云函数也不是很方便，触发器不能修改，且只能最多十个，而且账号多的话，很多会超过900s。目前我是复制了3个函数，所以就有了30个触发器。
> > 建议，在部署到云函数的的时候，函数名称不要固定，比如说以时间戳结尾。这样的话，就可以每次部署都是最新的了。老的函数可以手动删除或者看看能自动删除不。
> > 在请问一句，有没有什么能自动同步最新的脚本，且不限制脚本运行时长，不限制触发器数量的方式呢？QX的话，搞不起，太浪费电了。
> 
> 本地docker跑就好了，白嫖哪有不限制的

那我再抽空研究一下docker，只不顾我的机子是win，不知道好搞不

**Comment by lxk0301** [comment]
> > @sgzman 要换20。可以设置其他时间点。比如凌晨1:00
> 
> 发现云函数也不是很方便，触发器不能修改，且只能最多十个，而且账号多的话，很多会超过900s。目前我是复制了3个函数，所以就有了30个触发器。
> 建议，在部署到云函数的的时候，函数名称不要固定，比如说以时间戳结尾。这样的话，就可以每次部署都是最新的了。老的函数可以手动删除或者看看能自动删除不。
> 
> 在请问一句，有没有什么能自动同步最新的脚本，且不限制脚本运行时长，不限制触发器数量的方式呢？QX的话，搞不起，太浪费电了。

1、发现云函数也不是很方便，触发器不能修改，且只能最多十个，
回复：触发器，可以提交工单，让客服给你修改为50个，https://console.cloud.tencent.com/workorder/category?level1_id=6&level2_id=668&source=0&data_title=%E4%BA%91%E5%87%BD%E6%95%B0%C2%A0SCF&step=1 ；触发器不能直接修改的问题，目前已知提了2次工单给到腾讯，建议你们继续提交工单，这样可以加速腾讯的改善进度。

2、很多会超过900s。
回复：目前6个账号测试仅水果会超时，如果账号比较多的话，每5个分组建立一个函数。

3、在部署到云函数的的时候，函数名称不要固定，比如说以时间戳结尾。这样的话，就可以每次部署都是最新的了。
回复：目前部署云函数action自动部署仅默认serverless.yml,因为一些原因，需要保存serverless.yml这个配置。如果有新的配置需求，例如新的配置我们生成serverless_new.yml这个文件,目前想在一个仓库同时可以选择部署部署serverless.yml,或者serverless_new.yml是不能实现的，需要云函数支持，也已提了工单。你这个需求要等腾讯支持了以后再考虑实现，建议你们继续提交工单，这样可以加速腾讯的改善进度。

4、在请问一句，有没有什么能自动同步最新的脚本，且不限制脚本运行时长，不限制触发器数量的方式呢？
回复：建议docker、vps、路由器、群辉等
