### ISSUE TITLE
能不能在gitee平台实现？

### ISSUE THREAD

**Issue by hacken156026692** [lxk0301/jd_scripts#36]
github要封，那么，国内的gitee平台是否可以实现？谢谢！

**Comment by BlueskyClouds** [comment]
国内更不可能了，别想了

**Comment by issachigga** [comment]
异想天开现在的人

**Comment by hacken156026692** [comment]
> 异想天开现在的人

好吧，我不懂，只是问问而已。请问阁下现在有啥好办法？

**Comment by zyq19990925** [comment]
> > 异想天开现在的人
> 
> 好吧，我不懂，只是问问而已。请问阁下现在有啥好办法？

1.自己下载原来的代码，自己新建仓库，上传代码，直接变成你自己的项目
2.云函数

**Comment by hacken156026692** [comment]
> > > 异想天开现在的人
> > 
> > 
> > 好吧，我不懂，只是问问而已。请问阁下现在有啥好办法？
> 
> 1.自己下载原来的代码，自己新建仓库，上传代码，直接变成你自己的项目
> 2.云函数

好的，我有空研究一下

**Comment by lxk0301** [comment]
gitee 收费。而且费用很高，你薅羊毛的钱补不上他的费用
