### ISSUE TITLE
关于 Bark自建 推送的新问题。

### ISSUE THREAD

**Issue by Mark-1215** [lxk0301/jd_scripts#360]
## 期望增加的功能

A：Bark 推送昨天测试了一下，好像是证书引起的，原因不明，本地其他项目测试没问题。
日志：
Dec 17 10:00:06 Bark APP发送通知调用API失败！！
Dec 17 10:00:06 
Dec 17 10:00:07 RequestError: unable to verify the first certificate
Dec 17 10:00:07     at ClientRequest.<anonymous> (/scripts/node_modules/got/dist/source/core/index.js:953:111)
Dec 17 10:00:07     at Object.onceWrapper (events.js:422:26)
Dec 17 10:00:07     at ClientRequest.emit (events.js:327:22)
Dec 17 10:00:07     at ClientRequest.origin.emit (/scripts/node_modules/@szmarczak/http-timer/dist/source/index.js:39:20)
Dec 17 10:00:07     at TLSSocket.socketErrorListener (_http_client.js:426:9)
Dec 17 10:00:07     at TLSSocket.emit (events.js:315:20)
Dec 17 10:00:07     at emitErrorNT (internal/streams/destroy.js:92:8)
Dec 17 10:00:07     at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)
Dec 17 10:00:07     at processTicksAndRejections (internal/process/task_queues.js:84:21)
Dec 17 10:00:07     at TLSSocket.onConnectSecure (_tls_wrap.js:1501:34)
Dec 17 10:00:07     at TLSSocket.emit (events.js:315:20)
Dec 17 10:00:07     at TLSSocket._finishInit (_tls_wrap.js:936:8)
Dec 17 10:00:07     at TLSWrap.ssl.onhandshakedone (_tls_wrap.js:710:12) {
Dec 17 10:00:07   code: 'UNABLE_TO_VERIFY_LEAF_SIGNATURE',
Dec 17 10:00:07   timings: {
Dec 17 10:00:07     start: 1608170406976,
Dec 17 10:00:07     socket: 1608170406977,
Dec 17 10:00:07     lookup: 1608170406978,
Dec 17 10:00:07     connect: 1608170406979,
Dec 17 10:00:07     secureConnect: undefined,
Dec 17 10:00:07     upload: undefined,
Dec 17 10:00:07     response: undefined,
Dec 17 10:00:07     end: undefined,
Dec 17 10:00:07     error: 1608170406989,
Dec 17 10:00:07     abort: undefined,
Dec 17 10:00:07     phases: {
Dec 17 10:00:07       wait: 1,
Dec 17 10:00:07       dns: 1,
Dec 17 10:00:07       tcp: 1,
Dec 17 10:00:07       tls: undefined,
Dec 17 10:00:07       request: undefined,
Dec 17 10:00:07       firstByte: undefined,
Dec 17 10:00:07       download: undefined,
Dec 17 10:00:07       total: 13
Dec 17 10:00:07     }
Dec 17 10:00:07   }
Dec 17 10:00:07 }
Dec 17 10:00:07 

## 入口

A：

**Comment by lxk0301** [comment]
这。。。。我也不知如何解决了。

**Comment by Mark-1215** [comment]
我证书是自签的，找到原因了，2017年2月27日，npm不再支持自签名证书。https://blog.csdn.net/qq_39403545/article/details/87968957 跟Docker镜像环境有关系。

**Comment by lxk0301** [comment]
> 我证书是自签的，找到原因了，2017年2月27日，npm不再支持自签名证书。https://blog.csdn.net/qq_39403545/article/details/87968957 跟Docker镜像环境有关系。

那有解决办法吗?

**Comment by iouAkira** [comment]
@Mark-1215 我的建议是不要使用自签证书😂，按照这个说的取消SSL验证了，那是不是可能会影响的别https的请求呢？一定要使用自签证书的话，建议自行去容器里面配置关闭SSL验证，镜像这边不做调整。

**Comment by Mark-1215** [comment]
取消SSL验证应该就是字面意思，不验证了，不会有验证，使用应该是不受影响的。

**Comment by iouAkira** [comment]
@Mark-1215 为了自签证书 ，把所有的 HTTPS 都不验证 也不合常理啊，方向不对😂

**Comment by Mark-1215** [comment]
也是，哈哈，好吧，我只是有强迫症，感觉还是https安全。

**Comment by iouAkira** [comment]
> 也是，哈哈，好吧，我只是有强迫症，感觉还是https安全。

如果是自签的有问题，那用 `let's encrypt`  签发的应该没啥问题，可以用这个
