### ISSUE TITLE
获取docker images部分的日志乱码。

### ISSUE THREAD

**Issue by JunzhouLiu** [lxk0301/jd_scripts#363]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [x] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：获取docker images部分的日志乱码。具体出问题的应该是这部分代码

https://github.com/lxk0301/jd_scripts/blob/6745a1ebf9b1acebadd81ed8dde1107639d19cd4/docker/docker_entrypoint.sh#L39

### (2) 详细日志
A：
```
doying         | 
doying         | 11 packages are looking for funding
doying         |   run `npm fund` for details
doying         | 
doying         | found 0 vulnerabilities
doying         | 
##############################################################################
doying         | check docker images update...
doying         | ??????docker??????????????????...
doying         | get dockerhub repo images labels...
doying         | ??????dockerhub????????????labels??????...
doying         | moreutils tools installed, default task append |ts output
doying         | ???????????????moreutils???????????????????????????????????????ts ??????
doying         | The currently used is the default crontab task file: crontab_list.sh ...
doying         | ?????????????????????????????????????????? crontab_list.sh ...
doying         | Load the latest crontab task file...
doying         | ?????????????????????????????????...
doying         | Start crontab task main process...
doying         | ??????crondtab?????????????????????...
doying         | crond[54]: crond (busybox 1.31.1) started, log level 8
doying         | crond[54]: USER root pid  55 cmd node /scripts/jd_pigPet.js |ts >> /scripts/logs/jd_pigPet.log 2>&1
doying         | crond[54]: USER root pid  68 cmd node /scripts/jd_joy.js |ts >> /scripts/logs/jd_joy.log 2>&1
doying         | crond[54]: USER root pid  69 cmd node /scripts/jd_joy_feedPets.js |ts >> /scripts/logs/jd_joy_feedPets.log 2>&1

```

### (1) Node.js版本

A：
v8.10.0

### (2) npm版本

A：3.5.2

### (3)npm install的日志

A：

**Comment by iouAkira** [comment]
`docker-compose` 的问题，你试试  `docker logs 容器名` 看看

**Comment by iouAkira** [comment]
你可以本地构建试试，修改好没问题的话也可以PR到主库

**Comment by JunzhouLiu** [comment]
是`docker-compose`的问题，这里咨询一个问题，当前docker方式部署会自动更新crontab_list.sh文件吗？

如果我自己编写脚本，定时拉crontab_list.sh文件下来，是否需要重启容器生效。 我看到代码里是通过路径+环境变量中文件名读到文件读到的，这种方式应该不需要重启容器。但是因为不怎么熟悉这一块，所以想确认下这两个问题。

**Comment by iouAkira** [comment]
> 是`docker-compose`的问题，这里咨询一个问题，当前docker方式部署会自动更新crontab_list.sh文件吗？
> 
> 如果我自己编写脚本，定时拉crontab_list.sh文件下来，是否需要重启容器生效。 我看到代码里是通过路径+环境变量中文件名读到文件读到的，这种方式应该不需要重启容器。但是因为不怎么熟悉这一块，所以想确认下这两个问题。


[ `crontab_list.sh`  ](https://github.com/lxk0301/jd_scripts/blob/master/docker/crontab_list.sh)  是在仓库维护
 `default_task.sh` 每次执行会去 `git pull ` 更新
在下面这一块 `IF`  里面合并处理自定任务文件和最新的默认文件
https://github.com/lxk0301/jd_scripts/blob/6745a1ebf9b1acebadd81ed8dde1107639d19cd4/docker/default_task.sh#L77
然后这里加载生效上面处理过的定时任务文件
https://github.com/lxk0301/jd_scripts/blob/6745a1ebf9b1acebadd81ed8dde1107639d19cd4/docker/default_task.sh#L111

每次的默认定时任务都是在重复这个操作

**Comment by JunzhouLiu** [comment]
好的，我明白了。感谢你的详细解答。❤❤

**Comment by JunzhouLiu** [comment]
@iouAkira 请问你这个在issue中插入这样代码显示 是如何做到的。

![image](https://user-images.githubusercontent.com/17582066/102454571-32a7a480-4079-11eb-91d4-3420e7d25565.png)
