### ISSUE TITLE
京东看看执行38次终止

### ISSUE THREAD

**Issue by qingcher** [lxk0301/jd_scripts#366]
京东看看执行38次终止，api丢失。后面两次要手动点

**Comment by lxk0301** [comment]
自己抓包 跑。要跑脚本内置的就跑两次

**Comment by pikaqiu112** [comment]
@lxk0301 你把脚本自带运行次数设置成两次不就完了.....

**Comment by lxk0301** [comment]
> @lxk0301 你把脚本自带运行次数设置成两次不就完了.....

什么脚本自带运行次数？

**Comment by pikaqiu112** [comment]
@lxk0301 触发时间 设置成两次

**Comment by qingcher** [comment]
好的好的。感谢
