### ISSUE TITLE
在cron中增添随机化处理，为每一条cron命令前添加：  sleep $((RANDOM % 90 + 10));

### ISSUE THREAD

**Issue by hahahrfool** [lxk0301/jd_scripts#369]
## 期望增加的功能

A：新增一个crontab_list, 供用户选择，在cron中增添随机化处理，为每一条cron命令前添加：  sleep $((RANDOM % 90 + 10));

**Comment by EvineDeng** [comment]
@hahahrfool 有些不能随机

**Comment by lxk0301** [comment]
为何想着随机

**Comment by hahahrfool** [comment]
> 为何想着随机

减少cpu在同一时间的压力

**Comment by hahahrfool** [comment]
> @hahahrfool 有些不能随机

可甄选出不可随机的任务

**Comment by EvineDeng** [comment]
> > 为何想着随机
> 
> 减少cpu在同一时间的压力

除了必须准点运行的任务外，其他的任务基本上是错开的。

**Comment by lxk0301** [comment]
@hahahrfool 好像里面的cron。除了必须某个时间点运行的，一般都没有在同一时刻运行。😂

**Comment by hahahrfool** [comment]
> > > 为何想着随机
> > 
> > 
> > 减少cpu在同一时间的压力
> 
> 除了必须准点运行的任务外，其他的任务基本上是错开的。除非你不想准点运行。

# 点点券
20 0,20 * * * node /scripts/jd_necklace.js >> /scripts/logs/jd_necklace.log 2>&1
# 京喜工厂
20 * * * * node /scripts/jd_dreamFactory.js >> /scripts/logs/jd_dreamFactory.log 2>&1

# 微信小程序京东赚赚
10 11 * * * node /scripts/jd_jdzz.js >> /scripts/logs/jd_jdzz.log 2>&1
# 宠汪汪邀请助力
10 10,11 * * * node /scripts/jd_joy_run.js >> /scripts/logs/jd_joy_run.log 2>&1

# 东东超市
11 1-23/5 * * * node /scripts/jd_superMarket.js >> /scripts/logs/jd_superMarket.log 2>&1
# 京东抽奖机
11 1 * * * node /scripts/jd_lotteryMachine.js >> /scripts/logs/jd_lotteryMachine.log 2>&1

# 宠汪汪
15 */2 * * * node /scripts/jd_joy.js >> /scripts/logs/jd_joy.log 2>&1
# 宠汪汪喂食
15 */1 * * * node /scripts/jd_joy_feedPets.js >> /scripts/logs/jd_joy_feedPets.log 2>&1

**Comment by EvineDeng** [comment]
行吧，你提到的这几个我来优化下，没必要增加随机sleep，错开任务时间就好。

**Comment by hahahrfool** [comment]
个人认为随机不仅在于降低cpu功耗（占用率越高功耗越大，保持任务均匀有必要），还在于防京东检测。既然能随机sleep，并无额外开销，何乐而不为，而且不必特意调整到一个特定的时间。手动错开时间，不仅累，且容易出错。

**Comment by hclasmn** [comment]
> 个人认为随机不仅在于降低cpu功耗（占用率越高功耗越大，保持任务均匀有必要），还在于防京东检测。既然能随机sleep，并无额外开销，何乐而不为，而且不必特意调整到一个特定的时间。手动错开时间，不仅累，且容易出错。

真要检测，不是一个sleep能避免 的，你一天或者短时间完成那么多任务本身就可疑了， 东哥不在乎罢了

**Comment by EvineDeng** [comment]
@hahahrfool 多人同时连接服务器，随机多少算避开，很难讲

**Comment by hahahrfool** [comment]
> > 个人认为随机不仅在于降低cpu功耗（占用率越高功耗越大，保持任务均匀有必要），还在于防京东检测。既然能随机sleep，并无额外开销，何乐而不为，而且不必特意调整到一个特定的时间。手动错开时间，不仅累，且容易出错。
> 
> 真要检测，不是一个sleep能避免 的，你一天或者短时间完成那么多任务本身就可疑了， 东哥不在乎罢了

请尽人事，听天命，做到我们能做的最好。

**Comment by lxk0301** [comment]
@hahahrfool 你们都不用自定义cron的嘛？自定义cron  你说的应该可以随意修改哇

**Comment by lxk0301** [comment]
@hahahrfool 如果仅仅是单独为了防止京东检查的话。那一个随机sleep肯定是无用的。

**Comment by hahahrfool** [comment]
> @hahahrfool 如果仅仅是单独为了防止京东检查的话。那一个随机sleep肯定是无用的。

我说了，两个作用，降低抢占cpu等资源可能，降低检查风险

**Comment by hahahrfool** [comment]
> @hahahrfool 你们都不用自定义cron的嘛？自定义cron 你说的应该可以随意修改哇

当然可以自己改，我认为这个对大家都好，所以提建议，创建一个新的crontab_list， 供一些需求比较高的玩家选择

**Comment by lxk0301** [comment]
@hahahrfool issue先挂着吧，看看有多少人觉得有必要。

觉得有必要的人可以左下角图标点赞👍

**Comment by hahahrfool** [comment]
可以建一个脚本， 比如randomNode，内容为 sleep $((RANDOM % 90 + 10)); node $1

把crontab里的 需要替换的条目的 "node"命令 替换为 “randomNode"

**Comment by iouAkira** [comment]
我没啥意见，不过我也不太想去整理这些任务，对我来说没啥需求动力😂，你这边有思路可以改好测试好，PR上来；

我要建议要加的话不动 `crontab_list.sh` ,在 `shell` 里面处理，另外加一个 `ENABLE_RANDOM` 环境做判断 是否开启做随机处理，处理定时任务都在这个下面 `IF` 块里面了，代码都没东西，很容易看明白
https://github.com/lxk0301/jd_scripts/blob/feca0d7de085462801c76698283cc3a8069cff58/docker/default_task.sh#L75

**Comment by hahahrfool** [comment]
> 我没啥意见，不过我也不太想去整理这些任务，对我来说没啥需求动力😂，你这边有思路可以改好测试好，PR上来；
> 
> 我要建议要加的话不动 `crontab_list.sh` ,在 `shell` 里面处理，另外加一个 `ENABLE_RANDOM` 环境做判断 是否开启做随机处理，处理定时任务都在这个下面 `IF` 块里面了，代码都没东西，很容易看明白
> https://github.com/lxk0301/jd_scripts/blob/feca0d7de085462801c76698283cc3a8069cff58/docker/default_task.sh#L75

好的，很乐意帮忙。
