### ISSUE TITLE
大佬考虑一下东东工厂不

### ISSUE THREAD

**Issue by fm1223** [lxk0301/jd_scripts#37]
入口：首页-->数码电器-->东东工厂（限时秒杀上面的小卡片）
大佬能教教抓包不

**Comment by fm1223** [comment]
> 也是限时内完成才能有效吗？

对滴对滴，只有限定数量的物品，兑换完就没有了。。

**Comment by lxk0301** [comment]
@fm1223 你自己有换到过东西吗？

**Comment by 454053205** [comment]
> @fm1223 你自己有换到过东西吗？

有换过。领了几件小的了。充电线、自拍杆之类的。

**Comment by ITdesk01** [comment]
> > @fm1223 你自己有换到过东西吗？
> 
> 有换过。领了几件小的了。充电线、自拍杆之类的。

可以关掉 issue，已经有工厂脚本了

**Comment by qwycm** [comment]
希望增加东东工厂脚本，只需要收集点亮就行，攒够了电量再选择商品一次性投进去就可以换了。

**Comment by lxk0301** [comment]
@fm1223 

https://raw.githubusercontent.com/lxk0301/jd_scripts/master/jd_jdfactory.js

免费的那个生产的电力。多久时间会达到上限不在生产？

**Comment by fm1223** [comment]
> > @fm1223 你自己有换到过东西吗？
> 
> 有换过。领了几件小的了。充电线、自拍杆之类的。

如果一直存在当前电量中，会达到上限吗？

**Comment by fm1223** [comment]
> @fm1223
> 
> https://raw.githubusercontent.com/lxk0301/jd_scripts/master/jd_jdfactory.js
> 
> 免费的那个生产的电力。多久时间会达到上限不在生产？

我没达到过上限，大佬这效率牛逼

**Comment by lxk0301** [comment]
@fm1223 不知道。应该不会吧

**Comment by lxk0301** [comment]
@fm1223 你们注意观察 如果会的话。记得一个上限数量，再反馈给我。我做调整。

**Comment by fm1223** [comment]
> @fm1223 你们注意观察 如果会的话。记得一个上限数量，再反馈给我。我做调整。

👌

**Comment by Simple-Yi** [comment]
> @fm1223 你们注意观察 如果会的话。记得一个上限数量，再反馈给我。我做调整。

10秒1个电量，500个电量满，5000秒到上限不生产

**Comment by lxk0301** [comment]
@Simple-Yi 那84分钟就满了。看来得需要一个小时执行一次呢
