### ISSUE TITLE
小火箭中运行东东农场等出错

### ISSUE THREAD

**Issue by liuxianhao666** [lxk0301/jd_scripts#373]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ x] 没有类似的issue 

Q：是否仔细阅读了教程
- [ x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [x ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：shadowrocket中运行签到正常，但游戏类的都 不正常，如东东农场等

### (2) 详细日志
A：❗️script exception handler => SyntaxError : Unexpected token '{'. Expected '(' to start a 'catch' target. in method undefined line number : undefined, column: undefined
[23:30:25.522] faild to load local script file code

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by lxk0301** [comment]
和脚本无关
