### ISSUE TITLE
京东的那个看一看谁抓了discAcceptTask和discDoTask的包分享一下

### ISSUE THREAD

**Issue by danwangshimoluo** [lxk0301/jd_scripts#376]
京东的那个看一看谁抓了discAcceptTask和discDoTask的包分享一下

**Comment by OCEagle** [comment]
安卓正则用不了吗

**Comment by lxk0301** [comment]
> 安卓正则用不了吗，不太会用charles。

安卓抓的包和iOS不一样

**Comment by lxk0301** [comment]
> 京东的那个看一看谁抓了discAcceptTask和discDoTask的包分享一下

脚本里面已经有提供
