### ISSUE TITLE
直播红包雨脚本不可用

### ISSUE THREAD

**Issue by askiter** [lxk0301/jd_scripts#377]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [x] 方法四：iOS系统的代理软件

### (1) 具体问题
A：iphone 的 surge显示已经执行，但是未出现领取通知，我手工执行，提示不在相应的时间段
下面是手工执行的日志（红包雨时间段手工执行也是这个信息）
从日志中可以看到获取到的红包雨时间段仍然是15点那场，脚本里面那个获取任务的url，手工执行是
{"activityId":"RRA2N8MUYQcP2JMomjAJY7s79fyQ1Ar","startTime":1608361200000,"endTime":1608361500000}
和手工执行拿到的结果是一致的，都是15点那波

是因为url被cdn缓存了吗，脚本直到昨天23点那场还是正常的，之后就不行了（但是有的人可以），这个问题如何解决一下？谢谢

### (2) 详细日志
A：17:11:53.779958 下一场红包雨开始时间：Sat Dec 19 2020 15:00:00 GMT+0800 (CST)
17:11:53.780025 下一场红包雨结束时间：Sat Dec 19 2020 15:05:00 GMT+0800 (CST)
17:11:53.781181 不在红包雨时间之内
17:11:53.781670 

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by slj844909754** [comment]
我跟你一样
