### ISSUE TITLE
可以集成这个推送吗

### ISSUE THREAD

**Issue by XiaYi1002** [lxk0301/jd_scripts#379]
QQ推送，直观一些
https://cp.xuthus.cc/

**Comment by lxk0301** [comment]
功能已添加进去了

**Comment by XiaYi1002** [comment]
今天才发现酷推推送，会过滤%号。需要把desp里面%删除。

**Comment by lxk0301** [comment]
没有过滤。看后面的%符号
![1DF09326-24EE-4E8A-902A-02A080D5977F](https://user-images.githubusercontent.com/21308593/102750490-d908e800-43a0-11eb-958b-10cebae411e3.jpeg)

**Comment by XiaYi1002** [comment]
我自己有把那个server酱改成酷推，然后今天农场推送就没推给我，飞机收到了但是酷推没有，后面删了空格才有给我推。玄学呀。

**Comment by lxk0301** [comment]
@XiaYi1002 不知 你可以现在试试， 看看等会下午农场会给你发送通知不 ，我刚测试农场是没有问题的

**Comment by lxk0301** [comment]
![image](https://user-images.githubusercontent.com/21308593/102753900-11132980-43a7-11eb-9db7-16ab4ce11c69.png)

**Comment by XiaYi1002** [comment]
挺玄的 应该是我自己改的 没改好导致的吧  现在都有进行推送了 一切正常
