### ISSUE TITLE
互助力，剩下农村4位，萌宠4位，种豆2位

### ISSUE THREAD

**Issue by ZHANGLIANGzhangliang** [lxk0301/jd_scripts#38]
农场
74421f55fbaa424eac3c051d8df2e649
a6d7c5d3921b4db78a446940443cbdef
萌宠
MTE1NDUwMTI0MDAwMDAwMDM2MjgyNzAx
MTE1NDUwMTI0MDAwMDAwMDM4OTY4ODM5
种豆
mlrdw3aw26j3wcceffzxh2me5uwreuxwavvu3tq
f5pavyxxlph5pnjhw6ek3eistzsyzbdfiprb74y

**Comment by Andecy** [comment]
我也想互助，但是想问你们这些互助码是怎么获取的？
