### ISSUE TITLE
领京豆-心愿单

### ISSUE THREAD

**Issue by 18240713** [lxk0301/jd_scripts#381]
## 期望增加的功能

A：发现好货-领京豆-心愿单

## 入口

A：首页→发现好货→右下角悬浮球（领京豆）

**Comment by EchoChan314** [comment]
京东心愿单50豆捷径版本(非task脚本), 一次没做完就再点一次。

兼容  IOS13-14
-----------------------------
💁🏻‍♂️作者: shylocks，github同名，欢迎star

https://www.icloud.com/shortcuts/9b0f635311ae4a03ab8321f116bdec14
