### ISSUE TITLE
JD_DailyBonus.js not found

### ISSUE THREAD

**Issue by GoToBoy** [lxk0301/jd_scripts#383]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [x] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：./JD_DailyBonus.js not found ,执行京东签到脚本时候

### (2) 详细日志
A：
![image](https://user-images.githubusercontent.com/2384105/102726932-717d7900-435d-11eb-8fec-ee560537b595.png)
应该和Even的v3版本升级有关系，我close掉先

**Comment by Vesugierii** [comment]
@GoToBoy jd_bean_sign

**Comment by GoToBoy** [comment]
回复下最后是怎么处理的，mac环境下 用了npm install 出现了这个问题，
解决办法是删掉node_modules， 用yarn install
