### ISSUE TITLE
直播红包雨提示不在红包雨时间内

### ISSUE THREAD

**Issue by Dellear** [lxk0301/jd_scripts#388]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [x] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：
![image](https://user-images.githubusercontent.com/22325851/102742335-97237600-438f-11eb-8497-bf5b7dddde23.png)

### (2) 详细日志
A：
🔔直播红包雨, 开始!
您的cookie选择的是用&隔开

====================共有3个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2020/12/21 下午1:01:01=====================

下一场红包雨开始时间：Mon Dec 21 2020 11:00:00 GMT+0800 (中国标准时间)
下一场红包雨结束时间：Mon Dec 21 2020 11:05:00 GMT+0800 (中国标准时间)
不在红包雨时间之内

🔔直播红包雨, 结束! 🕛 0.82 秒

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by lxk0301** [comment]
@@随缘吧。这个每天都需要有人抓包维护。有时候还没直播间
