### ISSUE TITLE
目前是否可以引入自定义推送？

### ISSUE THREAD

**Issue by jmluang** [lxk0301/jd_scripts#393]
## 期望增加的功能

A：Docker 方式加入自定义推送是否可行？

现在发送通知都在 sendnotify.js 里面，不知道能不能做到下面这种功能呢？
```
if file_exists("custom_notify.js") 
customf = import ("custom_notify.js")
customf.send()
end if
```
不知道可不可行，工作量大不大

**Comment by lxk0301** [comment]
什么自定义？

自定义通知内容？还是自定义其他的通知方法？

**Comment by shange1993** [comment]
@lxk0301 能不能增加https://qmsg.zendee.cn/ 里的QQ通知啊 https://cp.xuthus.cc/ 里的没办法用，QQ加不上
