### ISSUE TITLE
配置了可用的socks5连接仍然无法推送到TG

### ISSUE THREAD

**Issue by caitaohjj** [lxk0301/jd_scripts#394]
![image](https://user-images.githubusercontent.com/39289808/102791884-9ff16780-43e2-11eb-8e9b-0e671d5767da.png)
一直报这个错

**Comment by lxk0301** [comment]
自己琢磨吧。😂

**Comment by lxk0301** [comment]
我在本地 window for clash测试过是可以的。服务器端搭建的clash。也是可以使用的

**Comment by caitaohjj** [comment]
诶，我也不知道啥情况。可能系统有关吧。我的这个socks链接。有时候IOS也是连不上。但是一旦连上了。就可以一直用。我的ANDROID就没有任何问题。
