### ISSUE TITLE
希望需要API的脚本强制加入随机延迟

### ISSUE THREAD

**Issue by qiangxinglin** [lxk0301/jd_scripts#395]
## 期望增加的功能

A：
如题, 随着用的人数越来越多, turing api那个网站一到repo中预设的时间就会有大量负载, 建议(fruit, plant, pet, ddfactory, joy_run)等等都在cron中预设随机延迟

## 入口

A：

**Comment by lxk0301** [comment]
手机端实现不了。目前两个docker 方法已经有添加延迟功能

**Comment by qiangxinglin** [comment]
> 手机端实现不了。目前两个docker 方法已经有添加延迟功能

有没有考虑过在脚本中植入sleep?

**Comment by lxk0301** [comment]
@qiangxinglin 不考虑。手机端好像只能用 setimeout实现。这样子脚本还是挂载在哪里。照样占着

**Comment by qiangxinglin** [comment]
@lxk0301 在访问API之前sleep, 错峰访问会有所缓解, 挂载在各自的客户端又无所谓的
```伪代码
  sleep(random(60))
  response = requests.get/post('api.turing.xxx')
```

**Comment by Mark-1215** [comment]
> 手机端实现不了。目前两个docker 方法已经有添加延迟功能

具体如何操作呢，帮助文档好像没有找到。

**Comment by qiangxinglin** [comment]
> > 手机端实现不了。目前两个docker 方法已经有添加延迟功能
> 
> 具体如何操作呢，帮助文档好像没有找到。

在compose file中加入environment `- RANDOM_DELAY_MAX=xxx`
