### ISSUE TITLE
愿能加上当天获取多少京豆统计这个功能

### ISSUE THREAD

**Issue by wj1988916** [lxk0301/jd_scripts#397]
愿能加上当天获取多少京豆统计这个功能

**Comment by lxk0301** [comment]
@wj1988916 当天没必要 。当天还没过完， 谁知道你获得了多少。

**Comment by wj1988916** [comment]
谢谢操心，我只是个建议。可以做个截止到当前时间当天京豆统计。Zero-S1/JD_tools 这个有这个功能，但是是个单账号的，我尝试改过，没成功。

**Comment by sgzman** [comment]
不是有昨天获取多少京豆吗？

**Comment by lxk0301** [comment]
暂不考虑加入今日收入功能

还有zero的也是可以多个账号的呢。

**Comment by Vesugierii** [comment]
@lxk0301 自己改 我给你发一下，等我回去

**Comment by Vesugierii** [comment]
> 愿能加上当天获取多少京豆统计这个功能

https://github.com/Vesugierii/jd_scripts/blob/main/beanchange
今天昨天还有7天的 lxk大佬的魔改版
