### ISSUE TITLE
新京豆活动，疯狂的JOY

### ISSUE THREAD

**Issue by yswcdmm** [lxk0301/jd_scripts#402]
## 期望增加的功能

A：京东新活动 活动地址crazy-joy.jd.com
可以使用的脚本https://github.com/gcdd1993/jd_scripts/blob/master/jd_crazy.js

## 入口

A：

**Comment by hclasmn** [comment]
运行了下，只会买1级，我都17级了，一直买1级

**Comment by zhuzf88** [comment]
> 运行了下，只会买1级，我都17级了，一直买1级

买一级最划算啊

**Comment by monkey-sking** [comment]
> > 运行了下，只会买1级，我都17级了，一直买1级
> 
> 买一级最划算啊

随着购买的次数，价格在上涨
理论上没有到最高级时，购买当前能购买的等级最划算
另外有个狗永远合不出来，到目前全服没有一个合出来的

我N个34级都合了，都没有出

**Comment by EchoChan314** [comment]
> > > 运行了下，只会买1级，我都17级了，一直买1级
> > 
> > 
> > 买一级最划算啊
> 
> 随着购买的次数，价格在上涨
> 理论上没有到最高级时，购买当前能购买的等级最划算
> 另外有个狗永远合不出来，到目前全服没有一个合出来的
> 
> 我N个34级都合了，都没有出

其实可以算的，1级的买多了就不如买2级的，2级的买多了就不如买3级的，以此类推到30级，有个算式可以算的，合成不需要成本，那么一只30级的，合成而来还是直接购买，只要合成所需金币小于购买，那么就是合成的最划算。

**Comment by hclasmn** [comment]
不能用了

**Comment by hclasmn** [comment]
![image](https://user-images.githubusercontent.com/32213103/102945032-9279d180-44f7-11eb-8513-a581092733b1.png)

**Comment by a3253933** [comment]
请问一下怎么能才用上这个脚本
