### ISSUE TITLE
东东工厂task获取问题

### ISSUE THREAD

**Issue by ys867** [lxk0301/jd_scripts#404]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [x] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：TypeError: $.taskVos is not iterable!
推测是获取任务没获取到？工厂已经手动选择商品，但任务一直没做
只有这一个不正常，别的都能运行
### (2) 详细日志
A：
![image](https://user-images.githubusercontent.com/34636453/102869971-57d05480-4477-11eb-96cc-3868f78ce407.png)

**Comment by lxk0301** [comment]
这个账号没有拿到正确的数据。导致脚本报错了
