### ISSUE TITLE
腾讯云函数运行jd_bean_sign.js出错

### ISSUE THREAD

**Issue by popeshaka** [lxk0301/jd_scripts#405]
报错信息：京东签到脚本执行异常:Error: in method 'console_log', argument 1 of type 'char *'

只有这个脚本有问题，其他js脚本都正常运行了，问了其他在用云函数的朋友，也是这个问题

**Comment by sgzman** [comment]
的确有这个问题，我也发现了

**Comment by watershy** [comment]
把通知关掉就行了

**Comment by sgzman** [comment]
> 把通知关掉就行了

这就相当于因噎废食了

**Comment by q4w5e6** [comment]
@sgzman 哦？影响签到吗？

**Comment by huangshi10492** [comment]
要怎么关闭，用JD_BEAN_SIGN_STOP_NOTIFY=ture吗

**Comment by lxk0301** [comment]
> 要怎么关闭，用JD_BEAN_SIGN_STOP_NOTIFY=ture吗

删除通知类的环境变量

**Comment by lxk0301** [comment]
这个问题就腾讯云函数出现错误。我目前也不知道如何解决
