### ISSUE TITLE
自己新建一个repo，然后把代码上传到自己的里面，使用之前的flow，运行Actions，应该可行吧

### ISSUE THREAD

**Issue by hupo376787** [lxk0301/jd_scripts#41]
谢谢大佬

**Comment by lxk0301** [comment]
需把这截图里面删掉或注释

![6AD912B8-3FB3-44A9-9B09-176169904355](https://user-images.githubusercontent.com/21308593/98677149-96162680-2397-11eb-9cb8-acf2a1473c9e.jpeg)

**Comment by hupo376787** [comment]
好的，谢谢大佬

**Comment by hupo376787** [comment]
@lxk0301 又打赏了一发，虽然不多，但是还是谢谢
