### ISSUE TITLE
proc_file.sh运行结果为空

### ISSUE THREAD

**Issue by hclasmn** [lxk0301/jd_scripts#412]
proc_file.sh运行后，log中是空的
![image](https://user-images.githubusercontent.com/32213103/102947086-76792e80-44fd-11eb-8a00-080339b635a4.png)

**Comment by iouAkira** [comment]
@hclasmn 你把这个六个改过日志输出的脚本跑一遍在执行这个提取任务试试看

**Comment by hclasmn** [comment]
> @hclasmn 你把这个六个改过日志输出的脚本跑一遍在执行这个提取任务试试看

好了，。谢谢指导

**Comment by iouAkira** [comment]
还有个bug，这个pr合进去了再试一下
https://github.com/lxk0301/jd_scripts/pull/417
