### ISSUE TITLE
能否建个群，互相分享互助码？（附我的互助码）

### ISSUE THREAD

**Issue by rcfan1** [lxk0301/jd_scripts#414]
## 期望增加的功能

A：能否建个群，互相分享互助码？

## 入口

A：种豆得豆：5hzfy7ibuddhfyjfha743p44nya72ro5pd34w7a
                       olmijoxgmjutze2h5rqt4tkrcsz45ufe33dzyfy
  东东萌宠互助码：
MTAxODc2NTEzMzAwMDAwMDAwNDA1NTM0MQ==
MTAxODc2NTEzNDAwMDAwMDAzMDgxMjcxMw==
京喜工厂互助码：
vpijhNvg1x6XdRgg_g7yVg==
-FuPWoCWvogGl-CpbAPvpw==
东东工厂互助码：
P04z54XCjVWnYaS5m9cZ2as2XRJk5DJtnPbCe0
P04z54XCjVWnYaS5uONubZQcqvgIWe_8CfF3ec
东东农场互助码：49a15d94620848c6ad5c1089001cae9f
18a98f199dd84f86a433a1321f087fea

有互的吗？互的话告诉我，我来添加大家

**Comment by lxk0301** [comment]
@rcfan1 telegram 群组 , https://t.me/JD_fruit_pet

有能力就进 , 没国内社交群

**Comment by creazy412** [comment]
`http://api.turinglabs.net/api/v1/jd/bean/read/${randomCount}/` 很好奇如何才能把自己的助力码也进入到这个助力码池中来？

**Comment by rcfan1** [comment]
> http://api.turinglabs.net/api/v1/jd/bean/read/${randomCount}/

估计这个是内置到了服务器了，想要进去比较难了，不过你可以找几个人，互相填互助码，5个人就可以了

**Comment by creazy412** [comment]
助力码都是永久有效的吗？还是跟 token 有效期有关呢？刚玩没多久，还没测试过

**Comment by happinesslijian** [comment]
有想法的可以加入微信群 
![image](https://user-images.githubusercontent.com/47111417/103253677-15e66780-49bd-11eb-989d-6b74c51c9d51.png)

**Comment by yaoshanliang** [comment]
东东农场： 5365f9f30d4a4325bb65c39d37e9d5f5
