### ISSUE TITLE
京东健康互助

### ISSUE THREAD

**Issue by CfortWang** [lxk0301/jd_scripts#416]
如图，每场都能领红包，仅限京东健康APP使用，可以买点口罩啥的，一场20+应该算比较少的了
互助码：904b2a8c4db9a295e0f4b03d3d0b20cf  对应脚本jd_jdh.js，加了的把自己的留下
[
![ex](https://user-images.githubusercontent.com/31876047/102953087-7d0ea280-450b-11eb-8b6e-0fcaa833edd4.jpg)
](url)

**Comment by lxk0301** [comment]
大家都知道了， 没必要开一个issue

**Comment by CfortWang** [comment]
> 大家都知道了， 没必要开一个issue

没看到关于京东健康互助的啊，也没环境变量，是互助码有效时间太短了吗

**Comment by lxk0301** [comment]
@CfortWang 暂时没有提供， 因为活动快要过期了。 这几天抽空弄一下吧

**Comment by Vesugierii** [comment]
@CfortWang 就10几天了，搞个这个感觉也没啥意义

**Comment by CfortWang** [comment]
> @CfortWang 就10几天了，搞个这个感觉也没啥意义

这倒也是，红包还只能京东健康用买不了啥，不过薅几盒口罩还是可以的
