### ISSUE TITLE
joy总动员

### ISSUE THREAD

**Issue by hclasmn** [lxk0301/jd_scripts#423]
## 期望增加的功能

A：joy总动员互加好友，自动测亲密度

## 入口

A：我的京豆-joy总动员

加好友：两个号
![friend_qr_code](https://user-images.githubusercontent.com/32213103/103058608-997b0f80-45dd-11eb-9073-89abcdd0d466.jpg)
![friend_qr_code(1)](https://user-images.githubusercontent.com/32213103/103058612-9bdd6980-45dd-11eb-85c8-7a391cf817b2.jpg)

**Comment by Mr-zhaohy** [comment]
入口在哪里

**Comment by hclasmn** [comment]
> 入口在哪里

不好意思，写错了，是我的京豆里面

**Comment by HiJackXD** [comment]
![6BA31ECF-D8A3-4281-8BFA-83D5F2F5573E](https://user-images.githubusercontent.com/12136689/103058424-12c63280-45dd-11eb-88bd-a13e1662a81b.JPG)
求加好友

**Comment by hclasmn** [comment]
> 求加好友

加了

**Comment by rua-aaa** [comment]
![微信图片_20201224141659](https://user-images.githubusercontent.com/46967328/103065966-d271af00-45f2-11eb-90c4-e866ad24a858.jpg)
++++

**Comment by b911ss** [comment]
![2eeca303bba89af8cae74377d97e665](https://user-images.githubusercontent.com/18023172/103074650-0950c080-4605-11eb-9c15-f384a8d71cfa.jpg)
来啊

**Comment by ginochanRS** [comment]
![Uploading 微信图片_20210103203532.jpg…]()

**Comment by ginochanRS** [comment]
![微信图片_20210103203532](https://user-images.githubusercontent.com/74497992/103478731-a7ae0480-4e03-11eb-96b8-d4502a69f1b6.jpg)
