### ISSUE TITLE
企业微信应用消息的推送支持（非机器人）

### ISSUE THREAD

**Issue by sxx1314** [lxk0301/jd_scripts#427]
- 由于方糖现在不能在第一级页面显示所有信息，每次都得点进去。
- 外加企业微信支持的推送类型非常丰富，包括传统的txt/图片/视频，现在还支持markdown和html语法直接推送文章。
- 虽然机器人比较简单只需要获取webhookurl，但是必须在企业微信的app内拉一个群组。而企业微信的应用消息却可以脱离企业微信在普通版本的微信内显示，其体验和公众号推送无异。

示例：
````
{
   "touser" : "UserID1|UserID2|UserID3",
   "toparty" : "PartyID1|PartyID2",
   "totag" : "TagID1 | TagID2",
   "msgtype" : "text",
   "agentid" : 1,
   "text" : {
       "content" : "你的快递已到，请携带工卡前往邮件中心领取。\n出发前可查看<a href=\"http://work.weixin.qq.com\">邮件中心视频实况</a>，聪明避开排队。"
   },
   "safe":0,
   "enable_id_trans": 0,
   "enable_duplicate_check": 0,
   "duplicate_check_interval": 1800
}


````

![](https://res.mail.qq.com/node/ww/wwopenmng/images/independent/doc/test_msg$5bc63c26.png)

[文档](https://work.weixin.qq.com/api/doc/90000/90135/90236 "文档")

成员列表部门id等都可以省略，因为应用本身可以设置可见的成员/部门。

我的实例
```
data = {
            "toparty": self.partyID,
            "msgtype": "mpnews",
            "agentid": self.agentID,
            "mpnews" :{
                "articles" : [
                {
                "title" : title,
                "thumb_media_id" : "xxxxxx(图片id 上传素材资源之后查看外链可以显示  必须自己的id  可以不设置)" ,
                "author" : "智能助手（文章作者）" ,
                "content_source_url": "（阅读原文的链接  可以不填写）",
                "content" : html（html代码  可以直接用markdown转换）,
                "digest": desp（简单描述 可以直接取自markdown的内容 自动摘取512字节）
                }
```

**Comment by sxx1314** [comment]
我是直接把原本的企业微信机器人推送改成了应用推送

**Comment by lxk0301** [comment]
也是公众号推送？

**Comment by sxx1314** [comment]
> 也是公众号推送？

体验和公众号推送差不多，直接在普通版本微信内就能推送信息。
也就是普通微信里会出现一个企业号，企业号里有各种应用推送。这样甚至每一个脚本都可以分配一个应用，推送时条理更加清晰。

**Comment by xiamo23** [comment]
发送请求地址：https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token={token}
token有效期为7200s，也就两小时，过期后需要重新提交申请。
token请求地址：https://qyapi.weixin.qq.com/cgi-bin/gettoken?corpid=企业ID&corpsecret=应用ID
返回格式为JSON
如果只是自己一个人用的话可以把{
   "touser" : "UserID1|UserID2|UserID3",
   "toparty" : "PartyID1|PartyID2",
   "totag" : "TagID1 | TagID2",}替换为
"touser" : "@all",
还有，能出一个自定义服务器推送的，我自己搭建了一个私人推送服务，通过可以通过POST或者GET
方式为
type 信息类型，必须，text，card。
title 标题，当类型为card时必选。
text 信息内容。
推送方式就是url/?type=card&title=标题&text=内容

**Comment by Huang28** [comment]
![1780764B6EC4536B366239CAA0E4B4B6](https://user-images.githubusercontent.com/52352624/103091923-9d844d00-4630-11eb-9fc7-53941cf16fec.png)
`const options1 = {
      url: `https://qyapi.weixin.qq.com/cgi-bin/gettoken`,
      json: {
        corpid:'企业微信id',
        corpsecret:'Secret',
      },
      headers: {
        'Content-Type': 'application/json',
      },
    };
    $.post(options1, (err, resp, data) => {
        var json = JSON.parse(data);
        accesstoken = json.access_token;
        const options = {
      url: `https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=${accesstoken}`,
      json: {
        touser:'推送人账号名称',
        agentid:'AgentId应用id',
        msgtype: 'textcard',
        textcard: {
          title: `${text}`,
          description: `${desp}`,
          url: '',
          btntxt: '更多'
        },
        safe:'0',
      },
      headers: {
        'Content-Type': 'application/json',
      },
    };
    $.post(options, (err, resp, data) => {});
      });
  });`
主要是企业微信需要4个值

**Comment by sxx1314** [comment]
> ![1780764B6EC4536B366239CAA0E4B4B6](https://user-images.githubusercontent.com/52352624/103091923-9d844d00-4630-11eb-9fc7-53941cf16fec.png)
> 
> 企业微信应用消息推送需要4个值
> 我直接在方法里面改了测试 用卡片式类型textcard效果还行
> 
> const options1 = {
> url: `https://qyapi.weixin.qq.com/cgi-bin/gettoken`,
> json: {
> corpid:'企业微信id',
> corpsecret:'Secret',
> },
> headers: {
> 'Content-Type': 'application/json',
> },
> };
> $.post(options1, (err, resp, data) => {
> var json = JSON.parse(data);
> accesstoken = json.access_token;
> const options = {
> url: `https://qyapi.weixin.qq.com/cgi-bin/message/send?access_token=${accesstoken}`,
> json: {
> touser:'推送人账号名称',
> agentid:'AgentId应用id',
> msgtype: 'textcard',
> textcard: {
> title: `${text}`,
> description: `${desp}`,
> url: '',
> btntxt: '更多'
> },
> safe:'0',
> },
> headers: {
> 'Content-Type': 'application/json',
> },
> };
> $.post(options, (err, resp, data) => {});
> });
> });

其实还有个优势就是可以创建n各应用，每个脚本都可以分配一个应用推送。显示的条理就更加清晰了

**Comment by lxk0301** [comment]
@sxx1314 @Huang28 @xiamo23 你们会的话。就麻烦pr过来一下吧，目前暂无空

**Comment by xiamo23** [comment]
> @ sxx1314 @ Huang28 @ xiamo23你们会的话。就麻烦pr过来一下吧，目前暂无空

我不会GIT提交代码。。。

**Comment by zqh2333** [comment]
期待这个

**Comment by sxx1314** [comment]
已支持 
[#483](https://github.com/lxk0301/jd_scripts/pull/483)
[#495](https://github.com/lxk0301/jd_scripts/pull/495)
