### ISSUE TITLE
运行jd_jdh.js出现错误

### ISSUE THREAD

**Issue by wanthigh** [lxk0301/jd_scripts#435]
所有任务全部是undefined

**Comment by watershy** [comment]
走了一遍debugger发现所有的错误消息都是no access ,是不是和领取奖励一样无解

**Comment by Naivev** [comment]
![image](https://user-images.githubusercontent.com/45974159/103063689-0944c680-45ed-11eb-9e7a-0a88baf14b80.png)

**Comment by lxk0301** [comment]
都一样
