### ISSUE TITLE
美丽颜究院

### ISSUE THREAD

**Issue by shitouer0515** [lxk0301/jd_scripts#436]
![Screenshot_20201224_123048](https://user-images.githubusercontent.com/10106144/103060795-57090100-45e4-11eb-8e06-919d05355380.jpg)
![Screenshot_20201224_122514_com jingdong app mall](https://user-images.githubusercontent.com/10106144/103060823-612aff80-45e4-11eb-9145-15769af7d0c3.jpg)
不知道这个苹果手机有没有，先占个位吧
 
 
 
 
 

 
## 期望增加的功能

A：

## 入口

A：

**Comment by lxk0301** [comment]
弄不了
