### ISSUE TITLE
nodejs运行工厂js无反应

### ISSUE THREAD

**Issue by poemxl** [lxk0301/jd_scripts#439]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [x] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：
运行node jd_dreamFactory.js后无任何打印信息就直接结束，跟其它js一样填写的cookie
### (2) 详细日志
A：

### (1) Node.js版本

A：v10.15.3

### (2) npm版本

A：6.14.5

### (3)npm install的日志

A：
F:\autoJs\scripts>cnpm install
| [0/4] Installing universalify@^0.1.2
WARN node unsupported "node@v10.15.3" is incompatible with got@^11.3.0, expected node@>=10.19.0
| [2/4] Installing url-join@^2.0.5
WARN node unsupported "node@v10.15.3" is incompatible with got@11.8.1 › http2-wrapper@^1.0.0-beta.5.2, expected node@>=10.19.0
√ Installed 4 packages
√ Linked 53 latest versions
√ Run 0 scripts
Recently updated (since 2020-12-17): 1 packages (detail see file F:\autoJs\scripts\node_modules\.recently_updates.txt)
  Today:
    → got@11.8.1 › @types/cacheable-request@6.0.1 › @types/node@*(14.14.16) (04:24:25)
√ All packages installed (58 packages installed from npm registry, used 5s(network 5s), speed 62.61kB/s, json 57(194.41kB), tarball 107.95kB)

**Comment by lxk0301** [comment]
依赖包没下载完？

**Comment by poemxl** [comment]
嗯，装完了吧，只有这一个运行不起

**Comment by poemxl** [comment]
我再更新node试一下

**Comment by poemxl** [comment]
![image](https://user-images.githubusercontent.com/37215215/103131552-2dcb9c00-46dc-11eb-84f9-b2fae45f8b7c.png)

**Comment by poemxl** [comment]
node版本： 12.16.0
npm版本： 6.14.10
使用npm安装无报错
node jd_fruit.js 正常运行
node jd_dreamFactory.js无反应

**Comment by lxk0301** [comment]
不知道你这是什么问题导致的。按理说不应该。我这边本地都是正常的

**Comment by poemxl** [comment]
看样子只有我一人，那好吧
