### ISSUE TITLE
京东健康APP瓜分百万红包脚本失效

### ISSUE THREAD

**Issue by danwangshimoluo** [lxk0301/jd_scripts#442]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 
无
Q：是否仔细阅读了教程
- [x ] 已仔细阅读教程 
是
## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：
脚本日志全是 undefined
手动进入App查看任务也没做。脚本失效。
### (2) 详细日志
A：
******开始【京东账号3】北奥***锤*********

您的分享助力码为：c0fec8ae********70d5e4a273e76f8
undefined
undefined
任务已做过
undefined
undefined
undefined
undefined
undefined
任务已做过
京东账号3北奥***锤
获得0张汪汪卡，共1970张汪汪卡
任务已做完，请手动领取奖励

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by lxk0301** [comment]
@danwangshimoluo 脚本失效了。

**Comment by sgzman** [comment]
的确失效了
