### ISSUE TITLE
云函数运行疯狂joy挂机脚本超时

### ISSUE THREAD

**Issue by hengwuming** [lxk0301/jd_scripts#445]
## 期望增加的功能

A：希望可以改进一下

## 入口

A：

**Comment by lxk0301** [comment]
没得办法， 云函数机制如此， 最大超时时间是 900秒。900/60=15分钟， 你可以设置一个cron， 16分钟运行一次即可

**Comment by hengwuming** [comment]
> 没得办法， 云函数机制如此， 最大超时时间是 900秒。900/60=15分钟， 你可以设置一个cron， 16分钟运行一次即可

嗯
