### ISSUE TITLE
关于解决docker-compose logs日志中文乱码的方案。

### ISSUE THREAD

**Issue by JunzhouLiu** [lxk0301/jd_scripts#452]
#363 

是否可以再dockerfile中指定相关字符集解决该问题
```
ENV LANG en_US.UTF-8  
ENV LANGUAGE en_US:en  
ENV LC_ALL en_US.UTF-8  
```

**Comment by hclasmn** [comment]
乱码是你的问题，而不是大家问题，你编辑器有问题吧

**Comment by JunzhouLiu** [comment]
> 乱码是你的问题，而不是大家问题，你编辑器有问题吧
你执行下docker-compose logs测试下。 跟编辑器和log文件没关系，是docker-compose logs输出中文字符集乱码的问题。

**Comment by hclasmn** [comment]
> > 乱码是你的问题，而不是大家问题，你编辑器有问题吧
> 
> 你执行下docker-compose logs测试下。 跟编辑器和log文件没关系，是docker-compose logs输出中文字符集乱码的问题。

那个log毫无意义

**Comment by hclasmn** [comment]
你要有需求，compose里面自己加下就好

**Comment by hclasmn** [comment]
乱码也只是前面一句话，主要内容还不是英文，

**Comment by iouAkira** [comment]
你俩不在一个频道，这个问题是docker- compose的问题，至于日志有没有意义，看个人需求，我尝试加了这几个环境变量问题依旧，你用 docker logs 容器名 看到的就没乱码了。

**Comment by hclasmn** [comment]
> 你俩不在一个频道，这个问题是docker- compose的问题，至于日志有没有意义，看个人需求，我尝试加了这几个环境变量问题依旧，你用 docker logs 容器名 看到的就没乱码了。

哈哈哈哈，确实，我只是觉得这个需求提的没意义，
![image](https://user-images.githubusercontent.com/32213103/103148219-6c269100-4798-11eb-9e46-32cd083c96eb.png)

**Comment by hclasmn** [comment]
我说怎么印象里没乱码呢

**Comment by JunzhouLiu** [comment]
> 你俩不在一个频道，这个问题是docker- compose的问题，至于日志有没有意义，看个人需求，我尝试加了这几个环境变量问题依旧，你用 docker logs 容器名 看到的就没乱码了。

是的，关注点不一样，确实不在一个频道，我只是比较关注这个乱码产生的原因，docker logs 容器id 查看确实没问题，后续我继续看下这个问题。

此帖终结。

**Comment by JunzhouLiu** [comment]
> 你俩不在一个频道，这个问题是docker- compose的问题，至于日志有没有意义，看个人需求，我尝试加了这几个环境变量问题依旧，你用 docker logs 容器名 看到的就没乱码了。

有giter或者slack的群组吗？想加进去一下，希望后续能够继续贡献。（今天测试了下RPI4，很舒服）

**Comment by iouAkira** [comment]
> > 你俩不在一个频道，这个问题是docker- compose的问题，至于日志有没有意义，看个人需求，我尝试加了这几个环境变量问题依旧，你用 docker logs 容器名 看到的就没乱码了。
> 
> 有giter或者slack的群组吗？想加进去一下，希望后续能够继续贡献。（今天测试了下RPI4，很舒服）

只有telegram群组 https://t.me/JD_fruit_pet
