### ISSUE TITLE
可以试试用jsdelivr代替githubusercontent网址的订阅

### ISSUE THREAD

**Issue by wbry** [lxk0301/jd_scripts#453]
## 期望增加的功能

A：国内raw.githubusercontent.net的DNS污染太严重了，经常更新出问题，可以换成有国内CDN的jsdelivr地址

## 入口

A：例如把
[https://raw.githubusercontent.com/lxk0301/jd_scripts/master/jd_fruit.js](https://raw.githubusercontent.com/lxk0301/jd_scripts/master/jd_fruit.js)
改为
[https://cdn.jsdelivr.net/gh/lxk0301/jd_scripts@master/jd_fruit.js](https://cdn.jsdelivr.net/gh/lxk0301/jd_scripts@master/jd_fruit.js)

**Comment by lxk0301** [comment]
不考虑。你 自己使用就行了。

cdn的延迟更新很严重
