### ISSUE TITLE
直播红包雨脚本工作不正常

### ISSUE THREAD

**Issue by askiter** [lxk0301/jd_scripts#455]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [x] 方法四：iOS系统的代理软件

### (1) 具体问题
A：运行时出错，提示活动太火爆

### (2) 详细日志
A：异常：{"msg":"活动太火爆，请稍后再试~","code":"0","subCode":"1"}
![image](https://user-images.githubusercontent.com/5763881/103145839-8605ab00-477b-11eb-95f2-3d3bef4d8b51.jpeg)

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by lcb1208** [comment]
自己还原下咯

**Comment by askiter** [comment]
> 自己还原下咯

还原什么？

**Comment by lxk0301** [comment]
周末有时候没有。忽略就行

**Comment by gzmac** [comment]
大佬，能告诉我直播间的ids怎么获得的？想在不正常的时候可以手动修改直播间的ids，更换直播间，谢谢！

**Comment by hacken156026692** [comment]
同问，一直异常。。。

**Comment by benz819** [comment]
经常场次时间判断错误就跳过没跑，要不别加判断了，到点就跑吧，反正计划任务会控制。

**Comment by benz819** [comment]
> 经常场次时间判断错误就跳过没跑，要不别加判断了，到点就跑吧，反正计划任务会控制。

火爆那个不知道怎么回事，我手动上去点又能得豆。
