### ISSUE TITLE
运行脚本账号出现API请求失败

### ISSUE THREAD

**Issue by 50733364** [lxk0301/jd_scripts#462]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ X] 没有类似的issue 

Q：是否仔细阅读了教程
- [ X] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ X] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：我用阿里的vps创docker运行得，前四个账号正常 后面添加的两个都显示 api请求失效 请问是有限制吗？

### (2) 详细日志
A：crazyJoy任务 API请求失败，请检查网路重试

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by 50733364** [comment]
详细日志  "Invalid character in header content [\"cookie\"]"
京喜工厂 API请求失败，请检查网路重试
"Invalid character in header content [\"cookie\"]"
一直这样。   cookie我设置好了的

Cookie5="pt_key=AAJf54KtADB6P5fZDAaTpqKJ_4YTXXXXXXXXXXXXXqlZ8yphUQSzRPhakhCJgWZQPplrMLjI; pt_pin=jd_6fXXXXXXX;"
Cookie6="pt_key=AAJf54OsADDw3w4LgtzG8Ikp8av2XXXXXXXXXXX9iTyPVfT6FjXvlbdKIjimUp_1eB6kTs; pt_pin=jd_79XXXXXXX;

**Comment by lxk0301** [comment]
你自己设置问题。

**Comment by 50733364** [comment]
额  可以请教下作者  大概哪里设置错了吗？  Cookie 我前面4个也是这样子设置的。  然后我试了下在云函数跑这两个账号是可以的。

**Comment by lxk0301** [comment]
@50733364 你自己按照docker里面的注释说明认真填写吧。或者就是你的cookie获取的有问题

**Comment by 50733364** [comment]
好  我再去试下  感谢回复

**Comment by lxk0301** [comment]
> 详细日志 "Invalid character in header content ["cookie"]"
> 京喜工厂 API请求失败，请检查网路重试
> "Invalid character in header content ["cookie"]"
> 一直这样。 cookie我设置好了的
> 
> Cookie5="pt_key=AAJf54KtADB6P5fZDAaTpqKJ_4YTXXXXXXXXXXXXXqlZ8yphUQSzRPhakhCJgWZQPplrMLjI; pt_pin=jd_6fXXXXXXX;"
> Cookie6="pt_key=AAJf54OsADDw3w4LgtzG8Ikp8av2XXXXXXXXXXX9iTyPVfT6FjXvlbdKIjimUp_1eB6kTs; pt_pin=jd_79XXXXXXX;

还有你认真看。你没发现你的cookie6最后面少一个双引号嘛？？？？？


不知你实际情况是什么样子的

**Comment by 50733364** [comment]
最后面那个双引号 是我没复制进来。  嗯 我少复制了个。 我看看到底是什么原因吧。 感谢
