### ISSUE TITLE
运行jd_crazy_joy_coin.js 无法获取金币参数

### ISSUE THREAD

**Issue by hengwuming** [lxk0301/jd_scripts#463]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否仔细阅读了教程
- [x ] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [x ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by hengwuming** [comment]
这是运行了200次左右的结果

**Comment by DoveBoy** [comment]
@hengwuming 更新最新的js，我运行了4000多次都正常的

**Comment by hengwuming** [comment]
> @hengwuming 更新最新的js，我运行了4000多次都正常的

我试试

**Comment by hengwuming** [comment]
> @hengwuming 更新最新的js，我运行了4000多次都正常的

感谢，可以了
