### ISSUE TITLE
种豆得豆 偷取好友判断问题

### ISSUE THREAD

**Issue by 2320142695** [lxk0301/jd_scripts#465]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否仔细阅读了教程
- [ x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ x] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：偷取好友的豆时判断的是大于等于3，我这边好友的豆都是最多的都是2，导致一直没有执行这一块的代码
https://github.com/lxk0301/jd_scripts/blob/master/jd_plantBean.js#L165

### (2) 详细日志
A：无

### (1) Node.js版本

A：12

### (2) npm版本

A：6.14

### (3)npm install的日志

A：无

**Comment by lxk0301** [comment]
好友没有三瓶。你不能偷

**Comment by 2320142695** [comment]
@lxk0301 不知道，最近才发现这段代码一直没有执行

**Comment by lxk0301** [comment]
> @lxk0301 不知道，最近才发现这段代码一直没有执行
有没有执行。你自己去app里面活动页面手动收取一下好友的就知道了。

如果提示你今天的收取机会已经用完。肯定是执行了 


另外种豆收取好友营养液，判断好友是大于等于三个的条件，是因为此种条件下收取是有几率收取两个

**Comment by 2320142695** [comment]
@lxk0301 大佬，这段代码我又跑了几天，日志中确实时没有发现关于这段代码的日志，是我这边不会出现大于等于3的情况吗？

**Comment by lxk0301** [comment]
@2320142695 自己先手动去APP活动页面，去收取一下好友的营养液就知道了， 如果提示已达上限， 肯定是执行了

**Comment by 2320142695** [comment]
@lxk0301  可以收取，没有提示达到上限

**Comment by lxk0301** [comment]
@2320142695 那就是没有执行。如果脚本没有出错的日志， 那应该是你的好友一直没有大于等于3瓶的人

**Comment by 2320142695** [comment]
@lxk0301 好吧，我把我的改成2

**Comment by lxk0301** [comment]
https://github.com/lxk0301/jd_scripts/compare/41cde5cbdf1c...d705a2b06398

已加了兼容
