### ISSUE TITLE
我在windows下跑jd_bean_sign.js会出现问题

### ISSUE THREAD

**Issue by hengwuming** [lxk0301/jd_scripts#469]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ x] 没有类似的issue 

Q：是否仔细阅读了教程
- [ x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ x] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：windows执行脚本报错

### (2) 详细日志
A：
PS D:\jd_scripts-master> node jd_bean_sign.js                                                                           {"name":"RequestError","code":"ENOENT","timings":{"start":1609054420625,"socket":1609054420627,"lookup":1609054420701,"error":1609054420707,"phases":{"wait":2,"dns":74,"total":82}}}
检测到您不能访问外网,将使用CDN下载JD_DailyBonus.js文件
文件下载完毕
*****************开始京东账号1 京豆签到*******************
开始替换变量
替换变量完毕

开始执行脚本签到，请稍等
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.
京东签到脚本执行异常:Error: Command failed: C:\Program Files\nodejs\node.exe ./JD_DailyBonus.js >> ./result.txt
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

### (1) Node.js版本

A：
v14.15.3
### (2) npm版本

A：6.14.9

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
常识：路径中带空格要加引号。

**Comment by hengwuming** [comment]
> 常识：路径中带空格要加引号。

路径中没有空格

**Comment by EvineDeng** [comment]
不认识failed？？？？？？建议环境变量调用node，不要写绝对路径。

failed: C:\Program Files\nodejs\node.exe ./JD_DailyBonus.js >> ./result.txt
'C:\Program' is not recognized as an internal or external command,
operable program or batch file.

**Comment by hengwuming** [comment]
> 不认识failed？？？？？？这么大个空格。。。建议环境变量调用node，不要写绝对路径。
> 
> failed: C:\Program Files\nodejs\node.exe ./JD_DailyBonus.js >> ./result.txt
> 'C:\Program' is not recognized as an internal or external command,
> operable program or batch file.

我知道了，是我把node安装在program file下，所以有个空格，感谢你帮我解答，谢谢。
