### ISSUE TITLE
每天更新代码后都没有成功杀死原本正在运行的jd_crazy_coin.js，导致占用进程越来越多

### ISSUE THREAD

**Issue by chaoQWQ** [lxk0301/jd_scripts#471]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [x] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：
目录下jd_scripts/docker/proc_file.sh脚本里，获取进程号失败,这里$1获取到的是用户名root，就导致没有杀死原进程，导致后面同时运行着多个jd_crazy_coin.js，应该换成$2才是进程号。
![image](https://user-images.githubusercontent.com/22882330/103170365-92266100-487e-11eb-8385-1736b16782d7.png)

### (2) 详细日志
A：
![image](https://user-images.githubusercontent.com/22882330/103170587-3c52b880-4880-11eb-9478-4600b6cf27e7.png)

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by qiangxinglin** [comment]
我测试了一下, 跟你不同
```
/scripts # ps -ef | grep "jd_crazy" | awk '{print "kill "$1}'
kill 710
kill 744
/scripts # ps -ef | grep "jd_crazy" | awk '{print "kill "$2}'
kill root
kill root
```

**Comment by iouAkira** [comment]
@qiangxinglin proc_file.sh 给docker1用的..其他方式要用自己改就是了

**Comment by chaoQWQ** [comment]
> proc_file.sh 给docker1用的..其他方式要用自己改就是了

嗯，我就自己改下吧
