### ISSUE TITLE
完成任务失败，风控用户无法参与任务~

### ISSUE THREAD

**Issue by google-mirror** [lxk0301/jd_scripts#472]
完成任务失败，风控用户无法参与任务~
脚本能被检测到?

**Comment by cjw20203** [comment]
你如果风控的话，手动点进去也是无法参加活动，更何况脚本了。建议你换个京东账号吧。

**Comment by google-mirror** [comment]
@cjw20203 之前手动没问题, 用脚本大概一周就这样提示风控了

**Comment by hclasmn** [comment]
用了3月毫无问题。你应该是因为别的问题黑了吧

**Comment by cjw20203** [comment]
> @cjw20203 之前手动没问题, 用脚本大概一周就这样提示风控了

那就没办法了。解不了

**Comment by hclasmn** [comment]
> > @cjw20203 之前手动没问题, 用脚本大概一周就这样提示风控了
> 
> 那就没办法了。解不了

还是有办法的，买plus。，然后疯狂购物，。半年后就解了，笑
