### ISSUE TITLE
希望增加点亮心愿功能,一天至少20豆

### ISSUE THREAD

**Issue by ljk4160** [lxk0301/jd_scripts#481]
## 期望增加的功能

A：

## 入口
https://h5.m.jd.com/babelDiy/Zeus/3mTNcpWt5JYh3aUCyo6gqKuF4pnx/index.html?_ts=1609203129263&utm_source=iosapp&utm_medium=appshare&utm_campaign=t_335139774&utm_term=Qqfriends&ad_od=share&utm_user=plusmember&gx=RnE1kTQNbmGMntRJ9d9zXCXT

![image](https://user-images.githubusercontent.com/9875024/103251544-0a427300-49b4-11eb-825e-7d678595c156.png)

A：

**Comment by hclasmn** [comment]
今天元旦活动，50个

**Comment by lxk0301** [comment]
早知道。做不了脚本
