### ISSUE TITLE
京东赚赚一直显示暂时看不到您的京东赚赚好友助力码

### ISSUE THREAD

**Issue by mengdie101** [lxk0301/jd_scripts#482]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [X] 没有类似的issue 

Q：是否仔细阅读了教程
- [X] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [X] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：京东赚赚一直显示暂时看不到您的京东赚赚好友助力码

### (2) 详细日志
A：
Dec 28 16:59:47 开始
Dec 28 16:59:48 随机取5个码放到您固定的互助码后面
Dec 28 16:59:48 第1个京东账号将要助力的好友["ATGEC3-fsrn13aiaEqiM","AUWE5maSSnzFeDmH4iH0elA","AUWE5m6WUmDdZC2mr1XhJlQ","AUWE5m_jEzjJZDTKr3nwfkg","A06fNSRc4GIqY38pMBeLKQE2InZA","AUWE5mf7ExDZdDmH7j3wfkA","AUWE5m6jBy2cNAWX7j31Pxw","AUWE5mK2UnDddDTX61S1Mkw","AUWE5mavGyGZdWzP5iCoZwQ","ADzNSmKyVxDIBZz0","S5KkcRR0eoQKEdR6glPJYdg","S5KkcRU0Z8AGFc0jynfIJfQ","AUWE5mPnExWEBXWWtjCockQ","S5KkcEXlmrBCudVO-xZJD"]
Dec 28 16:59:48 好友任务已完成，下次再给他助力吧~
Dec 28 16:59:48 好友任务已完成，下次再给他助力吧~
Dec 28 16:59:48 好友任务已完成，下次再给他助力吧~
Dec 28 16:59:48 好友任务已完成，下次再给他助力吧~
Dec 28 16:59:48 好友任务已完成，下次再给他助力吧~
Dec 28 16:59:48 好友任务已完成，下次再给他助力吧~
Dec 28 16:59:48 好友任务已完成，下次再给他助力吧~
Dec 28 16:59:48 好友任务已完成，下次再给他助力吧~
Dec 28 16:59:49 好友任务已完成，下次再给他助力吧~
Dec 28 16:59:49 好友任务已完成，下次再给他助力吧~
Dec 28 16:59:49 好友任务已完成，下次再给他助力吧~
Dec 28 16:59:49 好友任务已完成，下次再给他助力吧~
Dec 28 16:59:49 好友任务已完成，下次再给他助力吧~
Dec 28 16:59:49 好友任务已完成，下次再给他助力吧~
Dec 28 16:59:49 已满5人助力,暂时看不到您的京东赚赚好友助力码

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by EvineDeng** [comment]
没看见最后一句话吗：已满5人助力,暂时看不到您的京东赚赚好友助力码

**Comment by mengdie101** [comment]
> 没看见最后一句话吗：已满5人助力,暂时看不到您的京东赚赚好友助力码

好吧，助力满了就看不到了呀，明白了
