### ISSUE TITLE
Linux   ubuntu操作系统部署执行报错

### ISSUE THREAD

**Issue by lsh26** [lxk0301/jd_scripts#487]
按照教程进行部署，执行时出现报错，不知大佬知道缺少什么没有安装导致的报错吗？

<img width="1280" alt="WeChatff2a8d173244589665bf545b538d949f" src="https://user-images.githubusercontent.com/53509876/103273345-0c2f2500-49fa-11eb-9d4c-b9208e6ce2b0.png">

**Comment by lxk0301** [comment]
只有这么点日志嘛？
你的Contos是多少版本

**Comment by lsh26** [comment]
> 只有这么点日志嘛？
> 你的Contos是多少版本

是的。只有这么点日志。。。所以我不知从何解决了
系统是Linux（ubuntu 18.04）

<img width="658" alt="WeChata7eb96c3ab4f6fe90eac094dc700d020" src="https://user-images.githubusercontent.com/53509876/103274332-616c3600-49fc-11eb-8abb-a8efca69c483.png">

**Comment by lsh26** [comment]
> 只有这么点日志嘛？
> 你的Contos是多少版本

我把代码格式化之后，发现 try{}catch{}报错，我修改为try{}catch(e){}之后通过了这个报错。这应该是我什么东西的版本不对

![image](https://user-images.githubusercontent.com/53509876/103275463-2ddedb00-49ff-11eb-9c55-30dea474d7b2.png)
是我node版本不对吗？

**Comment by lsh26** [comment]
> 只有这么点日志嘛？
> 你的Contos是多少版本

已解决，升级node版本后，解决了报错，，感觉大佬回复

**Comment by lxk0301** [comment]
Linux 不能使用的话， 一般和两个问题有关，。一个是Contos的版本， 一个是nodejs版本，nodejs版本这里推荐使用10.x版本，nodejs 14.1.0版本不能使用。
