### ISSUE TITLE
用这个脚本薅多了会被京东封号吗？

### ISSUE THREAD

**Issue by 670058872** [lxk0301/jd_scripts#490]
用这个脚本薅多了会被京东封号吗？

**Comment by EvineDeng** [comment]
@670058872 怕封号就别用好了。

**Comment by 670058872** [comment]
> @670058872 怕封号就别用好了。
我就问一下会不会，要是会的话我挂几天就换小号，大佬别生气~

**Comment by EchoChan314** [comment]
> > 我就问一下会不会，要是会的话我挂几天就换小号，大佬别生气~

至少我已经玩快一年了，就一个号。

**Comment by 670058872** [comment]
> > > 我就问一下会不会，要是会的话我挂几天就换小号，大佬别生气~
> 
> 至少我已经玩快一年了，就一个号。

好的，多谢。
