### ISSUE TITLE
小米运动修改步数的问题

### ISSUE THREAD

**Issue by MaFuyan** [lxk0301/jd_scripts#492]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [x] 方法四：iOS系统的代理软件

### (1) 具体问题
A：
小米运动步数修改昨天开始不work了。小米运动APP中的步数无法实时同步QX修改的步数，且支付宝的步数没有改变。之前这一切都是正常work的。
尝试了第三方接入重新绑定支付宝，但是还是不work。

### (2) 详细日志
A：QX Log显示修改成功。
<img width="375" alt="image" src="https://user-images.githubusercontent.com/22090261/103351419-217d7f80-4ade-11eb-92f9-ace3ae61c55e.png">
B. 小米运动中的步数显示是11点45同步的。实际上我刚刚执行了一次修改，无法同步刚才修改的步数。
<img width="375" alt="image" src="https://user-images.githubusercontent.com/22090261/103351609-b84a3c00-4ade-11eb-8f6d-d41140d3e197.png">

**Comment by lxk0301** [comment]
嗯。我自己的也不行了 先暂时停止使用吧
