### ISSUE TITLE
东东工厂提取出来的好友互助码是错误的

### ISSUE THREAD

**Issue by gyq180** [lxk0301/jd_scripts#493]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x ] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [x ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：东东工厂提取出来的好友互助码是错误的,我看了一下日志是从22号早上10点左右后就错误了,错误的这个互助码无法完成互助任务,也无法提交到turinglabs上,我从turinglabs随即取到的好友互助码都是22号10点之前这种格式的

### (2) 详细日志
A：之前正确的互助码日志: 您的东东工厂好友助力邀请码：P04z54XCjVWnYaS5jQKDGX72ntXk6SAdRV73EE
错误的互助码日志: 【京东账号1（无限_梦幻）的东东工厂好友互助码】T022v_93RR0e8knRIRv8lfQKcgCjVWnYaS5kRrbA
这两个日志是同一个帐号所产生的日志

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by gyq180** [comment]
补充一点,刚刚发现健康抽奖机和东东工厂有一样的情况,并且日志里获取到的互助码和东东工厂的一模一样,同样是22号的某一时刻发生改变的

**Comment by lxk0301** [comment]
难道新的邀请码。不能互助了吗？

发生改变是京东那边改变的。

**Comment by gyq180** [comment]
好像不行了,我两个账户互相互助,每天第一次执行就报了互助已满

**Comment by lxk0301** [comment]
> 好像不行了,我两个账户互相互助,每天第一次执行就报了互助已满

有去活动页面查看实际上有没有助力上呢？

**Comment by gyq180** [comment]
> > 好像不行了,我两个账户互相互助,每天第一次执行就报了互助已满
> 
> 有去活动页面查看实际上有没有助力上呢？

我的旧互助码在turinglabs上,现在是助力满了,过了0点我手动执行观察下

**Comment by gyq180** [comment]
> > 好像不行了,我两个账户互相互助,每天第一次执行就报了互助已满
> 
> 有去活动页面查看实际上有没有助力上呢？

仔细看了下日志破案了,新的互助码可以助力上,那目前看来只是不能提交到turinglabs上了,日志里还显示随即取的20个旧格式的互助码也有助力成功的情况,那就是说新旧互助码都可以使用.

**Comment by lxk0301** [comment]
> > > 好像不行了,我两个账户互相互助,每天第一次执行就报了互助已满
> > 
> > 
> > 有去活动页面查看实际上有没有助力上呢？
> 
> 仔细看了下日志破案了,新的互助码可以助力上,那目前看来只是不能提交到turinglabs上了,日志里还显示随即取的20个旧格式的互助码也有助力成功的情况,那就是说新旧互助码都可以使用.

旧的互助码目前是可以使用的
