### ISSUE TITLE
数码电器新增签到领京豆

### ISSUE THREAD

**Issue by iwshw888** [lxk0301/jd_scripts#497]
## 期望增加的功能

A：京东首页数码电器里面新出现了签到领京豆的功能,每天都可以签到,而且可以邀请好友进行助力,
希望增加签到和互助脚本.

## 入口

A：京豆APP首页-数码电器-签到领京豆(东东工厂入口旁边)

**Comment by JohnED512** [comment]
野比的脚本应该整合这个了

**Comment by lxk0301** [comment]
野比的签到里面已经把这个给签到了。再做个邀请好友的没必要了

**Comment by pikaqiu112** [comment]
@lxk0301 东东工厂互助的有人吗？
