### ISSUE TITLE
移动网页 登录后， 发现没有各项活动的入口了

### ISSUE THREAD

**Issue by ToQuery** [lxk0301/jd_scripts#499]
在手机浏览器登录后发现没有各项活动的入口，怀疑狗东最近更新，增加了非正常参加活动的埋点。

是否需要暂停该脚本使用，或者 使用狗东app的agent 标识？

**Comment by lxk0301** [comment]
去APP找活动入口。

**Comment by ToQuery** [comment]
狗东是不是限制了移动网页的访问活动的功能，需要在请求的agent 增加狗东app的标识？

**Comment by lxk0301** [comment]
有的有限制，需要改UA
