### ISSUE TITLE
从大佬仓库里发现了一个备选方案

### ISSUE THREAD

**Issue by Castle1984** [lxk0301/jd_scripts#5]
好吧，恢复了，哈哈哈，当我没说

**Comment by dhy1233** [comment]
github里是不是已经不能运行了，怎么只有一个js

**Comment by Castle1984** [comment]
嗯，目前看来是的

**Comment by xuelang7009** [comment]
运行不了

**Comment by paopaojun** [comment]
> github里是不是已经不能运行了，怎么只有一个js

一样，，，有解决办法么。。。

**Comment by Castle1984** [comment]
Zero-S1/JD_tools （https://github.com/Zero-S1/JD_tools）
这是我原来想说的备选方案，不过脚本不全，可能不是很好...

**Comment by fivenull** [comment]
链接全都失效了
