### ISSUE TITLE
运行log日志显示成功，但是cookies还是显示失效

### ISSUE THREAD

**Issue by nick814** [lxk0301/jd_scripts#500]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x ] 没有类似的issue 

Q：是否仔细阅读了教程
- [x ] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [x ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：我用serv酱推送，我看到serv酱显示cookies失效，然后我更换了新的cookies，去查看log日志已经任务开始直接并且执行成功，但是推送给我通知还是显示cookies失效
我是在centos 7上跑的docker。

### (2) 详细日志
A：
Dec 31 17:01:01 【京东账号1】jj
Dec 31 17:01:01 【17点直播红包雨】暂无红包雨
Dec 31 17:01:01 
Dec 31 17:01:01 
Dec 31 17:01:01 🔔直播红包雨, 结束! 🕛 0.635 秒

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by lxk0301** [comment]
这种问题 ，自己好好检查你的京东cookie是否正确 和检查环境变量的设置
