### ISSUE TITLE
东东工厂运行错误(每次)

### ISSUE THREAD

**Issue by iwshw888** [lxk0301/jd_scripts#504]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [x] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

#### A：Jan 01 01:36:01 ******开始【京东账号1】圐圙勥烎*********
Jan 01 01:36:01 
Jan 01 01:36:01 开始
Jan 01 01:36:11 第1个京东账号将要助力的好友["T0225KkcRBsQ8FXSdBKnwvZZJwCjVWnYaS5kRrbA","T0225KkcREwf8FSEIk-mk_cDfQCjVWnYaS5kRrbA","T0225KkcRBwZ_FTfIk6mkvFYdQCjVWnYaS5kRrbA","T0225KkcRx9I8FDfcR31lqEIcACjVWnYaS5kRrbA","T018v_h0Rx8Y9FLeJR-b1ACjVWnYaS5kRrbA","T020-akNJ117ky-3R0mg4q1sCjVWnYaS5kRrbA","T0225KkcR0hI91CFck78xqFZfQCjVWnYaS5kRrbA"]
Jan 01 01:36:14 此京东账号1圐圙勥烎暂未选购商品
Jan 01 01:36:14 现在也能为您做任务和收集免费电力
Jan 01 01:36:14 {"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
Jan 01 01:36:14 {"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
Jan 01 01:36:14 {"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
Jan 01 01:36:14 {"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
Jan 01 01:36:14 {"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
Jan 01 01:36:15 {"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
Jan 01 01:36:15 {"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
Jan 01 01:36:15 成功收集19电量，当前蓄电池总电量：993740
Jan 01 01:36:15 
Jan 01 01:36:15 
Jan 01 01:36:15 此账号1圐圙勥烎暂未选择商品
Jan 01 01:36:15 
Jan 01 01:36:15 BoxJs或环境变量提供的心仪商品：英菲克可充电蓝牙键盘
Jan 01 01:36:15 
Jan 01 01:36:15 异常：{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
Jan 01 01:36:15 
Jan 01 01:36:15 ❗️东东工厂, 错误!
Jan 01 01:36:15 TypeError: $.canMakeList is not iterable
Jan 01 01:36:15     at /scripts/jd_jdfactory.js:190:38
Jan 01 01:36:15     at processTicksAndRejections (internal/process/task_queues.js:97:5)
Jan 01 01:36:15 京东账号1圐圙勥烎
Jan 01 01:36:15 已选商品：暂无
Jan 01 01:36:15 心仪商品：英菲克可充电蓝牙键盘
Jan 01 01:36:15 

### (1) Node.js版本

A：node --version

### (2) npm版本

A：6.14.4

### (3)npm install的日志

A：

**Comment by lxk0301** [comment]
明天再试试吧 ，第二个报错偶尔出现也正常

**Comment by iwshw888** [comment]
> 明天再试试吧 ，第二个报错偶尔出现也正常

今天测试还是不行

**Comment by lxk0301** [comment]
Jan 01 01:36:15 ❗️东东工厂, 错误!
Jan 01 01:36:15 TypeError: $.canMakeList is not iterable

这一块报错。是因为你账号没有拿到正常的数据导致出错

**Comment by iwshw888** [comment]
> Jan 01 01:36:15 ❗️东东工厂, 错误!
> Jan 01 01:36:15 TypeError: $.canMakeList is not iterable
> 
> 这一块报错。是因为你账号没有拿到正常的数据导致出错

挂了6个帐号，每个号都是这样的。让人头疼

**Comment by lxk0301** [comment]
> > Jan 01 01:36:15 ❗️东东工厂, 错误!
> > Jan 01 01:36:15 TypeError: $.canMakeList is not iterable
> > 这一块报错。是因为你账号没有拿到正常的数据导致出错
> 
> 挂了6个帐号，每个号都是这样的。让人头疼

脚本能做的。只能加个判断 ，然后让脚本不出错。 但是拿不到正确的京东数据。这个我也无能为力👐

**Comment by lxk0301** [comment]
加了判断， 你更新看看运行还会不会出现这个错误`TypeError: $.canMakeList is not iterable`

需更新脚本运行
