### ISSUE TITLE
京东首页——发现好货——加入心愿单，每天可以领取20-50京豆

### ISSUE THREAD

**Issue by hupo376787** [lxk0301/jd_scripts#512]
## 期望增加的功能

A：京东首页——发现好货——加入心愿单，每天可以领取20-50京豆

## 入口

A：京东首页——发现好货——加入心愿单，每天可以领取20-50京豆
![微信图片_20210101223147](https://user-images.githubusercontent.com/14960168/103440501-321a2b00-4c81-11eb-8363-513ef3856db0.jpg)
![微信图片_20210101223154](https://user-images.githubusercontent.com/14960168/103440505-35151b80-4c81-11eb-92d7-e4c458fec954.jpg)

**Comment by lxk0301** [comment]
早就知道了。做不了脚本
