### ISSUE TITLE
以互助

### ISSUE THREAD

**Issue by pipi242526** [lxk0301/jd_scripts#514]
东东农场
【pipi242526】572851e3f29c4df0a5d2e03d89266394

东东萌宠
【pipi242526】MTE1NDQ5OTUwMDAwMDAwNDMxMTUyODc=

种豆得豆
【pipi242526】ovhzc5s37vwk33aarcrrm7sify

京喜工厂
【pipi242526】q78W5lotHTh_Xs693GNQKA==

东东工厂
【pipi242526】T014_qQzGRwd91HVJgCjVWnYaS5kRrbA

互助麻烦@我

_Originally posted by @ktycky in https://github.com/lxk0301/jd_scripts/discussions/476#discussioncomment-255296_

**Comment by ktycky** [comment]
@pipi242526 已添加(握爪

**Comment by ktycky** [comment]
@pipi242526 已添加(握爪

开始助力京东账号1 - CatalystR的好友: 572851e3f29c4df0a5d2e03d89266394
【助力好友结果】: 已成功给【pipi242526】助力
给好友【pipi242526】助力获得2g水滴
【今日助力次数还剩】2次

**Comment by git1568** [comment]
东东农场
【jltx558】572851e3f29c4df0a5d2e03d89266394

东东萌宠
【jltx558】MTE1NDAxNzgwMDAwMDAwNDIyODE1Mjc=

种豆得豆
【pipi242526】olmijoxgmjutylghrr26mg6hernspu2sidwjs6i

京喜工厂
【jltx558】s0FhWjpe0T88SIy6seRJVg==

东东工厂
【jltx558】T0225KkcRhcd91HVJBr8nKVbIACjVWnYaS5kRrbA

东东赚赚
【jltx558】S5KkcRhcd91HVJBr8nKVbIA

互助麻烦@我

**Comment by pipi242526** [comment]
git1568 <notifications@github.com>于2021年1月2日 周六11:31写道：

**Comment by yuhongwei380** [comment]
东东农场
【yuhongwei380】 bf4b2f068f044a918aa913a4d3164353
种豆得豆
【yuhongwei380】olmijoxgmjutz7liniex4agansdy4l3lefz5dga
@pipi242526  我目前本地编译只用到这两个，所以就只互助了你的这两个，我其他有两个编译报错，还在自己研究

**Comment by pipi242526** [comment]
写好了，你叫什么？

yuhongwei380 <notifications@github.com>于2021年1月2日 周六19:41写道：
