### ISSUE TITLE
jd_jdh（集汪汪卡瓜分百万红包）活动仍在有效期内

### ISSUE THREAD

**Issue by chenyitian2004** [lxk0301/jd_scripts#515]
## 期望增加的功能

A：京东健康集汪汪卡瓜分百万红包（jd_jdh）活动1月5日结束，但是crontablist里面没有出现（https://github.com/lxk0301/jd_scripts/blob/master/docker/crontab_list.sh）

## 入口

A：

**Comment by lxk0301** [comment]
这个脚本失效了。所以去掉了
