### ISSUE TITLE
一月份收益明显减少

### ISSUE THREAD

**Issue by 928234269** [lxk0301/jd_scripts#518]
## 期望增加的功能

A：十二月的收益每天有300～400豆.现在每天大概200以下.

## 入口

A：

**Comment by OiCkilL** [comment]
确实，我也发现了。是被风控了还是没活动了呢

**Comment by jeff332** [comment]
> ## 期望增加的功能
> A：十二月的收益每天有300～400豆.现在每天大概200以下.
> 
> ## 入口
> A：

我基本都是在150-170之间浮动，来客有礼每次ck都失败

**Comment by lxk0301** [comment]
你有毒吧 收益减少也在这里开issue。

**Comment by lxk0301** [comment]
12月份的短期活动都结束了。肯定少了。脚本也推送了通知结束
