### ISSUE TITLE
关于企业微信 应用消息推送的说明

### ISSUE THREAD

**Issue by sxx1314** [lxk0301/jd_scripts#519]
- 鉴于部分同学不愿意看合并说明 [#495](https://github.com/lxk0301/jd_scripts/pull/495)
- 鉴于部分同学看不懂微信的 [文档]( https://work.weixin.qq.com/api/doc/90000/90135/90253)

### 因此在这里简单说明一下

[官网](https://work.weixin.qq.com)

#### thumb_media_id  
- 需要在管理工具-素材库 把图片上传企业微信素材库之后点击外链就能查询。
- 链接内会有mediaid=xxxxx
- **直接传是永久id，必须设置**。
- _只有你使用临时api上传素材才是临时素材_
- ~~由于没写方法转换 desp内容为html语法，因此文章详情内换行缺失。哪位大神有空可以补上，或者等我有空补上。~~
- 最新pr已修复文章详情换行问题。
### **不要设置奇奇怪怪的应用（包括名字/图标），可能会被ban整个企业/个人微信。**

**Comment by hclasmn** [comment]
![image](https://user-images.githubusercontent.com/32213103/103498568-32cce000-4e80-11eb-9d76-43cacfe78bfb.png)
![image](https://user-images.githubusercontent.com/32213103/103498618-66a80580-4e80-11eb-8197-94cca0041034.png)
每天都会对前一天总结，能够发出消息接收消息，素材库如图

**Comment by hclasmn** [comment]
![Screenshot_2021-01-04-11-32-46-31](https://user-images.githubusercontent.com/32213103/103498711-a0790c00-4e80-11eb-8f36-e04f814492d7.jpg)

**Comment by lxk0301** [comment]
企业微信应用通知， 获取 corpid的值,corpsecret的值,touser的值,agentid的值，素材库图片id
上面这些值 ， 需要登录。 然后登录需要下载企业微信APP才能扫描？

**Comment by hclasmn** [comment]
> 企业微信应用通知， 获取 corpid的值,corpsecret的值,touser的值,agentid的值，素材库图片id
> 上面这些值 ， 需要登录。 然后登录需要下载企业微信APP才能扫描？

是，第一次挺麻烦的，而且想推送到微信的话，要关注下企业二维码，否则只能在企业微信APP接收，比方糖方便的是代挂时候，不需要别人提供key了，关注下企业二维码就行了，

**Comment by lxk0301** [comment]
> > 企业微信应用通知， 获取 corpid的值,corpsecret的值,touser的值,agentid的值，素材库图片id
> > 上面这些值 ， 需要登录。 然后登录需要下载企业微信APP才能扫描？
> 
> 是，第一次挺麻烦的，而且想推送到微信的话，要关注下企业二维码，否则只能在企业微信APP接收，比方糖方便的是代挂时候，不需要别人提供key了，关注下企业二维码就行了，

好的， 我试试玩玩，刚才去 这里 https://work.weixin.qq.com/api/doc/90000/90135/90236 扫描登录，提示要我用企业微信APP扫描，

**Comment by lxk0301** [comment]
我一脸懵，我扫描登录进入后，这些值(corpid的值,corpsecret的值,touser的值,agentid的值，素材库图片id)，好像也没看到，企业APP里面也没，不知道如何去拿获取？

**Comment by sxx1314** [comment]
> > 企业微信应用通知， 获取 corpid的值,corpsecret的值,touser的值,agentid的值，素材库图片id
> > 上面这些值 ， 需要登录。 然后登录需要下载企业微信APP才能扫描？
> 
> 是，第一次挺麻烦的，而且想推送到微信的话，要关注下企业二维码，否则只能在企业微信APP接收，比方糖方便的是代挂时候，不需要别人提供key了，关注下企业二维码就行了，

- 不需要下载企业微信app，只需要在企业微信网页就能获取获取 corpid的值,corpsecret的值,touser的值,agentid的值，素材库图片id。
- 只需要在通讯录里填入正确的绑定了微信的手机号就能默认把任何人拉入普通微信中的企业应用。
- 整个流程可以脱离企业微信app

**Comment by sxx1314** [comment]
> 我一脸懵，我扫描登录进入后，这些值(corpid的值,corpsecret的值,touser的值,agentid的值，素材库图片id)，好像也没看到，企业APP里面也没，不知道如何去拿获取？

登录网页版企业微信即可查询，并不用下载企业微信app。

**Comment by lxk0301** [comment]
> > 我一脸懵，我扫描登录进入后，这些值(corpid的值,corpsecret的值,touser的值,agentid的值，素材库图片id)，好像也没看到，企业APP里面也没，不知道如何去拿获取？
> 
> 登录网页版企业微信即可查询，并不用下载企业微信app。

那啥？  企业微信网页  是这个 https://work.weixin.qq.com/？
![image](https://user-images.githubusercontent.com/21308593/103734938-ede3ad80-5027-11eb-955d-43fe4b9ac043.png)

**Comment by sxx1314** [comment]
> > > 我一脸懵，我扫描登录进入后，这些值(corpid的值,corpsecret的值,touser的值,agentid的值，素材库图片id)，好像也没看到，企业APP里面也没，不知道如何去拿获取？
> > 
> > 
> > 登录网页版企业微信即可查询，并不用下载企业微信app。
> 
> 那啥？ 企业微信网页 是这个 https://work.weixin.qq.com/ ？
> ![image](https://user-images.githubusercontent.com/21308593/103734938-ede3ad80-5027-11eb-955d-43fe4b9ac043.png)

是的  几个值是分开的  
- 企业详情里找企业id  
- 创建应用之后查应用id和secret   
- user在联系人里其实可以写死为all，因为应用本身可以设置可见范围，所以推送时加个推送目标没什么意义。

**Comment by hclasmn** [comment]
> > > > 我一脸懵，我扫描登录进入后，这些值(corpid的值,corpsecret的值,touser的值,agentid的值，素材库图片id)，好像也没看到，企业APP里面也没，不知道如何去拿获取？
> > > 
> > > 
> > > 登录网页版企业微信即可查询，并不用下载企业微信app。
> > 
> > 
> > 那啥？ 企业微信网页 是这个 https://work.weixin.qq.com/ ？
> > ![image](https://user-images.githubusercontent.com/21308593/103734938-ede3ad80-5027-11eb-955d-43fe4b9ac043.png)
> 
> 是的 几个值是分开的
> 
> * 企业详情里找企业id
> * 创建应用之后查应用id和secret
> * user在联系人里其实可以写死为all，因为应用本身可以设置可见范围，所以推送时加个推送目标没什么意义。

推送目标目的是一个应用推送不同 消息给不同微信，比如代挂账号推送给别人的时候，不需要新建第二个应用，其它参数不变，换个目标就行了，怎么可以说没意义

**Comment by lxk0301** [comment]
> > > > 我一脸懵，我扫描登录进入后，这些值(corpid的值,corpsecret的值,touser的值,agentid的值，素材库图片id)，好像也没看到，企业APP里面也没，不知道如何去拿获取？
> > > 
> > > 
> > > 登录网页版企业微信即可查询，并不用下载企业微信app。
> > 
> > 
> > 那啥？ 企业微信网页 是这个 https://work.weixin.qq.com/ ？
> > ![image](https://user-images.githubusercontent.com/21308593/103734938-ede3ad80-5027-11eb-955d-43fe4b9ac043.png)
> 
> 是的 几个值是分开的
> 
> * 企业详情里找企业id
> * 创建应用之后查应用id和secret
> * user在联系人里其实可以写死为all，因为应用本身可以设置可见范围，所以推送时加个推送目标没什么意义。
> * media_id 看前面

我进入网址， 登录需要扫描，我用企业微信APP扫描登录后，提示什么   当前账号不是企业管理员

**Comment by sxx1314** [comment]
> > > > > 我一脸懵，我扫描登录进入后，这些值(corpid的值,corpsecret的值,touser的值,agentid的值，素材库图片id)，好像也没看到，企业APP里面也没，不知道如何去拿获取？
> > > > 
> > > > 
> > > > 登录网页版企业微信即可查询，并不用下载企业微信app。
> > > 
> > > 
> > > 那啥？ 企业微信网页 是这个 https://work.weixin.qq.com/ ？
> > > ![image](https://user-images.githubusercontent.com/21308593/103734938-ede3ad80-5027-11eb-955d-43fe4b9ac043.png)
> > 
> > 
> > 是的 几个值是分开的
> > 
> > * 企业详情里找企业id
> > * 创建应用之后查应用id和secret
> > * user在联系人里其实可以写死为all，因为应用本身可以设置可见范围，所以推送时加个推送目标没什么意义。
> 
> 推送目标目的是一个应用推送不同 消息给不同微信，比如代挂账号推送给别人的时候，不需要新建第二个应用，其它参数不变，换个目标就行了，怎么可以说没意义

就算是代挂

> > > > > 我一脸懵，我扫描登录进入后，这些值(corpid的值,corpsecret的值,touser的值,agentid的值，素材库图片id)，好像也没看到，企业APP里面也没，不知道如何去拿获取？
> > > > 
> > > > 
> > > > 登录网页版企业微信即可查询，并不用下载企业微信app。
> > > 
> > > 
> > > 那啥？ 企业微信网页 是这个 https://work.weixin.qq.com/ ？
> > > ![image](https://user-images.githubusercontent.com/21308593/103734938-ede3ad80-5027-11eb-955d-43fe4b9ac043.png)
> > 
> > 
> > 是的 几个值是分开的
> > 
> > * 企业详情里找企业id
> > * 创建应用之后查应用id和secret
> > * user在联系人里其实可以写死为all，因为应用本身可以设置可见范围，所以推送时加个推送目标没什么意义。
> > * media_id 看前面
> 
> 我进入网址， 登录需要扫描，我用企业微信APP扫描登录后，提示什么 当前账号不是企业管理员

你需要有企业权限。没有就重新建企业

> > > > > 我一脸懵，我扫描登录进入后，这些值(corpid的值,corpsecret的值,touser的值,agentid的值，素材库图片id)，好像也没看到，企业APP里面也没，不知道如何去拿获取？
> > > > 
> > > > 
> > > > 登录网页版企业微信即可查询，并不用下载企业微信app。
> > > 
> > > 
> > > 那啥？ 企业微信网页 是这个 https://work.weixin.qq.com/ ？
> > > ![image](https://user-images.githubusercontent.com/21308593/103734938-ede3ad80-5027-11eb-955d-43fe4b9ac043.png)
> > 
> > 
> > 是的 几个值是分开的
> > 
> > * 企业详情里找企业id
> > * 创建应用之后查应用id和secret
> > * user在联系人里其实可以写死为all，因为应用本身可以设置可见范围，所以推送时加个推送目标没什么意义。
> 
> 推送目标目的是一个应用推送不同 消息给不同微信，比如代挂账号推送给别人的时候，不需要新建第二个应用，其它参数不变，换个目标就行了，怎么可以说没意义

不介意 消息安全性问题可以混用。授予所有用户此应用权限之后就算没有推送也会获得其他敏感权限，不在意的可以无视。

**Comment by mengdie101** [comment]
企业微信机器人通知不能发送消息到个人微信，企业微信应用消息通知可以发送到个人微信通知，是这样吗

**Comment by EvineDeng** [comment]
> > 企业微信应用通知， 获取 corpid的值,corpsecret的值,touser的值,agentid的值，素材库图片id
> > 上面这些值 ， 需要登录。 然后登录需要下载企业微信APP才能扫描？
> 
> 是，第一次挺麻烦的，而且想推送到微信的话，要关注下企业二维码，否则只能在企业微信APP接收，比方糖方便的是代挂时候，不需要别人提供key了，关注下企业二维码就行了，

如果要从微信中收取通知，要关注企业二维码？是指在微信中关注企业的微信公众号还是什么？

**Comment by EvineDeng** [comment]
> > > > > 我一脸懵，我扫描登录进入后，这些值(corpid的值,corpsecret的值,touser的值,agentid的值，素材库图片id)，好像也没看到，企业APP里面也没，不知道如何去拿获取？
> > > > 
> > > > 
> > > > 登录网页版企业微信即可查询，并不用下载企业微信app。
> > > 
> > > 
> > > 那啥？ 企业微信网页 是这个 https://work.weixin.qq.com/ ？
> > > ![image](https://user-images.githubusercontent.com/21308593/103734938-ede3ad80-5027-11eb-955d-43fe4b9ac043.png)
> > 
> > 
> > 是的 几个值是分开的
> > 
> > * 企业详情里找企业id
> > * 创建应用之后查应用id和secret
> > * user在联系人里其实可以写死为all，因为应用本身可以设置可见范围，所以推送时加个推送目标没什么意义。
> 
> 推送目标目的是一个应用推送不同 消息给不同微信，比如代挂账号推送给别人的时候，不需要新建第二个应用，其它参数不变，换个目标就行了，怎么可以说没意义

如果3个账号在一组内，依次是Cookie1、Cookie2、Cookie3，他们也能分别只收到自己的账号消息么？还是只能和其他通知方式一样，每个人都收三个账号的消息？

**Comment by sxx1314** [comment]
> > > > > > 我一脸懵，我扫描登录进入后，这些值(corpid的值,corpsecret的值,touser的值,agentid的值，素材库图片id)，好像也没看到，企业APP里面也没，不知道如何去拿获取？
> > > > > 
> > > > > 
> > > > > 登录网页版企业微信即可查询，并不用下载企业微信app。
> > > > 
> > > > 
> > > > 那啥？ 企业微信网页 是这个 https://work.weixin.qq.com/ ？
> > > > ![image](https://user-images.githubusercontent.com/21308593/103734938-ede3ad80-5027-11eb-955d-43fe4b9ac043.png)
> > > 
> > > 
> > > 是的 几个值是分开的
> > > 
> > > * 企业详情里找企业id
> > > * 创建应用之后查应用id和secret
> > > * user在联系人里其实可以写死为all，因为应用本身可以设置可见范围，所以推送时加个推送目标没什么意义。
> > 
> > 
> > 推送目标目的是一个应用推送不同 消息给不同微信，比如代挂账号推送给别人的时候，不需要新建第二个应用，其它参数不变，换个目标就行了，怎么可以说没意义
> 
> 如果3个账号在一组内，依次是Cookie1、Cookie2、Cookie3，他们也能分别只收到自己的账号消息么？还是只能和其他通知方式一样，每个人都收三个账号的消息？

同组ck=同组user  所以一起推送   需要多ck不同user的直接多clone几个几个项目即可
