### ISSUE TITLE
疯狂的joy能否新增一个环境变量控制是否自动购买

### ISSUE THREAD

**Issue by wxjbb** [lxk0301/jd_scripts#520]
## 期望增加的功能

A：希望疯狂的joy可以选择是否自动购买，因为后期每次都会自动购买30级的，然而有时候其实买低等级更划算，应该由用户自己控制更好

## 入口

A：疯狂的joy

**Comment by lxk0301** [comment]
已有。自己看提交记录。有提供一个环境变量

**Comment by wxjbb** [comment]
看到了，BUY_JPY_LEVEL。如果设置为0，是否会取消自动购买？

**Comment by lxk0301** [comment]
> 看到了，BUY_JPY_LEVEL。如果设置为0，是否会取消自动购买？

设置为0的话。会去买0级的。由于没有这个会导致购买失败。差不多就达到了取消购买了

**Comment by wxjbb** [comment]
明白了，感谢

**Comment by lxk0301** [comment]
@wxjbb 环境变量名字改了一下。现在为
BUY_JOY_LEVEL

**Comment by wxjbb** [comment]
@lxk0301 OK，感谢提醒
