### ISSUE TITLE
京喜工厂和财富岛-建议取消【随机助力打工】，日常已有固定队友互助交换

### ISSUE THREAD

**Issue by helzaasd** [lxk0301/jd_scripts#522]
（重要事情已经说了十遍😅）
-->
 
## 期望增加的功能

A：京喜工厂和财富岛-建议增加取消【随机助力打工】的选项，因为日常已有固定朋友互助交换

**Comment by lxk0301** [comment]
说了很多遍。 随机的只是加在固定的后面。

你如果找了三个固定的人。只会给固定的人先助力。

**Comment by helzaasd** [comment]
收到，谢谢老哥




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lxk0301/jd_scripts"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年1月3日(星期天) 下午4:57
收件人:&nbsp;"lxk0301/jd_scripts"<jd_scripts@noreply.github.com&gt;;
抄送:&nbsp;"丨哈库丨"<912095709@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [lxk0301/jd_scripts] 京喜工厂和财富岛-建议取消【随机助力打工】，日常已有固定队友互助交换 (#522)





 
说了很多遍。 随机的只是加在固定的后面。
 
你如果找了三个固定的人。只会给固定的人先助力。
