### ISSUE TITLE
The appid is unavailable for legal reasons. 我的腾讯云账号被封了吗？

### ISSUE THREAD

**Issue by nssiwi** [lxk0301/jd_scripts#524]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [x] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：使用serverless部署的时候提示
` The appid is unavailable for legal reasons. (reqId: NWZmMWU1NGNfYmVhNzM4MDlfNDMzYV9mODBmNzQ=)`
B：采用上传方式部署后，测试的时候提示
`资源不可用.%!(EXTRA string=InsufficientBalance)`
### (2) 详细日志
如上

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by hjfmailbox** [comment]
猜测，应该是欠费了，你进腾讯云账单看看。
