### ISSUE TITLE
关于提示cookie失效的问题和boxjs无法保存ck cookie的问题

### ISSUE THREAD

**Issue by ycg31** [lxk0301/jd_scripts#525]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [x] 方法一：本地安装Node.js（使用github action部署） 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
问题1：我配置了2个账号在同一个action中运行，cookie使用&连接， 之前运行一直没有问题，昨天突然账号2开始提示cookie过期，但是签到可以正常执行，昨日京豆收益也能正常获取。 账号1签到和其他脚本运行均正常。
问题1排查：昨天重新获取了一下账号2的cookie填进去还是不行，签到和昨日京豆收益正常，其他脚本仍然提示cookie过期，我的cookie都是用野比大佬的脚本获取的。

问题2：因为是cookie的问题，就想用大佬你的脚本来获取，结果提示获取成功了，但是打开boxjs里面并没有cookie  刷新也没有

### (2) 详细日志
A：
中间出现如下错误提示：

"Response code 520 (Origin Error)"
京喜工厂 API请求失败，请检查网路重试

#### 我仔细检查了下日志，这个错误信息应该是获取电力中偶尔网络错误，应该不是问题所在

后面运行又成功了：

【京东账号2】ruochen88314
【生产商品】一转三插座
【当前等级】高级学徒 2
【生产进度】51.21%
【招工进度】0/8
【发电机电力】当前 91.1 电力，未达到收获标准
【每日任务】领奖成功，共计 0 电力
【投入电力】投入成功，共计 500 电力
【收取自己零件】获得7电力
【收取好友零件】获得541电力

### (1) Node.js版本

A：v12.20.0

### (2) npm版本

A： 6.14.8

### (3)npm install的日志

A：Run npm install
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm WARN deprecated request-promise@4.2.6: request-promise has been deprecated because it extends the now deprecated request package, see https://github.com/request/request/issues/3142
npm WARN deprecated axios@0.20.0: Critical security vulnerability fixed in v0.21.1. For more information, see https://github.com/axios/axios/pull/3410
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm notice created a lockfile as package-lock.json. You should commit this file.
added 224 packages from 214 contributors and audited 224 packages in 5.925s

17 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities

### 完整action  yaml文件

name: 京喜工厂
on:
    workflow_dispatch:
    schedule:
        - cron: "0 */1 * * *"
    watch:
        types: [started]
    repository_dispatch:
        types: jd_dreamFactory
jobs:
    build:
        runs-on: ubuntu-latest
        if: github.event.repository.owner.id == github.event.sender.id
        steps:
            - name: 拉取代码
              uses: actions/checkout@v2
            - name: Use Node.js
              uses: actions/setup-node@v1
              with:
                  node-version: "12.x"
            - name: 安装依赖包
              run: |
                  npm install
            - name: "运行【京喜工厂】"
              run: |
                  node jd_dreamFactory.js
              env:
                  JD_COOKIE: ${{ secrets.JD_COOKIE || github.event.client_payload.JD_COOKIE }}
                  JD_DEBUG: ${{ secrets.JD_DEBUG || github.event.client_payload.JD_DEBUG }}
                  JD_USER_AGENT: ${{ secrets.JD_USER_AGENT || github.event.client_payload.JD_USER_AGENT }}
                  PUSH_KEY: ${{ secrets.PUSH_KEY || github.event.client_payload.PUSH_KEY }}
                  BARK_PUSH: ${{ secrets.BARK_PUSH || github.event.client_payload.BARK_PUSH }}
                  BARK_SOUND: ${{ secrets.BARK_SOUND || github.event.client_payload.BARK_SOUND }}
                  TG_BOT_TOKEN: ${{ secrets.TG_BOT_TOKEN || github.event.client_payload.TG_BOT_TOKEN }}
                  TG_USER_ID: ${{ secrets.TG_USER_ID || github.event.client_payload.TG_USER_ID }}
                  DD_BOT_TOKEN: ${{ secrets.DD_BOT_TOKEN || github.event.client_payload.DD_BOT_TOKEN }}
                  DD_BOT_SECRET: ${{ secrets.DD_BOT_SECRET || github.event.client_payload.DD_BOT_SECRET }}
                  IGOT_PUSH_KEY: ${{ secrets.IGOT_PUSH_KEY || github.event.client_payload.IGOT_PUSH_KEY }}
                  QQ_SKEY: ${{ secrets.QQ_SKEY || github.event.client_payload.QQ_SKEY }}
                  QQ_MODE: ${{ secrets.QQ_MODE || github.event.client_payload.QQ_MODE }}
                  PUSH_PLUS_TOKEN: ${{ secrets.PUSH_PLUS_TOKEN || github.event.client_payload.PUSH_PLUS_TOKEN }}
                  PUSH_PLUS_USER: ${{ secrets.PUSH_PLUS_USER || github.event.client_payload.PUSH_PLUS_USER }}
                  DREAMFACTORY_NOTIFY_CONTROL: ${{ secrets.DREAMFACTORY_NOTIFY_CONTROL || github.event.client_payload.DREAMFACTORY_NOTIFY_CONTROL }}
                  DREAM_FACTORY_SHARE_CODES: ${{ secrets.DREAM_FACTORY_SHARE_CODES || github.event.client_payload.DREAM_FACTORY_SHARE_CODES }}

**Comment by lxk0301** [comment]
提示cookie过期 ，那就是cookie过期了，
我库里面的脚本在手机端获取的cookie是在我的boxjs订阅里面(多账号ck管理)， 不在野比的订阅里面。
还有过期可能是野比那边的订阅里面的cookie过期了

**Comment by ycg31** [comment]
> 提示cookie过期 ，那就是cookie过期了，
> 我库里面的脚本在手机端获取的cookie是在我的boxjs订阅里面(多账号ck管理)， 不在野比的订阅里面。
> 还有过期可能是野比那边的订阅里面的cookie过期了

我就是很纳闷 ，我现在手机使用野比的一键签到是可以正常签到的，说明账号2的cookie还可以使用，另外我就在你的boxjs订阅里面(多账号ck管理)找不到cookie   已经是用你的脚本获取的cookie了 我把野比的cookie获取禁用了的  而且提示的是首次获取成功。正常是刷新就应该有吧。

**Comment by ycg31** [comment]
我刚才把两个账号cookie换了下顺序，  手动执行了下东东工厂  又没提示cookie失效了

**Comment by ycg31** [comment]
@lxk0301  实在不好意思 耽搁你的时间了
找到原因了。 因为我之前在docker上运行着脚本，我手动停掉了，后面停电来电重启自动启动了，docker里面的cookie过期了，而docker我使用的通知是一样的，所以才一直提示，再次表示歉意。
