### ISSUE TITLE
京东超市兑换成功钉钉推送bug

### ISSUE THREAD

**Issue by Htle000333** [lxk0301/jd_scripts#529]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [x] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：京东超市兑换京豆成功后推送时昵称显示为null

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by lxk0301** [comment]
你的sendNotify.js里面用的是很久之前的版本了吧？脚本不是最新的？

我自己的正常

![image](https://user-images.githubusercontent.com/21308593/103516723-eeefd000-4eab-11eb-829a-e83c027d5e2f.png)

**Comment by Htle000333** [comment]
> 你的sendNotify.js里面用的是很久之前的版本了吧？脚本不是最新的？
> 
> 我自己的正常
> 
> ![图片](https://user-images.githubusercontent.com/21308593/103516723-eeefd000-4eab-11eb-829a-e83c027d5e2f.png)

用docker二 jd-base部署，这个容器是自动拉你最新的库，按道理应该不是旧版本

**Comment by Htle000333** [comment]
> 你的sendNotify.js里面用的是很久之前的版本了吧？脚本不是最新的？
> 
> 我自己的正常
> 
> ![图片](https://user-images.githubusercontent.com/21308593/103516723-eeefd000-4eab-11eb-829a-e83c027d5e2f.png)

之前设置从gitee同步的库，现在换github同步明天再看看是不是库的问题

**Comment by lxk0301** [comment]
这个gitee仓库（https://gitee.com/lxk0301/scripts/tree/master）是旧的。 不在更新


这个gitee仓库（https://gitee.com/lxk0301/jd_scripts/tree/master）目前是同步更新github此仓库
