### ISSUE TITLE
docker办法一，多账号cookie采用换行隔开，jdCookie.js读取到的只有一个cookie

### ISSUE THREAD

**Issue by WoChen5770** [lxk0301/jd_scripts#530]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [ x] 没有类似的issue 

Q：是否仔细阅读了教程
- [ x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [x ] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：
![image](https://user-images.githubusercontent.com/26268544/103514834-71769080-4ea8-11eb-9bc5-70b3f5060fdb.png)
我把cookie打印出来(console.log(`您的cookie:${process.env.JD_COOKIE}`);)是这样的:
您的cookie:pt_pin=******;pt_key=******oI5jANio; pt_pin=jd_******;pt_key=******Au9ZU; pt_pin=******ixi;pt_key=******1IY;
在两个账号的cookie之间是一个空格，比如第一个cookie结尾和第二个开头 “Nio; pt_pin=”中间是一个空格
导致后面的代码只能识别出第三个cookie，显示：====================共有1个京东账号Cookie=========

### (2) 详细日志
A：

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by WoChen5770** [comment]
![image](https://user-images.githubusercontent.com/26268544/103515541-daaad380-4ea9-11eb-84a2-1851481b9753.png)
如图，在第二和第三个cookie前加 &，能识别出三个cookie，但是每个cookie后多了一个空格。

**Comment by WoChen5770** [comment]
按照说明，cookie之间用&隔开，不换行的话是没有问题的。
而我想换行显示是因为换行能清楚一点，特别是后面的助力码。多个账号，每个账号有多个助力码的情况下看的眼花缭乱

**Comment by iouAkira** [comment]
@WoChen5770 多空个对你有啥影响，你觉得空格有影响就放到一行用`&`连接好了

**Comment by WoChen5770** [comment]
> @WoChen5770 多空个对你有啥影响，你觉得空格有影响就放到一行用`&`连接好了

上面我也说了，放一行对后面的助力码不好修改，多个账号多个助力码很长不好找
至于空格有没有影响，cookie那应该没影响，但是助力码后面也会加上空格，这个有没有影响就没有去验证

**Comment by iouAkira** [comment]
@WoChen5770 推荐你用docker办法2 ，那个配置方便明了

**Comment by WoChen5770** [comment]
> @WoChen5770 推荐你用docker办法2 ，那个配置方便明了
![image](https://user-images.githubusercontent.com/26268544/103516687-e3040e00-4eab-11eb-9979-a0493f19b4c4.png)
docker1，docker2我都有用，各有千秋。

**Comment by iouAkira** [comment]
@WoChen5770 既然都明白这个issue没有开着的必要了 docker1不支持换行cookies连接，也没有支持的意向。

**Comment by WoChen5770** [comment]
> @WoChen5770 既然都明白这个issue没有开着的必要了 docker1不支持换行cookies连接，也没有支持的意向。

既然你要这样说我也没办法，不就是加个判断的事。
if (process.env.JD_COOKIE.indexOf(' ') > -1) {
    console.log(`您的cookie选择的是用 (空格)隔开\n`)
    CookieJDs = process.env.JD_COOKIE.split(' ');
}

**Comment by iouAkira** [comment]
@WoChen5770 不要想当然，自己测试过了再说话。你能保证每个人都知道把cookies中间本身的空格去掉吗？

**Comment by WoChen5770** [comment]
> @WoChen5770 不要想当然，自己测试过了再说话。你能保证每个人都知道把cookies中间本身的空格去掉吗？

浪费时间，什么态度？
cookie就填了两个属性，是pt_pin里有空格还是pt_key里有空格？

**Comment by lxk0301** [comment]
> ![image](https://user-images.githubusercontent.com/26268544/103515541-daaad380-4ea9-11eb-84a2-1851481b9753.png)
> 如图，在第二和第三个cookie前加 &，能识别出三个cookie，但是每个cookie后多了一个空格。

这种多cookie，使用换行并且前面加上一个`&`的，cookie前面会多出一个空格？

**Comment by iouAkira** [comment]
@WoChen5770

**Comment by dot5sa** [comment]
我个人认为吧空格都不会去掉的人应该不合适玩这个。玩这个的目的就在于提高自己学习的动力，而不是单纯的撸羊毛，如果是单纯的过来撸羊毛，凭什么要求别人帮你完美的撸。

**Comment by iouAkira** [comment]
![image](https://user-images.githubusercontent.com/6993269/103518669-23b15680-4eaf-11eb-9612-729e30e7d4fc.png)
你能保证所有的cookies  是手机抓的并且去了空格的吗，

**Comment by WoChen5770** [comment]
> > ![image](https://user-images.githubusercontent.com/26268544/103515541-daaad380-4ea9-11eb-84a2-1851481b9753.png)
> > 如图，在第二和第三个cookie前加 &，能识别出三个cookie，但是每个cookie后多了一个空格。
> 
> 这种多cookie，使用换行并且前面加上一个`&`的，cookie前面会多出一个空格？

cookie后多了一个空格，前面不加&，那么每个空格使用空格隔开。
也可以这样说，换行在变量`process.env.JD_COOKIE`中被解析成了空格

**Comment by WoChen5770** [comment]
> > ![image](https://user-images.githubusercontent.com/26268544/103515541-daaad380-4ea9-11eb-84a2-1851481b9753.png)
> > 如图，在第二和第三个cookie前加 &，能识别出三个cookie，但是每个cookie后多了一个空格。
> 
> 这种多cookie，使用换行并且前面加上一个`&`的，cookie前面会多出一个空格？

我看代码中考虑的是`\\n`
 if (process.env.JD_COOKIE.indexOf('\\n') > -1) {
    //环境变量兼容腾讯云和docker下\n会被转义成\\n
    console.log(`您的cookie选择的是用换行隔开\n`)
    CookieJDs = process.env.JD_COOKIE.split('\\n');

**Comment by lxk0301** [comment]
> > @WoChen5770 既然都明白这个issue没有开着的必要了 docker1不支持换行cookies连接，也没有支持的意向。
> 
> 既然你要这样说我也没办法，不就是加个判断的事。
> if (process.env.JD_COOKIE.indexOf(' ') > -1) {
> console.log(`您的cookie选择的是用 (空格)隔开\n`)
> CookieJDs = process.env.JD_COOKIE.split(' ');
> }

这种加空格来作为分隔符的，一个空格和两个空格是不一样的，脚本解析出来是不一样的

**Comment by lxk0301** [comment]
> > > ![image](https://user-images.githubusercontent.com/26268544/103515541-daaad380-4ea9-11eb-84a2-1851481b9753.png)
> > > 如图，在第二和第三个cookie前加 &，能识别出三个cookie，但是每个cookie后多了一个空格。
> > 
> > 
> > 这种多cookie，使用换行并且前面加上一个`&`的，cookie前面会多出一个空格？
> 
> 我看代码中考虑的是`\\n`
> if (process.env.JD_COOKIE.indexOf('\n') > -1) {
> //环境变量兼容腾讯云和docker下\n会被转义成\n
> console.log(`您的cookie选择的是用换行隔开\n`)
> CookieJDs = process.env.JD_COOKIE.split('\n');

`\\n`其实是无用的。当初不知道以为有用

**Comment by WoChen5770** [comment]
> > > @WoChen5770 既然都明白这个issue没有开着的必要了 docker1不支持换行cookies连接，也没有支持的意向。
> > 
> > 
> > 既然你要这样说我也没办法，不就是加个判断的事。
> > if (process.env.JD_COOKIE.indexOf(' ') > -1) {
> > console.log(`您的cookie选择的是用 (空格)隔开\n`)
> > CookieJDs = process.env.JD_COOKIE.split(' ');
> > }
> 
> 这种加空格来作为分隔符的，一个空格和两个空格是不一样的，脚本解析出来是不一样的

空格是脚本解析出来的，我的意思是 把换行解析成了空格

**Comment by WoChen5770** [comment]
> ![image](https://user-images.githubusercontent.com/6993269/103518669-23b15680-4eaf-11eb-9612-729e30e7d4fc.png)
> 你能保证所有的cookies 是手机抓的并且去了空格的吗，

这个我不清楚，我的cookie是F12拿的，里面没空格

**Comment by iouAkira** [comment]
@WoChen5770 脚本解析出来的？建议去容器里面 env 看一下

**Comment by WoChen5770** [comment]
> @WoChen5770 脚本解析出来的？建议去容器里面 env 看一下

你怎么就这么肯定不是脚本解析成空格的呢？

**Comment by iouAkira** [comment]
@WoChen5770 因为我都测试过

**Comment by WoChen5770** [comment]
![image](https://user-images.githubusercontent.com/26268544/103519448-835c3180-4eb0-11eb-8c0c-4872887becf0.png)

**Comment by WoChen5770** [comment]
> @WoChen5770 因为我都测试过

我在上面也说过，我用console.log(`您的cookie:${process.env.JD_COOKIE}`);打印了，也是空格

**Comment by iouAkira** [comment]
@WoChen5770 process.env.JD_COOKIE 这个是什么意思你应该清楚的吧，这个不就是去找`env` ?

**Comment by WoChen5770** [comment]
@iouAkira 
![image](https://user-images.githubusercontent.com/26268544/103520297-e601fd00-4eb1-11eb-95c8-50f13c3cbf30.png)
是找的环境变量，但是我截图不是说环境变量JD_COOKIE里是空格隔开吗

**Comment by iouAkira** [comment]
@WoChen5770 你说脚本解析的，我说跟脚本没关系，因为 docker 带进去的，脚本就一个取值，哪来什么解析

**Comment by WoChen5770** [comment]
@iouAkira 我明白了，你是对我说 `脚本解析为空格`有意见吧？好吧我承认这是我的话造成的误会。
我换个方式说，js拿到的这个变量是空格

**Comment by WoChen5770** [comment]
@iouAkira 脚本解析是口误。我中间说的是 换行在变量process.env.JD_COOKIE中被解析成了空格
