### ISSUE TITLE
各位大佬们，云函数在哪填加互助码？

### ISSUE THREAD

**Issue by v889dguang** [lxk0301/jd_scripts#533]
纯小白，不知道的云函数在哪加互助码
 
## 期望增加的功能

A：

## 入口

A：

**Comment by lxk0301** [comment]
使用环境变量。或者具体的脚本里面

**Comment by chengwaiwucheng** [comment]
这几个脚本里面
jdDreamFactoryShareCodes.js
jdFactoryShareCodes.js
jdFruitShareCodes.js
jdPetShareCodes.js
jdPlantBeanShareCodes.js
jdSuperMarketShareCodes.js
