### ISSUE TITLE
单个docker-composer下添加多个账号的时候助力有问题

### ISSUE THREAD

**Issue by 25ma** [lxk0301/jd_scripts#534]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [x] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：单个docker-composer下添加多个账号的时候助力有问题，我一共添加了7个账号， 按照逻辑应该是可以互相助力的，但是更根据推送的消息看是没有多个账号互相助力的操作，

### (2) 详细日志
A：
![image](https://user-images.githubusercontent.com/16587521/103608032-51e97180-4f55-11eb-9db5-f75b28854db6.png)
助力次数都没有用，只用了一次，还不知道用在哪里？ 有点奇怪

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by lxk0301** [comment]
第一。农场一天就四次助力机会。现在剩下四次说明一次都没用掉。
第二：给哪些人助力，自己去看看运行日志，里面有详细记录。
另外：如果里面没有你提供的固定的队友的码，说明你没提供或者提供的码填写格式不对。

**Comment by 25ma** [comment]
1. 我全部都是使用&符号进行间隔的助力码
![image](https://user-images.githubusercontent.com/16587521/103609220-582d1d00-4f58-11eb-929b-4c29eb0fcb52.png)

2. 日志中 查找助力记录是：
![image](https://user-images.githubusercontent.com/16587521/103609415-cd005700-4f58-11eb-9738-60d5867c9167.png)

3. 但是没在我的配置中，有奇怪 ，可以看得出来根本没有走我的配置
![image](https://user-images.githubusercontent.com/16587521/103609477-f0c39d00-4f58-11eb-903c-5623b9574250.png)

**Comment by 25ma** [comment]
我就是随便挑了一个助力的，上面说的 京东农场助力也是一样的，都没有完成助力

**Comment by iouAkira** [comment]
日志显示看来，是没有识别到你的配置，所以才使用脚本内置的，建议在仔细阅读一下配置说明，
https://github.com/lxk0301/jd_scripts/blob/master/githubAction.md#%E4%BA%92%E5%8A%A9%E7%A0%81%E7%B1%BB%E7%8E%AF%E5%A2%83%E5%8F%98%E9%87%8F
![image](https://user-images.githubusercontent.com/6993269/103610103-43ea1f80-4f5a-11eb-8253-336052378591.png)

**Comment by 25ma** [comment]
如上图，我的配置有什么问题吗？ 还请解惑 谢谢

**Comment by 25ma** [comment]
还是说多个好友如果需要互相助力的话，就需要把所有账号放在某个账号下 比如：
code2@code3@code4@code5@code6&code1@code3@code4@code5@code6

以上填写的互助码是给 ： 账号1 和 账号2 助力的， 因为自己不能给自己助力， 所以其中不会包含自己账号下的互助码， 是需要这样配置吗？

**Comment by lxk0301** [comment]
> 如上图，我的配置有什么问题吗？ 还请解惑 谢谢

去查看docker的环境变量生效了嘛

![image](https://user-images.githubusercontent.com/21308593/103610586-806a4b00-4f5b-11eb-9e3b-f4cdaa0c7127.png)

**Comment by 25ma** [comment]
![image](https://user-images.githubusercontent.com/16587521/103610758-d3440280-4f5b-11eb-8864-c42604cc23fa.png)
是有的

**Comment by lxk0301** [comment]
改动过yml文件，每次都需 执行`docker-compose up -d`

**Comment by iouAkira** [comment]
> 还是说多个好友如果需要互相助力的话，就需要把所有账号放在某个账号下 比如：
> code2@code3@code4@code5@code6&code1@code3@code4@code5@code6
> 
> 以上填写的互助码是给 ： 账号1 和 账号2 助力的， 因为自己不能给自己助力， 所以其中不会包含自己账号下的互助码， 是需要这样配置吗？

例如你自己有3帐号想互相助力 `code2@code3&code1@code3&code1@code2` 这样能明白吗，我上一条回复的连接仔细阅读都有说明的

**Comment by 25ma** [comment]
我是在windows 10 电脑上部署的 docker 环境

**Comment by iouAkira** [comment]
> 改动过yml文件，每次都需 执行`docker-compose up -d`

他应该是格式写错了，他连接让他再仔细读一遍

**Comment by 25ma** [comment]
> 改动过yml文件，每次都需 执行`docker-compose up -d`

是的 每次都有 执行 docker-compose up -d 操作

**Comment by 25ma** [comment]
> > 改动过yml文件，每次都需 执行`docker-compose up -d`
> 
> 他应该是格式写错了，所以我给他连接让他再仔细读一遍

我有7个账号，格式也发出来， 我的助力码是复制 sharecode.log 这个日志文件里面的

**Comment by 25ma** [comment]
> > 还是说多个好友如果需要互相助力的话，就需要把所有账号放在某个账号下 比如：
> > code2@code3@code4@code5@code6&code1@code3@code4@code5@code6
> > 以上填写的互助码是给 ： 账号1 和 账号2 助力的， 因为自己不能给自己助力， 所以其中不会包含自己账号下的互助码， 是需要这样配置吗？
> 
> 例如你自己有3帐号想互相助力 `code2@code3&code1@code3&code1@code2` 这样能明白吗，我上一条回复的连接仔细阅读都有说明的

大概明白你的意思了， 如果有多个账号，就需要把多个账号的助力码使用@符号连接起来，然后用&符号间隔这些助力码用于哪个账号 对吧

**Comment by iouAkira** [comment]
> > > 还是说多个好友如果需要互相助力的话，就需要把所有账号放在某个账号下 比如：
> > > code2@code3@code4@code5@code6&code1@code3@code4@code5@code6
> > > 以上填写的互助码是给 ： 账号1 和 账号2 助力的， 因为自己不能给自己助力， 所以其中不会包含自己账号下的互助码， 是需要这样配置吗？
> > 
> > 
> > 例如你自己有3帐号想互相助力 `code2@code3&code1@code3&code1@code2` 这样能明白吗，我上一条回复的连接仔细阅读都有说明的
> 
> 大概明白你的意思了， 如果有多个账号，就需要把多个账号的助力码使用@符号连接起来，然后用&符号间隔这些助力码用于哪个账号 对吧

对的，我发的连接里面找找应该也是有说明的和事例的

**Comment by 25ma** [comment]
> > > > 还是说多个好友如果需要互相助力的话，就需要把所有账号放在某个账号下 比如：
> > > > code2@code3@code4@code5@code6&code1@code3@code4@code5@code6
> > > > 以上填写的互助码是给 ： 账号1 和 账号2 助力的， 因为自己不能给自己助力， 所以其中不会包含自己账号下的互助码， 是需要这样配置吗？
> > > 
> > > 
> > > 例如你自己有3帐号想互相助力 `code2@code3&code1@code3&code1@code2` 这样能明白吗，我上一条回复的连接仔细阅读都有说明的
> > 
> > 
> > 大概明白你的意思了， 如果有多个账号，就需要把多个账号的助力码使用@符号连接起来，然后用&符号间隔这些助力码用于哪个账号 对吧
> 
> 对的，我发的连接里面找找应该也是有说明的和事例的

好的 ， 谢谢

**Comment by lxk0301** [comment]
@25ma 问题解决了？

**Comment by 25ma** [comment]
> @25ma 问题解决了？

我昨晚下班后重新修改配置，今天的助力可以了，我还准备优化优化，弄成同时启动多个docker 来并发执行任务 
因为我的账号太多了，修改配置非常不方便

**Comment by lxk0301** [comment]
@25ma docker 方法一里面有多个来并发运行的
