### ISSUE TITLE
Bark APP发送通知调用API失败

### ISSUE THREAD

**Issue by hecarli555** [lxk0301/jd_scripts#543]
Bark APP发送通知调用API失败，这是什么问题呢？貌似是前段时间出现的，用的是苹果的bark app，望大佬修复一下

**Comment by lxk0301** [comment]
话都不说清楚。修什么？

**Comment by hecarli555** [comment]
> 话都不说清楚。修什么？


> 话都不说清楚。修什么？

就是bark执行推送的时候提示“Bark APP发送通知调用API失败”，不能推送签到情况汇报了，请问这个问题怎么解决？

**Comment by lxk0301** [comment]
。。。。。。。。。。。。
什么运行环境

哪个脚本执行的

就算是推送失败， 也有打印的log


你给了我什么？？你这几句话， 我怎么看 ？我又不是神仙

**Comment by lxk0301** [comment]
哪个issue模板不是用来好看的

**Comment by hecarli555** [comment]
> 哪个issue模板不是用来好看的

![image](https://user-images.githubusercontent.com/76683744/103852131-38c3fa80-50e6-11eb-873a-5b81102f134c.png)
群辉的docker运行的qiandao

**Comment by lxk0301** [comment]
。。。
jd_bean_sign.js运行的？？

**Comment by hecarli555** [comment]
> 。。。
> jd_bean_sign.js运行的？？

对的对的。。。就是这个运行，小白一名，表达可能不太清楚，望大佬见谅，附上日志文件
[jd_bean_sign.log](https://github.com/lxk0301/jd_scripts/files/5779648/jd_bean_sign.log)

**Comment by lxk0301** [comment]
不用了， 我知道什么原因了，这个签到的推送日志太长，

目前Bark APP推送通知消息对推送内容长度有限制，太长会导致推送通知失败

还有就是之前我有做处理(如推送通知方式中包含BARK APP推送方式脚本会默认转换成简洁内容推送) 。 后面改了一点东西， 导致这个处理失效了。

**Comment by lxk0301** [comment]
你5分钟后， 更新脚本再次运行，应该bark app推送就会成功了
