### ISSUE TITLE
大佬小米运动可以添加一天运行两次吗

### ISSUE THREAD

**Issue by jinp5822** [lxk0301/jd_scripts#546]
大佬可以把小米运动的脚本添加比如上午运行7000到10000步的 到了晚上在次运行10000到15000步这样的功能吗

**Comment by jinp5822** [comment]
@lxk0301 大佬来看下这个功能可以实现吗

**Comment by lxk0301** [comment]
你这骚操作的目的何在？

**Comment by sgzman** [comment]
我现在刷步数号更新微信运动不行了，不知道为啥

**Comment by lxk0301** [comment]
> 我现在刷步数号更新微信运动不行了，不知道为啥

注销清除小米运动数据后。再重新关联绑定

**Comment by lxk0301** [comment]
进入小米运动 APP 点 - 我的 - 设置 - 账号与安全 - 点注销账号 - 点清除数据
公众号再取关
等 30 分钟后，在重新绑定需要同步的应用，即可继续使用刷步数
