### ISSUE TITLE
取关店铺中 0不起作用

### ISSUE THREAD

**Issue by wulove** [lxk0301/jd_scripts#547]
取关店铺中 0不起作用：
jd_unsubscribe.js中let goodPageSize = $.getdata('jdUnsubscribePageSize') || 20;// 运行一次取消多少个已关注的商品。数字0表示不取关任何商品；
goodPageSize 不会等于0，UN_SUBSCRIBES设置为0&0&&时，实际goodPageSize 会等于20

**Comment by lxk0301** [comment]
UN_SUBSCRIBES设置为0&0&&

拿到的其实是 字符串的'0' ，所以 goodPageSize 就是 等于 '0'，而不是 20

并不存在你说的bug

![image](https://user-images.githubusercontent.com/21308593/103877020-74bf8580-510f-11eb-8001-735e3bfea1b2.png)

**Comment by lxk0301** [comment]
环境变量设置的数字 ，脚本拿到的都是字符串， 而不是数字
