### ISSUE TITLE
yml添加了 为什么有些有actions 有些没有呢。。

### ISSUE THREAD

**Issue by twogenchen** [lxk0301/jd_scripts#55]
弄了一中午没搞明白 同样添加了yml
为什么有些会没有actions 修改保存yml也无效。
还有一个问题就是 比如新增了pigpet.js 我复制粘贴一个yml修改里面的把里面对应的脚本替换成pigpet 但是运行的时候又提示我requireConfig未定义又该怎么处理。。。

**Comment by HenryTSZ** [comment]
jd_moneyTree 提示:

> No results matched your search.
> Try broadening your search filters.

但明明有这个文件啊

**Comment by ScareTigerDeceiveHu** [comment]
动作的话、yml文件里面，把大佬的仓库地址，换成你自己的。
新js的话，你可以看看每个yml文件里面对比下、拿来相应的改里面的名称和调用js就行。


> 弄了一中午没搞明白 同样添加了yml
> 为什么有些会没有actions 修改保存yml也无效。
> 还有一个问题就是 比如新增了pigpet.js 我复制粘贴一个yml修改里面的把里面对应的脚本替换成pigpet 但是运行的时候又提示我requireConfig未定义又该怎么处理。。。

**Comment by lxk0301** [comment]
> 弄了一中午没搞明白 同样添加了yml
> 为什么有些会没有actions 修改保存yml也无效。
> 还有一个问题就是 比如新增了pigpet.js 我复制粘贴一个yml修改里面的把里面对应的脚本替换成pigpet 但是运行的时候又提示我requireConfig未定义又该怎么处理。。。

因为你当时脚本不是最新的
