### ISSUE TITLE
docker1部署下，全部账号显示API请求失败

### ISSUE THREAD

**Issue by lplbb** [lxk0301/jd_scripts#550]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [X] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：
云服务器下的所有在跑的账号的脚本全部API请求失败
### (2) 详细日志
A：京东签到日志：
Jan 08 00:00:58 ==================脚本执行- 北京时间(UTC+8)：2021-1-8 12:00:58 ├F10: AM┤=====================
Jan 08 00:00:58 
Jan 08 00:02:07 {"name":"RequestError","code":"EAI_AGAIN","timings":{"start":1610035325239,"socket":1610035325239,"lookup":1610035327239,"error":1610035327239,"phases":{"wait":0,"dns":2000,"total":2000}}}
Jan 08 00:02:07 检测到您不能访问外网,将使用CDN下载JD_DailyBonus.js文件
Jan 08 00:02:19 文件下载异常:RequestError: getaddrinfo EAI_AGAIN cdn.jsdelivr.net
Jan 08 00:02:19 
Jan 08 00:02:19 🔔京豆签到, 开始!
Jan 08 00:02:19 
Jan 08 00:02:19 ❗️京豆签到, 错误!
Jan 08 00:02:19 Error: ENOENT: no such file or directory, open './JD_DailyBonus.js'
Jan 08 00:02:19     at Object.openSync (fs.js:462:3)
Jan 08 00:02:19     at Object.readFileSync (fs.js:364:35)
Jan 08 00:02:19     at /scripts/jd_bean_sign.js:37:28
Jan 08 00:02:19     at processTicksAndRejections (internal/process/task_queues.js:97:5)
Jan 08 00:02:19 
Jan 08 00:02:19 🔔京豆签到, 结束! 🕛 91.392 秒

天天提鹅：
Jan 08 00:18:05 
Jan 08 00:18:07 {"name":"RequestError","code":"EAI_AGAIN","timings":{"start":1610036285029,"socket":1610036285030,"lookup":1610036287029,"error":1610036287029,"phases":{"wait":1,"dns":1999,"total":2000}}}
Jan 08 00:18:07 天天提鹅 API请求失败，请检查网路重试
Jan 08 00:18:09 {"name":"RequestError","code":"EAI_AGAIN","timings":{"start":1610036287032,"socket":1610036287032,"lookup":1610036289032,"error":1610036289032,"phases":{"wait":0,"dns":2000,"total":2000}}}
Jan 08 00:18:09 天天提鹅 API请求失败，请检查网路重试
Jan 08 00:18:11 {"name":"RequestError","code":"EAI_AGAIN","timings":{"start":1610036289039,"socket":1610036289039,"lookup":1610036291705,"error":1610036291705,"phases":{"wait":0,"dns":2666,"total":2666}}}
Jan 08 00:18:11 天天提鹅 API请求失败，请检查网路重试
Jan 08 00:18:11 
Jan 08 00:18:11 🔔天天提鹅, 结束! 🕛 10.067 秒

这里只列举了一个号的两个脚本的日志，实际上其他所有脚本也都是这样的报错，其他在跑的账号也是这样

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by lplbb** [comment]
Jan 08 06:05:22 20支衣架种植中...
Jan 08 06:05:22 
Jan 08 06:05:22 
Jan 08 06:05:22 初始化任务列表
Jan 08 06:05:23 开始签到
Jan 08 06:05:24 【签到成功】获得20g??\n
Jan 08 06:05:24 被水滴砸中： 否
Jan 08 06:05:24 签到结束,开始广告浏览任务
Jan 08 06:05:24 正在进行广告浏览任务: 每日签到抢888京豆
Jan 08 06:05:25 每日签到抢888京豆浏览任务完成
Jan 08 06:05:26 领取浏览每日签到抢888京豆广告奖励成功,获得5g
Jan 08 06:05:26 正在进行广告浏览任务: 9.9元5斤怀化冰糖橙
Jan 08 06:05:27 9.9元5斤怀化冰糖橙浏览任务完成
Jan 08 06:05:28 领取浏览9.9元5斤怀化冰糖橙广告奖励成功,获得5g
Jan 08 06:05:28 正在进行广告浏览任务: 品质母婴
Jan 08 06:05:29 品质母婴浏览任务完成
Jan 08 06:05:29 {"name":"HTTPError","timings":{"start":1610057109954,"socket":1610057109955,"lookup":1610057110025,"connect":1610057110183,"upload":1610057110183,"response":1610057129884,"end":1610057129892,"phases":{"wait":1,"dns":70,"tcp":158,"request":0,"firstByte":19701,"download":8,"total":19938}}}
Jan 08 06:05:29 东东农场 API请求失败，请检查网路重试
Jan 08 06:05:30 领取浏览品质母婴广告奖励成功,获得5g
Jan 08 06:05:30 正在进行广告浏览任务: 每日领88元年货补贴
Jan 08 06:05:31 每日领88元年货补贴浏览任务完成
Jan 08 06:05:32 领取浏览每日领88元年货补贴广告奖励成功,获得5g
Jan 08 06:05:32 正在进行广告浏览任务: 最高领10元红包
Jan 08 06:05:33 最高领10元红包浏览任务完成
Jan 08 06:05:34 领取浏览最高领10元红包广告奖励成功,获得5g
Jan 08 06:05:34 正在进行广告浏览任务: 农场升级补偿奖励
Jan 08 06:05:35 农场升级补偿奖励浏览任务完成
Jan 08 06:05:36 领取浏览农场升级补偿奖励广告奖励成功,获得20g
Jan 08 06:05:36 正在进行广告浏览任务: 炸鸡满199减60

发现自7号以来，京东农场和京东萌宠等小游戏的日志没有报错。

**Comment by lplbb** [comment]
最新更新：
发现所有在0-2点运行的脚本都会API请求失败
而除此之外的其他时间段都正常运行

总结：改一下my_my_crontab_list.sh配置里的时间

**Comment by iouAkira** [comment]
@lplbb 这是你的网络问题吧

**Comment by lplbb** [comment]
> @lplbb这是你的网络问题吧

设置在凌晨0-2点的运行脚本日志确实是报的网络问题，已经连续两天都是这样了，但是其他时间又好好的不知道是什么原因。
1月8日00:02:07检测到您不能访问外网，将使用CDN下载JD_DailyBonus.js文件------------jd_bean_sign其中的报错日志

**Comment by lplbb** [comment]
阿里云一直都开着的，按理说不应该呀

**Comment by iouAkira** [comment]
@lplbb 发工单问问阿里云，宿主可以弄个脚本记录一下0-2的网络请求任务。

**Comment by lplbb** [comment]
好

**Comment by lplbb** [comment]
阿里云官方回答
您好 ，如附件，分析日志发现在有因为内存溢出导致您的容器进程被kill的情况，目前看主机的内存已经恢复正常，建议您那边配置下虚拟内存缓解下内存的压力再观察下，同时建议您那边观察下内存的监控情况，当内存跑高的时候，登录服务器通过top等命令进行分析看下内存跑高的原因

**Comment by lplbb** [comment]
我估计是crazyjoy的挂机没有清干净导致每一次重启容器后吃的内存越来越多

**Comment by laoyuan863** [comment]
贵方：你好！信息收到，怎样才能处理好，尚未完全掌握其方法，若能远程协助处理最好，期待回复谢谢🙏

lplbb <notifications@github.com>于2021年1月10日 周日01:21写道：
