### ISSUE TITLE
京喜工厂部分功能失效

### ISSUE THREAD

**Issue by Naivev** [lxk0301/jd_scripts#556]
更新了最新的脚本

翻倍领取电力正常了
浏览任务部分失效了，手动正常
打工电力失效，手动正常
零件收取失效，手动正常
![image](https://user-images.githubusercontent.com/45974159/104082144-a307a700-526e-11eb-9239-01f5596b9b41.png)

**Comment by 345784078** [comment]
好像都这样了

**Comment by lxk0301** [comment]
我自己有个账号也这样子。其他账号正常

**Comment by lxk0301** [comment]
已解决

**Comment by kissfast** [comment]
2个号，第一个号同样的情况，第二个号正常。
什么情况呢？
