### ISSUE TITLE
京东赚赚、东东工厂、京喜工厂、疯狂的joy的互助码有环境变量吗

### ISSUE THREAD

**Issue by 627992512** [lxk0301/jd_scripts#559]
## 期望增加的功能

A：京东赚赚、东东工厂、京喜工厂、疯狂的joy的互助码的环境变量

## 入口

A：大佬，京东赚赚、东东工厂、京喜工厂、疯狂的joy的互助码有环境变量吗？

**Comment by lxk0301** [comment]
环境变量聚合里面有

**Comment by lxk0301** [comment]
不看readme就在这里问？

上面写的明明白白
