### ISSUE TITLE
微信收到推送：东东工厂cookie已失效 - null，可是cookie当前是生效的

### ISSUE THREAD

**Issue by Smart-Pikachu** [lxk0301/jd_scripts#581]
微信收到如下推送：
东东工厂cookie已失效 - null
京东账号1 null
请重新登录获取cookie
可是检查Docker的log，显示做任务是正常的，但是结束的时候获取返回结果的时候出现报错。
脚本：jd_jdfactory.js
这个是什么原因呢？

**Comment by Smart-Pikachu** [comment]
![3](https://user-images.githubusercontent.com/46123873/104145742-222de400-5403-11eb-8d35-ef4e298cc143.png)
![2](https://user-images.githubusercontent.com/46123873/104145746-2528d480-5403-11eb-936f-20d04230593b.png)
![1](https://user-images.githubusercontent.com/46123873/104145748-2823c500-5403-11eb-831d-29da7f778739.png)

**Comment by Smart-Pikachu** [comment]
种豆得豆也有类似问题，微信收到推送种豆得豆cookie已失效 null
但是检查dock的日志，显示脚本是成功执行的。
可能报错源自于API的报错网络问题。

[jd_plantBean.js]: 京东种豆得豆 API请求失败，请检查网路重试
[jd_plantBean.js]: 助力结果的code:0

**Comment by Smart-Pikachu** [comment]
好像所有脚本豆出现这个问题，微信均推送cookie失效，但是日志里面显示API查询请求失败，然后微信就推送cookie失效

[jd_joy.js]: 京东宠汪汪: API查询请求失败 ‼️‼️

**Comment by lxk0301** [comment]
根据仅有的有效信息，无法判断与解决。建议重新跑一次试试看

**Comment by Smart-Pikachu** [comment]
> 根据仅有的有效信息，无法判断与解决。建议重新跑一次试试看

我是根据docker3 进行配置的，重新执行 git pull 以及 docker-compose up --build --force-recreate --detach jd1 后依然出现这个情况。
基本上在所有脚本执行完之后，都会有下面的API请求失败，请检查网路重试的消息。
只要日志里面出现这个消息，微信就会接收到如下信息，可是进JD客户端检查是进行了脚本上的操作的。

京东种豆得豆cookie已失效 - null
京东账号1 null
请重新登录获取cookie


[jd_plantBean.js]: 免费水果 任务已完成
[jd_plantBean.js]: 
[jd_plantBean.js]: {"name":"HTTPError","timings":{"start":1610355603164,"socket":1610355603165,"lookup":1610355603169,"connect":1610355603176,"upload":1610355603176,"response":1610355630373,"end":1610355630396,"phases":{"wait":1,"dns":4,"tcp":7,"request":0,"firstByte":27197,"download":23,"total":27232}}}
[jd_plantBean.js]: 京东种豆得豆 API请求失败，请检查网路重试
[jd_plantBean.js]: 暂无扭蛋机会

**Comment by Smart-Pikachu** [comment]
> 根据仅有的有效信息，无法判断与解决。建议重新跑一次试试看

单独在Docker里面使用代码：docker exec jd1 bash -c 'set -o allexport; source /all; source /env; source /jd-scripts-docker/resolve.sh; cd /scripts; node jd_jdfactory.js' 调用脚本可以正常执行，不会再执行完成之后跳出API超时的报错，但是docker在crontab定时执行的时候会有API超时的报错，推送的报错为cookies失效。

京东账号1jd_XXX
京东账号1 jd_XXX
已选商品：蔡司屏幕清洁湿巾30片装
当前已投入电量/所需电量：282127/880000
已选商品剩余量：609
当前总电量：311740
当前完成度：35%


??东东工厂, 结束! ?? 17.106 秒

随机取20个码放到您固定的互助码后面(不影响已有固定互助)
[root@45 jd-scripts-docker]#

**Comment by iouAkira** [comment]
@Smart-Pikachu 我记得docker3不是因为夹带私货已经移除文档链接了吗？

**Comment by Smart-Pikachu** [comment]
> @Smart-Pikachu 我记得docker3不是因为夹带私货已经移除文档链接了吗？

你看Wiki里面，选docker ，里面还有Docker3的链接啊·····那Docker3我还能不能用啊···

**Comment by Smart-Pikachu** [comment]
找到原因了.
部署Docker3 的时候自动把三个docker都起来了，但是 env2 和env3 里面都是没有配置cookie的。
当前已经手工把 jd2 和jd3 关闭了。
监控了一会，没有推送cookie失败的消息了。
这个问题可以关闭了，谢谢。
