### ISSUE TITLE
京喜农场token问题

### ISSUE THREAD

**Issue by zglzw** [lxk0301/jd_scripts#582]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [ ] 方法三：Docker办法一
- [x] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：使用ios上的Thor软件成功抓取到了farm_jstoken，timestamp，phoneid，并按照格式填入了config.sh文件中，结果运行脚本后仍然提示请参考头部说明获取token或者改中非app专属种子。

### (2) 详细日志
A：开始第1个任务：每日签到
每日签到[做任务]：ret:1032 retmsg:"err operate env"
任务执行失败，种植的 APP 专属种子，请提供 token 或种植非 APP 种子

==============📣系统通知📣==============
京喜农场
请参考脚本头部说明获取token
或者改中非app专属种子，点击通知跳转
您未提供push+推送所需的PUSH_PLUS_TOKEN，取消push+推送消息通知

server酱发送通知消息成功

### (1) Node.js版本

A：v14.15.3

### (2) npm版本

A：6.14.9

### (3)npm install的日志

A：

**Comment by Mr-zhaohy** [comment]
same issue

**Comment by sxx1314** [comment]
？？？楼主怎么解决的

**Comment by zglzw** [comment]
https://github.com/EvineDeng/jd-base/issues/200，FanchangWang大佬说已经提交了pr

**Comment by FanchangWang** [comment]
代码已提交修复，请拉取一下代码再试试

**Comment by FanchangWang** [comment]
具体修复内容可见 pr #583
