### ISSUE TITLE
通知

### ISSUE THREAD

**Issue by qiaoborui** [lxk0301/jd_scripts#590]
## 期望增加的功能

A：通知发送时，添加用户名#tag，方便telegram频道检索

## 入口

A：

**Comment by lxk0301** [comment]
所以有什么用？

就全部类型的通知都有

**Comment by lxk0301** [comment]
@lxk0301 而且 需要每个脚本去修改。工作量大   我是不可能去弄的

**Comment by qiaoborui** [comment]
> 所以有什么用？
> 
> 
> 
> 就全部类型的通知都有

我想的是如果有多个cookie，放在同一频道，可以让cookie的主人根据tag检索他们的相关通知

**Comment by sxx1314** [comment]
> > 所以有什么用？
> > 就全部类型的通知都有
> 
> 我想的是如果有多个cookie，放在同一频道，可以让cookie的主人根据tag检索他们的相关通知

你还是自己多clone几个项目吧，多cookie匹配不同通知每个脚本都得修改，另外竟然都多通知了直接不同推送频道/应用不是更香。所以你还是多clone几个项目即可。
