### ISSUE TITLE
5个账号，3个显示异常是什么问题呢？

### ISSUE THREAD

**Issue by kzy3568** [lxk0301/jd_scripts#596]
开始【京东账号5】丽啊666

第1页: {"code":"0","detailList":[{"date":"2021-01-11 19:01:58","amount":"50","eventMassage":"东东农场"}]}
第2页: {"code":"0","detailList":[]}

==============📣系统通知📣==============
京豆变动通知
账号5：丽啊666
数据异常
try{QueryExpireJingdou({"errmsg":"","expirejingdou":[{"expireamount":0,"time":1610380799},{"expireamount":0,"time":1610467199},{"expireamount":0,"time":1610553599},{"expireamount":0,"time":1610639999},{"expireamount":0,"time":1610726399},{"expireamount":0,"time":1610812799},{"expireamount":0,"time":1610899199}],"ret":0}
);}catch(e){}

**Comment by lxk0301** [comment]
@kzy3568 再跑一次。获取去app上查看一下

**Comment by kzy3568** [comment]
> @kzy3568 再跑一次。获取去app上查看一下

跑了很多次了，APP里面手动点得花都正常。就是脚本就是3个异常，好奇怪

**Comment by lxk0301** [comment]
明天再看吧。反正现在是你账号返回的数据异常

**Comment by kzy3568** [comment]
> 明天再看吧。反正现在是你账号返回的数据异常

好的，谢谢！那3个是我新增得账号对这个有什么要求吗？
