### ISSUE TITLE
能不能把NobyDa京东签到jd_bean_sign.js文件弄成本地调用，不从远程下载了，以后需要更新文件，自己手动拉取放在文件夹里

### ISSUE THREAD

**Issue by treatself** [lxk0301/jd_scripts#60]
能不能把NobyDa京东签到jd_bean_sign.js文件弄成本地调用，不从远程下载了，以后需要更新文件，自己手动拉取放在文件夹里

**Comment by lxk0301** [comment]
@treatself 现在本来就是每次运行下载放到本地调用的

**Comment by treatself** [comment]
我的意思是连运行时那个下载过程都去掉，直接把文件手动弄过来放项目里，云函数那边运行的时候就不需要再保存什么了。

**Comment by kifast** [comment]
> 我的意思是连运行时那个下载过程都去掉，直接把文件手动弄过来放项目里，云函数那边运行的时候就不需要再保存什么了。

明白你意思,把下载文件 与 删除文件注释掉就可以了

` 
 // 下载最新代码
  await downFile();

console.log('运行完成后，删除下载的文件\n')
 await deleteFile(path);//删除result.
await deleteFile(JD_DailyBonusPath);//删除JD_DailyBonus.js

`

**Comment by lxk0301** [comment]
> 我的意思是连运行时那个下载过程都去掉，直接把文件手动弄过来放项目里，云函数那边运行的时候就不需要再保存什么了。

行不通，你没明白我脚本的机制

**Comment by kifast** [comment]
我确实是简单的看了一下, 以为是下载脚本后,替换了一下cookeis 就可以执行了
如果运行过一次,再把下载与删除脚本的代码给注释了,
应该可以达到他本地执行的要求 , 只是脚本不能自动更新而已.
不知理解是否正确

**Comment by danwangshimoluo** [comment]
> 我确实是简单的看了一下, 以为是下载脚本后,替换了一下cookeis 就可以执行了
> 如果运行过一次,再把下载与删除脚本的代码给注释了,
> 应该可以达到他本地执行的要求 , 只是脚本不能自动更新而已.
> 不知理解是否正确

好像确实不行，他这个签到文件执行的时候需要替换cookies，替换的时候需要写入操作，云函数还是不允许写入，除非重写签到机制。

**Comment by treatself** [comment]
好像确实不行，他这个签到文件执行的时候需要替换cookies，替换的时候需要写入操作，云函数还是不允许写入，除非重写签到机制。

**Comment by lxk0301** [comment]
@danwangshimoluo 云函数有一个虚拟的tmp文件。可以进行读写

具体见

https://github.com/lxk0301/jd_scripts/issues/26#issuecomment-725361747
