### ISSUE TITLE
发现一个领豆的地方[发现好货]

### ISSUE THREAD

**Issue by lyx32** [lxk0301/jd_scripts#622]
## 期望增加的功能

A：
领取京豆

## 入口

A：
在app「首页」下面一点有一个「发现好货」，右下角有一个「领京豆图标」，然后点击点击「加入心愿单」，就能得到京豆
1月7号 至 1月19号每人每天3次机会。每次最多1个豆子
1月20号 至 2月5号 每人每天10次机会。每次最多1个豆子
2月6号 至 2月10号 每人每天3次机会。每次最多1个豆子
豆子时限180天

**Comment by sgzman** [comment]
这个早就有了，最猛的时候一天10此机会，每次5豆

**Comment by lyx32** [comment]
> 
> 
> 这个早就有了，最猛的时候一天10此机会，每次5豆

好尴尬。。。

**Comment by lxk0301** [comment]
做不了脚本。不过有iOS捷径

**Comment by nick814** [comment]
> 做不了脚本。不过有iOS捷径

大佬 哪个捷径啊

**Comment by lxk0301** [comment]
> > 做不了脚本。不过有iOS捷径
> 
> 大佬 哪个捷径啊

京东心愿单50豆捷径版本(非task脚本), 一次没做完就再点一次。

兼容  IOS13-14
-----------------------------
💁🏻‍♂️作者: shylocks，github同名，欢迎star

https://www.icloud.com/shortcuts/9b0f635311ae4a03ab8321f116bdec14
