### ISSUE TITLE
建议关闭Issue功能

### ISSUE THREAD

**Issue by gcdd1993** [lxk0301/jd_scripts#63]
关闭Issue，建立TG群组或微信群讨论相关事宜，减少公开讨论，有助于长期发展

纯属个人建议 @lxk0301

**Comment by lxk0301** [comment]
考虑中，

群组有，不过不是国内的，

https://t.me/JD_fruit_pet

**Comment by hacken156026692** [comment]
see you later，是怎么回事？归隐闭关了吗？-_-||^_^

**Comment by lxk0301** [comment]
@hacken156026692 换了默认分支而已

**Comment by jiegangwu** [comment]
YML 文件怎么更新啊

**Comment by lplbb** [comment]
为什么标着不要fork还是有那么多的fork
