### ISSUE TITLE
东东工厂运行日志获取不到MyJdFactory了

### ISSUE THREAD

**Issue by 4rat** [lxk0301/jd_scripts#636]
**cat 2021-01-12-11-38-20.log**

🔔东东工厂, 开始!
您的cookie选择的是用&隔开

====================共有2个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/1/12 上午11:38:20=====================

开始获取东东工厂配置文件

您的互助码选择的是用&隔开

共2个京东账号

您提供了0个账号的东东工厂助力码

******开始【京东账号1】*********

由于您第1个京东账号未提供shareCode,将采纳本脚本自带的助力码

开始
第1个京东账号将要助力的好友["P04z54XCjVWnYaS5u2ak7ZCdan1Bdd2GGiWvC6_uERj"]
{"code":0,"data":{"bizCode":-9,"bizMsg":"助力失败丨助力已满员！谢谢你哦~","success":false},"msg":"调用成功"}
成功收集351电量，当前蓄电池总电量：58302

【京东账号1（*********）的东东工厂好友互助码】T0225KkcR0wY8VXRIxr9xvIKfQCjVWnYaS5kRrbA

每日开工打卡已完成
准备做此任务：好友助力
去京东首页点击“数码电器”已完成
上岛0元兑年货已做完
看看商品已做完
关注店铺已做完
此任务：开通一加品牌会员，跳过
每日10-13点巡厂已完成

已选商品：realme真我耳机经典版
当前已投入电量/所需电量：0/2380000
已选商品剩余量：601
当前总电量：58302
当前完成度：2%

**cat 2021-01-13-12-51-32.log**

🔔东东工厂, 开始!
您的cookie选择的是用&隔开

====================共有5个京东账号Cookie=========

==================脚本执行- 北京时间(UTC+8)：2021/1/13 下午12:51:32=====================

开始获取东东工厂配置文件

您的互助码选择的是用&隔开

共5个京东账号

您提供了0个账号的东东工厂助力码

******开始【京东账号1】******************

由于您第1个京东账号未提供shareCode,将采纳本脚本自带的助力码

开始
随机取20个码放到您固定的互助码后面(不影响已有固定互助)
第1个京东账号将要助力的好友["P04z54XCjVWnYaS5u2ak7ZCdan1Bdd2GGiWvC6_uERj","P04z54XCjVWnYaS5m9cZ2T71ShCwUaN58X8ZDE","P04z54XCjVWnYaS5jAKC2n63HlPlA","P04z54XCjVWnYaS5m9cZyCOqBgd66uB3XJr9w","P04z54XCjVWnYaS5jQADmP53HlPkQfN7qk","P04z54XCjVWnYaS5m9cZ2SsjHpLnF63B4PyYoE","P04z54XCjVWnYaS5mdXWj_41XxP","P04z54XCjVWnYaS5jcOAGf73X5IkgrCYvKsLvU","P04z54XCjVWnYaS5jQAAWP-1XhCiP8M04pZGyEf","P04z54XCjVWnYaS5mZJVGb-3nlJnA","P04z54XCjVWnYaS5nZXTTSpgyk","P04z54XCjVWnYaS5m9cZ2eu2nRDlyzHFN_El5M","P04z54XCjVWnYaS5m9cZ2Ssiy4ex_lZNy21tAU","P04z54XCjVWnYaS5uCRj7VhWqv0LMXW2KgK-A","P04z54XCjVWnYaS5m9cZ2Ssjy1JlxDWQ-qrC3I","P04z54XCjVWnYaS5jYADmH5231IlsdFj8WlWw4","P04z54XCjVWnYaS5m9cZ2b8jHpDnMIX9QQd7N8","P04z54XCjVWnYaS5m9cZ2TxiS0flEo1fQK0aU8","P04z54XCjVWnYaS5m9cZ2b72nwflkPcBMYBfec","P04z54XCjVWnYaS5u2GiLV2Q6nECw","P04z54XCjVWnYaS5klPUT6vwD8"]
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
{"code":0,"data":{"bizCode":-4001,"bizMsg":"点太快啦！等下再来吧","success":false},"msg":"调用成功"}
成功收集78电量，当前蓄电池总电量：68568

已选商品：realme真我耳机经典版
当前已投入电量/所需电量：0/2380000
已选商品剩余量：538
当前总电量：68568
当前完成度：3%

BoxJs或环境变量暂未提供心仪商品
如需兑换心仪商品，请提供心仪商品名称，否则满足条件后会为您兑换当前所选商品：realme真我耳机经典版

所选商品realme真我耳机经典版目前数量：538，且当前总电量为：68568，【不满足】兑换此商品所需总电量：2380000
故不一次性投入电力，一直放到蓄电池累计

京东账号1*********
京东账号1 *********
已选商品：realme真我耳机经典版
当前已投入电量/所需电量：0/2380000
已选商品剩余量：538
当前总电量：68568
当前完成度：3%

==============📣系统通知📣==============
东东工厂
京东账号1 *********
已选商品：realme真我耳机经典版
当前已投入电量/所需电量：0/2380000
已选商品剩余量：538
当前总电量：68568
当前完成度：3%

===============================================

**cat 2021-01-12-11-38-20.log |grep 东东工厂好友互助码**
【京东账号1（*********）的东东工厂好友互助码】T0225KkcR0wY8VXRIxr9xvIKfQCjVWnYaS5kRrbA
【京东账号2（*********）的东东工厂好友互助码】T0225KkcRRsYpwXSchP3laEIcACjVWnYaS5kRrbA

**cat 2021-01-13-12-51-32.log |grep 东东工厂好友互助码** 
未输出任何。

**Comment by Taffyw** [comment]
我的直接没做每日任务，只是助力了

**Comment by 4rat** [comment]
使用 docker exec jd bash jd jd_get_share_code now 获取到了 ，关闭此帖
