### ISSUE TITLE
重建了 Github Actions 文件，通过克隆码云(Gitee)的代码运行

### ISSUE THREAD

**Issue by lifeishard4me** [lxk0301/jd_scripts#64]
### 说明

这样的话，运行的 Github Action 与本仓库无关， Github 应该无法封禁主库了，希望楼主保持在同步码云的代码。我这边也同步更新相关的 Github Action.

> 地址：https://github.com/lifeishard4me/Actions

**Comment by angle2020** [comment]
楼主有教程不，求个教程

**Comment by zhanghaifei1997** [comment]
求教程

**Comment by sgzman** [comment]
我现在的操作是自己建了个仓库，直接把lxk大佬仓库的脚本给弄上去。
然后再弄个仓库用来执行yml文件跑action。
yml文件里面的checkout地址改成我自己的脚本仓库。
所以，除了yml文件更新需要自己手动操作，其他的不需要操作。而且jd脚本仓库会自动从lxk大佬仓库拉取最新的脚本。

**Comment by zhanghaifei1997** [comment]
嘎嘎嘎，加个qq请教一下，可能有不懂得步骤需要请教用一下




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "Five Million"<notifications@github.com&gt;; 
发送时间: 2020年11月12日(星期四) 上午9:16
收件人: "lxk0301/jd_scripts"<jd_scripts@noreply.github.com&gt;; 
抄送: "亚特兰蒂斯之夜"<2428669833@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [lxk0301/jd_scripts] 重建了 Github Actions 文件，通过克隆码云(Gitee)的代码运行 (#64)





 
我现在的操作是自己建了个仓库，直接把lxk大佬仓库的脚本给弄上去。
 然后再弄个仓库用来执行yml文件跑action。
 yml文件里面的checkout地址改成我自己的脚本仓库。
 所以，除了yml文件更新需要自己手动操作，其他的不需要操作。而且jd脚本仓库会自动从lxk大佬仓库拉取最新的脚本。

**Comment by 09wqlin** [comment]
> ### 说明
> 这样的话，运行的 Github Action 与本仓库无关， Github 应该无法封禁主库了，希望楼主保持在同步码云的代码。我这边也同步更新相关的 Github Action.
> 
> > 地址：https://github.com/lifeishard4me/Actions

摇金树的脚本好像启动不了？

**Comment by zhanghaifei1997** [comment]
> 我现在的操作是自己建了个仓库，直接把lxk大佬仓库的脚本给弄上去。
> 然后再弄个仓库用来执行yml文件跑action。
> yml文件里面的checkout地址改成我自己的脚本仓库。
> 所以，除了yml文件更新需要自己手动操作，其他的不需要操作。而且jd脚本仓库会自动从lxk大佬仓库拉取最新的脚本。

你好，我的qq：2428669833 可不可以加一下我，想请教一下

**Comment by danwangshimoluo** [comment]
关于这个办法，这里有提到过。各位参考这里 #34

**Comment by lxk0301** [comment]
> ### 说明
> 这样的话，运行的 Github Action 与本仓库无关， Github 应该无法封禁主库了，希望楼主保持在同步码云的代码。我这边也同步更新相关的 Github Action.
> 
> > 地址：https://github.com/lifeishard4me/Actions

请把此处的https://github.com/lifeishard4me/Actions/blob/main/.github/workflows/jd_sharecode.yml 文件删除,如自己需要,麻烦新建仓库单独放着自己使用, 不要添加到https://github.com/lifeishard4me/Actions里面
