### ISSUE TITLE
docker1多账号互助码不检测的问题

### ISSUE THREAD

**Issue by Storm4542** [lxk0301/jd_scripts#642]
## 1.关于你要提交的问题

Q：是否搜索了issue（包括已关闭的issue）
- [x] 没有类似的issue 

Q：是否仔细阅读了教程
- [x] 已仔细阅读教程 

## 2. 你使用的哪种部署方法

- [ ] 方法一：本地安装Node.js 
- [ ] 方法二：腾讯云函数
- [x] 方法三：Docker办法一
- [ ] 方法三：Docker办法二 
- [ ] 方法三：Docker办法三 
- [ ] 方法四：iOS系统的代理软件

### (1) 具体问题
A：多账号运行，在环境变量里写好了互助码，但是只有第一个账号能检测到互助码，其他账号都无法检测到

### (2) 详细日志
A：
Jan 13 08:07:01 ******开始【京东账号1】_Storm4542*********
Jan 13 08:07:01 
Jan 13 08:07:01 第1个京东账号将要助力的好友["34c7f6d201ec4fbc8c8512db18aabc6f","f0ba5daf47614b5da7e325d5c9e3a1d7","08fcf1ea4a1c41dba488dd44f4477718","53c6c09078d84610ad4ed53c7de3685e","c7d10258e5ad403da5a5809e320d64c1","8bdb876c57cb4dfea5ef51295490962b"]
//省略任务输出
Jan 13 08:07:43 
Jan 13 08:07:43 ******开始【京东账号2】小笨熊-0323*********
Jan 13 08:07:43 
Jan 13 08:07:43 由于您第2个京东账号未提供shareCode,将采纳本脚本自带的助力码

### (1) Node.js版本

A：

### (2) npm版本

A：

### (3)npm install的日志

A：

**Comment by fengmikaelson** [comment]
你互助码怎么填的？可以发来参考下吗？

**Comment by Storm4542** [comment]
> 你互助码怎么填的？可以发来参考下吗？

      #京东农场
    - FRUITSHARECODES=xxxx@xxxx@xxxx

**Comment by lxk0301** [comment]
自己好好阅读理解 环境变量的填写规则
