### ISSUE TITLE
请问群晖DOCKER里的代码会自动同步更新吗？

### ISSUE THREAD

**Issue by ufxymsn** [lxk0301/jd_scripts#66]
请问群晖DOCKER里的代码会自动同步更新吗，还是需要自己手动更新？

**Comment by lxk0301** [comment]
会

**Comment by zjs5201314** [comment]
我还想知道云函数的会同步更新吗？

**Comment by lxk0301** [comment]
> 我还想知道云函数的会同步更新吗？

不会

**Comment by ufxymsn** [comment]
在群晖DOCKER下载映像的时候选latest还是supportbot？哪个能保持自动更新？

**Comment by iouAkira** [comment]
@ufxymsn 都可以 ，`supportbot` 多了tg 机器人交互功能，不清楚的 使用 latest 即可
