### ISSUE TITLE
群晖DOCKER里的代码会自动同步是否有问题

### ISSUE THREAD

**Issue by hongyunfei** [lxk0301/jd_scripts#67]
![1605150208(1)](https://user-images.githubusercontent.com/34985241/98890451-f2cc2b00-24d6-11eb-8f40-a660ce17fe3d.jpg)
这个更新的地址好像不对，不知道怎么更新地址

**Comment by sysnxw** [comment]
docker-compose pull 更新容器先

**Comment by hongyunfei** [comment]
黑裙辉不太会玩
![2020-11-12_115308](https://user-images.githubusercontent.com/34985241/98893603-b8b25780-24dd-11eb-888c-45ebf9bc9406.png)

**Comment by hongyunfei** [comment]
![2020-11-12_115308](https://user-images.githubusercontent.com/34985241/98893627-c9fb6400-24dd-11eb-8633-95f91567ad58.png)

**Comment by hongyunfei** [comment]
> 黑裙辉不太会玩
![2020-11-12_115308](https://user-images.githubusercontent.com/34985241/98893685-ef886d80-24dd-11eb-91ad-9b3d2b1dfb0f.jpg)

**Comment by hongyunfei** [comment]
> 黑裙辉不太会玩
> ![2020-11-12_115308](https://user-images.githubusercontent.com/34985241/98893603-b8b25780-24dd-11eb-888c-45ebf9bc9406.png)

打了docker-compose pull

**Comment by laotun-s** [comment]
> > 黑裙辉不太会玩
> > ![2020-11-12_115308](https://user-images.githubusercontent.com/34985241/98893603-b8b25780-24dd-11eb-888c-45ebf9bc9406.png)
> 
> 打了docker-compose pull

docker-compose -f 目录 pull

**Comment by iouAkira** [comment]
@laotun-s 好好，看说明，有问题大家肯定都有问题
