### ISSUE TITLE
jd_lotteryMachine.js   已更新

### ISSUE THREAD

**Issue by ceiltop** [lxk0301/jd_scripts#72]
https://github.com/yangtingxiao/QuantumultX/blob/master/scripts/jd/jd_lotteryMachine.js  原作者已更新  是否可更新一下？
 建议而已

**Comment by lxk0301** [comment]
@ceiltop 这边已经用的原作者最新脚本运行的

**Comment by ceiltop** [comment]
感谢回复  顺便问下 docker1 安装的是否会自动同步源码？

**Comment by Tersd07** [comment]
好像直接eval运行原作者的最新脚本。
https://github.com/lxk0301/jd_scripts/blob/3152662893de73dd3e15925f62312d4682d6199f/jd_lotteryMachine.js#L22-L31

**Comment by lxk0301** [comment]
@ceiltop 会同步我这边的

**Comment by lxk0301** [comment]
@Tersd07 对的
