### ISSUE TITLE
东东超市特定地方进入领京豆

### ISSUE THREAD

**Issue by Twinzo1** [lxk0301/jd_scripts#73]
从 首页→京东超市→下方中间 也可以获得两个京豆，希望大佬添加一下

**Comment by Tersd07** [comment]
借楼：
首页中间的领卷→中间签到领红包的同行最右边“100元京卷”
有个没人任务每天有不定点卷，这次双11前比较多，可以换无门槛红包、无门槛券和一些全品类满减券。
蚊子腿也是肉😆

**Comment by lxk0301** [comment]
> 从 首页→京东超市→下方中间 也可以获得两个京豆，希望大佬添加一下

加了
