### ISSUE TITLE
【互助】有需要组团互助的吗

### ISSUE THREAD

**Issue by liby** [lxk0301/jd_scripts#76]
# 满了的就不要留了！如果互助完才满员的记得编辑一下，方便他人，谢谢 🙏

- 萌宠 - 空位 0：
    ~~`MTE1NDAxNzgwMDAwMDAwMzg5MTQ2ODk=`~~

- 水果/农场 - 空位 0：
    ~~`f08c533f840a468eb879dd996078e499`~~

- 种豆 - 空位 0：
    ~~`7q3whkxqumat7hns7ihs6pe7l6sadsvxxiozzpa`~~

加完了记得回复，留下你还有坑位的项目就可以了，我把你也加进去，满员就 Close Issue 了

<details>
<summary>已加入的互助码（个人记录用）</summary>

- 萌宠 - `PETSHARECODES` ：
    `MTAxODc2NTEzNTAwMDAwMDAyMzA2MTUwMQ==@MTAxODExNTM5NDAwMDAwMDAzOTc0MjI2Nw==@MTE1NDAxNzgwMDAwMDAwMzY1MzM4NjE=@MTE1NDAxNzYwMDAwMDAwNDAyOTk3NDc=@MTEzMzI0OTE0NTAwMDAwMDAzNzExMDE5OQ=`

- 农场 - `FRUITSHARECODES` ：
    `2268f2503edd4d9d976774c3c591374a@6461db36f9554bb6857e01d8a821fcf7@961da08d15794125af5b338151899d29@31e291f0aec943458b05c9040898187d@51411e66ebcb4e9fa9db021c74000163`

- 种豆 - `PLANT_BEAN_SHARECODES` ：
    `vh5jxqjorpa4ds6baxdrzvhd3i3h7wlwy7o5jii@4npkonnsy7xi23amhafv6zgfdpgs4dcr3hoynxy@ydl7oqrme2qghebcbr2z4grrh4@e7lhibzb3zek2qvtgibycxn3wpvg4x2mtupscaa@mlrdw3aw26j3wjnivxkefahr2gwje6llffn4wtq`
</details>

**Comment by zheng-wb** [comment]
> * 萌宠：
>   `MTE1NDAxNzgwMDAwMDAwMzg5MTQ2ODk=`
> * 农场：
>   `f08c533f840a468eb879dd996078e499`
> * 种豆
>   `7q3whkxqumat7hns7ihs6pe7l6sadsvxxiozzpa`
> 
> 加完了记得回复，我把你也加进去，满员就 Close Issue 了

怎么加，有没有教程

**Comment by liby** [comment]
@zheng-wb 
https://github.com/lxk0301/jd_scripts/blob/master/githubAction.md#%E4%BA%92%E5%8A%A9%E7%A0%81%E7%9A%84%E5%A1%AB%E5%86%99%E8%A7%84%E5%88%99

**Comment by umichan0621** [comment]
萌宠：
MTAxODc2NTEzNTAwMDAwMDAyMzA2MTUwMQ==

农场：
2268f2503edd4d9d976774c3c591374a

种豆
vh5jxqjorpa4ds6baxdrzvhd3i3h7wlwy7o5jii

**Comment by liby** [comment]
@umichan0621 👌

**Comment by lxyok** [comment]
东东农场：844d1048d0264935a4c28322d4237237@9f9d6fcd291d44edb6a5c9ee295c0774
东东萌宠：MTAxODExNTM5NDAwMDAwMDAzOTc0MjI2Nw==@MTE1NDAxNzgwMDAwMDAwMzY1MzM4NjE=
种豆得豆：e7lhibzb3zek2vtmke2qtgtytqrd6jb6i2mtway@e7lhibzb3zek2hav43rcgeufsq5v5gpnjx6vkcy
两个号，加了我的，说一下 互加

**Comment by umichan0621** [comment]
加了

**Comment by umichan0621** [comment]
> 东东农场：844d1048d0264935a4c28322d4237237@9f9d6fcd291d44edb6a5c9ee295c0774
> 东东萌宠：MTAxODExNTM5NDAwMDAwMDAzOTc0MjI2Nw==@MTE1NDAxNzgwMDAwMDAwMzY1MzM4NjE=
> 种豆得豆：e7lhibzb3zek2vtmke2qtgtytqrd6jb6i2mtway@e7lhibzb3zek2hav43rcgeufsq5v5gpnjx6vkcy
> 两个号，加了我的，说一下 互加

加了

**Comment by liby** [comment]
@lxyok ✅

**Comment by lxyok** [comment]
> @lxyok ✅

只能加你的萌宠了。

**Comment by liby** [comment]
@lxyok 那就只互加萌宠

**Comment by lxyok** [comment]
> @lxyok 那就只互加萌宠

好的。

**Comment by l8higher** [comment]
都加了
以下是我的
豆：4npkonnsy7xi23amhafv6zgfdpgs4dcr3hoynxy
宠：MTE1NDAxNzYwMDAwMDAwNDAyOTk3NDc=
农：6461db36f9554bb6857e01d8a821fcf7

**Comment by umichan0621** [comment]
@l8higher 加了

**Comment by umichan0621** [comment]
@lxyok 加了

**Comment by l8higher** [comment]
> @l8higher 加了

萌宠满了，豆和农场可以

**Comment by liby** [comment]
@l8higher ✅
满了的项目就不要发出来了吧

**Comment by l8higher** [comment]
> @l8higher ✅
> 
> 满了的项目就不要发出来了吧

你的我都加了啊。加完你的，我的萌宠才满。

**Comment by l8higher** [comment]
> @l8higher ✅
> 
> 满了的项目就不要发出来了吧

你加一下我的，然后我的萌宠才满。

**Comment by liby** [comment]
@l8higher 我也都加了...

**Comment by lxyok** [comment]
> @lxyok 加了

OK了

**Comment by jiegangwu** [comment]
东东农场：961da08d15794125af5b338151899d29
东东萌宠：MTEzMzI0OTE0NTAwMDAwMDAzNzExMDE5OQ==
种豆得豆：ydl7oqrme2qghebcbr2z4grrh4
互加

**Comment by liby** [comment]
@jiegangwu ✅

**Comment by l8higher** [comment]
> 东东农场：961da08d15794125af5b338151899d29
> 
> 东东萌宠：MTEzMzI0OTE0NTAwMDAwMDAzNzExMDE5OQ==
> 
> 种豆得豆：ydl7oqrme2qghebcbr2z4grrh4
> 
> 互加

农场和豆已加，我的在上面。

**Comment by jiegangwu** [comment]
> > 东东农场：961da08d15794125af5b338151899d29
> > 东东萌宠：MTEzMzI0OTE0NTAwMDAwMDAzNzExMDE5OQ==
> > 种豆得豆：ydl7oqrme2qghebcbr2z4grrh4
> > 互加
> 
> 农场和豆已加，我的在上面。加完告知一下

豆和农场已加

**Comment by jiegangwu** [comment]
> @jiegangwu ✅

3个都已加了么？

**Comment by hzui** [comment]
农场：6c3e202a03984bf29b28d96e01362456
萌宠： MTE1NDAxNzYwMDAwMDAwMzg2NzU0Mzk=

**Comment by hzui** [comment]
农场：6c3e202a03984bf29b28d96e01362456
萌宠： MTE1NDAxNzYwMDAwMDAwMzg2NzU0Mzk=种豆得豆：euvpbqykbzh3nwvsugi2e6m7ue

**Comment by liby** [comment]
@jiegangwu 都加了，可以在我一楼找到
![image](https://user-images.githubusercontent.com/38807139/99035470-b96ceb80-25ba-11eb-9aba-f7bf468ca0e6.png)

**Comment by jiegangwu** [comment]
> 东东农场：961da08d15794125af5b338151899d29
> 东东萌宠：MTEzMzI0OTE0NTAwMDAwMDAzNzExMDE5OQ==
> 种豆得豆：ydl7oqrme2qghebcbr2z4grrh4
> 互加

已加记录
宠物
MTE1NDAxNzgwMDAwMDAwMzg5MTQ2ODk=@
豆
4npkonnsy7xi23amhafv6zgfdpgs4dcr3hoynxy@f08c533f840a468eb879dd996078e499@
农场
6461db36f9554bb6857e01d8a821fcf7@7q3whkxqumat7hns7ihs6pe7l6sadsvxxiozzpa

**Comment by liby** [comment]
@hzui
![image](https://user-images.githubusercontent.com/38807139/99035769-516ad500-25bb-11eb-9cfd-dde6f7bfc84b.png)

你的回复好像没了，确认一下，你要互助吗

**Comment by hzui** [comment]
@liby 暂时互助不了。他们两个账号，互助两个我的就填满了

**Comment by liby** [comment]
@hzui 额，他们两个，也可以分别加你两次吧，用 & 隔开，如果他们会操作的话

**Comment by qaqc123** [comment]
种豆 e7lhibzb3zek2qvtgibycxn3wpvg4x2mtupscaa
萌宠 MTAxODc2NTEzNTAwMDAwMDAyMDU3NTQ1MQ==
水果 31e291f0aec943458b05c9040898187d
互助互助

**Comment by jiegangwu** [comment]
> 种豆 e7lhibzb3zek2qvtgibycxn3wpvg4x2mtupscaa
> 萌宠 MTAxODc2NTEzNTAwMDAwMDAyMDU3NTQ1MQ==
> 水果 31e291f0aec943458b05c9040898187d
> 互助互助

已加，我的在上边，互加

**Comment by qaqc123** [comment]
> > 种豆 e7lhibzb3zek2qvtgibycxn3wpvg4x2mtupscaa
> > 萌宠 MTAxODc2NTEzNTAwMDAwMDAyMDU3NTQ1MQ==
> > 水果 31e291f0aec943458b05c9040898187d
> > 互助互助
> 
> 已加，我的在上边，互加

ok

**Comment by liby** [comment]
@qaqc123 
种豆得豆和京东农场已加

**Comment by qaqc123** [comment]
> @qaqc123
> 种豆得豆和京东农场已加

你的发我一下

**Comment by liby** [comment]
@qaqc123 
1L 就是我的，你没加就发出来的吗...哥
![image](https://user-images.githubusercontent.com/38807139/99042679-1f13a480-25c8-11eb-930b-6e2059eea7c4.png)

**Comment by qaqc123** [comment]
> @qaqc123
> 1L 就是我的，你没加就发出来的吗...哥
> ![image](https://user-images.githubusercontent.com/38807139/99042679-1f13a480-25c8-11eb-930b-6e2059eea7c4.png)

加了

**Comment by sten666** [comment]
种豆得豆
mlrdw3aw26j3wjnivxkefahr2gwje6llffn4wtq@mlrdw3aw26j3wkazf2g76fjadxgkkqjelgtzdmy
萌宠MTAxODc2NTE0NzAwMDAwMDAyODIzMTM3NQ==@ MTAxODExNDYxMTEwMDAwMDAwMzk3NDcwMjU=
水果
51411e66ebcb4e9fa9db021c74000163@fb6b797c74ec4ace9819a46b8f3d9ba5

**Comment by sten666** [comment]
> 东东农场：844d1048d0264935a4c28322d4237237@9f9d6fcd291d44edb6a5c9ee295c0774
> 东东萌宠：MTAxODExNTM5NDAwMDAwMDAzOTc0MjI2Nw==@MTE1NDAxNzgwMDAwMDAwMzY1MzM4NjE=
> 种豆得豆：e7lhibzb3zek2vtmke2qtgtytqrd6jb6i2mtway@e7lhibzb3zek2hav43rcgeufsq5v5gpnjx6vkcy
> 两个号，加了我的，说一下 互加

已加
下面是我的
种豆得豆
mlrdw3aw26j3wjnivxkefahr2gwje6llffn4wtq@mlrdw3aw26j3wkazf2g76fjadxgkkqjelgtzdmy
萌宠MTAxODc2NTE0NzAwMDAwMDAyODIzMTM3NQ==@MTAxODExNDYxMTEwMDAwMDAwMzk3NDcwMjU=
水果
51411e66ebcb4e9fa9db021c74000163@fb6b797c74ec4ace9819a46b8f3d9ba5

**Comment by sten666** [comment]
> 种豆 e7lhibzb3zek2qvtgibycxn3wpvg4x2mtupscaa
> 萌宠 MTAxODc2NTEzNTAwMDAwMDAyMDU3NTQ1MQ==
> 水果 31e291f0aec943458b05c9040898187d
> 互助互助

已加
我的
种豆得豆
mlrdw3aw26j3wjnivxkefahr2gwje6llffn4wtq@mlrdw3aw26j3wkazf2g76fjadxgkkqjelgtzdmy
萌宠MTAxODc2NTE0NzAwMDAwMDAyODIzMTM3NQ==@MTAxODExNDYxMTEwMDAwMDAwMzk3NDcwMjU=
东东农场
51411e66ebcb4e9fa9db021c74000163@fb6b797c74ec4ace9819a46b8f3d9ba5

**Comment by liby** [comment]
@sten666 水果和种豆各加了一个，具体是哪个可以看 1L折叠部分

**Comment by qaqc123** [comment]
> > 种豆 e7lhibzb3zek2qvtgibycxn3wpvg4x2mtupscaa
> > 萌宠 MTAxODc2NTEzNTAwMDAwMDAyMDU3NTQ1MQ==
> > 水果 31e291f0aec943458b05c9040898187d
> > 互助互助
> 
> 已加
> 我的
> 种豆得豆
> mlrdw3aw26j3wjnivxkefahr2gwje6llffn4wtq@mlrdw3aw26j3wkazf2g76fjadxgkkqjelgtzdmy
> 萌宠MTAxODc2NTE0NzAwMDAwMDAyODIzMTM3NQ==@MTAxODExNDYxMTEwMDAwMDAwMzk3NDcwMjU=
> 东东农场
> 51411e66ebcb4e9fa9db021c74000163@fb6b797c74ec4ace9819a46b8f3d9ba5

已加

**Comment by sten666** [comment]
> @sten666 水果和种豆各加了一个，具体是哪个可以看 1L折叠部分

种豆加进去了；农场我之前复制了四个了，不过我也把你的加进去了

**Comment by liby** [comment]
OK，那我们就配对成功了，可以关闭 issue 了。

### 最后确认一下，两个的记得也把我分别在各个账号中加 1 次哦

萌宠 - 依次是 @umichan0621 、 @lxyok * 2、 @l8higher 、 @jiegangwu
`MTAxODc2NTEzNTAwMDAwMDAyMzA2MTUwMQ==@MTAxODExNTM5NDAwMDAwMDAzOTc0MjI2Nw==@MTE1NDAxNzgwMDAwMDAwMzY1MzM4NjE=@MTE1NDAxNzYwMDAwMDAwNDAyOTk3NDc=@MTEzMzI0OTE0NTAwMDAwMDAzNzExMDE5OQ=`

农场 - 依次是 @umichan0621 、 @l8higher 、 @jiegangwu 、@qaqc123 、 @sten666
2268f2503edd4d9d976774c3c591374a@6461db36f9554bb6857e01d8a821fcf7@961da08d15794125af5b338151899d29@31e291f0aec943458b05c9040898187d@51411e66ebcb4e9fa9db021c74000163

种豆 - 依次是 @umichan0621 、 @l8higher 、 @jiegangwu 、@qaqc123 、 @sten666
vh5jxqjorpa4ds6baxdrzvhd3i3h7wlwy7o5jii@4npkonnsy7xi23amhafv6zgfdpgs4dcr3hoynxy@ydl7oqrme2qghebcbr2z4grrh4@e7lhibzb3zek2qvtgibycxn3wpvg4x2mtupscaa@mlrdw3aw26j3wjnivxkefahr2gwje6llffn4wtq

**Comment by liby** [comment]
@umichan0621 、 @lxyok 、 @jiegangwu
不好意思，打扰一下，你们有空可以看一下是谁把我漏掉了吗
![image](https://user-images.githubusercontent.com/38807139/99144210-f3172280-269e-11eb-9d31-e3d2737246a8.png)

**Comment by lxyok** [comment]
@liby 

 我这里显示已经助力了
![](https://gitee.com/ligedone/pic/raw/ov/img/20201114174244.png)

**Comment by liby** [comment]
@lxyok 
额，冒昧问一下你两个号都把我加进去了。。因为这只看到了账号1

**Comment by lxyok** [comment]
Bryan Lee <notifications@github.com>于2020年11月14日 周六下午6:06写道：
