### ISSUE TITLE
如何保持群晖的docker内运行最新的code？目前看并没有更新

### ISSUE THREAD

**Issue by vistaup-chen** [lxk0301/jd_scripts#77]
作者您好！群晖docker日志中有看到 pull.log 中有显示Already up to date.
但是13日0点依旧运行了星推官，9点推送了 818 狂欢城。

请问docker中的代码会自动与github中同步么？

**Comment by lxk0301** [comment]
@vistaup-chen docker方法几？

还有就是你是不是使用了自定义cron 然后没自己删掉？

**Comment by vistaup-chen** [comment]
> @vistaup-chen docker方法几？
> 
> 还有就是你是不是使用了自定义cron 然后没自己删掉？

docker 的信息如下：
Client:
 Version:           18.09.8
 API version:       1.39
 Go version:        go1.11
 Git commit:        bfed4f5
 Built:             Fri Mar 13 06:46:11 2020
 OS/Arch:           linux/amd64
 Experimental:      false

Img 的信息如下：
REPOSITORY           TAG                 IMAGE ID            CREATED             SIZE
akyakya/jd_scripts   latest              e2f42a8aa683        2 days ago          102MB

没有使用自定义cron ，当时创建的时候就想到了与github的同步问题，因此保持了默认。
请问有什么排查方向和建议呢？ 群晖docker不更新问题还是比较麻烦的，如果我无法解决可能只能转用虚拟机了

**Comment by iouAkira** [comment]
@vistaup-chen docker exec -it  jd_scripts /bin/sh -c 'cat /scripts/docker/crontab_list.sh' 看看吧

**Comment by vistaup-chen** [comment]
> @vistaup-chen docker exec -it jd_scripts /bin/sh -c 'cat /scripts/docker/crontab_list.sh' 看看吧

在您提出docker版本问题后，我试着将docker卸载重装，并重新加载了最新img，pull.log中显示已经变更了文件，crontab_list.sh已经为最新。

问题已解决，但原因未找到。
暂时无法复现问题就查不了了，谢谢作者大大

**Comment by iouAkira** [comment]
@vistaup-chen .....
