### ISSUE TITLE
到底能不能fork？

### ISSUE THREAD

**Issue by zhuzf88** [lxk0301/jd_scripts#8]
看到提示前已经fork，需要删除吗？

**Comment by lxk0301** [comment]
可以自己新建 ,fork后怕你们自行添加 yml文件继续跑 action

**Comment by lxk0301** [comment]
到时候源头 ,还是我这里 ,可能又会被封

**Comment by as48511201** [comment]
感谢大佬

**Comment by qyaaaa** [comment]
> 可以自己新建 ,fork后怕你们自行添加 yml文件继续跑 action

那意思是clone到本地再上传吗？

**Comment by zhuzf88** [comment]
> 可以自己新建 ,fork后怕你们自行添加 yml文件继续跑 action

明白。另外想问一下，这个脚本执行会不会黑号啊，好像京东打压挺厉害。

**Comment by carrot-wu** [comment]
> 到时候源头 ,还是我这里 ,可能又会被封

看来还是走docker算了 能问一下镜像在更新完成之后会同步更新吗

**Comment by chen1006** [comment]
> 可以自己新建，fork后怕你们自己添加yml文件继续跑action

我新建导入可以码

**Comment by qianx443** [comment]
不跑action 腾讯云函数或者自己服务器可以不

**Comment by sgzman** [comment]
谁有之前的备份的全部yml文件，麻烦发一份，我自己跑，不用fork跑

**Comment by lxk0301** [comment]
> > 可以自己新建 ,fork后怕你们自行添加 yml文件继续跑 action
> 
> 那意思是clone到本地再上传吗？

对  ,还有自己新建哪些脚本的yml文件

**Comment by lxk0301** [comment]
> 不跑action 腾讯云函数或者自己服务器可以不

可以

**Comment by hacken156026692** [comment]
> 看来还是走docker算了 能问一下镜像在更新完成之后会同步更新吗

请问怎么docker啊？谢谢

**Comment by ZHANGLIANGzhangliang** [comment]
> 谁有之前的备份的全部yml文件，麻烦发一份，我自己跑，不用fork跑

给我一个呀

**Comment by hacken156026692** [comment]
> 谁有之前的备份的全部yml文件，麻烦发一份，我自己跑，不用fork跑

请问怎么自己跑？能否教一下？

**Comment by Castle1984** [comment]
> 谁有之前的备份的全部yml文件，麻烦发一份，我自己跑，不用fork跑

同求，1356681253@qq.com，有偿

**Comment by bigcandou** [comment]
同求285775408@qq.com

**Comment by qianx443** [comment]
同求yml文件

**Comment by fivenull** [comment]
同求，903494855@qq.com

**Comment by ZHANGLIANGzhangliang** [comment]
求一份，18320668322@163.com

**Comment by YouHolmes** [comment]
好心人求一份，825409689@qq.com

**Comment by tofuliang** [comment]
[workflows.zip](https://github.com/lxk0301/jd_scripts/files/5514580/workflows.zip)
上面需要workflows的，这里有。不要翻那啥了

**Comment by Castle1984** [comment]
> [workflows.zip](https://github.com/lxk0301/jd_scripts/files/5514580/workflows.zip)
> 上面需要workflows的，这里有。不要翻那啥了

感谢！大家也都自觉一点，不要fork了，还是新建吧

**Comment by hacken156026692** [comment]
> > [workflows.zip](https://github.com/lxk0301/jd_scripts/files/5514580/workflows.zip)
> > 上面需要workflows的，这里有。不要翻那啥了
> 
> 感谢！大家也都自觉一点，不要fork了，还是新建吧

请问怎么新建？怎么设置？

**Comment by Clackz** [comment]
看起来是因为大量使用了github的Actions功能占用太多资源所以被封了吧

**Comment by xuelang7009** [comment]
> 
> 
> 谁有之前的备份的全部yml文件，麻烦发一份，我自己跑，不用fork跑

同求

**Comment by xuelang7009** [comment]
求一份，xuelang7009@163.com

**Comment by dhy1233** [comment]
同求yml文件2215599622@qq.com

**Comment by tofuliang** [comment]
> 看到提示前已经fork，需要删除吗？

楼主你改改标题吧，帖子中间已经上传workflow了，进来的人都不看，一个劲的求求求。。。。

**Comment by ZHANGLIANGzhangliang** [comment]
> [workflows.zip](https://github.com/lxk0301/jd_scripts/files/5514580/workflows.zip)
> 上面需要workflows的，这里有。不要翻那啥了

感谢

**Comment by carrot-wu** [comment]
> 看起来是因为大量使用了github的Actions功能占用太多资源所以被封了吧

走的是都是楼主的github action 能不被封吗  把原项目clone下来自己上传走紫的githubaction 应该就没问题 麻烦的是 项目更新了不好同步

**Comment by sgzman** [comment]
> [workflows.zip](https://github.com/lxk0301/jd_scripts/files/5514580/workflows.zip)
> 上面需要workflows的，这里有。不要翻那啥了

上传了yml之后，运行，提示这个错误，怎么解决呢？

Run node jd_collectProduceScore.js
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module '/home/runner/work/my_jd_scripts/my_jd_scripts/jd_collectProduceScore.js'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:72:12)
    at internal/main/run_main_module.js:17:47 {
  code: 'MODULE_NOT_FOUND',
  requireStack: []
}
Error: Process completed with exit code 1.

**Comment by laotun-s** [comment]
同求yml，laotun.w@qq.com
