### ISSUE TITLE
云函数调用签到成功

### ISSUE THREAD

**Issue by ykrank** [lxk0301/jd_scripts#81]
只要指定路径到tmp下就行，需要注意的是node的路径也必须指定，否则默认使用的最低版本的node，导致运行失败。
[jd_bean_sign.txt](https://github.com/lxk0301/jd_scripts/files/5534806/jd_bean_sign.txt)

**Comment by ykrank** [comment]
如果是云函数，直接把txt改名为js直接替换即可。适配action之类我就不做了

**Comment by Jumeng-ms** [comment]
thinks
