### ISSUE TITLE
方法三出现的问题

### ISSUE THREAD

**Issue by di7gan** [lxk0301/jd_scripts#84]
我使用的方法三vps搭建的git，docker，docker-conplose方法
问题一：使用手动签到所有出现卡界面非常长的时间，
问题二：如何看日志或者脚本文件在哪里？
问题三：脚本如何实现自动运行。
还请赐教。谢谢

**Comment by di7gan** [comment]
![1-1](https://user-images.githubusercontent.com/20412710/99041413-d824af80-25c5-11eb-8bb8-d82d34e84e62.PNG)

**Comment by di7gan** [comment]
使用第4个和第5个账户处理，出现：
操作方法：复制的env1，env2，env3配置文件出来的，然后利用notepad++修改，文件名为env4或者env5，出现下面这错误。但是将文件修改为env1或者env2或者env3的时候进行执行操作，一切正常。

[root@localhost ~]# docker exec jd4  bash -c 'set -o allexport; source /all; source /env; source /jd-scripts-docker/resolve.sh; cd /scripts; node jd_bean_sign.js'
/env: line 2: $'\r': command not found
/env: line 3: $'\r': command not found
/env: line 5: $'\r': command not found

dock-complose.yml配置文件如下，也是从2和3里面复制出来，将2对应改成4，3对应改成5.
`version: "2.1"
x-logger: &logger
  logging:
    driver: "json-file"
    options:
      max-size: "10m"
      max-file: "5"
x-common: &common
  image: jd-scripts:latest
  build:
    context: .
    dockerfile: ./Dockerfile
  restart: always
services:
  jd1:
    <<: [ *logger, *common ]
    container_name: jd1
    volumes:
      - ./env/all:/all
      - ./env/env1:/env
  jd2:
    <<: [ *logger, *common ]
    container_name: jd2
    volumes:
      - ./env/all:/all
      - ./env/env2:/env
  jd3:
    <<: [ *logger, *common ]
    container_name: jd3
    volumes:
      - ./env/all:/all
      - ./env/env3:/env
  jd4:
    <<: [ *logger, *common ]
    container_name: jd4
    volumes:
      - ./env/all:/all
      - ./env/env4:/env      
  jd5:
    <<: [ *logger, *common ]
    container_name: jd5
    volumes:
      - ./env/all:/all
      - ./env/env5:/env      
      
      
      `

**Comment by Clackz** [comment]
这些问题应该去方法三的项目中提问
