### ISSUE TITLE
大佬，群晖多个docker并行运行的话，日志文件的路径该在哪改呢

### ISSUE THREAD

**Issue by 627992512** [lxk0301/jd_scripts#85]
目前是五个账号的log全写在一个.log文件里，有点混乱。

**Comment by iouAkira** [comment]
@627992512 把你的 json 文件从头到尾完整的看一遍，肯定能找到在哪改

**Comment by 627992512** [comment]
好的好的，解决了，谢谢dl。之前测试的时候没仔细看，把挂载点也改了，我说怎么没运行。
