### ISSUE TITLE
脚本基本上都只执行第一个账号是为啥，后面都报错

### ISSUE THREAD

**Issue by angle2020** [lxk0301/jd_scripts#88]
![QQ截图20201113234318](https://user-images.githubusercontent.com/65349186/99091200-83efee80-260a-11eb-8e11-853f442d0145.png)

**Comment by hhxs1987** [comment]
两个账号的英文的引号间还有英文的逗号。

**Comment by lxk0301** [comment]
自己京东cookie给的不对
