### ISSUE TITLE
docker三能不能更新下，好多过期活动还在

### ISSUE THREAD

**Issue by ChangWeiCat** [lxk0301/jd_scripts#89]
docker三能不能更新下，好多过期活动还在

**Comment by ChangWeiCat** [comment]
"getaddrinfo EAI_AGAIN wq.jd.com wq.jd.com:443"
京东手机狂欢城 API请求失败，请检查网路重试

开始【京东账号1】jd_

"getaddrinfo EAI_AGAIN rdcseason.m.jd.com rdcseason.m.jd.com:443"
京东手机狂欢城 API请求失败，请检查网路重试
"getaddrinfo EAI_AGAIN rdcseason.m.jd.com rdcseason.m.jd.com:443"
京东手机狂欢城 API请求失败，请检查网路重试
"getaddrinfo EAI_AGAIN rdcseason.m.jd.com rdcseason.m.jd.com:443"
京东手机狂欢城 API请求失败，请检查网路重试
"getaddrinfo EAI_AGAIN rdcseason.m.jd.com rdcseason.m.jd.com:443"
京东手机狂欢城 API请求失败，请检查网路重试

**Comment by lxk0301** [comment]
去docker那边反馈
