### ISSUE TITLE
boxjs订阅失败

### ISSUE THREAD

**Issue by hlok666** [lxk0301/jd_scripts#90]
按照教程把订阅地址复制过去 一直都不成功 提示格式错误
订阅地址https://raw.githubusercontent.com/lxk0301/jd_scripts/master/lxk0301.boxjs.json
请问大佬该如何解决

**Comment by yinjikai** [comment]
解决了吗

**Comment by hlok666** [comment]
已经解决了~是我节点的问题 多换几个节点就好了



---原始邮件---
发件人: "Jack Yin"<notifications@github.com&gt;
发送时间: 2020年11月27日(周五) 上午10:27
收件人: "lxk0301/jd_scripts"<jd_scripts@noreply.github.com&gt;;
抄送: "State change"<state_change@noreply.github.com&gt;;"hlok666"<522688974@qq.com&gt;;
主题: Re: [lxk0301/jd_scripts] boxjs订阅失败 (#90)




 
解决了吗
