### ISSUE TITLE
大佬，docker的手机狂欢城脚本该如何删除啊

### ISSUE THREAD

**Issue by 627992512** [lxk0301/jd_scripts#93]
它每天都推送消息让我删，我也想删，可是我不知道怎么删

**Comment by Vesugierii** [comment]
@627992512 在docker的脚本库里删应该是scripts目录

**Comment by lxk0301** [comment]
用谁的docker就看具体的操作说明，能自定义的就去自定义里面删除，不能自定义的就给docker那边提issue

**Comment by 627992512** [comment]
好的好的
