### ISSUE TITLE
【互助-农场和种豆】组团速来，差 2 位

### ISSUE THREAD

**Issue by liby** [lxk0301/jd_scripts#97]
# 满了的就不要留了！如果互助完才满员的记得编辑一下，方便他人，谢谢 🙏

- 水果/农场 - 空位 1 = 等待 @mmsc2020：
    `f08c533f840a468eb879dd996078e499`

- 种豆 - 空位 1 = 等待 @mmsc2020：
    `7q3whkxqumat7hns7ihs6pe7l6sadsvxxiozzpa`

**加完了记得回复**，留下你还有坑位的项目就可以了，我把你也加进去，**满员就 Close Issue 了**

<details>
<summary>已加入的互助码（个人记录用）</summary>

- 农场 - `FRUITSHARECODES` ：
    `2268f2503edd4d9d976774c3c591374a@6461db36f9554bb6857e01d8a821fcf7@31e291f0aec943458b05c9040898187d@ce4d27e43b3a4fb08e53fd6349c9e9aa@0bdf8f095bfd403c953705fe9e34178d`

- 种豆 - `PLANT_BEAN_SHARECODES` ：
    `vh5jxqjorpa4ds6baxdrzvhd3i3h7wlwy7o5jii@4npkonnsy7xi23amhafv6zgfdpgs4dcr3hoynxy@e7lhibzb3zek2qvtgibycxn3wpvg4x2mtupscaa@rntc64zizuwdnoqddxujlb6py4r27koi47syzzi@bqn4yrykl5tfwnzftmmqrl7vsy`
</details>

前几天开了一个帖子 #76  ，找到了 5 个人，但是直到今天我的农场和种豆还差人，在原帖艾特了他们，有两个迟迟不回复，没办法只能新开一个，希望大家**诚信互助**，这样搞来搞去挺麻烦的...

![image](https://user-images.githubusercontent.com/38807139/99183885-2ed2ea80-277a-11eb-809e-ca4b6d46c6eb.png)
![image](https://user-images.githubusercontent.com/38807139/99183810-92104d00-2779-11eb-94ae-44bbd16a5375.png)
![image](https://user-images.githubusercontent.com/38807139/99183823-b2d8a280-2779-11eb-96f4-884c0b4ed97f.png)

**Comment by qingcher** [comment]
种豆互助码

rntc64zizuwdnoqddxujlb6py4r27koi47syzzi

东东农场互助

ce4d27e43b3a4fb08e53fd6349c9e9aa

**Comment by qingcher** [comment]
你的放上去了，你也加下我的

**Comment by liby** [comment]
@qingcher ✅

**Comment by jack2365** [comment]
> 种豆互助码
> 
> 
> 
> rntc64zizuwdnoqddxujlb6py4r27koi47syzzi
> 
> 
> 
> 东东农场互助
> 
> 
> 
> ce4d27e43b3a4fb08e53fd6349c9e9aa

两个账号都加了你的哦，求互助
京东农场

ab62b594b3864ec7a4a23e1b175ddf5d

ff97a2f87c1c4617840e0f8f3cd4b1eb

东东萌宠

MTAxODc2NTEzNTAwMDAwMDAyOTE3MzY0MQ== MTEzMzI0OTE0NTAwMDAwMDAzODI5NDQxMQ==

种豆得豆

nqk3sljeoh6l53jqjuyrj6xow4z7nf5cssbfiwy

4npkonnsy7xi3pnhppmuf42z6hodne6hqvqtjzi

**Comment by mmsc2020** [comment]
京东农场
0bdf8f095bfd403c953705fe9e34178d

京东萌宠
MTE1NDQ5OTUwMDAwMDAwMzkwNDk2NTM=

种豆得豆
bqn4yrykl5tfwnzftmmqrl7vsy

**Comment by 1984oyt** [comment]
京东农场【您的互助码shareCode】 

93cf535af3e84c4e91dd93f37c268429

21bf76902e664fc180b7c45b5d30e9d5

7bb014a1c8104729977d7608c3e029fe

a17294a961714eecb5218ab2ec2fcad9


萌宠【您的互助码shareCode】 

MTE1NDUwMTI0MDAwMDAwMDM2OTU1NDY5

MTAxODc2NTEzMDAwMDAwMDAyNDcwNzIyNQ==

MTE1NDUwMTI0MDAwMDAwMDM5NDU5NTE3

MTE1NDUwMTI0MDAwMDAwMDM5NTgzMTcz



种豆得豆【您的互助码plantUuid】 

olmijoxgmjutyfu6ut26igo47oksshgz5u2rofy

olmijoxgmjutzmojonrn3rbikhcwiaxdk3eum3i

l4ex6vx6yynouo2wpokbogituvwlsr4xypak2ei

nkiu2rskjyetaneerkevqpn2ci53m6nnqwfjacy

**Comment by liby** [comment]
@mmsc2020 ✅
![image](https://user-images.githubusercontent.com/38807139/99187615-9d23a700-2792-11eb-93d2-114dcff968e3.png)

**Comment by jiegangwu** [comment]
> @mmsc2020 ✅
> ![image](https://user-images.githubusercontent.com/38807139/99187615-9d23a700-2792-11eb-93d2-114dcff968e3.png)

你的我加了，fengfeier6 就是我。

**Comment by zhangrenchuan** [comment]
农场：12719ceb556d4f8c9af645b66e804786
萌宠：MTAxODc2NTEzMjAwMDAwMDAyMDg5MTA5MQ==
种豆：yjn6d26ldestpldmexegrid3fj3bg35qkw6zowy

谢谢

**Comment by liby** [comment]
@jiegangwu 我就是知道 fengfeier6 是你才艾特你的，但你一直不回复，就重新开帖了，而且你看我截图里面确实没有 fengfeier6

**Comment by liby** [comment]
![image](https://user-images.githubusercontent.com/38807139/99207801-db07e600-27f9-11eb-9b94-0b20caf9e336.png)
@zhangrenchuan 
萌宠、种豆、农场都加完了，我的互助码在 1L，你加完告诉我吧

**Comment by zhangrenchuan** [comment]
加完了

**Comment by zhangrenchuan** [comment]
@liby 加完了 :)
