### ISSUE TITLE
获取助力码时候会卡死，能不能加一个超时？

### ISSUE THREAD

**Issue by dadamimi** [lxk0301/jd_scripts#99]
为什么我大多时候获取助力码时候会卡死，能不能加一个超时？
我是用win10 nodejs运行的，node版本是12.18.3。
屏蔽了await shareCodesFormat()才能每次都正常运行。

**Comment by lxk0301** [comment]
我这边从未遇到过，

而且await shareCodesFormat()里面即使那个API出现问题。也是不会一直卡死在那边的。

超时目前是加不了

**Comment by dadamimi** [comment]
> 我这边从未遇到过，
> 
> 而且await shareCodesFormat()里面即使那个API出现问题。也是不会一直卡死在那边的。
> 
> 超时目前是加不了

我调试了一下，是get链接的单引号问题，改为英文单引号，就能捕捉到异常信息“API请求失败，请检查网路重试”，正常执行下去。是我的nodejs版本问题吗？

**Comment by dadamimi** [comment]
> 我这边从未遇到过，
> 
> 而且await shareCodesFormat()里面即使那个API出现问题。也是不会一直卡死在那边的。
> 
> 超时目前是加不了

我是移动的网络，在路由器设置这个域名代理出去，暂时没问题了。
